### ISSUE TITLE
bug：Grid组件的动态获取数据时，数据存在重复时，@change返回的index错误

### ISSUE THREAD

**Issue by chendanlin** [dcloudio/uni-ui#100]
Grid的新版本（1.2.1）还有一个问题，在动态获取数据时，数据中前后有一部分重复，由于vue的渲染机制，uni-grid-item标签不能使用:key，不然复用还是会导致@change返回的index错误

**Comment by mehaotian** [comment]
必须保证每一项有一个唯一的id之类的字段，用于循环组件

**Comment by chendanlin** [comment]
就是由于有唯一id，数据存在重复的情况下，id相同的uni-grid-item没有被销毁，@change返回的index是uni-grid-item中的index，没销毁的uni-grid-item保留了上次的index，导致了返回的index错误，所以不能使用:key，保证每次渲染时uni-grid-item都被销毁，才可以保证index的正确性，但v-for一般都是要使用:key，不然一直warn，虽然使用上没问题

**Comment by chendanlin** [comment]
<template>
	<view>
		<uni-grid @change="handleGridChange">
			<uni-grid-item v-for="item in array" :key="item.id">{{item.id}}</uni-grid-item>
		</uni-grid>
		<button type="primary" @click="switchData">switch</button>
	</view>
</template>

<script>
	import uniGrid from '@/components/uni-grid/uni-grid.vue'
	import uniGridItem from '@/components/uni-grid-item/uni-grid-item.vue'
	const testData = [
		[{
			id: 1
		}, {
			id: 2
		}, {
			id: 3
		}, {
			id: 4
		}, {
			id: 5
		}, {
			id: 6
		}],
		[{
			id: 3
		}, {
			id: 4
		}, {
			id: 5
		}, {
			id: 6
		}, {
			id: 7
		}, {
			id: 8
		}],
		[{
			id: 5
		}, {
			id: 6
		}, {
			id: 7
		}, {
			id: 8
		}, {
			id: 9
		}, {
			id: 10
		}]
	]

	export default {
		components: {
			uniGrid,
			uniGridItem
		},
		data() {
			return {
				textIndex: 0,
				array: testData[0]
			}
		},
		methods: {
			handleGridChange: function(e) {
				const index = e.detail.index
				console.log("index: " + index);
			},
			switchData: function() {
				if (this.textIndex == 2) {
					this.textIndex = 0
				}
				this.array = testData[this.textIndex++]
			}
		}
	}
</script>

<style>

</style>

这是复现代码，多次单击切换数据后，输出的index就会出现错误

**Comment by chendanlin** [comment]
`<template>
	<view>
		<uni-grid @change="handleGridChange">
			<uni-grid-item v-for="item in array" :key="item.id">{{item.id}}</uni-grid-item>
		</uni-grid>
		<button type="primary" @click="switchData">switch</button>
	</view>
</template>

<script>
	import uniGrid from '@/components/uni-grid/uni-grid.vue'
	import uniGridItem from '@/components/uni-grid-item/uni-grid-item.vue'
	const testData = [
		[{
			id: 1
		}, {
			id: 2
		}, {
			id: 3
		}, {
			id: 4
		}, {
			id: 5
		}, {
			id: 6
		}],
		[{
			id: 3
		}, {
			id: 4
		}, {
			id: 5
		}, {
			id: 6
		}, {
			id: 7
		}, {
			id: 8
		}],
		[{
			id: 5
		}, {
			id: 6
		}, {
			id: 7
		}, {
			id: 8
		}, {
			id: 9
		}, {
			id: 10
		}]
	]

	export default {
		components: {
			uniGrid,
			uniGridItem
		},
		data() {
			return {
				textIndex: 0,
				array: testData[0]
			}
		},
		methods: {
			handleGridChange: function(e) {
				const index = e.detail.index
				console.log("index: " + index);
			},
			switchData: function() {
				if (this.textIndex == 2) {
					this.textIndex = 0
				}
				this.array = testData[this.textIndex++]
			}
		}
	}
</script>

<style>

</style>
`

**Comment by chendanlin** [comment]
`<template>
	<view>
		<uni-grid @change="handleGridChange">
			<uni-grid-item v-for="item in array" :key="item.id">{{item.id}}</uni-grid-item>
		</uni-grid>
		<button type="primary" @click="switchData">switch</button>
	</view>
</template>

<script>
	import uniGrid from '@/components/uni-grid/uni-grid.vue'
	import uniGridItem from '@/components/uni-grid-item/uni-grid-item.vue'
	const testData = [
		[{
			id: 1
		}, {
			id: 2
		}, {
			id: 3
		}, {
			id: 4
		}, {
			id: 5
		}, {
			id: 6
		}],
		[{
			id: 3
		}, {
			id: 4
		}, {
			id: 5
		}, {
			id: 6
		}, {
			id: 7
		}, {
			id: 8
		}],
		[{
			id: 5
		}, {
			id: 6
		}, {
			id: 7
		}, {
			id: 8
		}, {
			id: 9
		}, {
			id: 10
		}]
	]

	export default {
		components: {
			uniGrid,
			uniGridItem
		},
		data() {
			return {
				textIndex: 0,
				array: testData[0]
			}
		},
		methods: {
			handleGridChange: function(e) {
				const index = e.detail.index
				console.log("index: " + index);
			},
			switchData: function() {
				if (this.textIndex == 2) {
					this.textIndex = 0
				}
				this.array = testData[this.textIndex++]
			}
		}
	}
</script>

<style>

</style>
`

**Comment by chendanlin** [comment]
这是复现代码，多次点击切换按钮后，单击uni-grid-item，观察控制台的输出可以明显看出index出现错误


###template


	<template>
	<view>
		<uni-grid @change="handleGridChange">
			<uni-grid-item v-for="item in array" :key="item.id">{{item.id}}</uni-grid-item>
		</uni-grid>
		<button type="primary" @click="switchData">switch</button>
	</view>
	</template>

###script
	<script>
	import uniGrid from '@/components/uni-grid/uni-grid.vue'
	import uniGridItem from '@/components/uni-grid-item/uni-grid-item.vue'
	const testData = [
		[{
			id: 1
		}, {
			id: 2
		}, {
			id: 3
		}, {
			id: 4
		}, {
			id: 5
		}, {
			id: 6
		}],
		[{
			id: 3
		}, {
			id: 4
		}, {
			id: 5
		}, {
			id: 6
		}, {
			id: 7
		}, {
			id: 8
		}],
		[{
			id: 5
		}, {
			id: 6
		}, {
			id: 7
		}, {
			id: 8
		}, {
			id: 9
		}, {
			id: 10
		}]
	]

	export default {
		components: {
			uniGrid,
			uniGridItem
		},
		data() {
			return {
				textIndex: 0,
				array: testData[0]
			}
		},
		methods: {
			handleGridChange: function(e) {
				const index = e.detail.index
				console.log("index: " + index);
			},
			switchData: function() {
				if (this.textIndex == 2) {
					this.textIndex = 0
				}
				this.array = testData[this.textIndex++]
			}
		}
	}
	</script>

**Comment by mehaotian** [comment]
> @mehaotian 这是复现代码，多次点击切换按钮后，单击uni-grid-item，观察控制台的输出可以明显看出index出现错误
> 
> ### template
> ```
> <template>
> <view>
> 	<uni-grid @change="handleGridChange">
> 		<uni-grid-item v-for="item in array" :key="item.id">{{item.id}}</uni-grid-item>
> 	</uni-grid>
> 	<button type="primary" @click="switchData">switch</button>
> </view>
> </template>
> ```
> 
> ### script
> ```
> <script>
> import uniGrid from '@/components/uni-grid/uni-grid.vue'
> import uniGridItem from '@/components/uni-grid-item/uni-grid-item.vue'
> const testData = [
> 	[{
> 		id: 1
> 	}, {
> 		id: 2
> 	}, {
> 		id: 3
> 	}, {
> 		id: 4
> 	}, {
> 		id: 5
> 	}, {
> 		id: 6
> 	}],
> 	[{
> 		id: 3
> 	}, {
> 		id: 4
> 	}, {
> 		id: 5
> 	}, {
> 		id: 6
> 	}, {
> 		id: 7
> 	}, {
> 		id: 8
> 	}],
> 	[{
> 		id: 5
> 	}, {
> 		id: 6
> 	}, {
> 		id: 7
> 	}, {
> 		id: 8
> 	}, {
> 		id: 9
> 	}, {
> 		id: 10
> 	}]
> ]
> 
> export default {
> 	components: {
> 		uniGrid,
> 		uniGridItem
> 	},
> 	data() {
> 		return {
> 			textIndex: 0,
> 			array: testData[0]
> 		}
> 	},
> 	methods: {
> 		handleGridChange: function(e) {
> 			const index = e.detail.index
> 			console.log("index: " + index);
> 		},
> 		switchData: function() {
> 			if (this.textIndex == 2) {
> 				this.textIndex = 0
> 			}
> 			this.array = testData[this.textIndex++]
> 		}
> 	}
> }
> </script>
> ```

确认是Bug,因为为了保障全平台兼容，所以是检测到子组件加载，让一个标识递增的方式实现的点击返回索引，没有考虑到你说的这个情况 ，这种方式确实是考虑不周了，之后看一下怎么优化

**Comment by mehaotian** [comment]
uni-grid-item 新增一个 index 的属性，是一个唯一且不重复的标识，点击grid会返回当前标识。因框架限制，并不能百分百的知道子组件下标索引位置，所以目前只能用户自己传如一个标识，之后会想办法优化此处逻辑
