### ISSUE TITLE
uni-nav-bar.vue 组件中 所有的 “width: 750rpx;” 都应该用100% 

### ISSUE THREAD

**Issue by zhaoguoquan** [dcloudio/uni-ui#101]
uni-nav-bar.vue 组件中 所有的 “width: 750rpx;” 都应该用100% 而不应该用绝对数值。
这样在使用的时候才不会在设置了了page的 padding内边距的时候造成页面溢出（出现滚动条）。
在真正做页面的时候 才具有更多的灵活性。 因为uni-nav-bar组件会经常会嵌套在父容器中。

**Comment by Wangyaqi** [comment]
nvue分支已修改。目前使用的flex布局，在小程序端组件外部会被套一层元素，建议将组件父元素设置为 display:block
