### ISSUE TITLE
uniSwipeActionItem 组件左滑打开，松手之后就自动收起

### ISSUE THREAD

**Issue by ColinLQ** [dcloudio/uni-ui#103]

**Comment by ColinLQ** [comment]
找到原因了，按钮文字太小的时候，无法触发打开的阈值。

**Comment by ColinLQ** [comment]
` moveDirection(state.left, -40, instance, ownerInstance); ` 
当按钮文字太小时，`touchend` 之后  `state.left` 的值大于 -40，导致无法开启

**Comment by mehaotian** [comment]
正常情况下，你的按钮肯定是 要超过 40 个阙值的，不然你点击按钮都不好点击 ，如果确实有需要，可以在源码中调整一下阙值
