### ISSUE TITLE
nvue版，uniSteps无法显示

### ISSUE THREAD

**Issue by huanghaodong** [dcloudio/uni-ui#106]
用的demo的例子，nvue app 端 uniSteps无法显示
![image](https://user-images.githubusercontent.com/24872469/69971243-8fade680-155a-11ea-8b9d-a7f05d152213.png)

**Comment by Wangyaqi** [comment]
文档里面的引入方式容易造成迷惑，已修改。  import uniSteps from '@/components/uni-steps/uni-steps.vue'
