### ISSUE TITLE
uniIcons组件编译后在APP中不显示

### ISSUE THREAD

**Issue by sdzbzjh** [dcloudio/uni-ui#108]

**Comment by sdzbzjh** [comment]
编译无报错，APP不显示图标

**Comment by Wangyaqi** [comment]
运行到哪端？用的uniIcons是插件市场，Github还是npm安装的？

**Comment by Wangyaqi** [comment]
长时间未响应暂时关闭

**Comment by sdzbzjh** [comment]
> 运行安卓还是IOS？用的uniIcons是插件市场，Github还是npm安装的？

使用错误，现已解决问题，没注意icon变成icons了

**Comment by Wangyaqi** [comment]
之前这个修改发过公告，应该还是有些没通知到
