### ISSUE TITLE
nvue中使用uni-ui提示：You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by luchuan163** [dcloudio/uni-ui#112]
**uni-ui版本: 1.1.103
HBuilder X版本：2.4.4**
**代码：**
![QQ截图20191211150820](https://user-images.githubusercontent.com/34016172/70599431-15e7be00-1c28-11ea-8e58-a4ba8e2ee31f.jpg)

**APP端运行报错：**
![QQ截图20191211150519](https://user-images.githubusercontent.com/34016172/70599399-04061b00-1c28-11ea-90d9-aff894898adc.jpg)

**Comment by Wangyaqi** [comment]
把你的项目发上来我试试

**Comment by luchuan163** [comment]
[demo.zip](https://github.com/dcloudio/uni-ui/files/3953768/demo.zip)

**Comment by luchuan163** [comment]
> 把你的项目发上来我试试

[demo.zip](https://github.com/dcloudio/uni-ui/files/3953770/demo.zip)

**Comment by luchuan163** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"王亚琪"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月12日(星期四) 上午10:44
收件人:&nbsp;"dcloudio/uni-ui"<uni-ui@noreply.github.com&gt;;
抄送:&nbsp;"川歌"<417444176@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dcloudio/uni-ui] nvue中使用uni-ui提示：You may need an appropriate loader to handle this file type. (#112)




把你的项目发上来我试试

**Comment by Wangyaqi** [comment]
暂时不要在HBuilderX创建的项目中使用npm安装uni-ui，有待修复

**Comment by mylovehai** [comment]
原来不是我的问题。。。坐等修复

**Comment by mehaotian** [comment]
最新版本 HbuilderX 已经修复此问题，请更新hx验证，issues 将关闭，如有问题，请重新打开。
