### ISSUE TITLE
uni-number-box 在使用step为小数时有bug

### ISSUE THREAD

**Issue by hackchen01** [dcloudio/uni-ui#114]
使用代码
`<uni-number-box :value="1.1" :min="1.1" :max="8" :step="0.1"></uni-number-box>`
这样设置导致按加减按钮无法改变值，提供修复BUG方法
组件内 _calcValue 方法调整为
`_calcValue(type) {
				if (this.disabled) {
					return;
				}
				const scale = this._getDecimalScale();
				let value = this.inputValue * scale;
				let step = this.step * scale;
				if (type === "minus") {
					value -= step;
					if (value < (this.min * scale)) {
						return;
					}
					if(value > (this.max * scale)){
						value = this.max
					}
				} else if (type === "plus") {
					value += step;
					if (value > (this.max * scale)) {
						return;
					}
					if(value < (this.min * scale)){
						value = this.min
					}
				}

				this.inputValue = String(value / scale);
			},`

**Comment by hackchen01** [comment]
好像看的不大清楚，_calcValue 方法内判断 this.min 和 this.max 时需要乘以 scale 才能正确。

**Comment by hackchen01** [comment]
使用时
`<uni-number-box :value="1.1" :min="1.1" :max="8" :step="0.1"></uni-number-box>`

**Comment by mehaotian** [comment]
已经修改，这种情况，您可以直接提交pr
