### ISSUE TITLE
uni-number-box 当输入框内容为空时按加减按钮BUG

### ISSUE THREAD

**Issue by hackchen01** [dcloudio/uni-ui#115]
重现步骤，把输入框清空后，点击 加 / 减 按钮，计算错误
修复方法，_calcValue 方法，在 let value = this.inputValue * scale; 之前 加上 
`if(this.inputValue < this.min){
					this.inputValue = this.min;
				}`

**Comment by mehaotian** [comment]
下载更新最新 nuve-uni-ui 分支，已经修复该问题
