### ISSUE TITLE
倒计时组件，再ios上不显示

### ISSUE THREAD

**Issue by Darren-chenchen** [dcloudio/uni-ui#119]
微信小程序： 倒计时组件，ios上不显示，安卓和模拟器没问题。

使用方式
<UniCountdown v-if="remainSecond > 0" color="#000" background-color="#FFF" border-color="#FFF"
            @timeup="orderTimeup" 
			:show-day="false" 
			:hour="0" 
			:minute="remainMinutes" 
			:second="remainSecond">
          </UniCountdown>

倒计时
https://github.com/dcloudio/uni-ui/blob/master/src/components/uni-countdown/uni-countdown.vue

**Comment by Darren-chenchen** [comment]
安卓真机 
![image](https://user-images.githubusercontent.com/16269032/71066756-3ecefc80-21ae-11ea-9031-cf757a03c4bf.png)

ios 真机
![image](https://user-images.githubusercontent.com/16269032/71066810-6625c980-21ae-11ea-8297-7740eac0a11b.png)

**Comment by mehaotian** [comment]
微信小程序的 真机云兰 ios 不显示？ 还是 app 端的 ios 不显示？

**Comment by Darren-chenchen** [comment]
微信小程序的

**Comment by Darren-chenchen** [comment]
问题已找到，需要对后端返回的时间字符串处理下，不然真机转换成的date是null   
		let endStr = endTimer.replace(/-/g,"/");
