### ISSUE TITLE
UniIcons组件在安卓端的nvue页面(原生子窗体页面做为导航栏)的绑定事件无法触发

### ISSUE THREAD

**Issue by Yangson-Hung** [dcloudio/uni-ui#120]
### 配置文件
![image](https://user-images.githubusercontent.com/32238889/71167858-7910ca80-2290-11ea-89cc-c1899a8c13d1.png)
### 目录结构
![image](https://user-images.githubusercontent.com/32238889/71167898-8c239a80-2290-11ea-8ca0-1113572945b1.png)
### 主要代码
![image](https://user-images.githubusercontent.com/32238889/71167925-9cd41080-2290-11ea-851b-dd09fbafe414.png)
#### 绑定的事件
![image](https://user-images.githubusercontent.com/32238889/71168551-f8eb6480-2291-11ea-83ad-9937ca89f727.png)
_UniIcons使用的是_
[UniIcons](https://github.com/dcloudio/uni-ui/blob/master/src/components/uni-icons/uni-icons.vue)
这个和IDE创建的Hello-uniapp示例工程里的组件一样，我用的是工程里的

### 不使用UniIcons，可以触发
![image](https://user-images.githubusercontent.com/32238889/71169442-dfe3b300-2293-11ea-83ae-d0d0f47865c3.png)
![image](https://user-images.githubusercontent.com/32238889/71169458-e96d1b00-2293-11ea-89fb-a2436d56fb3b.png)
![image](https://user-images.githubusercontent.com/32238889/71169462-ec680b80-2293-11ea-87db-4cadbbb1578d.png)

**Comment by Wangyaqi** [comment]
你把项目打个zip包发上来我试试

**Comment by Yangson-Hung** [comment]
[bug-demo.zip](https://github.com/dcloudio/uni-ui/files/3983748/bug-demo.zip)

### 创建的新工程

**Comment by Yangson-Hung** [comment]
@Wangyaqi  你好,找到问题了吗

**Comment by Yangson-Hung** [comment]
![image](https://user-images.githubusercontent.com/32238889/71365276-70dec500-25d9-11ea-9cd9-ed25abd65995.png)

不好意思,我找到原因了,只要把绑定事件给 `uni-icons` 就行,我现在 `ide` 版本是  `2.4.6.20191210`。我之前的版本是 `2.4.2.20191115 `，然后之前的版本我在 `view` 里写  `uni-icons` ，然后绑定事件给 `view` 是没有问题的，升级到 `2.4.6` 版本就出现了这个问题。我估计是 `2.4.2` 版本的 `bug`

**Comment by Yangson-Hung** [comment]
![Snipaste_2019-12-23_23-20-04](https://user-images.githubusercontent.com/32238889/71365719-cb2c5580-25da-11ea-81ad-a23babc3175c.png)
![Snipaste_2019-12-23_23-26-11](https://user-images.githubusercontent.com/32238889/71366003-a84e7100-25db-11ea-935d-339f4bed4351.png)
如果我把` uni-icons.vue` 里的 `click `事件去掉，自己的事件还是写在 `view` 上，也没有问题。
所以是 `uni-icons` 内部的 `click` 事件影响了我自己的 `view` 的事件绑定。
**给个建议**：这种图标静态组件不要给 绑定事件，示例工程完全可以 图标外加个 `view` 绑定事件，没必要在图标组件内部搞个事件处理

**Comment by Wangyaqi** [comment]
我用了2.4.6也没出现你这个问题

**Comment by Yangson-Hung** [comment]
用的是我发的demo吗

**Comment by Wangyaqi** [comment]
用了你的demo确实有问题，我们研究研究
