### ISSUE TITLE
badge小红点样式问题

### ISSUE THREAD

**Issue by dying318** [dcloudio/uni-ui#123]
.uni-badge 为什么要加padding: 0px 6px;，好好的小红点变成长条，感觉发布测试很不够啊，之前已经提过一个样式问题。

**Comment by dying318** [comment]
两次升级uni-app，都是遇到bug回退了，不知道什么时候可以升级【捂脸】

**Comment by Wangyaqi** [comment]
因为无法确定用户会传什么进来。遇到具体Bug可以提出来

**Comment by Wangyaqi** [comment]
uni-app的Bug可以在uni-app的仓库下提，我们会尽快解决

**Comment by dying318** [comment]
> 因为无法确定用户会传什么进来。遇到具体Bug可以提出来
是指text吗？我传的是空格，因为不传的话，小红点显示不出来，这个应该算最基本的使用场景了吧。其实如果应用了dot样式，应该是不需要依赖text的

**Comment by Wangyaqi** [comment]
这个不是做红点的，设计的时候就是需要一个text的。你这个需求我们看一下怎么好弄，因为这个项目也要兼容nvue

**Comment by dying318** [comment]
不好意思，没细看，dot是项目里面自己额外加的样式。
我重新看了下uni-badge的样式，个人理解设置badge设置width没必要吧。如果height和line-height都是16px，font-size是10px，为了保持上下左右边距一致，可以`padding:0 3px; `，为了美观左右边距大一点也可以。如果text为空，那可以设置min-width为10px, 这样即使text为空，也是一个圆形。

**Comment by Wangyaqi** [comment]
min-width nvue不支持，想要多端统一不能直接这么玩

**Comment by dying318** [comment]
哦，nvue 这个没有研究。min-width只是为了支持text为空的情况下，也不一定需要考虑这个。主要是不能理解`width: 15px !important; `，既然还是important看来还是有我不知道的原因吧【捂脸】，但是简单的理解这里就是一个定高宽度自适应的元素吧。

**Comment by Wangyaqi** [comment]
你用的uni-badge是什么时候下载的，我看了最近好几个版本都没有这种写法了

**Comment by dying318** [comment]
再次不好意思，也是项目里面额外加的样式，查看样式没注意class是哪边定义的
