### ISSUE TITLE
SassError: Invalid argument(s): Unsupported output style "nested".

### ISSUE THREAD

**Issue by DijinDiandian** [dcloudio/uni-ui#126]
@ ./src/pages/common/video/video_intro_page.vue
 @ ./src/pages.json
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.24:8082/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./node_modules/@dcloudio/uni-ui/lib/uni-pagination/uni-pagination.vue?vue&type=style&index=0&id=2a2fdb66&lang=scss&scoped=true&

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Invalid argument(s): Unsupported output style "nested".

编译的时候报这个错，哪里配置不对嘛？
对应的版本是：

HBuilder X 2.5.1  
"@dcloudio/uni-ui": "^1.1.3"

**Comment by mehaotian** [comment]
提供一下代码片段，看一下怎么使用的

**Comment by mehaotian** [comment]
更新到最新的 HBuilderX ,  测试问题是否修复

**Comment by liugang** [comment]
https://github.com/webpack-contrib/sass-loader/issues/749

不要安装 `node-sass`, 安装 `sass` 可以解决：

```
npm install --save-dev sass fibers
```

https://www.npmjs.com/package/sass

A pure JavaScript implementation of Sass. Sass makes CSS fun again.

完整步骤：

```
npm install @dcloudio/uni-ui
npm install sass-loader
npm install --save-dev sass fibers
```


README里面的说明会导致这个issue遇到的问题：
> uni-ui 依赖 scss，若是 HBuilderX 中创建的 uni-app 项目，需要在 HBuilderX 中安装 scss 插件；如果是使用 cli 创建的 uni-app 项目，需要在项目下npm安装 node-sass 和 sass-loader

应该是：
> uni-ui 依赖 scss，若是 HBuilderX 中创建的 uni-app 项目，需要在 HBuilderX 中安装 scss 插件；如果是使用 cli 创建的 uni-app 项目，需要在项目下npm安装 sass, fibers 和 sass-loader
