### ISSUE TITLE
npm 1.1.5版本，app端 vue页面，uniNumberBox有问题

### ISSUE THREAD

**Issue by huanghaodong** [dcloudio/uni-ui#128]
初始值不限，点+或-报错如下
```_vm._calcValue is not a function; [Component] Event Handler Error @ node-modules/@dcloudio/uni-ui/lib/uni-number-box/uni-number-box#handleEvent```

**Comment by mehaotian** [comment]
所有平台报错？还是个别平台报错？

**Comment by huanghaodong** [comment]
目前只用到了

> 所有平台报错？还是个别平台报错？

其他平台不清楚。

**Comment by mehaotian** [comment]
升级最新 uni-ui ，问题已经修复
