### ISSUE TITLE
需求：NumberBox 可否提供标识，当页面中有多个NumberBox时无法确定是哪个NumberBox 

### ISSUE THREAD

**Issue by chendanlin** [dcloudio/uni-ui#129]
像购物车这样不确定数量的NumberBox ，无法为每个@change单独写一个方法，我需要有一个可以标识我触发的NumberBox 的属性

**Comment by Wangyaqi** [comment]
灵活的运用一下$event可以实现你这个需求

**Comment by chendanlin** [comment]
@Wangyaqi 是否是这样使用，但是这样我还是无法得到event
<uni-number-box @change="handleNumberChange($event)"></uni-number-box>

**Comment by Wangyaqi** [comment]
> @Wangyaqi 是否是这样使用，但是这样我还是无法得到event
> <uni-number-box @change="handleNumberChange($event)">

是你用$event接收原本的参数，然后用index之类的标识到底是哪一个，比如：
```
<view v-for="(item,index) in list" :key="index">
  <uni-number-box @change="handleNumberChange($event,index)">
</view>
```

**Comment by chendanlin** [comment]
<uni-number-box @change="handleNumberChange($event,index)">
这种使用方式完美解决了我的问题，十分感谢 @Wangyaqi
