### ISSUE TITLE
什么时候发布H5版本的demo页面？

### ISSUE THREAD

**Issue by kevinlvhsl** [dcloudio/uni-ui#13]
既然uni-ui是支持H5的，网页版demo什么时候发布？ uni-ui.io啥的demo页面好提前体验一下。

**Comment by hbcui1984** [comment]
手机浏览器访问：https://uniapp.dcloud.io/h5/pages/tabBar/extUI/extUI

**Comment by FullOfVigour** [comment]
@hbcui1984 您好，请问这个示例项目的源码能开放出来吗？如果已经开放了，能给个地址吗？
