### ISSUE TITLE
uni-drawer  抽屉无法设置宽度

### ISSUE THREAD

**Issue by 1025431504** [dcloudio/uni-ui#131]
![image](https://user-images.githubusercontent.com/48747641/72678029-20c22800-3add-11ea-81d7-c5fc92125a56.png)
设置组件宽度 整体的宽度都给修改了并没有修改弹出层的宽度，

**Comment by 1025431504** [comment]
代码里直接写死宽度 220px有点僵硬了

**Comment by yutiansut** [comment]
对 老版本的可以调  我回 0.0.6版本了

**Comment by 1025431504** [comment]
> 对老版本的可以调我回0.0.6版本了
你跳回去了吗 npm装的还是不行啊

**Comment by 1025431504** [comment]
这个插件还维护吗
