### ISSUE TITLE
@dcloudio/uni-ui 发行包中没有指定入口文件，如何实现import {uniBadge} from '@dcloudio/uni-ui'引入？

### ISSUE THREAD

**Issue by huadong** [dcloudio/uni-ui#135]
各位大神，使用说明中
```javascript
import {uniBadge} from '@dcloudio/uni-ui'
//import uniBadge from '@dcloudio/uni-ui/lib/uni-badge/uni-badge.vue' //也可使用此方式引入组件
export default {
    components: {uniBadge}
}
```

@dcloudio/uni-ui 发行包（版本：1.1.8）里没有指定入口文件，这个写法是怎么实现引入的？
>import {uniBadge} from '@dcloudio/uni-ui'

是必须在HBuilderX中使用吗？

我在vscode + typescript这么用，编译报错：
>Cannot find module '@dcloudio/uni-ui'
>import { uniBadge } from '@dcloudio/uni-ui'; 

求教🙏

**Comment by ZhiGang-Fang** [comment]
+1

**Comment by huadong** [comment]
这是由uni-app模板编译器提供解析。建议使用新的方式：easycom。

**Comment by syymo** [comment]
> 这是由uni-app模板编译器提供解析。建议使用新的方式：easycom。

vscode怎么解决呢？

**Comment by mrlmx** [comment]
> > 这是由uni-app模板编译器提供解析。建议使用新的方式：easycom。
> 
> vscode怎么解决呢？

@syymo  可以参考这里：https://github.com/dcloudio/uni-ui/issues/185#issuecomment-694959592
