### ISSUE TITLE
uni-list-item组件支付宝小程序报错

### ISSUE THREAD

**Issue by zengqingsong** [dcloudio/uni-ui#137]
支付宝小程序报如下错误：微信小程序正常。

从子分包页面登陆跳转到主分包出现如下错误，如果正常进入主分包页面没有错误。

[Vue warn]: Injection "list" not found

found in

---> /components/uni-list-item/uni-list-item
       <Root>

**Comment by Wangyaqi** [comment]
试试真机，看正常不

**Comment by mehaotian** [comment]
长时间未回复，issues 将关闭，如有问题，请重新打开
