### ISSUE TITLE
uni-swipe-action引入组件后编译正常，但微信小程序中直接报错, 编译位置跑到外层目录去了? 复制过来就没问题了, 赶紧修复一下 

### ISSUE THREAD

**Issue by msdog** [dcloudio/uni-ui#138]
系统win10

使用vue-cli搭建的项目，package.json显示
dependencies：    "@dcloudio/uni-ui": "^1.1.8",
devDependencies
    "@dcloudio/uni-cli-shared": "^2.0.0-25120200103006",
    "@dcloudio/uni-migration": "^2.0.0-25120200103006",
    "@dcloudio/uni-template-compiler": "^2.0.0-25120200103006",
    "@dcloudio/vue-cli-plugin-hbuilderx": "^2.0.0-25120200103006",
    "@dcloudio/vue-cli-plugin-uni": "^2.0.0-25120200103006",
    "@dcloudio/vue-cli-plugin-uni-optimize": "^2.0.0-25120200103006",
    "@dcloudio/webpack-uni-mp-loader": "^2.0.0-25120200103006",
    "@dcloudio/webpack-uni-pages-loader": "^2.0.0-25120200103006",

引入方式如下：
import { uniSwipeAction } from '@dcloudio/uni-ui'; export default { components: { uniSwipeAction } }
然后编译成功，微信小程序开发工具报错如下：
`
VM369:1 ./node-modules/@dcloudio/uni-ui/lib/uni-swipe-action/uni-swipe-action.wxml
./index.wxs not found from ./node-modules/@dcloudio/uni-ui/lib/uni-swipe-action/uni-swipe-action.wxml
![image](https://user-images.githubusercontent.com/34001318/75501084-ddc37080-5a09-11ea-9060-7cf300c17242.png)
怎么编译位置跑到外层目录去了? 复制过来就没问题了, 赶紧修复一下

**Comment by mehaotian** [comment]
提供一个你当前项目的demo ，问题一直复现不出来，看是不是有什么特殊的用法

**Comment by dailijian** [comment]
编译成微信小程序还是有这个问题
<img width="438" alt="截屏2021-04-03 下午4 18 55" src="https://user-images.githubusercontent.com/19890195/113472846-4c3df200-9498-11eb-9422-3522318b485d.png">
