### ISSUE TITLE
uniGrid click 事件有问题

### ISSUE THREAD

**Issue by loewe0202** [dcloudio/uni-ui#14]
![image](https://user-images.githubusercontent.com/18388889/55141516-840d5300-5175-11e9-9d1b-07c05df222b6.png)

点击效果：

![image](https://user-images.githubusercontent.com/18388889/55141531-8bccf780-5175-11e9-8c63-f85e2227e5e6.png)

**Comment by loewe0202** [comment]
我把 columnNum 写成 4  之后页面就乱了
![image](https://user-images.githubusercontent.com/18388889/55142108-cdaa6d80-5176-11e9-8cc0-7530250a5ec5.png)

**Comment by Aspirelz** [comment]
0.0.5 版本源码错误 ，uni-grid 中props 中定义的是columnNum ，使用的却是columnNumber
![image](https://user-images.githubusercontent.com/49021509/55144994-e3bb2c80-517c-11e9-9716-0dd1cae03e92.png)

**Comment by Aspirelz** [comment]
> 我把 columnNum 写成 4 之后页面就乱了
> ![image](https://user-images.githubusercontent.com/18388889/55142108-cdaa6d80-5176-11e9-8cc0-7530250a5ec5.png)

**Comment by dcloudhdx** [comment]
0.0.6已修复
