### ISSUE TITLE
uni-popup 弹窗 滚动事件会透传

### ISSUE THREAD

**Issue by cwwise** [dcloudio/uni-ui#140]
在支付宝小程序和头条小程序上有问题，微信小程序没有问题，

**Comment by HungryFour** [comment]
同上。

**Comment by mehaotian** [comment]
这个问题受限于小程序，所以 uni-ui 暂时还无解决此问题。

**Comment by cwwise** [comment]
不是啊，我后来的解决办法是自己按照网上的方式写的 可以解决

**Comment by HungryFour** [comment]
> 不是啊，我后来的解决办法是自己按照网上的方式写的 可以解决

支付宝的也可以解决吗。 可以贴出方法吗。
