### ISSUE TITLE
uni-drawer 的close事件代码执行两次

### ISSUE THREAD

**Issue by songsgroup** [dcloudio/uni-ui#146]
uni-drawer如果在close事件中设定visible属性，那么close事件就会执行两次。
测试方法：
在在pages/extUI/drawer/drawer.nvue的代码中
closeDrawer(e) {
				if (e === 'left') {
					this.showLeft = false
				} else {
					this.showRight = false
				}
				console.info("关闭信息");
			},
当点击空白处关闭的时候，可以看到输出两次“关闭信息”。
查看源代码发现关闭广播一次事件，修改属性的时候又广播一次事件。

**Comment by mehaotian** [comment]
bug 已经修复
