### ISSUE TITLE
uni-popup 弹窗内容无法滚动

### ISSUE THREAD

**Issue by ZeyZhang** [dcloudio/uni-ui#147]
在头条小程序中弹窗内容无法滚动

**Comment by mehaotian** [comment]
弹窗本身就没有滚动，需要在插槽中指定插槽内最外层元素的高度，如果使用scroll-view ，需要给scroll-view 指定固定高度。

issues 将关闭，如有问题，请重新打开

**Comment by Hideer** [comment]
@mehaotian @ZeyZhang  你好使用uni-popup 在支付宝小程序中能正常滚动，在微信上不能正常滚动,有对应的解决方案么

**Comment by prianyu** [comment]
> 弹窗本身就没有滚动，需要在插槽中指定插槽内最外层元素的高度，如果使用scroll-view ，需要给scroll-view 指定固定高度。
> 
> issues 将关闭，如有问题，请重新打开

上面的反馈是没有问题的，uni-popup本身不可滚动，可以通过在slot里设置外层容器来设置设置滚动。但是由于uni-popup的最外层使用了@touchmove.stop.prevent，这将导致在头条小程序下，slot里面的scroll-view无法滚动

**Comment by shensong1002** [comment]
怎么解决的

**Comment by dmcxys** [comment]
改造一下  uni-popup.vue
<view v-if="showPopup" class="uni-popup" :class="[popupstyle]">
		
		<uni-transition :mode-class="ani" :styles="transClass" :duration="duration" :show="showTrans" @click="onTap">
			<view @touchmove.stop.prevent="clear">
				<uni-transition v-if="maskShow" :mode-class="['fade']" :styles="maskClass" :duration="duration" :show="showTrans" @click="onTap" />
			</view>
			<view class="uni-popup__wrapper-box" @click.stop="clear">
				<slot />
			</view>
		</uni-transition>
	</view>

**Comment by dmcxys** [comment]
`<view v-if="showPopup" class="uni-popup" :class="[popupstyle]">
		<uni-transition :mode-class="ani" :styles="transClass" :duration="duration" :show="showTrans" @click="onTap">
			<view @touchmove.stop.prevent="clear">
				<uni-transition v-if="maskShow" :mode-class="['fade']" :styles="maskClass" :duration="duration" :show="showTrans" @click="onTap" />
			</view>
			<view class="uni-popup__wrapper-box" @click.stop="clear">
				<slot />
			</view>
		</uni-transition>
	</view>`

**Comment by dmcxys** [comment]
用 scroll-view 即可
