### ISSUE TITLE
多层级选择的组件方案

### ISSUE THREAD

**Issue by hugetiny** [dcloudio/uni-ui#148]
目前组件中我用多个SegmentedControl
如果选项过多，就有很多行SegmentedControl，样式很奇怪
有其他nvue的方案吗？

**Comment by hugetiny** [comment]
需求是第一眼就能看到小部分的二级菜单

**Comment by mehaotian** [comment]
后面会看情况，增加一些额外的自定义功能。暂时还没有太好的解决方案
