### ISSUE TITLE
uni-ui 能和 element-ui 一样全局使用么？

### ISSUE THREAD

**Issue by loewe0202** [dcloudio/uni-ui#15]
![image](https://user-images.githubusercontent.com/18388889/55142318-47425b80-5177-11e9-9631-669840898ec4.png)

**Comment by loewe0202** [comment]
import Vue from 'vue'
import UniUI from 'uni-ui'
import App from './App'

Vue.config.productionTip = false

App.mpType = 'app'

Vue.use(UniUI)

const app = new Vue({
	...App
})
app.$mount()

这样使用会报错

**Comment by 1353619565** [comment]
![image](https://user-images.githubusercontent.com/30641714/56403880-04673580-6296-11e9-8b50-c4560336add9.png)
会不会是你导入的名字不正确呢

**Comment by loewe0202** [comment]
上面的引用是在每个要使用的页面中引用，但是我想要的效果是在app.js中引用之后在其他页面就不需要引用了




| |
loewe0202
邮箱：18170146863@163.com
|

Signature is customized by Netease Mail Master

在2019年04月19日 11:27，uyu 写道：


会不会是你导入的名字不正确呢

**Comment by 1353619565** [comment]
> 上面的引用是在每个要使用的页面中引用，但是我想要的效果是在app.js中引用之后在其他页面就不需要引用了
是通过 npm install uni-ui 还是npm install @dcloudio/uni-ui 导入的呢，如果是后者是不是应该写 import UniUi from '@dcloudio/uni-ui'

**Comment by 1353619565** [comment]
> 上面的引用是在每个要使用的页面中引用，但是我想要的效果是在app.js中引用之后在其他页面就不需要引用了
是通过 npm install uni-ui 还是npm install @dcloudio/uni-ui 导入的呢，如果是后者是不是应该写 import UniUi from '@dcloudio/uni-ui'

**Comment by 1353619565** [comment]
> 上面的引用是在每个要使用的页面中引用，但是我想要的效果是在app.js中引用之后在其他页面就不需要引用了

是通过 npm install uni-ui 还是npm install @dcloudio/uni-ui 导入的呢，如果是后者是不是应该写 import UniUi from '@dcloudio/uni-ui'

**Comment by javascriptchen** [comment]
h5支持，其他平台不支持
