### ISSUE TITLE
在ios13.4中nvue页面白屏，麻烦能够紧急解决一下吗？

### ISSUE THREAD

**Issue by adrianWCC** [dcloudio/uni-ui#150]
uni-icons在ios版本13.4中 nvue页面白屏。

**Comment by mehaotian** [comment]
是什么样的白屏？ 什么内容都不显示 ？只显示 tabbar ？ 其他组件有无这个问题 ？真机还是模拟器？有无报错？

**Comment by mehaotian** [comment]
因为长时间未回复，暂时关闭 issues ,如仍有问题，请重新打开。
