### ISSUE TITLE
grid组件和自己写flex布局的区别

### ISSUE THREAD

**Issue by hugetiny** [dcloudio/uni-ui#151]
grid组件和自己写flex布局的区别是什么，试了一下支付宝小程序 grid案例好像更新一点（配了一点应用的图标），但是边框都乱了，有的多有的少。

**Comment by mehaotian** [comment]
使用组件的目的，就是为了减少自己的布局 ，提供一些额外的功能，直接使用，不需要自己去写这些逻辑。
