### ISSUE TITLE
form表单提交函数无法获取picker的name值

### ISSUE THREAD

**Issue by Yangson-Hung** [dcloudio/uni-ui#155]
平台：app安卓端
HX版本：2.6.9.20200403
代码：
![image](https://user-images.githubusercontent.com/32238889/78870875-6a396800-7a79-11ea-8efb-8c1aed66616e.png)
![image](https://user-images.githubusercontent.com/32238889/78871062-b5ec1180-7a79-11ea-8a99-303005bdcaeb.png)
页面：
![image](https://user-images.githubusercontent.com/32238889/78871086-be444c80-7a79-11ea-9d1c-a6e661668240.png)
结果：
![image](https://user-images.githubusercontent.com/32238889/78871124-cdc39580-7a79-11ea-8a56-793adbd2e32f.png)
其他都有：
![image](https://user-images.githubusercontent.com/32238889/78871276-0e231380-7a7a-11ea-87d9-60eab5618b6f.png)

**Comment by Wangyaqi** [comment]
uni-app的问题可以去uni-app仓库下发issue
