### ISSUE TITLE
Cannot find module './uni-badge.vue

### ISSUE THREAD

**Issue by lijiananha** [dcloudio/uni-ui#158]
Cannot find module './uni-badge.vue 
重现
1.npm install @dcloudio/uni-ui
2.<template>
	<view class="content">
		<uni-badge text="1"></uni-badge>
		<uni-badge text="2" type="success" @click="bindClick"></uni-badge>
		<uni-badge text="3" type="primary" :inverted="true"></uni-badge>
	</view>
</template>

<script>
	import uniBadge from '@dcloudio/uni-ui/lib/uni-badge/uni-badge.vue' 
	
	export default{
		components: {uniBadge}
	};
</script>

**Comment by lijiananha** [comment]
npm install sass-loader -D
npm install node-sass -D

**Comment by mehaotian** [comment]
cli 还是 hx 项目？ 看一下 node_modules/@dcloudio/uni-ui 下是否成功安装 uni-ui

**Comment by mehaotian** [comment]
因长时间未回复，暂时关闭 issues ，如仍有问题，请重新打开。
