### ISSUE TITLE
uni-list-item如何绑定touch事件

### ISSUE THREAD

**Issue by yupeng2015** [dcloudio/uni-ui#16]
uni-list-item绑定了touch事件，发现提示错误。
代码：
`<uni-list>
<uni-list-item @touchstart="touchStart" @touchmove="touchMove" v-for="(item,index) in task.data" :title="item.content" class="uni-list-item" show-arrow="false"></uni-list-item>
</uni-list>`
运行到微信开发工具报错：
`VM657:1 thirdScriptError
Cannot read property 'touches' of undefined; [Component] Event Handler Error @ pages/index/Index#handleEvent
TypeError: Cannot read property 'touches' of undefined`

**Comment by 1353619565** [comment]
可以贴一下component中对应函数的代码，便于定位Cannot read property 'touches' of undefined这个错误

**Comment by yupeng2015** [comment]
> 可以贴一下component中对应函数的代码，便于定位Cannot read property 'touches' of undefined这个错误

这个组件是dcloudio/uni-ui里面的uniListItem，我没细查，不过我的解决方案是在uniListItem的外层套了一层view，把事件绑定到view就可以了，暂时就先这样解决吧
