### ISSUE TITLE
我想将今天以前的日期都弄成灰色不可选应该改哪里？

### ISSUE THREAD

**Issue by Tron1234** [dcloudio/uni-ui#164]
如题

**Comment by mehaotian** [comment]
设置开始时间，startDate

**Comment by Tron1234** [comment]
ok

**Comment by Tron1234** [comment]
因为我的需求是弹框模式需要监听change事件，我这边改了代码，打开了change事件，但是selected不能实时监听数据变化，因为是数组，直接用watch无法监听到数据变化，我通过将selected转成Json字符串放在computed中，再对computed的这个属性进行监听，才能监听到数据变化

**Comment by mehaotian** [comment]
> 因为我的需求是弹框模式需要监听change事件，我这边改了代码，打开了change事件，但是selected不能实时监听数据变化，因为是数组，直接用watch无法监听到数据变化，我通过将selected转成Json字符串放在computed中，再对computed的这个属性进行监听，才能监听到数据变化

组件内不对 selected 做特殊处理，应该在给selected赋值的时候，就确定数组内数据发生变化，使用 $set 去更新数据 ，或者使用 splice 去更新数据。

**Comment by Tron1234** [comment]
我用的是$set，但是组件内监听不到selected的变化，后来查了下

利用这个方法成功监听到selected数据变化






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "HaoTian"<notifications@github.com&gt;; 
发送时间: 2020年5月11日(星期一) 下午3:48
收件人: "dcloudio/uni-ui"<uni-ui@noreply.github.com&gt;; 
抄送: "夜雨般的十年"<506980247@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dcloudio/uni-ui] 我想将今天以前的日期都弄成灰色不可选应该改哪里？ (#164)





  
因为我的需求是弹框模式需要监听change事件，我这边改了代码，打开了change事件，但是selected不能实时监听数据变化，因为是数组，直接用watch无法监听到数据变化，我通过将selected转成Json字符串放在computed中，再对computed的这个属性进行监听，才能监听到数据变化
  
组件内不对 selected 做特殊处理，应该在给selected赋值的时候，就确定数组内数据发生变化，使用 $set 去更新数据 ，或者使用 splice 去更新数据。

**Comment by Tron1234** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "HaoTian"<notifications@github.com&gt;; 
发送时间: 2020年5月11日(星期一) 下午3:48
收件人: "dcloudio/uni-ui"<uni-ui@noreply.github.com&gt;; 
抄送: "夜雨般的十年"<506980247@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dcloudio/uni-ui] 我想将今天以前的日期都弄成灰色不可选应该改哪里？ (#164)





  
因为我的需求是弹框模式需要监听change事件，我这边改了代码，打开了change事件，但是selected不能实时监听数据变化，因为是数组，直接用watch无法监听到数据变化，我通过将selected转成Json字符串放在computed中，再对computed的这个属性进行监听，才能监听到数据变化
  
组件内不对 selected 做特殊处理，应该在给selected赋值的时候，就确定数组内数据发生变化，使用 $set 去更新数据 ，或者使用 splice 去更新数据。
