### ISSUE TITLE
在ios12以上 H5端双击会放大组件，难以返回

### ISSUE THREAD

**Issue by Tron1234** [dcloudio/uni-ui#165]
目前找到一个方法禁止calendar组件双击放大
首先加入一下css样式
* {
		-webkit-text-size-adjust: none;
		zoom: 1;
		touch-action: manipulation;
		cursor: pointer;
		-webkit-tap-highlight-color: rgba(0, 0, 0, 0)
	}
然后在create中加入
// #ifdef H5
			document.addEventListener("touchstart", event => {
			    if(event.touches.length > 1) {
			        console.log("zoom plz stahp");
			        event.preventDefault();
			        event.stopPropagation(); // maybe useless
			    }
			}, {passive: false});
			// #endif
即可禁止组件在safari上双击放大

**Comment by Fasttian** [comment]
双击是整页面放大应该是你的项目没有设置视口禁止缩放：
```html
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
```
