### ISSUE TITLE
关于uni-pop里面使用的几处translateY

### ISSUE THREAD

**Issue by keephungryHF** [dcloudio/uni-ui#166]
&.top {
      top: 0;
      left: 0;
      width: 100%;
      transform: translateY(-100%);
    }

    &.bottom {
      bottom: 0;
      left: 0;
      width: 100%;
      transform: translateY(100%);
    }
源代码里面的这两个transform属性一定会被后面的    
 &.uni-top,
 &.uni-bottom {
       transform: translateY(0);
  }
这个覆盖吧？

因为 在
     <view
      :class="[type, ani, animation ? 'ani' : '', !custom ? 'uni-custom' : '']"
      class="uni-popup__wrapper"
      @click="close(true)">
的里面，两个class一定会有，type里面一定是top，center或者bottom，ani里面一定是uni-top，uni-center，uni-bottom。

**Comment by mehaotian** [comment]
会被覆盖，样式里面的是废弃代码，之后会删除掉。
