### ISSUE TITLE
uni-ui的slot插槽实在是太少了

### ISSUE THREAD

**Issue by Tibbersss** [dcloudio/uni-ui#17]
例如uni-app的card，head部分就没有插槽，如果想做一个head右侧文字点击查看更多的功能，就没法做，可参考https://youzan.github.io/vant-weapp/#/card
还有list，强烈建议增加右侧插槽功能，picker和cell是绝配，然而现在只能自己布局。。。
插槽功能的设计建议参考vant和mint-ui，都很优雅使用，建议所有组件都增加扩展一下插槽功能，基本上大多数组件的传入参数所显示的dom都建议扩展成默认+slot，这样自由度更高

**Comment by Wangyaqi** [comment]
谢谢你的建议，我们尽量保证易用性与兼容性的情况下增加灵活性
