### ISSUE TITLE
在vue页面使用uni-popup组件，APP版点击蒙层关闭不了弹出层

### ISSUE THREAD

**Issue by qasim0901** [dcloudio/uni-ui#170]
在vue页面使用uni-popup组件，H5可以点击蒙层关闭弹出层，但是在APP版点击蒙层关闭不了弹出层

**Comment by mehaotian** [comment]
所有的app 都不行，还是个别机型有问题？有没有具体的报错提示

**Comment by mehaotian** [comment]
因长时间未回复，暂时关闭 issues ， 如仍有问题，请重新打开。
