### ISSUE TITLE
npm + easycom custom方式，微信小程序会提示找不到组件

### ISSUE THREAD

**Issue by laravuel** [dcloudio/uni-ui#171]
用npm方式引入ui组件库，配合easycom custom自定义组件查找方式，小程序中编译提示组件找不到。

```
// package.json 

"@dcloudio/uni-ui": "^1.1.9"
```

```
// pages.json
"easycom": {
		"autoscan": true,
		"custom": {
			"uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue"
		}
	}
```

**Comment by aetherwu** [comment]
easycom 找不到组件：

vue.runtime.esm.js?e143:619 [Vue warn]: Unknown custom element: <uni-popup-dialog> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by mehaotian** [comment]
那个组件找不到？还是所有组件都找不到 ？ 如果都找不到尝试重新编译项目

**Comment by Lang-Zh** [comment]
我也出现来  npm引入uview  app和h5正常  微信小程序就报错找不到组件

**Comment by laravuel** [comment]
我是由于使用了淘宝镜像cnpm install引起的，最后统一换成npm install就好了
