### ISSUE TITLE
<uni-list-item>中rightText内容超长出现顶掉左边title和右边arrow、撑搞整行的bug

### ISSUE THREAD

**Issue by minkayangjie** [dcloudio/uni-ui#175]
![image](https://user-images.githubusercontent.com/65053934/83345112-eb0e3500-a341-11ea-819e-f92e9b50ec97.png)

**Comment by mehaotian** [comment]
那端出现的问题？

**Comment by mehaotian** [comment]
长时间未回复 ，暂时关闭 issue ，如果还有问题请打开并继续提问
