### ISSUE TITLE
ts报错

### ISSUE THREAD

**Issue by ImKarson** [dcloudio/uni-ui#178]
Module build failed (from ./node_modules/ts-loader/index.js):
09:41:33.784 Error: error while parsing tsconfig.json
09:41:33.784     at Object.loader (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/ts-loader/dist/index.js:19:18)
09:41:33.790 [tsl] ERROR
09:41:33.790       TS18002: The 'files' list in config file 'tsconfig.json' is empty.

**Comment by mehaotian** [comment]
uni-ui 目前还没适配 ts ，建议使用 easyCom 的方式引入组件
