### ISSUE TITLE
npm 安装，编译到支付宝小程序文件带“@”，导致代码上传失败

### ISSUE THREAD

**Issue by xiaodel** [dcloudio/uni-ui#18]
npm 安装uniapp ui支付宝上传代码失败(不支持包含“@”文件名)。

import {uniBadge} from '@dcloudio/uni-ui';
 export default {
		components: {
			uniBadge
		},
![image](https://user-images.githubusercontent.com/24968415/56579433-b5f1c800-6602-11e9-832f-c1cafc7a5130.png)
![image](https://user-images.githubusercontent.com/24968415/56579448-bf7b3000-6602-11e9-84f7-0e17acd7800e.png)
![image](https://user-images.githubusercontent.com/24968415/56579531-ff421780-6602-11e9-86b2-5299e414478e.png)

![image](https://user-images.githubusercontent.com/24968415/56579543-0832e900-6603-11e9-80bd-c04673b080be.png)

**Comment by Wangyaqi** [comment]
这边测试没问题，本项目已重构为uniapp cli项目，详见readme
