### ISSUE TITLE
<uni-list-item>组件thumb设置为本地的图片路径在微信小程序报错

### ISSUE THREAD

**Issue by wengfengtong** [dcloudio/uni-ui#180]
<uni-list-item title="标题文字" thumb="@/static/imgs/icons/like.png"></uni-list-item>

**Comment by mehaotian** [comment]
怎么写的？报什么错误 ？

**Comment by mehaotian** [comment]
因长时间未回复暂时关闭issues,如还是有问题请 reopen issues。
