### ISSUE TITLE
APP端 popup 组件 this.$refs.tip.open() 有时失效，复现频率低，但多点能稳定复现

### ISSUE THREAD

**Issue by yijun-blockin** [dcloudio/uni-ui#181]
问题描述：
popup 组件 this.$refs.tip.open() 有时失效

具体场景：
答题页面点击选项，错误触发弹窗，小概率点击弹窗没有弹出（已经打了log确保点击且触发了this.$refs.tip.open()事件）

HBuilder版本：2.6.16

触发机型：安卓 Vivo X21

复现频率：偶现，且必现

具体实现：wgt包嵌入APP

**Comment by yangyl568** [comment]
我也遇到了，但是 关闭 动画好像就好了，不过 慢了点。。。  求官方出来解答下

**Comment by yijun-blockin** [comment]
> 我也遇到了，但是 关闭 动画好像就好了，不过 慢了点。。。 求官方出来解答下

关闭了动画，也会有，求官方修复

**Comment by mehaotian** [comment]
vue 页面 还是 nvue 页面？

**Comment by yijun-blockin** [comment]
> vue 页面 还是 nvue 页面？

Vue 的页面，nvue没有试过，不太清楚

**Comment by mehaotian** [comment]
> > vue 页面 还是 nvue 页面？
> 
> Vue 的页面，nvue没有试过，不太清楚

下载一个最新的 hx ，试一下 看看还会不会有这个问题？

**Comment by mehaotian** [comment]
popup 目前确实会有问题 ，是动画延时之类的影响 ，正在优化中，修复完毕会更新通知

**Comment by mehaotian** [comment]
最新组件有对应的优化 ，使用最新组件测试是否正常 ，如还有问题 ，请 reopen issues
