### ISSUE TITLE
小程序滑动bug。动态渲染的option，按钮位置不更新

### ISSUE THREAD

**Issue by sea-forever-zh** [dcloudio/uni-ui#184]
小程序滑动的问题：
左右快点滑动几次，就会无限开关。
动态渲染action的位置问题：
多个类型列表，按钮个数不一致，更换列表后，第一次渲染的按钮位置有bug。
比如，列表1有3个按钮，再切换到列表2（2个按钮），就会有一个按钮留白。如果从列表2切换到列表1，有一个按钮会不可见。

**Comment by mehaotian** [comment]
问题已经修复，下载最新组件验证，issues 暂时关闭，如果还有问题，请重新打开
