### ISSUE TITLE
typescript下无法引入uni-ui

### ISSUE THREAD

**Issue by keyiis** [dcloudio/uni-ui#185]
已经安装了组件，但是在页面引入会报错。是什么原因呢？
![image](https://user-images.githubusercontent.com/7766085/84590425-03657000-ae69-11ea-9eb9-42fc5271f488.png)

![image](https://user-images.githubusercontent.com/7766085/84590416-eaf55580-ae68-11ea-933b-57e038b396de.png)

**Comment by slgxmh** [comment]
引用的方式不对，readme里这么写的
![image](https://user-images.githubusercontent.com/13213238/87946613-d560f480-cad4-11ea-8c1e-0f807aea54d9.png)

**Comment by mrlmx** [comment]
如果 TypeScript 项目，可以考虑使用配置一下 [easycom](https://uniapp.dcloud.io/collocation/pages?id=easycom)，实现自动导入 uni-ui 的组件，用起来是否方便。

配置方式：在项目 pages.json 文件中，加入以下配置即可：

```javascript
{
    //	...
    "easycom": {
        "autoscan": true,
        "custom": {
            "^uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue"
        }
    }
}
```

![image](https://user-images.githubusercontent.com/23074726/93620285-5886c400-fa0c-11ea-8264-956715c63eea.png)

由于有些 uni-app 的组件包含了其他子组件，你有可能需要使用，所以这种情况，还是需要手动全路径导入。

```javascript
import uniCalendarItem from '@dcloudio/uni-ui/lib/uni-calendar/uni-calendar-item.vue'
```

也可以通过配置 easycom，来实现自动导入的功能，具体可以参考下方链接：

https://github.com/dcloudio/uni-ui/issues/64#issuecomment-692805163

**Comment by mehaotian** [comment]
目前uni-ui还没有适配兼容 ts ,请参考以上回答，可以使用 easyCom 的方式。后续会兼容。
