### ISSUE TITLE
日历组件，range模式，选好起始时间以后，重新选择区间，需要点击三次才能完成

### ISSUE THREAD

**Issue by candyAndBella** [dcloudio/uni-ui#186]

**Comment by candyAndBella** [comment]
比如选择了6.15-6.16.想要重新选择6.18-6.19。先点击6.18再点击6.19.无法完成选择区间。发现选择的日期从6.18变为了6.19.还需要再次点击6.18.才能完成区间的选择

**Comment by mehaotian** [comment]
在选择完成之后，下次点击是取消上次的选择结果

**Comment by mehaotian** [comment]
长时间无回复，暂时关闭 issues ，如还有问题，请重新打开
