### ISSUE TITLE
IndexedList 索引列表支付宝小程序报错

### ISSUE THREAD

**Issue by sywsywsyw** [dcloudio/uni-ui#187]
IndexedList 索引列表  组件 
`
// #ifndef APP-NVUE
				uni.createSelectorQuery()
					.in(this)
					.select('#list')
					.boundingClientRect()
					.exec(ret => {
						this.winOffsetY = ret[0].top
						this.winHeight = ret[0].height
						this.itemHeight = this.winHeight / this.lists.length
					})
				// #endif
				// #ifdef APP-NVUE
				dom.getComponentRect(this.$refs['list'], (res) => {
					this.winOffsetY = res.size.top
					this.winHeight = res.size.height
					this.itemHeight = this.winHeight / this.lists.length
				})
				// #endif
`
uni.createSelectorQuery().in(this)
.in(this) 在支付宝小程序是不被支持的 官网文档也有说明，这个应该怎么判断一下，现在在支付宝小程序报错了

**Comment by Fasttian** [comment]
用条件编译排除支付宝 #ifndef APP-NVUE || MP-ALIPAY
