### ISSUE TITLE
SwipeAction的click回调过程中，组件执行了click事件

### ISSUE THREAD

**Issue by dying318** [dcloudio/uni-ui#191]
在点击优化菜单进入click回调后，业务操作是显示一个modal窗口，另外在modal窗口的mask层添加了点击关闭的事件。
测试发现，在click回调中完成modal的显示后，mask的click事件被自动触发了，导致刚modal自动关闭了。
尝试在click回调中使用setTimeout去显示modal，可以实现跳过组件的自动click（暂猜测是组件执行了click操作）后显示modal。

**Comment by dying318** [comment]
另外，点击swipe的菜单，有个console输出

**Comment by mehaotian** [comment]
看你的代码逻辑实现，贴一下代码片段，有点没看明白你是什么意思 ，多余日志已经删除

**Comment by mehaotian** [comment]
uni-swipe-action 组件更新，可以验证是否修复您说的问题 ，issues 暂时关闭，如还有问题，请重新打开。
