### ISSUE TITLE
uniSearchBar 在微信小程序中报 hideKeyboard:fail:input not exists

### ISSUE THREAD

**Issue by saoraozhe3hao** [dcloudio/uni-ui#192]
uniSearchBar 在安卓微信小程序中报
(in promise) MiniProgramError
{"errMsg":"hideKeyboard:fail:input not exists"}

**Comment by hustlz** [comment]
我也碰到了同样的问题，mate30手机报错。
请问现在解决了么？

**Comment by hsuBnOediH** [comment]
同问

**Comment by zhetengbiji** [comment]
确认有问题的话，需要反馈的微信小程序社区。

**Comment by architectUser** [comment]
好像是输入英文或数字的时候就会有这类问题，请问有人解决这个问题吗

**Comment by PhoebeJH** [comment]
在真机调试的时候确实遇到过这个问题，但是当我提交正式版之后，使用起来是正常的，这个bug就不存在了，原本模拟器上被遮挡的部分也能看见

**Comment by yuli123456** [comment]
> uniSearchBar 在安卓微信小程序中报
> (in promise) MiniProgramError
> {"errMsg":"hideKeyboard:fail:input not exists"}

如何解决

**Comment by 18148764734** [comment]
初步排查是微信小程序那边的问题，暂未复现该问题，应该是微信小程序那边已经修复，此ISSUE暂时关闭
