### ISSUE TITLE
collapse折叠面板内容区域包含textarea会有问题

### ISSUE THREAD

**Issue by ChandZhang** [dcloudio/uni-ui#193]
问题机型：小米8；
微信版本：7.0.16；
collapse折叠面板，被折叠的内容区域使用textarea，textarea中输入内容，将面板折叠，此时，内容区域正常被折叠，但是textarea中的内容仍会显示出来。
（textarea是原生组件）

开发工具正常,Iphone手机正常, 小米8手机真机有问题.

**Comment by ChandZhang** [comment]
`<uni-collapse accordion="true">
			<uni-collapse-item title="显示标题" open="true">
				<textarea style="width: 200px;height: 100px; border: 1px solid #000000;" />
			</uni-collapse-item>
</uni-collapse>`

这样直接使用。textarea 中输入的文字，在折叠后就会显示

**Comment by mehaotian** [comment]
使用最新开发工具和组件，此问题已经不存在 ，暂时关闭 issue ,如仍有问题请 reopen issue 继续提问。
