### ISSUE TITLE
uni-list 报错Injection “list” not found

### ISSUE THREAD

**Issue by GannonSun** [dcloudio/uni-ui#194]
`<uni-list>
	<uni-list-item title="姓名" :note="a" :showArrow="false"></uni-list-item>
	<uni-list-item title="身份证号" :note="b" :showArrow="false"></uni-list-item>
	<uni-list-item title="手机号" :note="c" :showArrow="false"></uni-list-item>
</uni-list>`
如果把这一段放到card里，会报错
[Vue warn]: Injection “list” not found
undefined is not an object (evaluating ‘this.list.firstChildAppend’)

**Comment by mehaotian** [comment]
什么平台报错？

**Comment by mehaotian** [comment]
问题已经修复 ，请更新组件测试，issue 暂时关闭，如果还有疑问请重新打开并提问
