### ISSUE TITLE
uniCombox选中某一项之后，再点击选择就只会显示当前选项，必须删除当前选中内容才能显示出所有备选项

### ISSUE THREAD

**Issue by luvletterldl** [dcloudio/uni-ui#197]
![image](https://user-images.githubusercontent.com/26115291/86910586-81592600-c14c-11ea-8c87-6772759901b8.png)
![image](https://user-images.githubusercontent.com/26115291/86910600-874f0700-c14c-11ea-830c-d4ad0b88b865.png)
除非删除当前选中的内容才能显示出所有可选项

**Comment by 18148764734** [comment]
因为combox设计如此，就是根据文字来动态显示的呀
