### ISSUE TITLE
同一版本下发布到npm的代码个demo的代码不一致?npm版本有明显bug

### ISSUE THREAD

**Issue by 643104191** [dcloudio/uni-ui#201]
发布到npm的代码
105行有明显的bug
https://github.com/dcloudio/uni-ui/blob/9994b163827be6493baafcc473a1bdabebf89b63/packages/uni-ui/lib/uni-rate/mixins/rate-mixin.js#L105

但是作为demo的代码
把相关bug给修复了
https://github.com/dcloudio/uni-ui/blob/9994b163827be6493baafcc473a1bdabebf89b63/src/components/uni-rate/mixins/rate-mixin.js#L111
```javascript
this.$nextTick(() => {
  setTimeout(() => {
    this._getSize()
  }, 50)
})
```

而且demo里的代码和发布到npm里代码,很明显两份代码,
demo里的195行,发布到npm的却只有184行

不知道你们版本管理/代码同步怎么做的!!

**Comment by mehaotian** [comment]
npm 已经更新
