### ISSUE TITLE
uni-list-item show-arrow属性无效

### ISSUE THREAD

**Issue by greenmonking** [dcloudio/uni-ui#202]
``
<uni-list>
                <uni-list-item  title="用户协议" thumb="/static/images/my-img/agreement_icon.png"></uni-list-item>
            </uni-list>

箭头不显示

**Comment by greenmonking** [comment]
<uni-list>
                <uni-list-item @click="goServe('2')" title="用户协议" thumb="/static/images/my-img/agreement_icon.png"></uni-list-item>
            </uni-list>

**Comment by greenmonking** [comment]
`<uni-list>
                <uni-list-item @click="goServe('2')" title="用户协议" thumb="/static/images/my-img/agreement_icon.png"></uni-list-item>
            </uni-list>`

**Comment by mehaotian** [comment]
如果是使用npm 的话， show-arrow 已经废弃了 ，参考文档 https://github.com/dcloudio/uni-ui/tree/master/src/components/uni-list

**Comment by chenli1989** [comment]
@mehaotian show-arrow都已经废弃了，怎么1.2.5版本又改回来了？

**Comment by mehaotian** [comment]
> @mehaotian show-arrow都已经废弃了，怎么1.2.5版本又改回来了？

为了向下兼容

**Comment by mehaotian** [comment]
issue 暂时关闭，如果还有疑问请重新打开并提问

**Comment by shaoyahu** [comment]
你好 , 目前(2023-03-02)使用了 link 和 to 属性后箭头还是没有出现 , 然后上面的参考文档404了
<uni-list-item link="navigateTo" to="/pages/search/search" title="去搜索"></uni-list-item>
