### ISSUE TITLE
请教一下 Swiper 里面的 Popup 无法全屏覆盖，该怎么办好呢？

### ISSUE THREAD

**Issue by aetherwu** [dcloudio/uni-ui#204]
![](https://i.v2ex.co/81jGTXb0.png)

popup 只显示在 swiper 里了。
如果用组件通讯会让逻辑变复杂，而且难以跟随层级变化，不太想用这种方法。

**Comment by bluefantasy728** [comment]
我自己封装的弹窗也遇到了这个问题，原因应该是自己写的浮层用了position:fixed，但是一旦这个元素的某一上层父级元素用了transform:translate之后，这个浮层就不再更具窗口定位了

**Comment by aetherwu** [comment]
> ![](https://camo.githubusercontent.com/634ad050701943c8322dfbeab3540f7535638fec/68747470733a2f2f692e763265782e636f2f38316a47545862302e706e67)
> 
> popup 只显示在 swiper 里了。
> 如果用组件通讯会让逻辑变复杂，而且难以跟随层级变化，不太想用这种方法。

最后还是抽出来放到父组件里去解决了。
每个自组件自带浮层会导致渲染变慢。
