### ISSUE TITLE
uni-indexed-list 索引条不起作用

### ISSUE THREAD

**Issue by Tan-Tshunglee** [dcloudio/uni-ui#205]
![问题截图](https://user-images.githubusercontent.com/6026909/90024008-fe952f00-dce6-11ea-9b6a-9787899e6b33.png)

点击索引之后只出现了一个黑色的圆圈，没有快速定位到字母索引的列表位置

    "@dcloudio/uni-ui": "^1.2.4",

**Comment by 18148764734** [comment]
测试并未复现该问题，猜测此bug在新版的indexed-list已经修复，此ISSUE暂时关闭
