### ISSUE TITLE
建议把node-sass换成dart-sass以提高开发体验

### ISSUE THREAD

**Issue by syq7970** [dcloudio/uni-ui#206]
由于众所周知的原因node-sass在国内安装困难，官网已经主推dart-sass了，建议依赖换成dart-sass。

**Comment by mehaotian** [comment]
安装的时候 直接 npm install sass sass-loader -D 就可以了，如果报错 `TypeError: this.getOptions is not a function` ,那可能是 sass-loader 版本过高导致 ，使用 `@10.1.0` 就可以。

issue 暂时关闭 ，如仍有疑问，请reopen issue 继续提问。
