### ISSUE TITLE
uniPopup position：middle 在列表类页面中，当前页面高度超过一屏时，弹窗框的位置不对

### ISSUE THREAD

**Issue by captain-c** [dcloudio/uni-ui#21]
![image](https://user-images.githubusercontent.com/18734429/57206024-49f56380-6ff5-11e9-9b93-c4e44bfd6c1d.png)
这个top: 50%的缘故

**Comment by Wangyaqi** [comment]
问题已修改

**Comment by theForagingPawns** [comment]
问一下   unipopup里的弹窗的高度为0，无法在弹窗内做定位相关操作，有解决方法么
