### ISSUE TITLE
支付宝小程序使用collapse组件报错 Injection "collapse" not found

### ISSUE THREAD

**Issue by hongyu2016** [dcloudio/uni-ui#210]
支付宝小程序使用collapse组件报错 Injection "collapse" not found
vendor.js:5265 [Vue warn]: Injection "collapse" not found

found in

---> <UniCollapseItem> at components/uni-collapse-item/uni-collapse-item.vue

![image](https://user-images.githubusercontent.com/20429634/91113537-66208680-e6b8-11ea-917d-25fdc83fe2da.png)

**Comment by mehaotian** [comment]
组件优化了 Inject 写法，使用最新组件测试 ，如仍有问题 ，请 reopen issues
