### ISSUE TITLE
uni-popup 同一个弹窗打开多次后会延迟打开

### ISSUE THREAD

**Issue by 132liyh** [dcloudio/uni-ui#211]
实际上代码已经执行到open方法里面了
就是里面有一个定时器
目前是打开这个弹窗的时候定时器就存在了
但是清楚定时器是在下一次打开或者关闭的时候

解决办法就是把清楚定时器放到定时器 里面
定时器结束就清楚这个
问题 就解决了

**Comment by mehaotian** [comment]
最新版本优化性能问题 ，如仍有问题 ，请reopen issues
