### ISSUE TITLE
uni-popup组件在真机上需要很长时间才能弹出来

### ISSUE THREAD

**Issue by xiatianyouxue** [dcloudio/uni-ui#212]

**Comment by 132liyh** [comment]
进入组件源码
open方法里面和close方法里面
在定时器里面清楚定时器

**Comment by xiatianyouxue** [comment]
感谢回复,现在改了下快多了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dcloudio/uni-ui"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月25日(星期二) 下午4:35
收件人:&nbsp;"dcloudio/uni-ui"<uni-ui@noreply.github.com&gt;;
抄送:&nbsp;"夏天有雪"<1828432894@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dcloudio/uni-ui] uni-popup组件在真机上需要很长时间才能弹出来 (#212)





 
进入组件源码
 open方法里面和close方法里面
 在定时器里面清楚定时器

**Comment by 132liyh** [comment]
我的小程序也有这个问题
之前一直没想到看源码

**Comment by xiatianyouxue** [comment]
我一开始就去看源码了,只是没看懂






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dcloudio/uni-ui"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月25日(星期二) 下午4:46
收件人:&nbsp;"dcloudio/uni-ui"<uni-ui@noreply.github.com&gt;;
抄送:&nbsp;"夏天有雪"<1828432894@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dcloudio/uni-ui] uni-popup组件在真机上需要很长时间才能弹出来 (#212)





 
我的小程序也有这个问题
 之前一直没想到看源码

**Comment by 132liyh** [comment]
🤣

**Comment by xiatianyouxue** [comment]
尴尬了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dcloudio/uni-ui"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月25日(星期二) 下午5:07
收件人:&nbsp;"dcloudio/uni-ui"<uni-ui@noreply.github.com&gt;;
抄送:&nbsp;"夏天有雪"<1828432894@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dcloudio/uni-ui] uni-popup组件在真机上需要很长时间才能弹出来 (#212)





 
🤣

**Comment by mehaotian** [comment]
最新组件优化动画卡顿问题，如仍有问题  ，请reopen issues

**Comment by 104160112** [comment]
我定时器50毫秒，还是很慢

**Comment by 104160112** [comment]
> > 我定时器50英里，还是很慢
> 
> 那个平台安卓还是ios？vue还是nvue？系统版本是多少？

微信小程序，vue,有时候很快，有时候又很慢

**Comment by 104160112** [comment]
> 很慢指的是什么？打开慢还是动画慢？有没有开启真机调试？

就是用open打开弹窗，几秒后弹窗才出现，开发者正常，就是真机有点慢

**Comment by mehaotian** [comment]
用的组件是否最新的？ 把 open 里的源码里贴出来我看一下

**Comment by 104160112** [comment]
> 用的组件是否最新的？ 把 open 里的源码里贴出来我看一下

open() {
  this.showPopup = true
  this.$nextTick(() => {
	  clearTimeout(this.timer)
	  this.timer = setTimeout(() => {
		  this.showTrans = true
	  }, 50);
  })
  this.$emit('change', {
	  show: true
  })
}
之前同事遗留的问题，不知道是否最新版，是否要重新引入最新版

**Comment by 132liyh** [comment]
建议在open方法的时候返回Promise函数

**Comment by mehaotian** [comment]
最新 uni-popup 已经优化相关问题 ，请使用 最新组件验证性能是否有提升 ，issue 暂时关闭 ，如仍有问题请 reopen issue 继续提问。

**Comment by dilireba521** [comment]
你好，这个问题是解决了吗？我在，版本1.6.2，底部弹框操作时在iPhone X 上大概有2～3s的延迟，在红米K20 Pro上有大概 0.5～1.5s的延迟
