### ISSUE TITLE
uni-popup组件，当type为top时 input无效。type为bottom时正常。

### ISSUE THREAD

**Issue by redbattle** [dcloudio/uni-ui#216]

**Comment by redbattle** [comment]
代码示例：
```
 <uni-popup ref="popup_name" type="top">
  <view class="cu-form-group">
    <view class="title"><text class="text-red">*</text>姓名</view>
    <input v-model="params.name" type="text" placeholder="请输入姓名" />
  </view>
</uni-popup>
```

<img width="426" alt="WX20200911-144430@2x" src="https://user-images.githubusercontent.com/14000007/92877525-d27fe180-f43d-11ea-93f3-af3e655361e6.png">

<img width="426" alt="WechatIMG30" src="https://user-images.githubusercontent.com/14000007/92877764-107d0580-f43e-11ea-9b0e-7355dd9db601.jpeg">

微信开发工具表现正常；手机预览和真机调试input无效
手机系统 iOS 13.6.1
微信版本 7.0.14

**Comment by mehaotian** [comment]
组件更新 ，使用最新组件测试是否正常

**Comment by mehaotian** [comment]
如仍有问题 ，请 reopen issues
