### ISSUE TITLE
[Q]用HBuilderX 写企业微信小程序，如何使用/core/helpers/promise对企业微信的api进行自定义的promisify？

### ISSUE THREAD

**Issue by sonofmagic** [dcloudio/uni-ui#221]
在HBuilderX不知道怎么把这个util给导进来，我把源码里的interceptor.js promise.js 和 shared里面引用的方法搞进来了

**Comment by mehaotian** [comment]
关于 uni-app 请到 https://github.com/dcloudio/uni-app 下提问
