### ISSUE TITLE
uni-swipe-action-item组件嵌套使用会，导致父节点的uni-swipe-action-item 无法左右滑动

### ISSUE THREAD

**Issue by yicong1406410220** [dcloudio/uni-ui#223]
uni-swipe-action-item组件嵌套，导致父节点的uni-swipe-action-item 无法左右滑动
![0LRLU0@URE@}8 AEM %7_HR](https://user-images.githubusercontent.com/20357196/93967021-caf2fd80-fd98-11ea-8d50-e5a9fcef6331.png)
这张图是无法左滑

**Comment by yicong1406410220** [comment]
![Uploading 0LRLU0@URE@}8[AEM]%7_HR.png…]()

**Comment by Fasttian** [comment]
swipe-action 组件不支持嵌套自身
