### ISSUE TITLE
TS项目引入'@dcloudio/uni-ui'缺少声明文件

### ISSUE THREAD

**Issue by swing-hh** [dcloudio/uni-ui#224]
Cannot find module '@dcloudio/uni-ui' or its corresponding type declarations.Vetur(2307)

**Comment by mrlmx** [comment]
TypeScript 项目，可以通过如下方式引入组件：

```JavaScript
import uniBadge from '@dcloudio/uni-ui/lib/uni-badge/uni-badge.vue'
```

不过，更推荐使用使用 easycom 的方式引入，配置之后，就无需手动引入 uni-ui 组件，可以直接在项目中使用。

具体可以看此处文档：

[方式三（cli + easycom）](https://github.com/dcloudio/uni-ui#%E6%96%B9%E5%BC%8F%E4%B8%89cli--easycom)
