### ISSUE TITLE
uni-ui 表单组件 uni-forms 提交时 this.$refs.form 为undefined

### ISSUE THREAD

**Issue by Leebusan** [dcloudio/uni-ui#229]
本地测试：
[
![微信图片_20201112153001](https://user-images.githubusercontent.com/14209918/98908882-0938ad80-24fc-11eb-9049-2792a9f292d8.png)
](url)
官方示例：
![微信图片_20201112153134](https://user-images.githubusercontent.com/14209918/98908989-2a010300-24fc-11eb-8c81-8736125720f8.png)

**Comment by Fasttian** [comment]
已处理，更新到最新版本尝试
