### ISSUE TITLE
uni-app开发的多端组件库，不能被纯vue项目调用

### ISSUE THREAD

**Issue by Kellercai** [dcloudio/uni-ui#231]
想请教一下，如果想用uni-app开发多端组件库，其生成的H5组件可以让非uniapp项目引用。这个方案可行吗？目前发现uni-app的组件库都是提供给uni-app项目使用的。希望官方解答一下。

**Comment by mehaotian** [comment]
目前还不行 ，因为uni-app 内置了一些基础组件，直接用到其他项目，有些组件可能工作会不正常。

**Comment by mehaotian** [comment]
issue 暂时关闭，如果新疑问 ，请再次打开提问
