### ISSUE TITLE
canvas在uni-popup里面无效

### ISSUE THREAD

**Issue by fightingSunnyGirl** [dcloudio/uni-ui#232]

**Comment by Fasttian** [comment]
弹窗弹出后再初始化 canvas
`<template>
	<view class="">
		<button @click="open">打开弹窗</button>
		<uni-popup ref="popup" type="bottom">
			<canvas style="width: 300px; height: 200px;" canvas-id="firstCanvas" id="firstCanvas"></canvas>
		</uni-popup>
	</view>
</template>

<script>
	export default {
		data() {
			return {
			}
		},
		onLoad() {

		},
		methods: {
			open() {
				this.$refs.popup.open()
				setTimeout(() => {
					this.draw()
				}, 500)
			},
			draw() {
				var context = uni.createCanvasContext('firstCanvas')
				
				context.setStrokeStyle("#00ff00")
				context.setLineWidth(5)
				context.rect(0, 0, 200, 200)
				context.stroke()
				context.setStrokeStyle("#ff0000")
				context.setLineWidth(2)
				context.moveTo(160, 100)
				context.arc(100, 100, 60, 0, 2 * Math.PI, true)
				context.moveTo(140, 100)
				context.arc(100, 100, 40, 0, Math.PI, false)
				context.moveTo(85, 80)
				context.arc(80, 80, 5, 0, 2 * Math.PI, true)
				context.moveTo(125, 80)
				context.arc(120, 80, 5, 0, 2 * Math.PI, true)
				context.stroke()
				context.draw()
			}
		}
	}
</script>

`
