### ISSUE TITLE
HbuilderX 2.9.8 完整版 用uni-ui模板创建项目无法使用 是软件问题么？

### ISSUE THREAD

**Issue by ding-love-yu** [dcloudio/uni-ui#234]
##### 用uni-ui模板创建项目后目录结构如下：
![image](https://user-images.githubusercontent.com/16078611/100191337-e7432000-2f2a-11eb-9a6a-3ae0d5044f8f.png)
其它目录结构都没有 是否是BUG？这个该如何使用？

**Comment by Fasttian** [comment]
内部的地址错了，你先从插件市场导入[uni-ui 示例工程](uni-ui https://ext.dcloud.net.cn/plugin?id=55)
