### ISSUE TITLE
uni-combox组件问题

### ISSUE THREAD

**Issue by vbin-dev** [dcloudio/uni-ui#235]
uni-combox组件，在微信小程序上有问题，一个页面有多个此组件时，除了第一个外，其他的组件，内容不能加载，直接显示无匹配项？？？运行到chrome浏览器测试，是没问题的。环境HbuildX2.9.11 微信开发者工具1.03.2010240。还有个情况是，当表单内只存在一个 uni-combox组件，且内容列表比较长时，下拉框底部会被截断显示不全，以表单底部为界限。

**Comment by vbin-dev** [comment]
![image](https://user-images.githubusercontent.com/68646130/100212609-86c2db80-2f48-11eb-93c5-f41e730232f9.png)

**Comment by Fasttian** [comment]
确认bug

**Comment by 18148764734** [comment]
现版本已修复，此issue关闭！
