### ISSUE TITLE
组件样式能不能不加scoped？

### ISSUE THREAD

**Issue by mkanako** [dcloudio/uni-ui#236]
组件样式能不能不加scoped？我个人感觉似乎不太必要啊

目前遇到的问题是，有些组件样式我想稍微做些调整，因为加了scoped，逼得我要通过加`!important`来生效

**Comment by mehaotian** [comment]
非 Nvue 平台可以使用深度选择器 `>>>` 覆盖样式 ，scss 使用 `/deep/`
