### ISSUE TITLE
按照使用说明npm导入，并且配置了easycom，但小程序编译时找不到组件

### ISSUE THREAD

**Issue by Longder** [dcloudio/uni-ui#237]
按照使用说明npm导入，并且配置了easycom，但小程序编译时找不到组件
Component is not found in path "node-modules/@dcloudio/uni-ui/lib/uni-section/uni-section"

**Comment by jsonwu5** [comment]
H5端也是一样的问题

`Error: Cannot find module '@dcloudio/uni-ui/lib/uni-pop-up/uni-pop-up.vue'`

完全按照文档引入以及设置了easycom，node_modules里也有正确安装了@dcloudio/uni-ui文件夹

```JavaScript
// 这两种方式引入都报错
import uniPopUp from "@dcloudio/uni-ui/lib/uni-popup/uni-popup";

import { uniPopUp } from "@dcloudio/uni-ui";
```

**Comment by jsonwu5** [comment]
把pages.json里的easycom配置全部删掉，然后h5下可以使用```import uniPopUp from "@dcloudio/uni-ui/lib/uni-popup/uni-popup.vue";```这种方法引入，但是按需引入还是会报错。

**Comment by tianrenlin** [comment]
> 把pages.json里的easycom配置全部删掉，然后h5下可以使用`import uniPopUp from "@dcloudio/uni-ui/lib/uni-popup/uni-popup.vue";`这种方法引入，但是按需引入还是会报错。

感谢。几乎以npm方式引入都是这种情况，我怀疑都没认真测试过，估计主要用hbuilderx测试。草，卡了我半小时

**Comment by Fasttian** [comment]
如果是 vue-cli 创建的项目，需要安装依赖，安装 sass，sass-loader ，执行两条命令 npm i sass -D，npm i sass-loader -D

**Comment by wangxiaolei5** [comment]
我使用的时候是因为在script中引入了但是在页面上没有使用这个组件报了这个错

**Comment by cqgsm** [comment]
> > 把pages.json里的easycom配置全部删掉，然后h5下可以使用`import uniPopUp from "@dcloudio/uni-ui/lib/uni-popup/uni-popup.vue";`这种方法引入，但是按需引入还是会报错。
> 
> 感谢。几乎以npm方式引入都是这种情况，我怀疑都没认真测试过，估计主要用hbuilderx测试。草，卡了我半小时

老哥最后怎么解决的？

**Comment by zhangjuanjuan01** [comment]
import {uniTable,uniTh} from '@dcloudio/uni-ui';这样引入，直接报第二个找不到，报错信息如下：

VM369 WAService.js:2 Error: Component is not found in path "node-modules/@dcloudio/uni-ui/lib/uni-th/uni-th" (using by "pages/home/index")

但是直接通过import uniTh from '@dcloudio/uni-ui/lib/uni-th/uni-th.vue';这种方式引入就没问题
盼回复

**Comment by mehaotian** [comment]
npm 方式安装的组件，最好也使用 easycom 的方式 ，不建议使用 import 的方式，有些组件内部有引用关系 ，引用关系目前使用的是 uni_ modules的相对位置 ，所以可能会出现找不到组件的问题 ，这个问题目前只能通过  easycom 方式解决

**Comment by mehaotian** [comment]
issue 长时间不回复暂时关闭 ，如仍有疑问，请 reopen issue 继续提问。

**Comment by leyue** [comment]
长时间不回复就直接关闭。。。
你回复了吗？？？
你解决了吗。。。

**Comment by 1596944197** [comment]
所以咋解决，一个一个import？那有依赖关系的咋办？？

**Comment by mehaotian** [comment]
> 所以咋解决，一个一个import？那有依赖关系的咋办？？
配置 easycom  ，无需引入组件直接使用。
```
// pages.json
{
	"easycom": {
		"autoscan": true,
		"custom": {
			// uni-ui 规则如下配置
			"^uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue"
		}
	},
	
	// 其他内容
	pages:[
		// ...
	]
}

```

**Comment by mehaotian** [comment]
> > 所以咋解决，一个一个import？那有依赖关系的咋办？？
> > 配置 easycom  ，无需引入组件直接使用。
> 
> ```
> // pages.json
> {
> 	"easycom": {
> 		"autoscan": true,
> 		"custom": {
> 			// uni-ui 规则如下配置
> 			"^uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue"
> 		}
> 	},
> 	
> 	// 其他内容
> 	pages:[
> 		// ...
> 	]
> }
> ```



> 长时间不回复就直接关闭。。。 你回复了吗？？？ 你解决了吗。。。


看不到我上面的回复吗 ？

**Comment by 1596944197** [comment]
> > 长时间不回复就直接关闭。。。 你回复了吗？？？ 你解决了吗。。。
> 
> 看不到我上面的回复吗 ？

我早配了esaycom啊，还是不行啊
![image](https://user-images.githubusercontent.com/68650762/179892914-1a711a5a-20e6-4c64-bba3-d32b2d3187b1.png)

**Comment by 1596944197** [comment]
我看了一下node_modules，甚至都没uni-section这个文件夹,版本问题？可我装的是最新的

**Comment by mehaotian** [comment]
> 我看了一下node_modules，甚至都没uni-section这个文件夹,版本问题？可我装的是最新的

uni-section 这个组件本来就不是 uni-ui 的标准组件，只在示例里用了，所以没发布

**Comment by MyPrototypeWhat** [comment]
<img width="581" alt="image" src="https://user-images.githubusercontent.com/43230886/180354990-5da89c60-01a8-44ab-95f1-5a2eaed9ebec.png">
<img width="983" alt="image" src="https://user-images.githubusercontent.com/43230886/180355040-0b9302b7-3eff-4dea-9799-6377b2f9b24c.png">

`import { uniSwipeAction, uniSwipeActionItem } from "@dcloudio/uni-ui";` 这么写就报错 

` pages/letter/index.json: ["usingComponents"]["uni-swipe-action-item"] 未找到 ` 

使用图中注释的那么写没问题...这个怎么解决

**Comment by MyPrototypeWhat** [comment]
> <img alt="image" width="581" src="https://user-images.githubusercontent.com/43230886/180354990-5da89c60-01a8-44ab-95f1-5a2eaed9ebec.png">
> 
> <img alt="image" width="983" src="https://user-images.githubusercontent.com/43230886/180355040-0b9302b7-3eff-4dea-9799-6377b2f9b24c.png">
> 
> `import { uniSwipeAction, uniSwipeActionItem } from "@dcloudio/uni-ui";` 这么写就报错
> 
> `pages/letter/index.json: ["usingComponents"]["uni-swipe-action-item"] 未找到`
> 
> 使用图中注释的那么写没问题...这个怎么解决

好家伙 没事了 居然没有`uniSwipeActionItem`组件... 去掉引入就好了

**Comment by mehaotian** [comment]
> > <img alt="image" width="581" src="https://user-images.githubusercontent.com/43230886/180354990-5da89c60-01a8-44ab-95f1-5a2eaed9ebec.png">
> > <img alt="image" width="983" src="https://user-images.githubusercontent.com/43230886/180355040-0b9302b7-3eff-4dea-9799-6377b2f9b24c.png">
> > `import { uniSwipeAction, uniSwipeActionItem } from "@dcloudio/uni-ui";` 这么写就报错
> > `pages/letter/index.json: ["usingComponents"]["uni-swipe-action-item"] 未找到`
> > 使用图中注释的那么写没问题...这个怎么解决
> 
> 好家伙 没事了 居然没有`uniSwipeActionItem`组件... 去掉引入就好了

因为uni-ui 库比较特殊，所以一般不建议自行引入 ，配置好 easycom 后，直接使用就可以，不需要在次引入组件了

**Comment by fengexa** [comment]
我也配置好 easycom 后，也是不显示组件

**Comment by fengexa** [comment]
`//组件自动引入规则
	"easycom": {
		"autoscan": true,
		"custom": {
			// uni-ui 规则如下配置
			"^uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue"
		}
	},`
	我觉得配置没问题呀

**Comment by fengexa** [comment]
不想按需导入，每次都导入，太麻烦了

**Comment by fengexa** [comment]
按需导入可以实现，但是自动就不行了
