### ISSUE TITLE
为什么组件库选用px而不是rpx？

### ISSUE THREAD

**Issue by liujiayii** [dcloudio/uni-ui#238]
px在iPad上变形严重，手动改成rpx后才正常，官方有改成rpx的计划吗？或者有什么解决方案

**Comment by zhetengbiji** [comment]
具体哪个组件严重变形？提供截图看下

**Comment by liujiayii** [comment]
> 具体哪个组件严重变形？提供截图看下

额变形用词不对 在iPhone上看起来差不多正常的尺寸，在iPad上组件小到快看不见了

**Comment by zhetengbiji** [comment]
> > 具体哪个组件严重变形？提供截图看下
> 
> 额变形用词不对 在iPhone上看起来差不多正常的尺寸，在iPad上组件小到快看不见了

具体是哪个

**Comment by liujiayii** [comment]
![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2020-12-04 at 16 49 22](https://user-images.githubusercontent.com/38902744/101142961-41419500-3651-11eb-9e6e-d85e2bae204b.png)
![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2020-12-04 at 16 52 05](https://user-images.githubusercontent.com/38902744/101142978-469edf80-3651-11eb-95a3-6724aa38cb41.png)
正常尺寸的是手动改成rpx的版本，特别小的是原始版本， @zhetengbiji

**Comment by nyrf** [comment]
> > > 具体哪个组件严重变形？提供截图看下
> > 
> > 
> > 额变形用词不对 在iPhone上看起来差不多正常的尺寸，在iPad上组件小到快看不见了
> 
> 具体是哪个

可以试下searchBar的，在pad上看，只有字放大了，整体没变，结果就是很奇怪 的样子

**Comment by clfeng** [comment]
很好奇，本身uniapp就有rpx这套方案，为什么组件库整体不使用功能这个单位去做处理呢

**Comment by zhetengbiji** [comment]
rpx 的使用存在一些限制：1. 适合屏幕宽度在小范围内变化、2. 屏幕方向锁定

而 uni-ui 要适配的范围比较广，不能直接采用 rpx 解决

遇到 uni-ui 适配上的问题，具体提出即可。

**Comment by mehaotian** [comment]
不同屏幕适配已经在接下来的计划中。

**Comment by mehaotian** [comment]
issue 暂时关闭 ，如仍有问题 ，请 reopen issue 继续提问。

**Comment by anihCevol** [comment]
我有一点不太明白：移动端开发 使用rpx,但看了下相关UI框架的单位都是px，如果不处理px，不就会出现不同屏幕尺寸：框架字体永远是一样大的，而开发的样式又是自适应，不是很奇怪吗。
有对应的 px转rpx方案吗

**Comment by yutucc** [comment]
@anihCevol 同问

**Comment by WalkAlone0325** [comment]
看这个问题2020年的，现在都2023年了，有解决方案了吗？我想问问，官方的 `transformPx` 也被弃用了，还有什么方案可以，或者说转换 组件库的 px 为 rpx

**Comment by cqlql** [comment]
@WalkAlone0325 我是编写postcss插件解决的

build/postcss-pxtorpx.js
```js
const processed = Symbol('processed');

module.exports = (opts = {}) => {
  return {
    // 插件名
    postcssPlugin: 'postcss-pxtorpx',

    /**
     * 这个钩子遍历所有大部分CSS属性(如background, color, font-size, etc.)
     * 其他特殊属性如 `@`开头的属性需要用 AtRule 钩子处理
     */
    Declaration(decl, postcss) {
      if (decl[processed]) return;

      // 标记当前 node 已处理
      decl[processed] = true;

      // 将px单位替换为rpx
      if (decl.value && decl.value.indexOf('px') > -1) {
        decl.value = decl.value.replace(/(\d+)px/g, (m, v) => v * 2 + 'rpx');
      }
    },
  };
};
```
vite.config.js 中使用
```js
import { defineConfig } from 'vite';
import postcssPxtorpx from './build/postcss-pxtorpx';
export default defineConfig({
  css: {
    postcss: {
      plugins: [postcssPxtorpx()],
    },
  },
});
```
