### ISSUE TITLE
表单校验catch 没有走

### ISSUE THREAD

**Issue by changle110** [dcloudio/uni-ui#239]
this.$refs.form.submit().then((res)=>{
					// 成功返回，res 为表单数据
					// 其他逻辑处理 
					// ...
					console.log(res);
				}).catch((err)=>{
					// 表单校验验失败，err 为具体错误信息
					// 其他逻辑处理
					// ...
					console.log(2);
				})

**Comment by mehaotian** [comment]
贴一下具体代码 ，校验规则

**Comment by mehaotian** [comment]
问题未复现 ，暂时关闭 issue  ，如还有问题请重新打开并提问。
