### ISSUE TITLE
编写微信小程序uni-popup组件内使用textarea的placeholder属性初始显示与输入内容后再删除显示的占位符样式不一致问题

### ISSUE THREAD

**Issue by mykang0318** [dcloudio/uni-ui#242]
编写微信小程序uni-popup组件内使用textarea的placeholder属性第一次显示与输入内容后再删除内容显示的样式不一致。初始的placeholder样式不生效，需要输入内容后再删除内容显示的占位符样式才生效。微信开发者工具上运行和上传成体验版运行有问题，但是在内置浏览器上运行和真机调试显示的样式却没有问题。

**Comment by mehaotian** [comment]
测试一下如果不使用 uni-popup  是否会有同样的问题出现？

**Comment by mehaotian** [comment]
issue 暂时关闭 ，如仍有问题，请 reopen issue 继续提问。
