### ISSUE TITLE
uni-popup弹出层如从顶部出来（type: top），内部的input输入框就无法输入，大家有遇到过吗？

### ISSUE THREAD

**Issue by 15821978209** [dcloudio/uni-ui#243]
在小程序里面 输入框无法输入

**Comment by mehaotian** [comment]
那个平台出现的问题？

**Comment by 15821978209** [comment]
微信小程序上，苹果手机



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: HaoTian <notifications@github.com&gt;
发送时间: 2020年12月15日 11:08
收件人: dcloudio/uni-ui <uni-ui@noreply.github.com&gt;
抄送: woshiliyuhuan <1456013810@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[dcloudio/uni-ui] uni-popup弹出层如从顶部出来（type: top），内部的input输入框就无法输入，大家有遇到过吗？ (#243)





 
那个平台出现的问题？

**Comment by mehaotian** [comment]
组件更新 ，使用最新组件测试是否正常

**Comment by mehaotian** [comment]
如仍有问题 ，请 reopen issues
