### ISSUE TITLE
uni-popup dialog 对话框 小程序无法正常显示

### ISSUE THREAD

**Issue by fq1327912591** [dcloudio/uni-ui#244]

**Comment by mehaotian** [comment]
真机还是模拟器？有没有报错？或者影响其他功能？

**Comment by fq1327912591** [comment]
> 真机还是模拟器？有没有报错？或者影响其他功能？

真机和模拟器都无法打开，页面没有报错，mask遮罩层打开了，但是对话框没显示

**Comment by liujiusheng** [comment]
我也有这个情况

**Comment by damaohub** [comment]
微信小程序真机和模拟器都无法打开，页面没有报错，mask遮罩层打开了，但是对话框没显示，不知道什么原因

**Comment by mehaotian** [comment]
组件更新 ，优化了卡顿等性能问题 ，使用最新组件，已经修复上述问题，如仍有问题 ，请 reopen issues
