### ISSUE TITLE
uni-ui h5 组件使用问题

### ISSUE THREAD

**Issue by guojingwen** [dcloudio/uni-ui#245]
android 版本   5.0.2 
HTC  Sense 版本 6.0
h5版本构建 引入
import {
	uniSwipeAction,
	uniSwipeActionItem,
} from '@dcloudio/uni-ui';
报错 
![image](https://user-images.githubusercontent.com/12098305/101876947-3db98b00-3bc8-11eb-851b-b42d3b65447f.png)

尝试吧uni-ui组件copy到项目中使用 
import uniSwipeAction from './components/uni-swipe-action/uni-swipe-action.vue';
import uniSwipeActionItem from './components/uni-swipe-action-item/uni-swipe-action-item.vue';
则正常

**Comment by guojingwen** [comment]
只要是在uni-app 的组件含有mixins且mixins中有内容，则在android 5.0系统就会包上面的错误

**Comment by mehaotian** [comment]
android 机上的 h5 页面 ？

**Comment by guojingwen** [comment]
> android 机上的 h5 页面 ？

是的

**Comment by mehaotian** [comment]
我验证一下

**Comment by Fasttian** [comment]
如果是 vue-cli 创建的项目，需要安装依赖，安装 sass，sass-loader 就可以了，执行两条命令 `npm i sass -D`，`npm i sass-loader -D`

**Comment by guojingwen** [comment]
> 如果是 vue-cli 创建的项目，需要安装依赖，安装 sass，sass-loader 就可以了，执行两条命令 `npm i sass -D`，`npm i sass-loader -D`

不是这个问题，  你继续在 android 5.0系统的手机上测试一下uni-ui组件的使用问题

**Comment by Fasttian** [comment]
> > 如果是 vue-cli 创建的项目，需要安装依赖，安装 sass，sass-loader 就可以了，执行两条命令 `npm i sass -D`，`npm i sass-loader -D`
> 
> 不是这个问题， 你继续在 android 5.0系统的手机上测试一下uni-ui组件的使用问题

用文本描述一下报错吧，图片看不见了

**Comment by mehaotian** [comment]
问题长时间不回复 ，暂时关闭 ，如仍有问题 ，请 reopen issue 继续提问。
