### ISSUE TITLE
npm方式安装搭配easycom报错：找不到uni-indexed-list-item

### ISSUE THREAD

**Issue by aszx-fyh** [dcloudio/uni-ui#248]
是uni-indexed-list-item放到了uni-indexed-list组件目录下,导致 easycom规则："^uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue", 失效了。
请问这是bug吗，

**Comment by mehaotian** [comment]
问题已经 修复 ，npm 稍后会发布新版本
