### ISSUE TITLE
重大问题：组件导出路径存在问题

### ISSUE THREAD

**Issue by duhang666** [dcloudio/uni-ui#25]
我在使用‘SwiperDot 轮播图指示点’组件时发现按照文档操作不生效，查找node_modules下的依赖发现@dcloudio/uni-ui包中的index.js各组件的导出路径有问题，我只能通过`@dcloudio/uni-ui/lib/`的方式引入 🐷

index.js中原代码如下：
`import * as uniSwiperDot/uniSwiperDot.vue from './uni-swiper-dot/uni-swiper-dot.vue/uni-swiper-dot/uni-swiper-dot.vue.vue'`

我注意到uni-ui/build/build-lib.js:54行：
`return `import * as ${names.join('')} from './${name}/${name}.vue'``

🐷

**Comment by Wangyaqi** [comment]
全局引入的方式正在修改，可以先在App.vue内使用从`@dcloudio/uni-ui`引入，近期会修复
