### ISSUE TITLE
修改 uni.scss 后, 组件 (uni-ui) 没有变化

### ISSUE THREAD

**Issue by cuiko** [dcloudio/uni-ui#255]
node: v10.18.1
node-sass: v4.9.4
sass-loader: v10.1.0
@dcloudio/uni-ui: v1.2.10
cli 环境

如果是我哪里操作或者理解有误的话, 往指正.

![image](https://user-images.githubusercontent.com/33982919/103530592-aabbfa00-4ec2-11eb-8b96-5b25fed1cf98.png)
![image](https://user-images.githubusercontent.com/33982919/103530647-c0312400-4ec2-11eb-8fd2-e1952d87bbb6.png)

**Comment by mehaotian** [comment]
uni.scss 是让你在自己的组件中使用的，并不会影响内置组件的样式

**Comment by cuiko** [comment]
ok, 谢谢解答.
