### ISSUE TITLE
uni-data-checkbox使用出现报错

### ISSUE THREAD

**Issue by wxharry** [dcloudio/uni-ui#256]
# uni-data-checkbox使用出现报错

复制了https://ext.dcloud.net.cn/plugin?id=3456 中第一个例子，运行结果正常，但控制台会报错。~~（逼死强迫症了）~~

请问我是哪里写错了？有什么方法解决吗？谢谢了！

```
<template>
  <view>
    <uni-data-checkbox
      v-model="value"
      :localdata="range"
      @change="change"
    ></uni-data-checkbox>
  </view>
</template>

<script>
import { uniDataCheckbox } from "@dcloudio/uni-ui";
export default {
  components:{
    uniDataCheckbox
  },
  data() {
    return {
      value: 0,
      range: [
        { value: 0, text: "篮球" },
        { value: 1, text: "足球" },
        { value: 2, text: "游泳" },
      ],
    };
  },
  methods: {
    change(e) {
      console.log("e:", e);
    },
  },
};
</script>

<style>
</style>
```

![image](https://user-images.githubusercontent.com/39271899/104095150-3c1ada00-52d0-11eb-9d49-2f4d4a788a24.png)

**Comment by mehaotian** [comment]
看一下 npm 安装的是那个版本？ 我这测试没有复现这个错误啊

**Comment by wxharry** [comment]
npm是v6.11.3，刚才更新了一下是v6.14.11，还是这个报错

**Comment by mehaotian** [comment]
> npm是v6.11.3，刚才更新了一下是v6.14.11，还是这个报错

可能我的描述有些错误，是 npm 安装的 uni-ui 是那个版本。

**Comment by wxharry** [comment]
> > npm是v6.11.3，刚才更新了一下是v6.14.11，还是这个报错
> 
> 可能我的描述有些错误，是 npm 安装的 uni-ui 是那个版本。

哦哦 是我理解有问题，当前uni-ui版本是v1.2.10

**Comment by mehaotian** [comment]
试了一下，还是没复现，能给我发一个工程吗，做一个简单的小demo ，我看是不是环境问题。

**Comment by pndgz** [comment]
[Vue warn]: Error in created hook: "TypeError: Cannot read property 'dataset' of undefined"

found in

---> <UniDataChecklist> at node_modules/@dcloudio/uni-ui/lib/uni-data-checkbox/uni-data-checkbox.vue
       <UniListItem> at node_modules/@dcloudio/uni-ui/lib/uni-list-item/uni-list-item.vue
         <UniList> at node_modules/@dcloudio/uni-ui/lib/uni-list/uni-list.vue

clientdb.js L 89 let events = this.$scope.dataset.eventOpts  the $scope is undefined

**Comment by sad-xu** [comment]
我也遇到了，似乎是 `node_modules/@dcloudio/uni-ui/lib/uni-data-checkbox/clientdb.js L89` 的条件编译失效了
`#ifdef MP-TOUTIAO` 里的语句在 `H5` 环境里依然执行了

我是用 `cli` 创建的项目，并手动修改过依赖版本号至当前最新

**Comment by pndgz** [comment]
transpileDependencies: ['@dcloudio'] 可以解决

**Comment by mehaotian** [comment]
因为 cli 项目默认是不编译 node_modules 下的组件，导致有些功能失效

需要在根目录创建 `vue.config.js` 文件 ，增加 `@dcloudio/uni-ui` 包的编译

```javascript

module.exports = {
    transpileDependencies:['@dcloudio/uni-ui']
}

```

**Comment by mehaotian** [comment]
issue 暂时关闭 ，如仍有问题 ，请reopen issue 继续提问。
