### ISSUE TITLE
这些标签是怎么回事？？？

### ISSUE THREAD

**Issue by yangjingchuang** [dcloudio/uni-ui#257]
![image](https://user-images.githubusercontent.com/29910922/105113680-53439e00-5b00-11eb-970a-6f302c028d2d.png)

**Comment by mehaotian** [comment]
这是那个平台？你这个示例看起来不太新啊 ，那里的示例？

**Comment by yangjingchuang** [comment]
> 这是那个平台？你这个示例看起来不太新啊 ，那里的示例？

![image](https://user-images.githubusercontent.com/29910922/108590576-3fa98280-739f-11eb-9f78-5109fbb294a3.png)
苹果手机上面也有，苹果8p

**Comment by mehaotian** [comment]
使用组件，不存在此问题
