### ISSUE TITLE
无法通过计时器进行打开弹窗并且点击蒙版关闭onchange中打印日志无限循环

### ISSUE THREAD

**Issue by LowGuylollipop** [dcloudio/uni-ui#259]
0.点击蒙版关闭后我在change事件中打印日志无限打印日志 

1.我通过计时器自动弹出弹窗出现Cannot read property 'open' of undefined（实例没初始化?我是放在onReady里的

**Comment by mehaotian** [comment]
组件有优化 ，请使用最新组件测试 ，如仍有问题 ，请 reopen issues
