### ISSUE TITLE
uni-drawer点击遮罩关闭后无法再打开

### ISSUE THREAD

**Issue by acelance** [dcloudio/uni-ui#26]
uni-drawer点击遮罩关闭后无法再打开 visible即使设置为true也没有用

**Comment by acelance** [comment]
问题已解决,按照源码的逻辑需要配合close事件使用才会正常,给组件监听close事件的处理函数,使其visible与开启Drawer时状态取反即可

**Comment by xhb** [comment]
@acelance  打开 unidrawer 后 遮挡住底部的 tabbar 有没有什么解决办法？？？？
