### ISSUE TITLE
uni-easyinput 输入内容后点击完成，文字内容显示不完整

### ISSUE THREAD

**Issue by geekgray** [dcloudio/uni-ui#260]
设备：iphone12promax
系统版本: 14.3
运行环境：(H5) 微信浏览器、Safair 官网Demo即可复现
![WechatIMG780](https://user-images.githubusercontent.com/17681801/106107877-70bcdb80-6182-11eb-8763-634c64f0e18b.jpeg)

**Comment by mehaotian** [comment]
应该是 ios 的兼容问题 ，下次更新修复。

**Comment by mehaotian** [comment]
使用最新组件，验证是否正常 ，issue 暂时关闭 ，如仍有问题请 reopen issue 继续提问。
