### ISSUE TITLE
插件市场dialog示例代码出错

### ISSUE THREAD

**Issue by bj-tang** [dcloudio/uni-ui#261]
https://ext.dcloud.net.cn/plugin?id=329

dialog 对话框 提供的示例代码为
<uni-popup ref="popup" type="dialog">
    <uni-popup-dialog type="input" message="成功消息" :duration="2000" :before-close="true" @close="close" @confirm="confirm"></uni-popup-dialog>
</uni-popup>
 type="input"是过时的 应该更正为 mode="input"

**Comment by mehaotian** [comment]
感谢指出，文档已经更新
