### ISSUE TITLE
SassError: Undefined variable

### ISSUE THREAD

**Issue by buqiyuan** [dcloudio/uni-ui#263]
![image](https://user-images.githubusercontent.com/39730999/106609772-e836a480-65a0-11eb-88c4-5fafcd6d0c61.png)
已经按照文档来了，该装的也装了，编辑器也重启过了，还是不行。快点救救孩子吧！

环境：
node: v14.14.0
vue-cli 4.5.11
builderX 3.0.7.20210123

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/106611004-68113e80-65a2-11eb-9baf-b0d2d30e0377.png)

**Comment by mehaotian** [comment]
把 src 拖入到 HBuilderX 中运行 ，看看能正常运行吗
