### ISSUE TITLE
uni-file-picker 在微信开发者工具中无法打开文件选择

### ISSUE THREAD

**Issue by DevinChen1** [dcloudio/uni-ui#264]
代码是这样的

			<view>
			    <uni-file-picker  ref="files" file-mediatype="all" :limit="1" :auto-upload="false"
				@progress="progress" 
				@success="success" 
				@fail="fail" 
				@select="select">
				</uni-file-picker>
			    <button @click="upload">上传文件</button>
			</view>

**Comment by DevinChen1** [comment]
报错：chooseMessageFile:fail param extension should not be empty.
HBuildx 3.1

**Comment by mehaotian** [comment]
已经做兼容处理
