### ISSUE TITLE
uni-forms提交的时候radio-group的表单验证有问题，明明选了，会提示请选择

### ISSUE THREAD

**Issue by chaegumi** [dcloudio/uni-ui#265]
```html
<uni-forms-item label="类型" name="price_type">
        <radio-group @change="binddata('price_type', $event.detail.value)">
          <label> <radio value="0" /> 按时长 </label>
          <label> <radio value="1" /> 按人数 </label>
        </radio-group>
      </uni-forms-item>

```

![image](https://user-images.githubusercontent.com/9654650/107313045-bbb4e800-6acc-11eb-9e09-9fb55da9f33b.png)

```javascript

rules = {
	 price_type: {
		 rules: [
			 {
				 required: true, 
				 errorMessage:'请选择类型',
			},
		 ]
	 }

```

**Comment by mehaotian** [comment]
你看下是不是选择 「按人数」就可以通过了？ 或者把 value 改成 1  ，2 不要 用 0 ，确定一下是不是 0 按 false 处理了？

**Comment by chaegumi** [comment]
不是这个原因，这边类型和价格都是必填的，
我只选了类型，点击确定提示我要填价格，
我填了价格之后，这个时候点击确定可以提交，
然后我故意清空价格，点确定会要求我选择类型和填写价格，这个时候好像把类型的验证状态清除了，我填了价格，还是要我选类型

**Comment by mehaotian** [comment]
forms 的 value 属性改成   v-model="xxx" 试一试，应该是数据没有双向绑定导致的
