### ISSUE TITLE
表单中对时间戳格式的值校验不通过

### ISSUE THREAD

**Issue by JA-Coding-J** [dcloudio/uni-ui#267]
![image](https://user-images.githubusercontent.com/63656376/107462587-60036100-6b97-11eb-9d02-532336ecd7c0.png)
在date方法中返回false

**Comment by mehaotian** [comment]
这是那里的代码 ？贴一段完整点的代码片段

**Comment by JA-Coding-J** [comment]
> 这是那里的代码 ？贴一段完整点的代码片段

这是组件中的源码，在validate.js文件中。
如果是时间戳格式的值会经过这两个方法的处理，并在`date`方法中返回`false`，继而导致校验不通过

**Comment by mehaotian** [comment]
问题已经修复，请使用最新的组件测试一下，看看是否正常

**Comment by mehaotian** [comment]
issue 暂时关闭 ，如仍有问题 ，请 reopen issue 继续提问。
