### ISSUE TITLE
已于https://ext.dcloud.net.cn/plugin?id=28不同步，导致安卓打包app后图标不正常显示

### ISSUE THREAD

**Issue by EagleChinaWu** [dcloudio/uni-ui#270]
已于https://ext.dcloud.net.cn/plugin?id=28不同步，导致安卓打包app后图标不正常显示

已于https://ext.dcloud.net.cn/plugin?id=28不同步，导致安卓打包app后图标不正常显示

已于https://ext.dcloud.net.cn/plugin?id=28不同步，导致安卓打包app后图标不正常显示

**Comment by xiaopin** [comment]
我通过 npm + easycom 方式引入 uni-ui，发现在支付宝小程序中uni-icons 显示成方块了，不知道为什么，微信小程序和H5则正常。

**Comment by mehaotian** [comment]
问题已经在排查中
