### ISSUE TITLE
uni popup 微信小程序 this.$refs.popupBottom.open is not a function

### ISSUE THREAD

**Issue by MewTyrant** [dcloudio/uni-ui#271]
`
<uni-popup id="popupBottom" ref="popupBottom" :type="type" :animation="false" @change="change">
	<view class="popup-content">popup 内容，此示例没有动画效果</view>
</uni-popup>`

添加引用
import { UniPopup } from '@dcloudio/uni-ui';
export default {
	comments: {
		navbar,
		UniPopup
	}
}
使用方式
![image](https://user-images.githubusercontent.com/24793839/108975846-e2287500-76c1-11eb-9daf-019554fedaf0.png)

H5可以正常使用， 小程序抛出异常 this.$refs.popupBottom.open is not a function

popupBottom 的堆栈为
![image](https://user-images.githubusercontent.com/24793839/108975690-b907e480-76c1-11eb-8298-e802b7225722.png)

**Comment by Fasttian** [comment]
应该是组件引用的问题，uni-popup 依赖了另一个 uni-ui 的组件

``/node_modules/@dcloudio/uni-ui/lib/uni-popup/uni-popup.vue`` 中手动引入uni-transition 组件：
``` js
	import uniTransition from '../uni-transition/uni-transition.vue'
```

附带解决一个监听报错：

``/node_modules/@dcloudio/uni-ui/lib/uni-popup/popup.js``  中修改：
```js
if (window) {
	window.addEventListener('resize', fixSize)
	this.$once('hook:beforeDestroy', () => {
		window.removeEventListener('resize', fixSize)
	})
}
```

**Comment by Fasttian** [comment]
> 如按需引用，相互引用的组件需要手动添加依赖，所以，建议统一使用 easycom

安装好 `uni-ui` 之后，需要配置 `easycom` 规则，让 `npm` 安装的组件支持  `easycom`

打开项目根目录下的 `pages.json` 并添加 `easycom` 节点：

```javascript
// pages.json

{
	"easycom": {
		"autoscan": true,
		"custom": {
			// uni-ui 规则如下配置
			"^uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue"
		}
	},
	
	// 其他内容
	pages:[
		// ...
	]
}

```

**Comment by Fasttian** [comment]
> 如按需引用，相互引用的组件需要手动添加依赖，所以，建议统一使用 easycom

安装好 `uni-ui` 之后，需要配置 `easycom` 规则，让 `npm` 安装的组件支持  `easycom`

打开项目根目录下的 `pages.json` 并添加 `easycom` 节点：

```javascript
// pages.json

{
	"easycom": {
		"autoscan": true,
		"custom": {
			// uni-ui 规则如下配置
			"^uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue"
		}
	},
	
	// 其他内容
	pages:[
		// ...
	]
}

```

**Comment by MewTyrant** [comment]
> > 如按需引用，相互引用的组件需要手动添加依赖，所以，建议统一使用 easycom
> 
> 安装好 `uni-ui` 之后，需要配置 `easycom` 规则，让 `npm` 安装的组件支持 `easycom`
> 
> 打开项目根目录下的 `pages.json` 并添加 `easycom` 节点：
> 
> ```js
> // pages.json
> 
> {
> 	"easycom": {
> 		"autoscan": true,
> 		"custom": {
> 			// uni-ui 规则如下配置
> 			"^uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue"
> 		}
> 	},
> 	
> 	// 其他内容
> 	pages:[
> 		// ...
> 	]
> }
> ```

这种方式用过，还是不可以， 后面我单独把模块源码加载我的项目目录 components中使用，就正常了。 我个人是应用型的，就没有纠结具体的错误问题。

**Comment by xiaoyierle** [comment]
> 您好，可以告知下如何加载到项目目录components中的吗？感谢

**Comment by xiaoyierle** [comment]
> > 如按需引用，相互引用的组件需要手动添加依赖，所以，建议统一使用 easycom
> 
> 安装好 `uni-ui` 之后，需要配置 `easycom` 规则，让 `npm` 安装的组件支持 `easycom`
> 
> 打开项目根目录下的 `pages.json` 并添加 `easycom` 节点：
> 
> ```js
> // pages.json
> 
> {
> 	"easycom": {
> 		"autoscan": true,
> 		"custom": {
> 			// uni-ui 规则如下配置
> 			"^uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue"
> 		}
> 	},
> 	
> 	// 其他内容
> 	pages:[
> 		// ...
> 	]
> }
> ```

您好，我想问下 easycom 这个插件如何针对 npm的 项目引用 uni-ui去进行配置
