### ISSUE TITLE
期望可通过命令行的方式启动uni-ui项目

### ISSUE THREAD

**Issue by clfeng** [dcloudio/uni-ui#273]
期望整个工程可以通过命令行的方式进行运行，目前文档里也没有相应的说明

**Comment by mehaotian** [comment]
uni-ui 只是一个ui 库，安装后，需要运行 uni-app 项目 ，可以使用命令行运行。

**Comment by clfeng** [comment]
您好!您的邮件我已收到，我将尽快查收并给您答复，谢谢！
