### ISSUE TITLE
uni-ui 国际化

### ISSUE THREAD

**Issue by xiaopin** [dcloudio/uni-ui#275]
请问 uni-ui 目前是不考虑国际化吗，组件内部直接使用了简体中文的文字（如：uni-datetime-picker、uni-calendar等组件）

**Comment by mehaotian** [comment]
国际化在计划内，后续会支持uni-ui全组件的国际化

**Comment by demon-zhonglin** [comment]
> 国际化在计划内，后续会支持uni-ui全组件的国际化

目前有该计划的上线时间吗？
