### ISSUE TITLE
非H5出现window报错undefined, popUp组件

### ISSUE THREAD

**Issue by cher0420** [dcloudio/uni-ui#278]
**问题描述**
popUp组件在小程序端因为查找不到window出现报错

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
Cannot read property 'addEventListener' of undefined"

found in

---> <UniPopup> at node_modules/@dcloudio/uni-ui/lib/uni-popup/uni-popup.vue
**预期结果**
希望组件更新下容错

**实际结果**
Cannot read property 'addEventListener' of undefined"

found in

---> <UniPopup> at node_modules/@dcloudio/uni-ui/lib/uni-popup/uni-popup.vue

**系统信息:**
 - 发行平台:  微信小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
if(window){
//执行监听行为
}

**Comment by Ulyssesyi** [comment]
回退版本后是正常的，看代码是新版本在2月5号中加入的适配PC的代码后，popup.js中mounted里面的resize监听编译到微信小程序中了，我以为是mixin处理条件编译不正确，但是自己新建的测试项目使用mixin时uniapp还是可以正确处理条件编译的。最终@mehaotian希望可以看一下

**Comment by mehaotian** [comment]
应该是使用 cli 方式导致了 条件编译失效 了 ，问题在排查中了

**Comment by mehaotian** [comment]
问题已解决 ，暂时关闭 issue ，如仍有问题请 reopen issue 继续提问。
