### ISSUE TITLE
找不到 uni-status-bar

### ISSUE THREAD

**Issue by kikooo** [dcloudio/uni-ui#279]
1.0.7版本的changelog里写了修复 easycom 下，找不到 uni-status-bar 的bug。
但是这个问题在1.1.12版本里有复现。升级到最近版本1.2.11也不行。

可以通过回退到1.0.7版本修复，但是希望bug-fix可以向上兼容。

**Comment by kikooo** [comment]
回退到1.0.7版本的话很多东西都不能用了。比如list组件的slot之类的。希望有空可以看一下，谢谢。。

**Comment by mehaotian** [comment]
1.2.12 已经修复 ，使用 npm 需要配置 easycom
