### ISSUE TITLE
数字输入框组件change 警告

### ISSUE THREAD

**Issue by dodododooo** [dcloudio/uni-ui#28]
-------code-------

<uni-number-box :value="selectedCount" @change="v => selectedCount = v" :min="minCount" :max="maxCount"></uni-number-box>

------code--------

----出现VUE 禁止修改prop警告
Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "value"

found in

---> node-modules/@dcloudio/uni-ui/lib/uni-number-box/uni-number-box
       node-modules/@dcloudio/uni-ui/lib/uni-popup/uni-popup

**Comment by Wangyaqi** [comment]
现在没这个问题了
