### ISSUE TITLE
更新到1.2.11后问题

### ISSUE THREAD

**Issue by lmf** [dcloudio/uni-ui#284]
项目是通过cli + npm方式安装的依赖，直接import uniPopup from '@dcloudio/uni-ui'后，找不到uni-transition，然后加上easycom配置，uni-nav-bar又找不到uni-status-bar，所以这个版本测试了吗？

**Comment by 289420843** [comment]
同样的问题

**Comment by Fasttian** [comment]
> 直接import uniPopup from '@dcloudio/uni-ui'后，找不到uni-transition
组件内部引用的问题，目前要兼顾 uni_modules 的目录结构，不太好处理，建议还是使用 easycom。

>然后加上easycom配置，uni-nav-bar又找不到uni-status-bar
这个问题已处理，更新 uni-nav-bar 尝试

**Comment by mehaotian** [comment]
问题以及处理，暂时关闭 issue ，如仍有问题请reopen issue 继续提问。
