### ISSUE TITLE
uni-swipe-action App vue页面报错：undefined is not an object (evaluating 'navigator.userAgent')

### ISSUE THREAD

**Issue by 1103409364** [dcloudio/uni-ui#285]
uni-swipe-action-item 按钮被点击时：undefined is not an object (evaluating 'navigator.userAgent')

是组件 mpwxs.js 文件中 onClickForPC 外的条件注释：// #ifdef H5 导致的

**Comment by Fasttian** [comment]
已修复，更新一下 v1.1.8（2021-03-26）
