### ISSUE TITLE
swipe-action更新到1.18版本后swipe-action-item的click会同时触发两次的解决办法

### ISSUE THREAD

**Issue by aihanjiao** [dcloudio/uni-ui#287]
## 报错截图：
![image](https://user-images.githubusercontent.com/59612542/113080857-27cce600-920a-11eb-8c61-f6da6e79ef89.png)
## 如图：
![image](https://user-images.githubusercontent.com/59612542/113080812-1552ac80-920a-11eb-8e06-8739b7e75699.png)
![image](https://user-images.githubusercontent.com/59612542/113080836-1edc1480-920a-11eb-986e-d40caf8e2a95.png)
### 解决办法（瞎猜）试了app真机、微信小程序、h5都没问题：
![image](https://user-images.githubusercontent.com/59612542/113080928-521ea380-920a-11eb-9f5a-7e3ec11dd33c.png)

**Comment by jiahongsheng** [comment]
多谢，问题解决了

**Comment by aihanjiao** [comment]
可能还是有人不知道咋改，稍微画个图
![新建项目](https://user-images.githubusercontent.com/59612542/116639652-959c3700-a99b-11eb-8762-0aaad8ec7875.png)

**Comment by lslvmq** [comment]
感谢大佬！ 解决了。就是不知道这是什么原因

**Comment by hezhishu2014** [comment]
应该就是判断pc不准确

**Comment by June-elisa** [comment]
感谢大佬，完美解决

**Comment by mehaotian** [comment]
问题已经修复

**Comment by mehaotian** [comment]
问题已经修复 ，issue 暂时关闭 ，如仍有问题请 reopen issue 继续提问。

**Comment by wangshaoyun111** [comment]
感谢大佬
