### ISSUE TITLE
uni-easyinput clearable不生效

### ISSUE THREAD

**Issue by punkvv** [dcloudio/uni-ui#288]

**Comment by AnaniZhu** [comment]
+1 ，同样遇到此问题。

**字节小程序 IOS 环境**

点击删除图标，数据层是已经清空了的，但是视图层未更新。

**安卓手机无此问题**

**Comment by mehaotian** [comment]
问题已经修复 ，暂时关闭 issue ，如仍有问题，请reopen issue 继续提问。
