### ISSUE TITLE
在组件中写了overflow,发现overflow没有作用

### ISSUE THREAD

**Issue by ZHDLFFY** [dcloudio/uni-ui#290]
在组件中写了overflow,发现overflow没有作用

**Comment by Fasttian** [comment]
哪一个组件，具体什么情况下，这个描述谁能知道怎么回事？

**Comment by ZHDLFFY** [comment]
> 哪一个组件，具体什么情况下，这个描述谁能知道怎么回事？
就是popup组件，在里面写个view，然后view中写style="overflow:auto", 发现不滚动。我猜可能是我没有用插槽的原因

**Comment by chenyuncai** [comment]
我也遇到了，PC端开发工具没问题，手机真机上不能滚动，指定各种高度也不行。实际上内容两三屏。
