### ISSUE TITLE
uni-table组件无法给tr或者td添加点击事件

### ISSUE THREAD

**Issue by InMyLife888** [dcloudio/uni-ui#291]
业务需求点击当前行或最后一个单元格进入详情页，无法实现

**Comment by Fasttian** [comment]
目前不支持，预计下一个版本支持，可以先用button 调转详情的方式过渡一下

**Comment by mehaotian** [comment]
在 tr td 上使用原生事件 `@click.native` 即可

**Comment by mehaotian** [comment]
issue 暂时关闭 ，如仍有问题 ，请 reopen issue 继续提问。
