### ISSUE TITLE
字节小程序中 uni-popup 内渲染 textarea，点击不聚焦

### ISSUE THREAD

**Issue by AnaniZhu** [dcloudio/uni-ui#295]
平台: 字节小程序
设备：IOS 抖音环境访问字节小程序

现象:
当 uni-popup 存在 textarea 时，手指触碰点击 textarea，毫无反应，并不会触发聚焦弹出键盘。

查看源码是因为如下代码(uni-popup.vue)所导致, 删除此段代码正常，官方有什么处理方案嘛？

![image](https://user-images.githubusercontent.com/26708304/114526838-eb719f00-9c79-11eb-9791-36610117fea5.png)

**Comment by mehaotian** [comment]
组件更新 ，使用最新组件测试是否正常

**Comment by mehaotian** [comment]
问题已经修复 ，暂时关闭 issue ,如仍有问题 ，请 reopen issue 继续提问。
