### ISSUE TITLE
字节小程序中uni-popup中嵌套scroll-view无法滑动

### ISSUE THREAD

**Issue by NanmiCoder** [dcloudio/uni-ui#297]
![image](https://user-images.githubusercontent.com/47178017/114843301-40451f00-9e0c-11eb-9de7-d6e91feae389.png)

**Comment by NanmiCoder** [comment]
同样的代码编译到，百度、微信都是没问题的。

**Comment by NanmiCoder** [comment]
目前处理方案是对字节平台增加条件编译取消uni-popup组件中的@touchmove.stop.prevent事件

**Comment by mehaotian** [comment]
@touchmove.stop.prevent 目的就是为了避免滚动的，不太建议 popup 中放 scroll-view ，可能会影响打开速度 ，或者样式问题

**Comment by AnaniZhu** [comment]
> @touchmove.stop.prevent 目的就是为了避免滚动的，不太建议 popup 中放 scroll-view ，可能会影响打开速度 ，或者样式问题

但弹窗里的确有内容过长是需要滚动的，这种情况就没办法用了么?

**Comment by mehaotian** [comment]
> > @touchmove.stop.prevent 目的就是为了避免滚动的，不太建议 popup 中放 scroll-view ，可能会影响打开速度 ，或者样式问题
> 
> 但弹窗里的确有内容过长是需要滚动的，这种情况就没办法用了么?

使用 overflow-y:scroll
