### ISSUE TITLE
1.2.12版本uni-popup组件样式丢失

### ISSUE THREAD

**Issue by 15152929190** [dcloudio/uni-ui#298]
遮罩层没了；内容不居中了；弹出动画没了

**Comment by Fasttian** [comment]
什么平台，什么情况下出现的呢？

**Comment by 15152929190** [comment]
在微信小程序上出现上述问题；浏览器端没问题

**Comment by mehaotian** [comment]
组件已经更新 ，使用dev代码或者插件市场安装最新组件尝试，看看是否还有问题？

**Comment by mehaotian** [comment]
issues 暂时关闭 ，如仍有问题请 reopen issues 继续提问。

**Comment by mehaotian** [comment]
issues 暂时关闭 ，如仍有问题请 reopen issues 继续提问。
