### ISSUE TITLE
uni-swipe-action组件在小程序端使用不了

### ISSUE THREAD

**Issue by 15152929190** [dcloudio/uni-ui#299]
1. 使用版本是1.2.10  在h5端可以正常使用；在小程序端无法使用，也没有报错，就是滑不动
2. 升级1.2.12版本后  h5端正常使用，小程序端报错nv_navigator is not defined

**Comment by Fasttian** [comment]
已修复，更新到最新版尝试

**Comment by BILYHO** [comment]
最新版也是报错
![image](https://user-images.githubusercontent.com/23090650/115950570-a4539b80-a50e-11eb-8222-48189927fd5b.png)

**Comment by mehaotian** [comment]
是 cli 项目 ？
