### ISSUE TITLE
in uni-ui/packages/uni-nav-bar/uni-nav-bar.vue

### ISSUE THREAD

**Issue by BHABGS** [dcloudio/uni-ui#3]
我看了下源码，都是中文注释，我猜应该是国人开发的，所以我还是用中文说吧。
现在呢又一个问题在uni-nav-bar，当right-text 使用2个中文字符的时候，它只显示一个中文字符，在iphonex下。

**Comment by hulinNeil** [comment]
你是直接使用在H5运行还是运行到APP?

**Comment by BHABGS** [comment]
在app 里

**Comment by hbcui1984** [comment]
长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
