### ISSUE TITLE
npm + easycom Module not found: Error: Can't resolve '@dcloudio/uni-ui/lib/uni-badge/uni-badge.vue'

### ISSUE THREAD

**Issue by cqgsm** [dcloudio/uni-ui#301]
找不到模块啊

**Comment by Fasttian** [comment]
uni-ui si 是哪一个版本？

**Comment by wuhan169** [comment]
1.2.13，现在都不敢升级，一升级就起不起来，总是有bug，发布之前不能用demo先检查一遍吗

**Comment by cqgsm** [comment]
^1.2.13 这个版本，头皮发麻

**Comment by Zhang-Shaoqiang** [comment]
1.2.13这个包的目录结构怎么还发生变化啦，需要加packages引
"^uni-(.*)": "@dcloudio/uni-ui/packages/lib/uni-$1/uni-$1.vue",

**Comment by Fasttian** [comment]
npm 包 @dcloudio/uni-ui@1.2.13 版本发布错误，已被 deprecate，请更新一下 @dcloudio/uni-ui@1.2.14 版本

**Comment by mehaotian** [comment]
issues 暂时关闭 ，如仍有问题请 reopen issues  继续提问。
