### ISSUE TITLE
【bug】uni-easyinput 组件，confirmType属性不生效。

### ISSUE THREAD

**Issue by koibi2** [dcloudio/uni-ui#306]
插件文档链接：[https://ext.dcloud.net.cn/plugin?id=3455](https://ext.dcloud.net.cn/plugin?id=3455)
少了一个属性 confirmType，类型是 text 时，IOS右下角确认按钮显示为特定文字。
希望尽快修复。
版本（最新版本）：0.0.10

![image](https://user-images.githubusercontent.com/34370367/116856401-aebc1680-ac2d-11eb-8f4c-7bf36df48021.png)

**Comment by mehaotian** [comment]
问题已经修复，暂时关闭issues ,如仍有问题请 reopen issues 继续提问。
