### ISSUE TITLE
[uni-field] uni-field 输入框组件在输入字符的时候抛出错误

### ISSUE THREAD

**Issue by koalaqinqin** [dcloudio/uni-ui#307]
报错信息：
1. Error in v-on handler: "TypeError: Cannot set property 'undefined' of undefined"
![image](https://user-images.githubusercontent.com/11988905/117315359-34ec8d00-aeba-11eb-85c9-053bf33bc610.png)

![image](https://user-images.githubusercontent.com/11988905/117315449-4a61b700-aeba-11eb-841a-3b73aa14dedc.png)

2. clear 图标消失
![image](https://user-images.githubusercontent.com/11988905/117315629-6f562a00-aeba-11eb-9190-3556c8e43600.png)

![image](https://user-images.githubusercontent.com/11988905/117312717-daeac800-aeb7-11eb-8149-13a273050bb6.png)

**Comment by mehaotian** [comment]
uni-field 组件已经停止维护 ，请使用 uni-easyinput 代替
