### ISSUE TITLE
Type Options 失效,

### ISSUE THREAD

**Issue by xin-zhao33** [dcloudio/uni-ui#308]
Type Options 失效,不管type 类型设置什么,都是从top 位置弹出

**Comment by mehaotian** [comment]
什么组件？ uni-popup ?

**Comment by mehaotian** [comment]
是不是在使用 open 的时候 传人了 top？`this.$refs.popup.oopem('top')` ,如果是这样的话，会覆盖属性上的tpyt 值。如还有问题 请reopen issues.
