### ISSUE TITLE
点击遮罩不能关闭

### ISSUE THREAD

**Issue by jcq-1129** [dcloudio/uni-ui#312]
点击遮罩不能关闭

**Comment by mehaotian** [comment]
uni-popup ?

**Comment by jcq-1129** [comment]
是的。我在其中写了一个view 但是没有占满整个页面 只能点击最下方 才能关闭

**Comment by mehaotian** [comment]
问题已经修复  a460d0b2af078d793b1793a7504df0612c542c26
