### ISSUE TITLE
图片加载报错

### ISSUE THREAD

**Issue by Zhongxiangyun** [dcloudio/uni-ui#314]
[渲染层网络层错误]

 Failed to load local image resource /uni_modules/uni-datetime-picker/components/uni-datetime-picker/icon/cale-50.png 

 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error)

**Comment by tties** [comment]
我也遇到相同的问题

**Comment by Fasttian** [comment]
没这个问题了，这个图标已经打包成了 base64，请更新最新版 uni-datetime-picker
