### ISSUE TITLE
popup 无法关闭

### ISSUE THREAD

**Issue by xywdegithub** [dcloudio/uni-ui#319]
popup 若popup弹出后直接点击灰色区域则可以关闭 但弹出后点击内容后 再点击灰色区域就无法关闭  也无法触发change 和beforeClose事件

**Comment by mehaotian** [comment]
什么平台出现的这个问题 ？

**Comment by thc007** [comment]
同样遇到，官网例子就不行，点击内容区域后，再点击遮罩层无法关闭popup

**Comment by mehaotian** [comment]
问题已经修复 ，下载最新组件

**Comment by mehaotian** [comment]
问题已经修复，暂时关闭 issues ,如仍有问题，请reopen issues 继续提问。
