### ISSUE TITLE
【BUG】uni-list-item组件的clickable 属性不生效

### ISSUE THREAD

**Issue by koibi2** [dcloudio/uni-ui#320]
`:hover-class="(!clickable && !link) || disabled || showSwitch ? '' : 'uni-list-item--hover'"`
这行判断有问题

**Comment by mehaotian** [comment]
判断没有问题 ，贴一下你的代码 ，看一下怎么用的？

**Comment by koibi2** [comment]
看错了，自己代码的问题。
