### ISSUE TITLE
uni-file-picker无法使用 

### ISSUE THREAD

**Issue by lijun998** [dcloudio/uni-ui#330]
在使用中会报错  uniCloud.chooseAndUploadFile is not a function
当前hbuderx版本为3.1.11

**Comment by mehaotian** [comment]
现在的 uni-file-picker 是和 uniCloud 关联的 ，需要先关联 服务空间 ，才可以使用 ，后续会优化这部分的内容

**Comment by mehaotian** [comment]
使用最新 uni-file-picker 组件，已经取消与 uniCloud的强绑定 ，暂时关闭 issue ,如仍有问题 ，请 reopen issue 继续提问。
