### ISSUE TITLE
nvue 中使用组件报 WARNING

### ISSUE THREAD

**Issue by PrescottPS** [dcloudio/uni-ui#331]
在nvue页面中使用 uni-ui 的组件时，控制台报警告如下图：
![image](https://user-images.githubusercontent.com/8056301/123204842-79280100-d4eb-11eb-9e51-c1e0505cdecd.png)

查看 `uni-badge` 的源代码，使用的条件编译是 `APP-NVUE`, 与告警信息中提示的 `APP-PLUS-NVUE` 不一致，是否因为这个原因导致？ 
![image](https://user-images.githubusercontent.com/8056301/123205518-a628e380-d4ec-11eb-8c69-969cf8fb1536.png)

**uni-ui 是否支持 nvue 渲染**

运行环境：
使用 HBuilderX  3.1.18.20210609 ， 新建的 uni-ui 模板项目

**Comment by mehaotian** [comment]
nvue 下不支持 align-self 这个样式属性

**Comment by PrescottPS** [comment]
> nvue 下不支持 align-self 这个样式属性

不支持的话，为什么还通过条件编译加上这个属性？

**Comment by mehaotian** [comment]
应该是代码写错了，我测试一下看看

**Comment by Fasttian** [comment]
测试 nvue 下支持 align-self，编译条件写错了（应为  #ifdef APP-PLUS-NVUE）
