### ISSUE TITLE
uni-popup组件无法正常弹出

### ISSUE THREAD

**Issue by RexHarris** [dcloudio/uni-ui#338]
复现版本1.3.5，但我试过1.2.5版本没有这样的问题

**Comment by mehaotian** [comment]
贴代码

**Comment by RexHarris** [comment]
![image](https://user-images.githubusercontent.com/43196431/124694631-40891e00-df14-11eb-86ac-c293424a6d13.png)
![Uploading image.png…]()

**Comment by RexHarris** [comment]
代码片段![image](https://user-images.githubusercontent.com/43196431/124694960-d624ad80-df14-11eb-8149-57a5d3f5867b.png)

**Comment by RexHarris** [comment]
等了五天没有人给出解决方案，现使用原生小程序中的page-container组件实现需求

**Comment by mehaotian** [comment]
控制台已经报错了，缺少组件 uni-transtion ,  npm 安装的组件，需要配合 easyCom 使用组件，否则有些依赖组件会引用不正常

**Comment by mehaotian** [comment]
issue 暂时关闭 ，如仍有问题请 reopen issue 继续提问
