### ISSUE TITLE
NumberBox一个值变动另一个值也变动 bug

### ISSUE THREAD

**Issue by huaiguoguo** [dcloudio/uni-ui#34]
uniapp当中的循环当中使用有bug,
我在两个循环当中使用NumberBox插件
发现，### 一个NumberBox  的值变动，另一个NumberBox也变动

在线等

![image](https://user-images.githubusercontent.com/1888094/61709553-17504100-ad82-11e9-8fd5-c2be3b6345f5.png)
![image](https://user-images.githubusercontent.com/1888094/61709584-23d49980-ad82-11e9-96d3-f8a10dd7b91d.png)
![image](https://user-images.githubusercontent.com/1888094/61709623-32bb4c00-ad82-11e9-93cb-c52940b34154.png)

**Comment by huaiguoguo** [comment]
我单独拿到循环外面没有是正常的

![image](https://user-images.githubusercontent.com/1888094/61709788-8fb70200-ad82-11e9-8a17-5b1f39f86e2a.png)

![image](https://user-images.githubusercontent.com/1888094/61709828-a4939580-ad82-11e9-9303-b7a108bcf7eb.png)
请问这是什么原因

**Comment by huaiguoguo** [comment]
在同一个循环当中放两个NumberBox就没有问题
![image](https://user-images.githubusercontent.com/1888094/61709948-f9cfa700-ad82-11e9-890c-67237d7585c8.png)

**Comment by huaiguoguo** [comment]
我试了一下用这种方法是ok的，  也就是证明 使用v-if的时候   这个插件存在bug
![image](https://user-images.githubusercontent.com/1888094/61710246-bf1a3e80-ad83-11e9-9d16-87ac3f614037.png)
![image](https://user-images.githubusercontent.com/1888094/61710255-c6414c80-ad83-11e9-84d9-999e8ab40a72.png)
![image](https://user-images.githubusercontent.com/1888094/61710259-cb9e9700-ad83-11e9-990d-764c024bdce3.png)

**Comment by Wangyaqi** [comment]
可以给v-if加上:key ,这也是vue推荐的做法
[vue风格指南](https://cn.vuejs.org/v2/style-guide/#%E6%B2%A1%E6%9C%89%E5%9C%A8-v-if-v-else-if-v-else-%E4%B8%AD%E4%BD%BF%E7%94%A8-key-%E8%B0%A8%E6%85%8E%E4%BD%BF%E7%94%A8)
