### ISSUE TITLE
uni-pagination分页插件，用 this.$nextTick 刷新数据后，页码会跳到第1页。

### ISSUE THREAD

**Issue by CyrusZhou-CN** [dcloudio/uni-ui#342]
由于要实现购物车中修改了数据，在产品页也同步更新，用到了this.$nextTick ,但是刷新数据后，uni-pagination分页插件页码会跳到第1页。
重现步骤：
先在商品页选大于1的分页，选择购物车页 重新选回商品页，触发 onShow , this.$nextTick(() 执行后， 页码就会重置成第1页

代码如下：
```
onShow: function() {
			console.log('Index Show');
			let data = this.goodsList;
			this.goodsList = [];
			this.$nextTick(() => {
				this.goodsList = data;
			});`
		},
```

**Comment by lsqtzj** [comment]
找到解决方法了，用 :value 替代 :current 
如：
<uni-pagination :value="current" :total="total" :pageSize="pageSize"  title="标题文字" :show-icon="true"
				@change="change" />
