### ISSUE TITLE
前端项目启动就开始有这个问题了

### ISSUE THREAD

**Issue by LzOo0oO** [dcloudio/uni-ui#343]
[pages/contacts/list] Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./uni_modules/uni-load-more/components/uni-load-more/uni-load-more.wxss:234:35)

**Comment by mehaotian** [comment]
那个平台 ？ 是不是 nvue ?

**Comment by mehaotian** [comment]
因长时间无回复暂时关闭 issue ,如仍有问题请 reopen issue 继续提问。
