### ISSUE TITLE
什么时候会支持vue3

### ISSUE THREAD

**Issue by dw08** [dcloudio/uni-ui#344]

**Comment by zhetengbiji** [comment]
小程序、H5平台已支持vue3。App 平台进行中。详见https://ask.dcloud.net.cn/article/37834

**Comment by mehaotian** [comment]
最新版本 1.3.7 已经支持 vue3

**Comment by mehaotian** [comment]
issues 暂时关闭 ，如仍有问题请 reopen issue 继续提问。
