### ISSUE TITLE
表单提交后res返回为空对象

### ISSUE THREAD

**Issue by RexHarris** [dcloudio/uni-ui#345]
![image](https://user-images.githubusercontent.com/43196431/126284174-5b8b5cf3-6c67-4874-9c6f-332812cc2fdf.png)
```
<uni-forms ref="testform" :modelValue="formData">
      <uni-forms-item label="测试区域" name="testInput">
        <input v-model="formData.testInput" @input="binddata('testInput',$event.detail.value)"/>
      </uni-forms-item>
      <button formType="submit">下一步</button>
      <button @click="onTest">测试提交</button>
    </uni-forms>
```
```
data() {
    return {
      formData: {
        testInput: ''
      },
      rules: {
        testInput: {
          rules: [{
            required: true,
            errorMessage: '请输入',
          }]
        }
      }
    }
  },
```
```
methods: {
 
    onTest() { 
      this.$refs.testform.validate().then(res=>{
          console.log('formData: ', this.formData)
          console.log('表单数据信息：', res);
      }).catch(err =>{
          console.log('表单错误信息：', err);
      })
    },
}
```

**Comment by RexHarris** [comment]
![image](https://user-images.githubusercontent.com/43196431/126284829-0fb1b6d4-a83f-4299-9bdd-5ebea03a14f3.png)
uni-forms和uni-forms-item 使用easycom导入

**Comment by mehaotian** [comment]
什么平台 ？modelValue 改成 value 试一试

**Comment by RexHarris** [comment]
小程序
改成value结果仍返回空对象

**Comment by mehaotian** [comment]
![image](https://user-images.githubusercontent.com/26707388/126292501-49177001-57fc-442e-8f90-e997e532c57e.png)

你规则绑定到那里去了 ？

**Comment by RexHarris** [comment]
上面的代码的确是忘记绑定rules了，我试了一下，添加rules绑定，并用validate提交之后返回的数据是正常的，但我把rules去掉，并使用submit提交却为空对象

**Comment by mehaotian** [comment]
> 上面的代码的确是忘记绑定rules了，我试了一下，添加rules绑定，并用validate提交之后返回的数据是正常的，但我把rules去掉，并使用submit提交却为空对象

如果不配置rules 就是不参与校验 ，所以不会返回对象 ，这个问题已经修复了，稍后发布
