### ISSUE TITLE
uni-segmented-control 分段器   组件页面中的css修改无效

### ISSUE THREAD

**Issue by airmz** [dcloudio/uni-ui#348]
浏览器缓存也清了 也重新编译了  组件内的style scoped属性也添加了  也尝试了添加/deep/ 都不生效 页面中的css还是原来的

**Comment by Fasttian** [comment]
控制台审查元素样式，是否有你添加的样式，如有，是否优先级不够

**Comment by codexu** [comment]
长时间未响应，问题暂时关闭；
若后续依然有问题，可reopen这个issue。
