### ISSUE TITLE
uni-popup-dialog未适配uni.scss主题色

### ISSUE THREAD

**Issue by Saraiby** [dcloudio/uni-ui#349]
uni-ui/uni_modules/uni-popup/components/uni-popup-dialog/uni-popup-dialog.vue
![image](https://user-images.githubusercontent.com/79783642/126854429-76f88c06-96b0-4da7-9d3d-7b810583a1fc.png)
![image](https://user-images.githubusercontent.com/79783642/126854455-c05555ef-1502-4fa0-b048-a1aa5746a051.png)

**Comment by mehaotian** [comment]
uni-popup-dialog 不算uni-ui 的正式组件，只是 uni-popup 的扩展 ，主要用途是用来给用户参考实现扩展

issue 暂时关闭 ，如仍有问题请 reopen issue 继续提问。
