### ISSUE TITLE
快手APP中uni-icon显示异常

### ISSUE THREAD

**Issue by jotzhao** [dcloudio/uni-ui#351]
在快手app中使用uni-icon的话，不能正常显示，显示一个方框。
使用的代码是：
```
<uni-icons type="arrowright" color="#4299EA" size="15"></uni-icons>
```
烦请看一下是怎么回事。
![Uploading 微信图片_20210726215042.png…]()

**Comment by Fasttian** [comment]
确认bug

**Comment by 18148764734** [comment]
现版本测试未复现，猜测已经修复，后续type赋值需要加上 - 
例如： arrow-right
