### ISSUE TITLE
uni-icon 存在可点击元素的响应区域过小

### ISSUE THREAD

**Issue by guyskk** [dcloudio/uni-ui#353]
微信小程序 Audits 评测时，会报告 uni-icon 存在可点击元素的响应区域过小，这些图标是纯展示用，我没有绑定 click 事件。希望在没有绑定 click 事件时，uni-icon 内部也不要绑定空的 click 事件，否则会影响微信小程序体验评分。

**Comment by Fasttian** [comment]
uni-icons 默认大小是16*16，有点小，为了向下兼不能修改，不过可以通过 size 属性设置大小；click事件是必须抛出的，如果你的不需要可以从组件内部移除。

**Comment by guyskk** [comment]
@Fasttian 图标大小不需要调整，问题在 click 事件。
当图标仅用作展示时，可以设置 uni-icons 内部不绑定 click 事件吗？

如果我没理解错：uni-icons 内部用了其他组件，然后绑定其 click 事件，再 emit 出 click 事件。
我希望设置uni-icons 内部组件不绑定click事件。

**Comment by mehaotian** [comment]
icon 元素内只有一个text元素 ，绑定事件的原因是为了 实现 <uni-icons @click="xxx"> 类似用法 ，如不写的话，在标签上需要使用修饰符才能绑定事件。  issue 暂时关闭 ，如仍有问题 ，请 reopen issue 继续提问。
