### ISSUE TITLE
uni-datetime-picker 报错

### ISSUE THREAD

**Issue by nobage** [dcloudio/uni-ui#354]
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'calendar' of undefined"

根据提示找到问题，isPhone=true 时clear方法中的 this.$refs.pcSingle 为undefined 。

暂时通过如下处理解决问题：

```
if(!this.isPhone){
	this.$refs.pcSingle.calendar.fullDate = ''
	this.$refs.pcSingle.setDate()
}
```

**Comment by Fasttian** [comment]
已修复，更新一下 https://ext.dcloud.net.cn/plugin?id=3962， npm下一版发布
