### ISSUE TITLE
uni-tag 颜色类型(type)不是default，大小尺寸(size)是small 显示不正确

### ISSUE THREAD

**Issue by wangsuiche** [dcloudio/uni-ui#356]
` 
<uni-tag text="测试" type="warning" size="small" :circle="true" ></uni-tag>
`
uni-tag-text 会覆盖掉uni-tag-text--small的字体大小，导致字体大小显示不正确。

**Comment by Fasttian** [comment]
bug 已处理，更新一下， https://ext.dcloud.net.cn/plugin?name=uni-tag
