### ISSUE TITLE
uni-number-box能不能提供size属性可以调整大小

### ISSUE THREAD

**Issue by Duanzihuang** [dcloudio/uni-ui#359]
尊敬的uni-ui团队，能不能给uni-number-box能不能提供size属性可以调整大小，感谢。

**Comment by Fasttian** [comment]
目前没有支持，如果你的项目不使用Firefox，可以临时使用 `zoom: 70%` 处理一下

**Comment by codexu** [comment]
长时间未响应，问题暂时关闭；
若后续依然有问题，可reopen这个issue。
