### ISSUE TITLE
uni-data-checkbox  mode="list" 图标不见了

### ISSUE THREAD

**Issue by webhejian** [dcloudio/uni-ui#360]
![image](https://user-images.githubusercontent.com/50898616/128823789-25e99519-1453-43c2-a85e-f661bf88f0cf.png)
其他模式下都正常

**Comment by webhejian** [comment]
![image](https://user-images.githubusercontent.com/50898616/128823923-1e5a8411-8fdd-40d6-b305-e44d1b0dc436.png)

**Comment by webhejian** [comment]
![image](https://user-images.githubusercontent.com/50898616/128827713-591db5cb-9338-455a-99ee-5ea9731a9755.png)
mode为list的时候styleBackgroud为空

**Comment by Fasttian** [comment]
在什么平台下有这个问题？h5？小程序？

**Comment by 490626721** [comment]
同样问题，单选样式切换为列表时选中样式未显示，平台：web
