### ISSUE TITLE
i18n依赖报错（平台判断注释写漏了）

### ISSUE THREAD

**Issue by listen-amo** [dcloudio/uni-ui#369]
![image](https://user-images.githubusercontent.com/33443525/130421997-549caeb1-27a8-4c79-beb8-8dc83b8e4cc8.png)
这部分导入的代码加上平台判断可以解决

**Comment by mehaotian** [comment]
具体表现是什么 ？

**Comment by 505799690** [comment]
在小程序下 这个地方i18n 只会加载en
