### ISSUE TITLE
uni-forms验证逻辑bug

### ISSUE THREAD

**Issue by listen-amo** [dcloudio/uni-ui#370]
![image](https://user-images.githubusercontent.com/33443525/130766816-be8ed311-4bf8-433e-a62e-1e6c6acaeabf.png)
无力吐槽，，，表单项的值清空的时候这里直接return，所以用于验证值的 formData 对象里面始终有值。下边这行是我改过的

**Comment by mehaotian** [comment]
问题已经修复 ，不过不是这个问题造成的，实际的赋值不是这个地方  ，issue 暂时关闭 ，如仍有问题请 reopen issue 继续提问。
