### ISSUE TITLE
uni-nav-bar的缺陷如下修复，希望官方采纳

### ISSUE THREAD

**Issue by yangjinlin-ops** [dcloudio/uni-ui#374]
.uni-navbar .uni-navbar__header {
	justify-content: space-between;
}

.uni-navbar .uni-navbar__header .uni-navbar__header-container {
	justify-content: center;
}

.uni-navbar .uni-navbar__header>uni-view:nth-child(1),
.uni-navbar .uni-navbar__header>uni-view:nth-child(3) {
	width: 70rpx;
	justify-content: center;
}

.uni-navbar .uni-navbar__header>uni-view:nth-child(1) .uni-icons {
	font-size: 44rpx !important; /* 如果图标的尺寸做的再标准点就好了 */
	font-weight: normal;
}

**Comment by mehaotian** [comment]
已修改
