### ISSUE TITLE
render函数无法使用`uni-forms`创建元素

### ISSUE THREAD

**Issue by arrayliny** [dcloudio/uni-ui#375]
我在封装自己的forms组件时，使用render函数无法使用`uni-forms`创建元素，必须手动注册到全局。希望想模板语法一样，提供可以直接render使用的解决办法

**Comment by mehaotian** [comment]
uniapp 暂时不推荐使用 render ,非h5 都是不能使用的

**Comment by mehaotian** [comment]
issue 暂时关闭 ，如仍有问题请 reopen issue。
