### ISSUE TITLE
uni-datetime-picker插槽失效

### ISSUE THREAD

**Issue by 321802282** [dcloudio/uni-ui#376]
版本 1.4.2

`<uni-datetime-picker v-model="single">我是一个插槽，点击我</uni-datetime-picker>`

![image](https://user-images.githubusercontent.com/34932584/131635733-1dfd9872-d58b-4311-a114-74ef3258457d.png)

**Comment by Fasttian** [comment]
HBuilder X 创建的项目，还是 cli 项目？

**Comment by mehaotian** [comment]
因长时间无回复暂时关闭 issue ,如仍有问题请 reopen issue 继续提问。
