### ISSUE TITLE
`uni-icons` 有的图标不能正常显示

### ISSUE THREAD

**Issue by clai-wh** [dcloudio/uni-ui#377]
`hx 3.2.6.20210901-alpha` `vue3`

![屏幕截图 2021-09-11 165207](https://user-images.githubusercontent.com/52877043/132942356-63b53a08-cb2a-459d-a9b1-9ff2da3b4876.png)

h5 elements DOM 显示

![屏幕截图 2021-09-11 165503](https://user-images.githubusercontent.com/52877043/132942509-38c477f9-9bd2-4f8f-9e7c-9a3ed1882b46.png)

h5页面

![屏幕截图 2021-09-11 165225](https://user-images.githubusercontent.com/52877043/132942358-98a4b6f9-151d-47ba-98aa-58b5b6420e88.png)

APP 页面

![屏幕截图 2021-09-11 165655](https://user-images.githubusercontent.com/52877043/132942459-9b1e7724-620b-4640-9026-794c1d26136e.png)

**Comment by mehaotian** [comment]
提供一下你的开发环境，vue2 还是vue3 ？ 组件版本 ？组件来源

**Comment by clai-wh** [comment]
> 提供一下你的开发环境，vue2 还是vue3 ？ 组件版本 ？组件来源

`vue3` 
也把该组件改成了 setup 的格式
通过 插件市场下载的(非 `uni_modules` 版本)

**Comment by clai-wh** [comment]
> > 提供一下你的开发环境，vue2 还是vue3 ？ 组件版本 ？组件来源
> 
> `vue3`
> 也把该组件改成了 setup 的格式
> 通过 插件市场下载的(非 `uni_modules` 版本)
> 
> `script`
> ![屏幕截图 2021-09-14 133903](https://user-images.githubusercontent.com/52877043/133201479-af698c9e-e82d-40c6-a3be-bc8c9dc86fc1.png)

已解决
