### ISSUE TITLE
支付宝小程序使用uni-search-bar存在输入问题

### ISSUE THREAD

**Issue by wangsuiche** [dcloudio/uni-ui#379]
代码如下：
` 
<uni-search-bar v-model="searchText"></uni-search-bar>
`

当输入速度比较快的时候，或者输入内容很多后，长按Backspace，就会出现闪屏。

uni-search-bar版本1.1.2
HBuilder X版本 3.1.17

**Comment by 18148764734** [comment]
未复现该问题，推测此问题已经修复，此issue暂时关闭
