### ISSUE TITLE
v3引入uni-ui  使用后 打包app报错，导致无法打包

### ISSUE THREAD

**Issue by Yiloufglei** [dcloudio/uni-ui#380]
![1631584610(1)](https://user-images.githubusercontent.com/48450234/133181999-975d20a9-d2d1-4fab-b33c-eca6c61d3c4d.png)
还望大佬解决一下

**Comment by mehaotian** [comment]
你这个组件是怎么来？npm 安装 ？插件市场？还是从 hello uni-app 拷贝过来的？

**Comment by Fasttian** [comment]
`@charset "UTF-8";` 没有用处，直接删掉即可

**Comment by mehaotian** [comment]
从插件市场导入项目 ，不要从hello uni-app 拷贝 。

issue 暂时关闭 ，如仍有问题 ，请 reopen issue .
