### ISSUE TITLE
uni-popup组件在真机上需要很长时间才能弹出来

### ISSUE THREAD

**Issue by dilireba521** [dcloudio/uni-ui#381]
[https://github.com/dcloudio/uni-ui/issues/212](url)这个问题好像任然存在，我在uni-popup版本1.6.2，底部弹框操作时在iPhone X 上大概有2～3s的延迟，在红米K20 Pro上有大概 1～1.5s的延迟。
看了下源码，时间影响最大的是uni-transition组件内的open()方法内的setTimeout事件，想了想应该是js单线程任务队列中，这段逻辑在比较靠后的时间才执行，注释掉代码后iPhone X 在1～1.5s的延迟，红米K20 Pro延迟在1s以内。
不过这边有个TODO想知道有哪些问题可以透露下吗？想判断下是否依然使用这种方式实现功能。

```
open() {
	clearTimeout(this.timer)
	this.transform = ''
	this.isShow = true
	let { opacity, transform } = this.styleInit(false)
	if (typeof opacity !== 'undefined') {
		this.opacity = opacity
	}
	this.transform = transform
	// 确保动态样式已经生效后，执行动画，如果不加 nextTick ，会导致 wx 动画执行异常
	this.$nextTick(() => {
		// TODO 定时器保证动画完全执行，目前有些问题，后面会取消定时器
		// this.timer = setTimeout(() => {
			this.animation = createAnimation(this.config, this)
			this.tranfromInit(false).step()
			this.animation.run()
			this.$emit('change', {
				detail: this.isShow
			})
		// }, 10)
	})
},
```

**Comment by mehaotian** [comment]
使用最新版本组件，你这代码已经是很老的组件代码，issue 暂时关闭 ，如仍有问题请 reopen issue

**Comment by dilireba521** [comment]
> 使用最新版本的组件，你这代码已经是老的组件代码了，issue 暂时关闭，如有问题请重新打开 issue
![image](https://user-images.githubusercontent.com/59365302/133768925-c71f6684-b83a-4dad-8b84-df1f6c9cb560.png)
你好，我是这个月才开始的项目，插件是使用uniapp官网可视化操作添加入项目的，又看了下uniapp git地址的版本号和我现在项目是一致的，但还是出现这种卡顿的问题。

**Comment by mehaotian** [comment]
最新版本就是1.6.2 ，如果你没更新过代码 ，那你上面发的代码就是错误的，如果更新过代码 ，并保证代码是最新的，那可能是其他问题导致 ，而且只是个别手机卡顿，我需要测试一下

**Comment by dilireba521** [comment]
非常感谢，主要是ios手机辛苦多测试下，要是没有出现类似的问题，希望及时告知下

**Comment by mehaotian** [comment]
使用最新组件，测试了多个ios ,均为出现卡顿问题 ，跑示例也是一样有卡顿问题吗？

**Comment by dilireba521** [comment]
找到问题的原因了，动画卡顿情况只是在编译模式会出现，关闭编译模式后直接在后台打开小程序就没有问题了。之前测试一直没留意这个情况，非常感谢你的帮助
