### ISSUE TITLE
引入uni-swipe-action和uni-swipe-action-item 在Android List列表下不可见区域的侧滑划不动

### ISSUE THREAD

**Issue by xufengzi** [dcloudio/uni-ui#382]
引入uni-swipe-action和uni-swipe-action-item 在Android List列表下不可见区域的侧滑划不动，下面 是getSelectorQuery 方法获取侧滑按钮的数据 有高度的是可显示的区域可以侧滑，高度为0 不可显示区域，List列表滑到可现实区域侧滑划不动
13:41:47.200 [Object] [{"size":{"height":88.36363220214844,"right":0,"bottom":220,"width":0,"left":0,"top":131.6363525390625},"r...}  at lib/components/swipeAction/bindingx.js:266
13:41:47.219 [Object] [{"size":{"height":88.36363220214844,"right":0,"bottom":308.7272644042969,"width":0,"left":0,"top":220.363...}  at lib/components/swipeAction/bindingx.js:266
13:41:47.240 [Object] [{"size":{"height":88.36363220214844,"right":0,"bottom":397.45452880859375,"width":0,"left":0,"top":309.09...}  at lib/components/swipeAction/bindingx.js:266
13:41:47.261 [Object] [{"size":{"height":88.36363220214844,"right":0,"bottom":486.18182373046875,"width":0,"left":0,"top":397.81...}  at lib/components/swipeAction/bindingx.js:266
13:41:47.281 [Object] [{"size":{"height":88.36363220214844,"right":0,"bottom":574.9090576171875,"width":0,"left":0,"top":486.545...}  at lib/components/swipeAction/bindingx.js:266
13:41:47.301 [Object] [{"size":{"height":88.36363220214844,"right":0,"bottom":663.6363525390625,"width":0,"left":0,"top":575.272...}  at lib/components/swipeAction/bindingx.js:266
13:41:47.322 [Object] [{"size":{"height":88.36363220214844,"right":0,"bottom":752.3635864257812,"width":0,"left":0,"top":664},"r...}  at lib/components/swipeAction/bindingx.js:266
13:41:47.342 [Object] [{"size":{"height":88.36363220214844,"right":0,"bottom":841.0909423828125,"width":0,"left":0,"top":752.727...}  at lib/components/swipeAction/bindingx.js:266
13:41:47.363 [Object] [{"size":{"height":0,"right":0,"bottom":0,"width":0,"left":0,"top":0},"result":true},{"size":{"height":0,"...}  at lib/components/swipeAction/bindingx.js:266
13:41:47.384 [Object] [{"size":{"height":0,"right":0,"bottom":0,"width":0,"left":0,"top":0},"result":true},{"size":{"height":0,"...}  at lib/components/swipeAction/bindingx.js:266
13:41:47.405 [Object] [{"size":{"height":0,"right":0,"bottom":0,"width":0,"left":0,"top":0},"result":true},{"size":{"height":0,"...}  at lib/components/swipeAction/bindingx.js:266
13:41:47.424 [Object] [{"size":{"height":0,"right":0,"bottom":0,"width":0,"left":0,"top":0},"result":true},{"size":{"height":0,"...}  at lib/components/swipeAction/bindingx.js:266
13:41:47.445 [Object] [{"size":{"height":0,"right":0,"bottom":0,"width":0,"left":0,"top":0},"result":true},{"size":{"height":0,"...}  at lib/components/swipeAction/bindingx.js:266
13:41:47.466 [Object] [{"size":{"height":0,"right":0,"bottom":0,"width":0,"left":0,"top":0},"result":true},{"size":{"height":0,"...}  at lib/components/swipeAction/bindingx.js:266
13:41:47.487 [Object] [{"size":{"height":0,"right":0,"bottom":0,"width":0,"left":0,"top":0},"result":true},{"size":{"height":0,"...}  at lib/components/swipeAction/bindingx.js:266
13:41:47.508 [Object] [{"size":{"height":0,"right":0,"bottom":0,"width":0,"left":0,"top":0},"result":true},{"size":{"height":0,"...}  at lib/components/swipeAction/bindingx.js:266
13:41:47.528 [Object] [{"size":{"height":0,"right":0,"bottom":0,"width":0,"left":0,"top":0},"result":true},{"size":{"height":0,"...}  at lib/components/swipeAction/bindingx.js:266
13:41:47.552 [Object] [{"size":{"height":0,"right":0,"bottom":0,"width":0,"left":0,"top":0},"result":true},{"size":{"height":0,"...}  at lib/components/swipeAction/bindingx.js:266
13:41:47.570 [Object] [{"size":{"height":0,"right":0,"bottom":0,"width":0,"left":0,"top":0},"result":true},{"size":{"height":0,"...}  at lib/components/swipeAction/bindingx.js:266

**Comment by mehaotian** [comment]
已经存在相同issue ,当前issue 暂时关闭
