### ISSUE TITLE
ui-popup input 模式在vue3下面无法显示title和按钮文字

### ISSUE THREAD

**Issue by alimwang** [dcloudio/uni-ui#389]
![image](https://user-images.githubusercontent.com/9711287/134838772-7b3c6cbb-4e76-4d59-81f3-f22c2f841ec3.png)
微信模拟器
微信基础库: 2.19.5

vue2正常

**Comment by mehaotian** [comment]
有没有报错？确认一下组件版本

**Comment by mehaotian** [comment]
使用最新版本的 HBuilderX  ，应该是国际化问题导致的，暂时关闭 issue ，如仍有问题 ，请 reopen issue 继续提问。
