### ISSUE TITLE
uni-easyinput 设置 trim="all" 后仍然能够输入空格

### ISSUE THREAD

**Issue by WuFengXue** [dcloudio/uni-ui#390]
插件版本：0.1.4

现象：
1、行尾可以输入空格，遇到非空格字符时才会把前面的空格清除
2、通过打印日志，实际取值是去除空格了的

预期：任何场景都不能输入空格

官方插件DEMO示例如下：

![uni-easyinput组件清除空格UI异常](https://user-images.githubusercontent.com/12031430/135235653-ff29681e-5e59-42a4-8fa8-20a5834349ff.gif)

**Comment by mehaotian** [comment]
现在的逻辑确实是你描述的这样 ，是可以输入空格的 ，只是会对空格进行处理
