### ISSUE TITLE
TypeError: _vm.__get_style is not a function

### ISSUE THREAD

**Issue by jiyuan12354** [dcloudio/uni-ui#391]
问题简述：
使用npm方式创建的模板项目，始终没办法集成uni-ui

复现步骤：
![image](https://user-images.githubusercontent.com/14569395/135739657-b8de7d67-4f2d-4ba9-af1c-7b3ed1c16613.png)
![image](https://user-images.githubusercontent.com/14569395/135739688-ffa414cd-058c-41fd-81b9-3d5655bb3d2a.png)
`node -v                   v14.17.0`

```
vue create -p dcloudio/uni-preset-vue#vue3 my-uni-vue3-project
// 选择Typescript，一路默认配置

yarn add sass -D

yarn add sass-loader@10.1.1 -D

yarn add @dcloudio/uni-ui
```

使用 npm + easycom 集成（直接npm使用不知道咋用，uni-ui的readme没有vue3引入的示例貌似？）
![image](https://user-images.githubusercontent.com/14569395/135739898-08377147-546f-45ed-954a-83f66e75ab07.png)
![image](https://user-images.githubusercontent.com/14569395/135739906-a4fa75a8-e446-428a-b65c-023471607a5b.png)
![image](https://user-images.githubusercontent.com/14569395/135739919-ae9ac6ec-52ff-42e7-8379-0b1b19c22908.png)

步骤就是这样，完完全全按Readme来的，但是 yarn dev:mp-weixin 之后用微信开发工具打开dist下的工程显示如下错误！
![image](https://user-images.githubusercontent.com/14569395/135739991-0dcd6375-30ab-410e-8309-306361903fd1.png)

**Comment by jiyuan12354** [comment]
换了非TypeScript模板试了也是这样 （ npm + easycom ），这框架行不行啊！

**Comment by jiyuan12354** [comment]
重试了一遍，依旧是报这个错

**Comment by mehaotian** [comment]
问题一直无法复现，希望可以提供一个完成的测试工程

**Comment by jiyuan12354** [comment]
related https://github.com/dcloudio/uni-app/issues/2469
uni-ui/uni-badge used computed style
