### ISSUE TITLE
uni-data-pickerview bind value=0 时无法选中

### ISSUE THREAD

**Issue by guyskk** [dcloudio/uni-ui#392]
当 value 值等于 0 时，无法选中 localdata 数值中 value=0 的选项。

```vue
<uni-data-picker
    class="input-picker"
    :localdata="options"
    :value="value"
    @change="onChange"
  ></uni-data-picker>
```

可能是这里 `&& !this.value` 把 0 当作 false 处理，导致 value 没有被使用：
https://github.com/dcloudio/uni-ui/blob/master/packages/lib/uni-data-pickerview/uni-data-picker.js#L132

**Comment by 18148764734** [comment]
注意value传值是为数组类型。改成[0]
