### ISSUE TITLE
uni-forms 组件rules不生效

### ISSUE THREAD

**Issue by qhh001** [dcloudio/uni-ui#398]
https://ext.dcloud.net.cn/plugin?id=2773，官方例子的完整实例，
![image](https://user-images.githubusercontent.com/20916888/137270167-b380e7c1-c02e-4adf-9c8c-8999db3c1531.png)

![image](https://user-images.githubusercontent.com/20916888/137270272-cfd75f44-52a1-430f-b7db-2545a429b405.png)

![image](https://user-images.githubusercontent.com/20916888/137270297-a546e289-88f1-4d03-ade1-f1a88c7a9f0a.png)
样式不生效也不校验规则

**Comment by mehaotian** [comment]
样式和校验规则都不生效的话 ，检查组件使用正确引用

**Comment by mehaotian** [comment]
因长时间无回复暂时关闭 issue ，如仍有问题请 reopen issue 继续提问。
