### ISSUE TITLE
uni-icon 多端显示问题

### ISSUE THREAD

**Issue by CR903** [dcloudio/uni-ui#4]
H5端可以显示：
![image](https://user-images.githubusercontent.com/7643647/51301744-400e1b80-1a6b-11e9-9aa5-6e8851425aa1.png)

微信小程序无法显示：
![image](https://user-images.githubusercontent.com/7643647/51301764-50be9180-1a6b-11e9-80ce-42cb8840561d.png)

app端：
![image](https://user-images.githubusercontent.com/7643647/51301788-6469f800-1a6b-11e9-846f-8779a50e5c56.png)

代码如下：
![image](https://user-images.githubusercontent.com/7643647/51301821-7d72a900-1a6b-11e9-9ed7-d2458d178713.png)

**Comment by CR903** [comment]
非常感谢回复。

![image](https://user-images.githubusercontent.com/7643647/51373545-69967800-1b3b-11e9-8796-98bf8a1b5cc7.png)


我是这样引入的，编译后没有出现警告。

微信出现了此元素
![image](https://user-images.githubusercontent.com/7643647/51373735-d1e55980-1b3b-11e9-9e32-1a8269e785ed.png)

**Comment by hulinNeil** [comment]
小程序调试的时候标签显示 uni-icon 说明组件引用不成功。
使用目前你这种引入组件的方式只有cli创建的uni-app项目和HBuilderX1.4.7+版本创建的uni-app项目支持（HBuilderX还未发正式版，QQ交流群里有最新的HBuilder1.4.7的安装包）

**Comment by CR903** [comment]
谢谢。

那不是这个版本的HBuilderX可以以什么方式引入呢？

**Comment by hulinNeil** [comment]
使用如下方式引入，不过这两天估计更新HBuilderX了，到时就支持了
`
import uniBadge from '@dcloudio/uni-ui/lib/uni-badge/uni-badge.vue'
`

**Comment by CR903** [comment]
OK。谢谢，已经可以了。
