### ISSUE TITLE
怎么完成微信小程序的测试。

### ISSUE THREAD

**Issue by zhaoyajie413** [dcloudio/uni-ui#40]
怎么将项目运行到小程序中呢。package.json中好像也没有找到脚本。小程序好像无法用Vue.component来注册全局组件。

**Comment by Wangyaqi** [comment]
参考uni-app官网 [运行并发布uni-app](https://uniapp.dcloud.io/quickstart?id=%e8%bf%90%e8%a1%8c%e5%b9%b6%e5%8f%91%e5%b8%83uni-app)

**Comment by zhaoyajie413** [comment]
我下载了@dcloudio/uni-ui 这个包，但是在小程序中组件并没有挂载。
const install = function(Vue, options) {
	const components = require.context('../packages', true, /\.vue$/)
	components.keys().forEach(fileName => {
		// 获取组件配置
		const componentConfig = components(fileName)['default']
		// 全局注册组件
		Vue.component(componentConfig.name, componentConfig)
	})
}
export default install
这样处理貌似只能在h5注册组件。

**Comment by Wangyaqi** [comment]
uni-ui是基于vue的组件库，推荐搭配uni-app使用

**Comment by tzzhmm** [comment]
> uni-ui是基于vue的组件库，推荐搭配uni-app使用

您好,问您个问题
我的**在小程序端 loadMore 区域展示 Undefined**
具体参考 [](https://ask.dcloud.net.cn/question/77475) 有详细问题描述及截图
