### ISSUE TITLE
修改遮罩层透明度问题，vue-ref是遮罩层class，有过渡动画时会有两层。

### ISSUE THREAD

**Issue by requestVcs1** [dcloudio/uni-ui#403]
两个transition标签内都有vue-ref如何修改透明度两个都修改了，透明度叠加了

**Comment by mehaotian** [comment]
贴一下具体的代码和结果 ，有点没看明白

**Comment by codexu** [comment]
长时间未响应，问题暂时关闭；
若后续依然有问题，可reopen这个issue。
