### ISSUE TITLE
支付宝小程序中uni-icon打包异常(CLI创建的uniapp项目)

### ISSUE THREAD

**Issue by gaochuang159753** [dcloudio/uni-ui#405]
<style lang="scss" scoped>
	/* #ifndef APP-NVUE */
	@font-face {
		font-family: uniicons;
		src: url('./uni.ttf') format('truetype');
	}

	/* #endif */

	.uni-icons {
		font-family: uniicons;
		text-decoration: none;
		text-align: center;
	}
</style>

uni-icons中引入./uni.ttf打包成支付宝小程序之后路径是/node_modules/@dcloudio/uni-ui/lib/uni-icons/uni.ttf, 然而这个文件找不到, 会在支付宝中报错

**Comment by 18148764734** [comment]
现版本已修复，路径正常引入，此ISSUE正常关闭
