### ISSUE TITLE
uni-table 表格H5版在PC模式，使用date筛选在数据量少，时间选取UI会被挡住的问题

### ISSUE THREAD

**Issue by sdfwds4** [dcloudio/uni-ui#406]
uni-table 表格H5版在内置浏览器的PC模式上，和Chrome浏览器上，使用date筛选在数据量少时，时间选取UI会被挡住的问题。

操作系统：Windows 10
HBuilderX：3.2.9.20210927
uni-table：1.1.0（2021-07-30）

代码：
`
<uni-th width="170" align="center" filter-type="date" @filter-change="onDateFilterChanged">注册时间</uni-th>
`

![image](https://user-images.githubusercontent.com/7692002/138454221-af228ee1-bc9d-4bae-983b-ca974fa26831.png)

**Comment by mehaotian** [comment]
确实会有这个问题 ，因为外层添加了滚动 ，滚动需要 overflow:hidden ,所以会影响里面的元素显示，目前的解决方案是给 表格增加一个固定的合适高度 ，不要自动撑高，可暂时解决

**Comment by codexu** [comment]
长时间未响应，问题暂时关闭；
若后续依然有问题，可reopen这个issue。
