### ISSUE TITLE
uni-nav-bar设置fixed为true时宽度不是100%

### ISSUE THREAD

**Issue by labike** [dcloudio/uni-ui#407]
<img width="775" alt="截屏2021-10-27 上午10 41 07" src="https://user-images.githubusercontent.com/15871933/138990907-0ba88b3a-889f-4c2e-a92a-a210d7c46c36.png">

如图示, 去掉fiexd=true恢复正常

**Comment by mehaotian** [comment]
看一下你模板代码的结构

**Comment by labike** [comment]
```
<template>
    <view>
        <uni-nav-bar />
        <scrollview>
             .........
        </scrollview>
    </view>
</template>
```
