### ISSUE TITLE
uni-ui 如何在 vite 打包的 uni-app 框架中使用？

### ISSUE THREAD

**Issue by sufuWang** [dcloudio/uni-ui#414]
使用 `npx degit dcloudio/uni-preset-vue#vite my-vue3-project` 新建一个项目，如何在其中使用 uni-ui ？

**Comment by EvinqWang** [comment]
请问你解决了吗？ 怎么使用 "transpileDependencies"   对node_modules 下的uni-ui进行编译

**Comment by dyh333** [comment]
有人回答下没？？？

**Comment by juweinan** [comment]
这个到底怎么玩，vite中是没有 transpileDependencies 的

**Comment by wghe110** [comment]
同样问题

**Comment by StringKe** [comment]
@codexu 麻烦查看一下这个问题，如果直接按照文档使用 `import {uniCard} from '@dcloudio/uni-ui'` 这样的方式倒入，但这个 npm 包并没有配置入口文件。

**Comment by codexu** [comment]
vite 不需要配置 transpileDependencies。
安装 uni-ui sass，然后配置 pages easycom 即可
