### ISSUE TITLE
uni-collapse在leftwindow中使用报错

### ISSUE THREAD

**Issue by SunSi12138** [dcloudio/uni-ui#418]
![image](https://user-images.githubusercontent.com/54728594/144290256-8d63b871-c4a7-4c50-9771-f139f53e63bb.png)
![image](https://user-images.githubusercontent.com/54728594/144345197-e5857664-8dc1-4230-b16a-49b9f21d9440.png)

组件不能正确初始化
uni-ui版本：1.4.9，modul安装

**Comment by 18148764734** [comment]
现版本在vue2/3环境测试下均未复现该问题，猜测现版本已经修复，此issue暂时关闭
