### ISSUE TITLE
app 中无效

### ISSUE THREAD

**Issue by guwei000** [dcloudio/uni-ui#42]
用在app上面的时候，数据不显示，这是为什么，有的时候还会莫名的报错，uni
        .createSelectorQuery()
        .in(this)
        .select(`#${this.elId}`)
        .boundingClientRect()
        .exec(ret => {
          this.btnGroupWidth = ret[0].width;
        });
说: Cannot read property 'width' of null 

![image](https://user-images.githubusercontent.com/26682207/62848514-a069f080-bd0e-11e9-93ec-2c0e4e6f6271.png)
![image](https://user-images.githubusercontent.com/26682207/62848543-baa3ce80-bd0e-11e9-98ac-0a904bd1b088.png)

**Comment by guwei000** [comment]
在h5上是一切正常的

**Comment by Wangyaqi** [comment]
现已更新github，插件市场，npm
