### ISSUE TITLE
uni-load-more nvue页面不显示文字

### ISSUE THREAD

**Issue by haliuhei** [dcloudio/uni-ui#425]
https://github.com/dcloudio/uni-ui/blob/0ba41fb9d3785d9e85963de6a7900cd840dcc9fc/uni_modules/uni-load-more/components/uni-load-more/uni-load-more.vue#L112
注释了计算属性，导致nvue页面不显示文字

**Comment by 18148764734** [comment]
现版本已修复，感谢反馈
