### ISSUE TITLE
uni-number-box 数字输入框键盘模式

### ISSUE THREAD

**Issue by sunnyyuu** [dcloudio/uni-ui#428]
uni-number-box 数字输入框控件当step为小数时，弹出的键盘不带小数点，应该设置键盘为digit而非number

**Comment by passioncsu** [comment]
amz  这个竟然2年前就提了  还没修  这个项目是已经死了吗?  没人维护了吗

**Comment by 18148764734** [comment]
感谢反馈，十分抱歉此问题长时间搁置，现版本已修复

> amz 这个竟然2年前就提了 还没修 这个项目是已经死了吗? 没人维护了吗
