### ISSUE TITLE
hbuilderx 3.3.2.20211218-alpha版本使用uni-swipe-action编译报错

### ISSUE THREAD

**Issue by Iongtao** [dcloudio/uni-ui#429]
编译错误：
[plugin:vite:vue] Could not load /Users/longtao/dhf/qt-uni/uni_modules/uni-swipe-action/components/uni-swipe-action-item/wx.wxs?vue&type=wxs&index=0&src&name=wxsswipe&lang.wxs (imported by ../../../../../../Users/longtao/dhf/qt-uni/uni_modules/uni-swipe-action/components/uni-swipe-action-item/uni-swipe-action-item.vue): Illegal tag name. Use '&lt;' to print '<'.

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/issues/3069

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/commit/89c7fe9d186d1354f7c6a37ec9791463845e77f0

**Comment by Iongtao** [comment]
> 

这个问题是已经修复了吗 好像还没有更新版本？

**Comment by fxy060608** [comment]
> > 
> 
> 这个问题是已经修复了吗 好像还没有更新版本？

未更新

**Comment by Iongtao** [comment]
>

**Comment by Iongtao** [comment]
编译时候后出现了这样的错误，但好像不影响运行
![image](https://user-images.githubusercontent.com/24762616/147427384-dbc7cc62-92b9-4053-ba5a-06c41f6cd761.png)
