### ISSUE TITLE
left icon 颜色不能被修改，总是显示#333，即使为uni-nav-bar添加了color属性

### ISSUE THREAD

**Issue by qiyue-lyr** [dcloudio/uni-ui#430]
![image](https://user-images.githubusercontent.com/35659384/147331868-9009777a-cd2b-48f4-a3ea-286b5a6c376b.png)

**Comment by ihwf** [comment]
没改啊,还是一样 @mehaotian

**Comment by mehaotian** [comment]
你看错 目录了，在 uni_modules 下的组件才是源码

**Comment by ihwf** [comment]
用 npm 装的...
