### ISSUE TITLE
通过npm方式引入，找不到uni-ui-scss/variables.scss文件

### ISSUE THREAD

**Issue by Laobalu** [dcloudio/uni-ui#431]
我通过uni-app的vue-cli模式**开发小程序插件**时，**npm安装**`"@dcloudio/uni-ui": "^1.4.9"`，找不到变量文件。

### 官方文档事例
需要在`uni.sass`文件引入变量文件`uni-ui-scss/variables.scss`。
```js
/* 需要放到文件最上面 */
@import '@/uni_modules/uni-ui-scss/variables.scss';
```
### 我的问题
我是用**npm安装**的`@dcloudio/uni-ui`，并没有uni_modules目录，并且在`node_modules/@dcloudio/uni-ui`目录下没有找到`variables.scss`这个变量文件，以下附上目录截图。请问我该如何引入？
<img width="472" alt="截屏2021-12-29 下午12 23 08" src="https://user-images.githubusercontent.com/20024124/147627295-3942d782-2878-4b04-89b4-171a656d2352.png">

**Comment by mehaotian** [comment]
替换为 @import '@dcloudio/uni-ui/uni-ui-scss/variables.scss';

**Comment by Laobalu** [comment]
> 大佬你看我截的图，红框里装的依赖都**没有这个文件**，不可能导入的了啊

**Comment by Laobalu** [comment]
> 替换为 @import '@dcloudio/uni-ui/uni-ui-scss/variables.scss';

大佬你看我截的图，红框里装的依赖都**没有这个文件**，不可能导入的了啊

**Comment by mehaotian** [comment]
> > 替换为 @import '@dcloudio/uni-ui/uni-ui-scss/variables.scss';
> 
> 大佬你看我截的图，红框里装的依赖都**没有这个文件**，不可能导入的了啊

代码修改提交了，但是 npm 还没发布最新的呢 ，稍后发布一下

**Comment by mehaotian** [comment]
你把 lib 展开看一下

**Comment by Laobalu** [comment]
> 你把 lib 展开看一下

找到了，感谢大佬`@dcloudio/uni-ui/lib/uni-scss/variables.scss`

**Comment by guda-art** [comment]
good, 建议官网更新一下
