### ISSUE TITLE
关于uni-collapse-item中的uni-grid大小问题

### ISSUE THREAD

**Issue by moxisuki** [dcloudio/uni-ui#434]
大佬们我问下
我在uni-collapse-item里面放uni-grid
为什么在QQ小程序展开大小就有问题
H5
![R`I4VPYLQBKCIQ BX@6@X{Y](https://user-images.githubusercontent.com/59305689/147847889-ec854899-5db8-4f61-b7af-3ed53ce25f05.png)

QQ
![P6ZP5393T4T_VC81 6E N1H](https://user-images.githubusercontent.com/59305689/147847893-70eceede-2469-4b04-9ba2-a1f4005b5f6c.png)

code
![image](https://user-images.githubusercontent.com/59305689/147847899-865ed93d-e9d2-4502-882a-0376995c9151.png)

**Comment by mehaotian** [comment]
不能这么使用 ，因为在折叠面板中，是通过 v-if 显示隐藏的，但是 uni-grid 会计算元素宽高 ，所以有时候会获取不到 元素信息 ，导致 uni-grid 没有宽高 ，后续我看怎么优化一下
