### ISSUE TITLE
maskClick事件无效

### ISSUE THREAD

**Issue by MonGDCH** [dcloudio/uni-ui#454]
在微信小程序中使用 `uni-datetime-picker` 组件，type为date类型， maskClick事件无效

```vue
<uni-datetime-picker ref="dateSelect" type="date" @change="selectDate" @maskClick="closeDate">
    <text></text>
</uni-datetime-picker>
```

问题：
源代码 `uni-datetime-picker.vue` 组件中未监听 `calendar.vue` 组件上报的 `close` 事件

**Comment by simple-ice** [comment]
相同问题

**Comment by codexu** [comment]
uni-datetime-picker@2.2.7 已修复
