### ISSUE TITLE
uni-popup-dialog 组件 input 进入页面时自动弹出键盘

### ISSUE THREAD

**Issue by xluoyu** [dcloudio/uni-ui#457]
使用ios真机测试时复现的问题

官方示例中也有此问题

**Comment by mehaotian** [comment]
确实会这样 ，打开后会自动获取焦点

**Comment by rathubby** [comment]
我去年就遇到这个问题，后来为了避开它，自己写input，在 mounted 调用 setTimeout 设置 focus 为true。
现在vue3中，必须要使用<uni-pop-dialog> 才不报错，结果又遇到这个问题了。
![苹果真机popup_focus问题](https://user-images.githubusercontent.com/5339767/169438268-1414180c-5c0c-48e4-af2a-dc02617f70bd.png)

**Comment by Ping-Gao** [comment]
vue3 暴力解决方案:

1. 组件上加个v-if
```
v-if="ifRenderDialog"
```
2. 声明所需变量
```
const ifRenderDialog = ref<boolean>(false);
const vm = getCurrentInstance();
```
3. 之后需要打开popup使用的时候再让他渲染到dom里如下
```
ifRenderDialog.value = true;
await nextTick();
// @ts-ignore
vm?.refs.inputDialog.open();
```

**Comment by 18148764734** [comment]
感谢反馈，现已添加focus属性，请到插件市场更新，用户可自行控制打开弹窗时是否自动聚焦

**Comment by wochalei** [comment]
@18148764734 
![1](https://github.com/dcloudio/uni-ui/assets/78481132/c1519a02-960e-4596-a945-495b3c64f187)
![2](https://github.com/dcloudio/uni-ui/assets/78481132/28a575b0-bb17-42bb-9a7e-66235f5e21ef)
苹果手机，设置focus为true，手机整机测试还是显示键盘弹框，打印发现会执行两遍，建议默认设置为false
