### ISSUE TITLE
微信开发者工具报的警告

### ISSUE THREAD

**Issue by llk2yq** [dcloudio/uni-ui#464]
![image](https://user-images.githubusercontent.com/22813922/156884506-5ea266cf-13f4-473f-9f9c-8a77ed504dcf.png)

![image](https://user-images.githubusercontent.com/22813922/156884572-e2904cd8-8886-4703-9d06-51b9a28fd7f4.png)

vue3，小程序平台。

**Comment by mehaotian** [comment]
可以不用理会 ，微信小程序插槽的警告 ，不影响功能使用，后续框架会修复

**Comment by llk2yq** [comment]
> 可以不用理会 ，微信小程序插槽的警告 ，不影响功能使用，后续框架会修复

了解。
