### ISSUE TITLE
uni-search-bar不能很方便地修改placeholder和输入文字的颜色（设置颜色无效）

### ISSUE THREAD

**Issue by chenshu-97** [dcloudio/uni-ui#475]
<uni-search-bar class="search-input" bgColor="rgba(0, 0, 0, 0.15)" :radius="39" style="color: #FFFFFF"
			@confirm="search" :focus="true" v-model="searchValue" cancelButton="false" placeholder="搜索试试">
			</uni-search-bar>

**Comment by 18148764734** [comment]
感谢反馈，现版本已添加，请到插件市场更新。
