### ISSUE TITLE
使用vite+vue3  调用uni-section时报错

### ISSUE THREAD

**Issue by xkkkA** [dcloudio/uni-ui#477]
[vite]: Rollup failed to resolve import "@dcloudio/uni-ui/lib/uni-section/uni-section.vue" from 
"src/pages/device/Index.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

**Comment by izjing** [comment]
我也是同样的问题，没人解决吗？

**Comment by mehaotian** [comment]
这是怎么使用报错的 ？ uni-ui 并没有发布  uni-section 组件，这个组件是给示例使用的本地组件，这个路径肯定是找不到的
