### ISSUE TITLE
组件的uni-list文件夹里面为什么有uni-list - 副本.vue和uni-list.vue两个文件，name都是'uniList'

### ISSUE THREAD

**Issue by rzshuo** [dcloudio/uni-ui#479]
组件的uni-list文件夹里面为什么有uni-list - 副本.vue和uni-list.vue两个文件，name都是'uniList'

**Comment by rzshuo** [comment]
第一个原因找到了，你们的文档有问题 文档是uni-list设置，实际是uni-list-item

**Comment by mehaotian** [comment]
多余文件已经删除 ，不同组件的 border 功能不同
