### ISSUE TITLE
uni-easyinput的clearable显示策略

### ISSUE THREAD

**Issue by aihanjiao** [dcloudio/uni-ui#482]
如果uni-easyinput绑定的v-model值为null，也会显示clearable。不应该只有 val !== ''的情况才被显示
<img width="192" alt="1649192447(1)" src="https://user-images.githubusercontent.com/59612542/161848329-97a250e5-0897-4c49-9607-53da043559c8.png">
当前判断是否显示clearable的逻辑为clearable && (val !== '') && !disabled
<img width="484" alt="1649192276(1)" src="https://user-images.githubusercontent.com/59612542/161847864-392fc096-b16c-4ae3-88de-18910c6ce547.png">
应该改为clearable && val && !disabled更合理
<img width="429" alt="1649192342(1)" src="https://user-images.githubusercontent.com/59612542/161848046-9c5f15c1-2870-4404-b931-e9bb0c42320f.png">
需要的话我可以提个pr

**Comment by rzshuo** [comment]
也发现上来就显示删除图标

**Comment by mehaotian** [comment]
确实是有问题 ，可以提交pr

**Comment by aihanjiao** [comment]
> 确实是有问题 ，可以提交pr

已提交

**Comment by aihanjiao** [comment]
并没有解决问题，这样改很显然没有考虑到undefined的情况@mehaotian

**Comment by rzshuo** [comment]
H5端还是会显示删除按钮

**Comment by mehaotian** [comment]
已优化
