### ISSUE TITLE
uni-nav-bar设置statusBar问题

### ISSUE THREAD

**Issue by jonny-xhl** [dcloudio/uni-ui#483]
## 描述

设置uni-nav-bar的statusBar以及backgroundColor属性后状态栏工具看不到内容。

**示例：**
```html
<uni-nav-bar fixed statusBar left-icon="left" leftText="返回" title="测试" backgroundColor="#FFFFFF" color="#333333">
</uni-nav-bar>
```
**效果：**

![b3aac047a0536ac807f2c49dd4a5272](https://user-images.githubusercontent.com/29520329/162116637-f31b5b06-4a3b-44ca-a759-547742b1f735.jpg)

**Comment by mehaotian** [comment]
可以在 pages.json 里对应页面配置成 深色状态栏，只所以看不到是因为 ，现在状态栏颜色是白色
