### ISSUE TITLE
uni-easyinput 数字0会被无视掉

### ISSUE THREAD

**Issue by LinHuijuan** [dcloudio/uni-ui#490]
改成这样就好
    if (this.value == undefined) {
      this.val = this.modelValue;
    }
    if (this.modelValue == undefined) {
      this.val = this.value;
    }
<img width="305" alt="image" src="https://user-images.githubusercontent.com/36183982/163315648-5edd5700-b4d1-4c2b-9e27-e77b7a7111e5.png">

**Comment by juukee** [comment]
0 本身就代表没有，所以默认是不显示的

**Comment by mehaotian** [comment]
npm 1.4.14 已经修复这个问题 ，或者插件市场下载最新插件
