### ISSUE TITLE
vite下uni-file-picker未找到

### ISSUE THREAD

**Issue by XFJGitHub** [dcloudio/uni-ui#493]
官网只有vue.config.js的配置，vite的时候怎么使用呢？现在好多uni-ui都不能使用
Component is not found in path "node-modules/@dcloudio/uni-ui/lib/uni-file-picker/uni-file-picker"
easyCom已配

**Comment by mehaotian** [comment]
看一下你的 easycom 是怎么配置的

**Comment by Ltzero** [comment]
同样是vite项目，报Component is not found in path "node-modules/@dcloudio/uni-ui/lib/uni-calendar/uni-calendar，
easyCom已配，检查了一下发现路径下面是有这个文件的
"easycom": {
    "autoscan": true,
    "custom": {
      "^uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue",
      "^uni-calendar": "@dcloudio/uni-ui/lib/uni-calendarddd/uni-calendar.vue"
    }
 }
 单独设置也不行

**Comment by koi646** [comment]
这个问题解决了吗

**Comment by 18148764734** [comment]
现版本暂未复现该问题，猜测该BUG已修改，此ISSUE暂时关闭
