### ISSUE TITLE
构建无解

### ISSUE THREAD

**Issue by Suminger** [dcloudio/uni-ui#496]
![image](https://user-images.githubusercontent.com/78029640/165063018-a85b8a90-705f-4956-8369-c7d7e5316f4e.png)
源码需要怎么构建呢

**Comment by Suminger** [comment]
请问一下如何构建成npm 包下载的形式

**Comment by mehaotian** [comment]
在 package 下 修改一下版本号在构建 ，相同版本不会构建成功
