### ISSUE TITLE
uni-swipe-action在nvue下报错vue3

### ISSUE THREAD

**Issue by haliuhei** [dcloudio/uni-ui#497]
[https://ask.dcloud.net.cn/question/143665](https://ask.dcloud.net.cn/question/143665)
社区已发帖但是沉底了。已提供复现demo.
![pic](https://user-images.githubusercontent.com/57513459/165086400-8b2ae026-66f3-49be-a7a3-fb87f8f720d6.png)

**Comment by mehaotian** [comment]
问题已修复 ，使用 HBuilderX 3.4.13+ 版本 ，下载并更新最新组件验证
