### ISSUE TITLE
uni-icon 多端显示问题

### ISSUE THREAD

**Issue by Ttou** [dcloudio/uni-ui#50]
图标组件在H5下不会显示，小程序下会显示
![深度截图_选择区域_20190902100534](https://user-images.githubusercontent.com/4298437/64086205-6b7b1780-cd69-11e9-9b4b-35ce5a278de4.png)
![深度截图_选择区域_20190902100502](https://user-images.githubusercontent.com/4298437/64086208-70d86200-cd69-11e9-9359-3e5028c70ba0.png)
![深度截图_选择区域_20190902100607](https://user-images.githubusercontent.com/4298437/64086213-746be900-cd69-11e9-8243-d476934d1006.png)

**Comment by wanganxp** [comment]
新版已经解决
