### ISSUE TITLE
Hbuilder导入插件之后uni-section不存在【紧急‼️】

### ISSUE THREAD

**Issue by lkzwc** [dcloudio/uni-ui#500]
![image](https://user-images.githubusercontent.com/84896877/165878436-7e0642b8-6e0b-42a8-8fbc-862a14fd1adb.png)

**Comment by walkerco** [comment]
你先回退版本使用v1.3.6应该没问题

**Comment by lkzwc** [comment]
没人吗？:rocket

**Comment by mehaotian** [comment]
什么地方用到 Section 了？ 这是一个未发布组件，只在 示例中使用 ，可以下载组件示例查看
