### ISSUE TITLE
uni-forms-item.vue unInit方法不应该删除数据

### ISSUE THREAD

**Issue by wangnaihe** [dcloudio/uni-ui#501]
![image](https://user-images.githubusercontent.com/13247600/165888190-42e82fd9-075e-459d-ac98-519e15976c1c.png)
这里删除了form的数据，实际上不应该删除

**Comment by mehaotian** [comment]
影响原始数据了 ？

**Comment by wangnaihe** [comment]
> 
![image](https://user-images.githubusercontent.com/13247600/167080323-7fdc15c9-a4b3-4f52-a155-c131f5e991a8.png)

![image](https://user-images.githubusercontent.com/13247600/167080275-be20d7e2-a20a-4193-926e-5860d1ea3440.png)
是的，formData最终会引用modelValue

**Comment by mehaotian** [comment]
收到，稍后更新组件
