### ISSUE TITLE
uni-transition组件里写uni-data-picker，uni-data-picker的底部弹框会从uni-transition容器弹出，不会从界面底部弹出！

### ISSUE THREAD

**Issue by yuxiaobo123123** [dcloudio/uni-ui#502]
uni-transition组件里写uni-data-picker，uni-data-picker的底部弹框会从uni-transition容器弹出，不会从界面底部弹出
![现象](https://user-images.githubusercontent.com/63474746/166084150-f71be518-43c2-40d6-814b-348c2ca0b488.png)
排查出原因是 uni-transition容器style里的transform样式影响了picker里的fixed定位，
![样式](https://user-images.githubusercontent.com/63474746/166084220-2828a380-3ec9-4157-b589-a76070a1a99d.png)
在源码里open方法里添加
setTimeout(() => {
	this.transform = 'none !important'
}, this.durationTime);
结束过度动画后复位样式，
![解决](https://user-images.githubusercontent.com/63474746/166084265-a80c7219-1736-40da-a8ba-d5ca7488e2c7.png)

测试h5，和小程序可以解决该问题

**Comment by mehaotian** [comment]
不建议这么使用 ，因为 uni-data-picker 有自己的弹出逻辑 ，不适合在方面放这个动画组件
