### ISSUE TITLE
 uni-ui更新日志太混乱，建议统一标准

### ISSUE THREAD

**Issue by Baiyuetribe** [dcloudio/uni-ui#504]
建议改成全球通用标准
- 破坏
  - 描述破坏性或重大更新
- 新增
  - 描述新增组件或内容
- 优化
  - 已有内容优化
- 修复
  - 修复内容
  
相关案例：
![image](https://user-images.githubusercontent.com/43716063/166774716-7eab9332-f33b-46c6-84f6-b8fe03af5eef.png)

https://www.naiveui.com/zh-CN/os-theme/docs/changelog

**Comment by mehaotian** [comment]
具体指的是什么地方的日志 ？github ?还是插件市场？ https://ext.dcloud.net.cn/plugin?id=55&update_log

**Comment by Baiyuetribe** [comment]
> 具体指的是什么地方的日志 ？github ?还是插件市场？ https://ext.dcloud.net.cn/plugin?id=55&update_log

对的，就你给的这个链接，混乱不堪

**Comment by mehaotian** [comment]
> > 具体指的是什么地方的日志 ？github ?还是插件市场？ https://ext.dcloud.net.cn/plugin?id=55&update_log
> 
> 对的，就你给的这个链接，混乱不堪

收到，后续会逐渐优化这个问题
