### ISSUE TITLE
uni-number-box的bug

### ISSUE THREAD

**Issue by zhengjf1988** [dcloudio/uni-ui#505]
在电脑上微信小程序打开可以输入字母，然后就变成NaN
![image](https://user-images.githubusercontent.com/16054422/167144848-740d3c2d-8e0f-4c4e-8038-7edaaaa6f794.png)

在手机上打开微信小程序，输入数据的时候，uni-number-box的样式、位置发生变化，
![image](https://user-images.githubusercontent.com/16054422/167145673-5866e5fa-b18d-4e8d-b75c-75c7e7ac5825.png)
![image](https://user-images.githubusercontent.com/16054422/167145734-3b166436-dd86-4b05-b1a0-dafc3182ab2d.png)

**Comment by mehaotian** [comment]
1. 目前还未兼容pc 小程序，之后会兼容
2. 需要提供一个简单的demo ,暂时还未复现

**Comment by codexu** [comment]
长时间未响应，问题暂时关闭；
若后续依然有问题，可reopen这个issue。
