### ISSUE TITLE
uni-th 打包非H5平台时会将filter-dropdown打包进来，filter-dropdown为无关依赖

### ISSUE THREAD

**Issue by theDogIsMyself** [dcloudio/uni-ui#508]

**Comment by theDogIsMyself** [comment]
解决方案：
![69601652263524_ pic](https://user-images.githubusercontent.com/30501861/167825219-a2c75bad-33ac-4173-8b3f-07afe69b3029.jpg)
![69611652263532_ pic](https://user-images.githubusercontent.com/30501861/167825227-8af47ed3-c068-4b76-ac93-1d983dbb288e.jpg)

**Comment by theDogIsMyself** [comment]
@dcloudio/uni-ui/lib/uni-th/uni-th.vue

**Comment by theDogIsMyself** [comment]
代码位置

**Comment by theDogIsMyself** [comment]
代码位置：@dcloudio/uni-ui/lib/uni-th/uni-th.vue

**Comment by theDogIsMyself** [comment]
修改前微信小程序问题截图：
<img width="563" alt="image" src="https://user-images.githubusercontent.com/30501861/167828011-b49245cb-397e-442d-83c7-8769a357ec65.png">

**Comment by mehaotian** [comment]
dropdown 是
