### ISSUE TITLE
[Vue warn]: Error in v-on handler: "ReferenceError: isPC is not defined"    真机调试 swipe action警告

### ISSUE THREAD

**Issue by w1o9960720** [dcloudio/uni-ui#509]
ReferenceError: isPC is not defined
 [Vue warn]: Error in v-on handler: "ReferenceError: isPC is not defined"
 found in
 <UniSwipeActionItem> at node_modules/@dcloudio/uni-ui/lib/uni-swipe-action-item/uni-swipe-action-item.vue:1
<UniSwipeAction> at node_modules/@dcloudio/uni-ui/lib/uni-swipe-action/uni-swipe-action.vue:1

**Comment by w1o9960720** [comment]
mpwxs.js // #ifdef H5
import {
	isPC
} from "./isPC"
// #endif
// #ifdef APP-VUE|| MP-WEIXIN || H5

只在 h5引入    真机 报错 isPC is  undefined  用ispc 这个函数去判断时 应该只在h5下才执行判断  还有onClickForPC函数里的$emit可以不用写了  我注释掉 试了h5 真机都能能正常运行  不会执行两次

**Comment by w1o9960720** [comment]
mpwxs.js文件 

// #ifdef H5
import {
	isPC
} from "./isPC"
// #endif
// #ifdef APP-VUE|| MP-WEIXIN || H5

只在h5引入 下面的方法里 isPC()应该在h5下调用  真机环境就没有引入isPC     不知道为啥   点击right-option里的按钮 会触发两次 一次是appTouchStart函数 一次是onClickForPC  在真机 h5 这两个函数都会触发  所以就触发了两次

**Comment by mehaotian** [comment]
已修复
