### ISSUE TITLE
Bug: uni-popup 没导入uni-transition，导致未配置 easycom，在 script 中局部注册组件不可用

### ISSUE THREAD

**Issue by xiaoxiangmoe** [dcloudio/uni-ui#513]
Bug: uni-popup 没导入uni-transition，导致未配置 easycom，在 script 中局部注册组件不可用

https://github.com/dcloudio/uni-ui/blob/d7eaccbbb18c18e08e59a889e4fae627e5ff6089/uni_modules/uni-popup/components/uni-popup/uni-popup.vue#L4

https://github.com/dcloudio/uni-ui/blob/d7eaccbbb18c18e08e59a889e4fae627e5ff6089/uni_modules/uni-popup/components/uni-popup/uni-popup.vue#L49-L53

---

在理想情况下，如果用户没有配置 easycom，用户应该可以局部注册组件使用。

**Comment by mehaotian** [comment]
使用 easycom , 目前设计有缺陷 ，后续后优化。
