### ISSUE TITLE
uni-data-select 下拉框选择器 整体禁用&单个选型禁用

### ISSUE THREAD

**Issue by duduodudu** [dcloudio/uni-ui#514]
uni-data-select 下拉框选择器
[文档](https://uniapp.dcloud.io/component/uniui/uni-data-select.html#api )中`disable | 是否禁用`，但是实际上没有效果。
[搜索源码对应文件](https://github.com/dcloudio/uni-ui/blob/master/uni_modules/uni-data-select/components/uni-data-select/uni-data-select.vue) 没有disable，虽然可以自动更改的方式。
1. 建议加上disable 属性，对uni-data-select 设置是否禁用。
2. 建议localdata ，对options进行禁用。
谢谢

**Comment by ClearNull2000** [comment]
已修复，请耐心等待下一个版本更新！
