### ISSUE TITLE
`data-picker-view`在微信开发者工具中报的警告

### ISSUE THREAD

**Issue by llk2yq** [dcloudio/uni-ui#516]
`v-for`没有加`key`

**Comment by ClearNull2000** [comment]
在v-for属性后面加上:key="数据项的唯一标识"

**Comment by llk2yq** [comment]
@ClearNull2000 有没有一种可能，这是一个`uni-ui`的组件？

**Comment by ClearNull2000** [comment]
一样的啊，这是因为你使用v-for必须要绑定key，它会提升diff效率！！！

**Comment by llk2yq** [comment]
有没有一种可能，我说的是内部代码？
`data-picker`引用了`data-picker-view`，`data-picker-view`内部的`v-for`没有加`key`。

**Comment by ClearNull2000** [comment]
已优化

**Comment by llk2yq** [comment]
👍，建议检查一下其它组件是否也有类似报警告的。

**Comment by ClearNull2000** [comment]
👌

**Comment by songpeng0501** [comment]
哪个版本解决的
