### ISSUE TITLE
uni-file-picker 不能设置仅拍照上传

### ISSUE THREAD

**Issue by rathubby** [dcloudio/uni-ui#524]
我使用本地图片上传，没有使用 uniCloud 图片上传， 图片上传会弹出相册或者拍照，都是工作的。但是现在需求是仅允许拍照上传图片，看了下 uni.chooseImage 中开放了参数 sourceType，可以设定 相册或者拍照。

但是在现有的 uni-file-picker中，发现无法定制参数 sourceType, 主要逻辑落在文件[uni-file-picker.vue](https://github.com/dcloudio/uni-ui/blob/35ffa5d3f48de3a9f632dfe75354de743632fe3f/uni_modules/uni-file-picker/components/uni-file-picker/uni-file-picker.vue)第341行函数 chooseFiles 中，非常希望能够补上这个功能，方便外部设定参数 sourceType,

跪谢!

**Comment by mehaotian** [comment]
收到
