### ISSUE TITLE
uni-data-select 下拉框选择器会出现蓝色阴影。？

### ISSUE THREAD

**Issue by lphwxl** [dcloudio/uni-ui#526]
![image](https://user-images.githubusercontent.com/23658463/173182439-d4449222-f3d0-4783-bb6f-f7e450fb0420.png)

**Comment by codexu** [comment]
这个蓝色阴影应该是你的开发者工具元素选择器卡住了，跟组件无关

**Comment by codexu** [comment]
此 bug 已修复
