### ISSUE TITLE
uni-data-checkbox 样式在nvue页面失效

### ISSUE THREAD

**Issue by openpython** [dcloudio/uni-ui#529]
正常运行的项目，HBuilderX升级到最新版后，nvue页面中使用 uni-data-checkbox 样式都失效了，测试发现 vue页面中显示正常。

**Comment by codexu** [comment]
未测试出此 bug，请提供详细信息和 demo

**Comment by codexu** [comment]
长时间未响应，问题暂时关闭；
若后续依然有问题，可reopen这个issue。
