### ISSUE TITLE
uni-tag inverted 在安卓app中不显示边框

### ISSUE THREAD

**Issue by rathubby** [dcloudio/uni-ui#532]
在离线打包的安卓app测试中发现，版本为 3.0.0-alpha-3041520220609002， 原因似乎是计算得到的边框过窄，
    border-width: 0.03125rem;
改成1px恢复正常。

补丁如下
.uni-tag {
  border-width: 1px!important;
}

**Comment by 18148764734** [comment]
感谢反馈，现已修复，下个版本提交时会带上此次更新
