### ISSUE TITLE
【version:1.4.16】vue3 字节小程序中uni-datetime-picker报TypeError: at setTimeout callback Cannot read property 'setDefaultMultiple' of undefined

### ISSUE THREAD

**Issue by amihhs** [dcloudio/uni-ui#535]
vue3 字节小程序中uni-datetime-picker报TypeError: at setTimeout callback Cannot read property 'setDefaultMultiple' of undefined错误
，无法正常选择。
点击对应日期后，选中样式没有跟着变化，但点击确认后，能选择成功

插件市场示例项目能正常复现

**Comment by zhenyuWang** [comment]
测试 vue2 字节小程序复现该问题，2.2.16 已修复
