### ISSUE TITLE
uni-nav-bar组件自定义插槽内容无效

### ISSUE THREAD

**Issue by yinbug** [dcloudio/uni-ui#539]
在vue3下 uni-nav-bar组件自定义插槽内容无效，官方示例中也是无效的。

**官方示例vue3**
![image](https://user-images.githubusercontent.com/37343304/176570770-8f420733-0695-4b52-9c44-6523c5fe6ffc.png)

**官方示例vue2**
![image](https://user-images.githubusercontent.com/37343304/176570820-0e5c8e56-f213-441a-9a69-efc3a117dd42.png)

**Comment by mehaotian** [comment]
已更新插件示例
