### ISSUE TITLE
bug：uni-data-checkbox

### ISSUE THREAD

**Issue by huangzhonghuai** [dcloudio/uni-ui#544]
https://github.com/dcloudio/uni-ui/blob/8712be7bd6f37ecd73933108e618060c6ef80cfc/uni_modules/uni-data-checkbox/components/uni-data-checkbox/uni-data-checkbox.vue#L70

**Comment by mehaotian** [comment]
什么问题？

**Comment by zhaoteee** [comment]
这个mixins是从哪里引入的 会报reading 'length'错误 移除这一行就可以了
![image](https://user-images.githubusercontent.com/20012605/184268616-269f681b-38a4-4bd0-87d4-ece57bbfc4fc.png)

**Comment by codexu** [comment]
3.5.5+ 已修复
