### ISSUE TITLE
npm  的方式安装，easycom 导入的方式存在问题

### ISSUE THREAD

**Issue by chuyun** [dcloudio/uni-ui#546]
![image](https://user-images.githubusercontent.com/19328403/177485461-f9a4c207-7ad4-414a-8f62-8258c6845c5c.png)

图示 lib 下不存在组件了，使用新的方式也存在特殊情况
"^uni-(.*)": "@dcloudio/uni-ui/uni_modules/uni-$1/components/uni-$1/uni-$1.vue",
<img width="292" alt="image" src="https://user-images.githubusercontent.com/19328403/177485696-ac44ac5f-626c-4f14-8ea3-ddf91276563b.png">

**Comment by mehaotian** [comment]
更新 npm 1.4.19 ，已经修复该问题
