### ISSUE TITLE
能否做到自动打包到对应的子包里面

### ISSUE THREAD

**Issue by myweb2019** [dcloudio/uni-ui#551]
编译的时候，能否将引入的组件，自动打包到对应的子包中，而不是全部打包到主包中，比如我主包未使用到该UI组件库，但是在子包中引用了，我想让他打包到当前子包内，如何做到

**Comment by mehaotian** [comment]
目前 uni-app 还不支持将组件打包到子呢，如果想打包到子包内，目前的做法只能是将组件动到子包目录下。
