### ISSUE TITLE
uni.scss中引入/uni-scss/variables.scss，改了主色不起作用的原因？

### ISSUE THREAD

**Issue by GreatBoy** [dcloudio/uni-ui#552]
/* 需要放到文件最上面 */
@import '@/uni_modules/uni-scss/variables.scss';

/*
 以下变量是默认值，如不需要修改可以不用给下面的变量重新赋值
 */
// 主色
$uni-primary: #78B664;
$uni-primary-disable:mix(#fff,$uni-primary,50%);
$uni-primary-light: mix(#fff,$uni-primary,80%);

**Comment by mehaotian** [comment]
在什么地方用的 ？

**Comment by codexu** [comment]
长时间未响应，问题暂时关闭；
若后续依然有问题，可reopen这个issue。
