### ISSUE TITLE
uni-fab 在折叠的时候点击右上角可以触发 trigger

### ISSUE THREAD

**Issue by FangHanZreo** [dcloudio/uni-ui#555]
点击图片指示位置可以复现bug。
![image](https://user-images.githubusercontent.com/16750422/179279211-eebff584-685f-4ded-90f8-06163749e6eb.png)

建议在 _onItemClick 添加判断
![image](https://user-images.githubusercontent.com/16750422/179280063-0353b2fd-2410-4646-8b7d-76f8ad7bd4ec.png)

**Comment by FangHanZreo** [comment]
#556 相关 pr

**Comment by mehaotian** [comment]
> #556 相关 pr

pr 已合并
