### ISSUE TITLE
pages.json里面的tabBar.list.iconfont在ios和微信小程序下面无法显示图标

### ISSUE THREAD

**Issue by jamestack** [dcloudio/uni-ui#562]
`"tabBar": {
		"color": "#7a7a7a",
		"backgroundColor": "#ffffff",
		"selectedColor": "#000000",
		"iconfontSrc": "/static/iconfont/iconfont.ttf",
		"list": [{
			"pagePath": "pages/index/index",
			"text": "Numers",
			"iconfont": {
				"text": "\ue729",
				"color": "#7a7a7a",
				"selectedColor": "#000000"
			}
		}, {
			"pagePath": "pages/country/country",
			"text": "Regions",
			"iconfont": {
				"text": "\ue72d",
				"color": "#7a7a7a",
				"selectedColor": "#000000"
			}
		},`
在使用vue3+nvme页面情况下，经测试：
在H5、Android下面正常显示，
在ios、微信小程序下面图标显示空白

**Comment by codexu** [comment]
这个问题不属于 uni-ui，请将此问题发布到 [uni-app issues](https://github.com/dcloudio/uni-app/issues)
