### ISSUE TITLE
uni-popup没有禁止滑动的选项

### ISSUE THREAD

**Issue by chenyexuan** [dcloudio/uni-ui#565]
如题所述，在可以下拉的列表中，没有传入相应的阻止滑动滚动事件

**Comment by codexu** [comment]
请尽量详细的说明此问题，提供可复现的简单 demo。
参考[禁止滚动穿透](https://uniapp.dcloud.net.cn/component/uniui/uni-popup.html#%E7%A6%81%E6%AD%A2%E6%BB%9A%E5%8A%A8%E7%A9%BF%E9%80%8F)，不知是否可以解决你的问题。

**Comment by codexu** [comment]
长时间未响应，问题暂时关闭；
若后续依然有问题，可reopen这个issue。
