### ISSUE TITLE
uni-forms-item required为fasle 依然显示红色*

### ISSUE THREAD

**Issue by zhangchenna** [dcloudio/uni-ui#570]
rule 配置了 required：true 触发红色*
uni-forms-item required为fasle 依然显示红色*
跟文档描述不符

是否必填，配置此参数不会显示输入框左边的必填星号，如需要，请配置uni-forms-item组件的的required为true

**Comment by zhangchenna** [comment]
<template #label/> 可以这样先跳过这个bug @mehaotian

**Comment by mehaotian** [comment]
已经优化
