### ISSUE TITLE
uni-data-checkbox报错

### ISSUE THREAD

**Issue by A-PASSER-BY** [dcloudio/uni-ui#575]
uni-ui使用的版本是："version": "1.4.20"
HBuilderX使用的是：3.5.3.20220729
  
使用uni-data-checkbox后，页面加载不出来，控制台报TypeError: Cannot read property 'length' of undefined，
vue.config.js中也输入了 transpileDependencies: ["@dcloudio/uni-ui"],
请问是怎么回事？求解答

**Comment by codexu** [comment]
请提供 bug 复现 demo，或者进入 [https://ext.dcloud.net.cn/plugin?id=3456](https://ext.dcloud.net.cn/plugin?id=3456) 使用 HBuilderX 导入示例项目，测试示例是否能复现此 bug

**Comment by seebin** [comment]
我也出现了。把cli版本将为2.0.1-34920220630001好使了，不能轻易升级呀

**Comment by zhetengbiji** [comment]
> 我也出现了。把cli版本降为2.0.1-34920220630001好使了，不能轻易升级呀

CLI创建的项目版本也可以更新到 2.0.1-35320220729002

**Comment by Wangyaqi** [comment]
HBuilderX创建的项目可以在HBuilderX安装目录执行`npx patch-hbuilderx-plugins`对此问题进行临时修复。注意此命令依赖于git

**Comment by KyleTang** [comment]
> 我也出现了。把cli版本降为2.0.1-34920220630001好使了，不能轻易升级呀

我安装HBuilderX.3.5.3.20220729遇到了一样的问题，下载了**旧版本HBuilderX.3.4.7.20220422就好使**了（uniapp-cli版本是3.4.7-2022042217，依赖的uni-cli-i18n是^2.0.1-34720220422001）。

从报错的地方溯源分析来看，应该是vue-cli-plugin-uni依赖的uni-cloud里的代码有问题，逻辑考虑不周期，出了异常以后，出问题应该只影响到局部，现在影响了全局。现在影响的结果就是HBuilderX.3.5.3.20220729的小程序预览全是空白，根本没法用。

uni-cloud包编译后的index.js文件格式化后的：
```JavaScript
(function() {
    {
        var e = m;         // debug断点 m是undefined
        var _t21 = {};
        if (1 === e.length)
            _t21 = e[0],
            sn = sn.init(_t21),
            sn.isDefault = !0;
        else {
            var _t22 = ["auth", "callFunction", "uploadFile", "deleteFile", "getTempFileURL", "downloadFile", "database", "getCurrentUSerInfo", "importObject"];
            var _n14;
            _n14 = e && e.length > 0 ? "应用有多个服务空间，请通过uniCloud.init方法指定要使用的服务空间" : y ? "应用未关联服务空间，请在uniCloud目录右键关联服务空间" : "uni-app cli项目内使用uniCloud需要使用HBuilderX的运行菜单运行项目，且需要在uniCloud目录关联服务空间",
            _t22.forEach(function(e) {
                sn[e] = function() {
                    return console.error(_n14),
                    Promise.reject(new M({
                        code: "SYS_ERR",
                        message: _n14
                    }));
                }
                ;
            });
        }
        Object.assign(sn, {
            get mixinDatacom() {
                return Zt(sn);
            }
        }),
        Wt(sn),
        sn.addInterceptor = v,
        sn.removeInterceptor = A,
        d && "web" === g && (window.uniCloud = sn);
    }
}
)();
```

我的HBuilderX.3.5.3.20220729使用“npx patch-hbuilderx-plugins”尝试修复，也是不好使的。

目前回退到 旧版本HBuilderX.3.4.7.20220422，等待官方修复uni-cloud工程的代码吧。

**Comment by Wangyaqi** [comment]
此问题已在HBuilderX 3.5.5版本修复

**Comment by KyleTang** [comment]
> 此问题已在HBuilderX 3.5.5版本修复

好的，此后在 [https://github.com/dcloudio/uni-app/issues/3809](https://github.com/dcloudio/uni-app/issues/3809) 反馈。
