### ISSUE TITLE
cli项目npm引入方式下，uni-icons图标在支付宝小程序中显示空白

### ISSUE THREAD

**Issue by huanghaodong** [dcloudio/uni-ui#576]
cli项目npm引入方式下，uni-icons图标在支付宝小程序中显示空白。cli项目才会出现上述问题，HBuilderX 项目正常！
版本@dcloudio/uni-ui": "^1.4.20

**Comment by mehaotian** [comment]
确认bug ，预计 HBuilderX3.6.4 alpha 修复

**Comment by 18148764734** [comment]
现版本已修复，此ISSUE暂时关闭
