### ISSUE TITLE
vite + vue3 项目编译到支付宝小程序 uni-data-picker 组件样式错乱

### ISSUE THREAD

**Issue by huhan-y** [dcloudio/uni-ui#578]
![image](https://user-images.githubusercontent.com/25815617/184815343-39d4e377-f307-4ac7-a4a2-7c8aae55f5de.png)

uni-data-picker 组件中引用了uni-data-pickerview 组件，这两个组件中类名重复导致页面样式错乱

![image](https://user-images.githubusercontent.com/25815617/184815616-6f7d5e8d-0060-4995-8192-6d5531a46e65.png)
![image](https://user-images.githubusercontent.com/25815617/184815677-26cffbc4-106c-4be4-b988-13015898dfc3.png)

在node_modules/@dcloudio/uni-ui/lib/uni-data-picker 和 uni-data-pickerview源码中style标签加上scoped属性可以临时解决问题：

![image](https://user-images.githubusercontent.com/25815617/184816033-eca69b4e-87aa-49e9-931f-2b64ae74c858.png)

**Comment by 18148764734** [comment]
感谢反馈。现修复的代码已提交。
HBuilderX 3.99.2023121601-alpha 已修复。
而通过cli命令行创建的项目后续会同步发布
后续会在 manifest.json 里添加 styleIsolation 配置，默认值为 apply-shared。
