### ISSUE TITLE
form表单校验规则 rules 里面判断是否必填 required：true 后 uni-forms-item 前面带有型号，文档不是说不影响界面显示？

### ISSUE THREAD

**Issue by zxc009521** [dcloudio/uni-ui#580]

**Comment by liwenfengg** [comment]
#570

**Comment by liwenfengg** [comment]
<uni-forms-item name="phone">
          <template #label>
            
            
            
            <view hidden />
          </template>
          <uni-easyinput
            v-model="form.phone" :input-border="false" :trim="true" type="number" prefix-icon="person"
            placeholder="请输入手机号码"
          />
        </uni-forms-item>

**Comment by mehaotian** [comment]
已优化
