### ISSUE TITLE
uni-data-picker如果子项和父项value一样就停不下来了

### ISSUE THREAD

**Issue by RoadsideParty** [dcloudio/uni-ui#583]
数据如下:
![image](https://user-images.githubusercontent.com/54093484/186371103-d951537a-81cb-4654-a21b-cfe77ea3b82a.png)
结果如下:
![image](https://user-images.githubusercontent.com/54093484/186371183-ecb65d69-3a03-462d-9b4f-17a95666fb42.png)

**Comment by codexu** [comment]
value 必须唯一，处理一下数据吧

**Comment by codexu** [comment]
长时间未响应，问题暂时关闭；
若后续依然有问题，可reopen这个issue。
