### ISSUE TITLE
uni-popup 编译到微信小程序中，slot 内组件不会重新构建。

### ISSUE THREAD

**Issue by xhlsrj** [dcloudio/uni-ui#584]
使用 vue 3 进行开发时发现：
```vue
<uni-popup ref="popup">
  <OneCustomComponent />
</uni-popup>
```
uni-popup 使用 v-if 条件控制。
在编译到 H5 环境下，uni-popup 打开时，slot 内部组件实例会被重新构建，进入对应的生命周期。如上的```OneCustomComponent```。
而在编译到微信小程序环境下，uni-popup 打开时，slot 内部组件实例不会被重新构建。
而是在 uni-popup 打开前就会被提前构建，而且实例不会随 uni-popup 关闭而销毁。通过调用```onMounted```输出日志即可验证。
这种差异需要额外处理来保持和编译到 H5 环境下的统一。
希望可以修正该问题。

**Comment by codexu** [comment]
这个问题与 vue3 和 uni-popup 组件没有关系，与各平台 v-if 的控制有关。
经过测试，仅微信小程序(wx-if )和 QQ小程序(qq-if) 会出现此问题，其他平台渲染方式都是一致的。
你可以直接在微信和QQ原生小程序开发中测试试一下复现此问题。

**Comment by xhlsrj** [comment]
> 这个问题与 vue3 和 uni-popup 组件没有关系，与各平台 v-if 的控制有关。 经过测试，仅微信小程序(wx-if )和 QQ小程序(qq-if) 会出现此问题，其他平台渲染方式都是一致的。 你可以直接在微信和QQ原生小程序开发中测试试一下复现此问题。

如果因为平台的原因，那么在同一平台下 v-if 的表现应该一致，但测试结果并非如此。以编译到微信小程序环境测试：

自定义组件 OneCustomComponent：
```vue
<script setup>
import { onMounted, onUnmounted } from 'vue';

onMounted(() => console.log('onMounted'));

onUnmounted(() => console.log('onUnmounted'));
</script>
```
测试对照用例：
一：自定义组件会销毁和重建，说明编译 v-if 指令结果符合预期。
```vue
<OneCustomComponent v-if="isShow" />
```

二：自定义组件只受 isShow 控制销毁和重建，说明 uni-popup 对组件实例没产生影响。
```vue
<uni-popup ref="popup">
  <OneCustomComponent v-if="isShow" />
</uni-popup>
```

三：自定义组件不会销毁和重建，说明 uni-popup 对组件实例没产生影响。
```vue
<uni-popup ref="popup">
  <OneCustomComponent />
</uni-popup>
```

可以看出独立使用 v-if 是符合预期的，而使用 uni-popup 并没出现和 v-if 一样的结果。所以有理由相信是 uni-popup 的关系导致内部的 v-if 没起到应有的作用。

**Comment by codexu** [comment]
单独使用 v-if 确实是符合预期的，你举的例子是没错的，但要测试的方式是外层是组件的方式，内部组件在 微信和QQ 上不会被重新构建。
举个例子：
```vue
<WrapperComponent>
   <ContentComponent />
</WrapperComponent>
```
WrapperComponent 通过 v-if 控制时，ContentComponent  mounted 在 微信和QQ 上只触发一次，并且不会销毁。
你可以自己测试一下，这个是微信平台和其他平台的差异。

**Comment by xhlsrj** [comment]
> 单独使用 v-if 确实是符合预期的，你举的例子是没错的，但要测试的方式是外层是组件的方式，内部组件在 微信和QQ 上不会被重新构建。 举个例子：
> 
> ```
> <WrapperComponent>
>    <ContentComponent />
> </WrapperComponent>
> ```
> 
> WrapperComponent 通过 v-if 控制时，ContentComponent mounted 在 微信和QQ 上只触发一次，并且不会销毁。 你可以自己测试一下，这个是微信平台和其他平台的差异。

确实如此，感谢说明。

附微信小程序原生测试代码：
index.wxml
```HTML
<button bindtap="show">show</button>
<button bindtap="hide">hide</button>
<wrapper-component class="wrapper">
  <content-component></content-component>
</wrapper-component>
```
index.js
```js
Page({
  show() {
    const wrapper = this.selectComponent('.wrapper')
    wrapper.setData({ isShow: true })
  },
  hide() {
    const wrapper = this.selectComponent('.wrapper')
    wrapper.setData({ isShow: false })
  }
})
```
WrapperComponent.wxml
```HTML
<view>
  <view wx:if="{{isShow}}">
    <slot></slot>
  </view>
</view>
```
WrapperComponent.js
```
Component({ data: { isShow: false } })
```
ContentComponent.js
```js
Component({
  lifetimes: {
    attached() { console.log('attached'); },
    detached() { console.log('detached'); }
  }
})
```
