### ISSUE TITLE
页面【uni_modules/uni-data-checkbox/components/uni-data-checkbox/uni-data-checkbox]错误: TypeError: Cannot read property 'length' of undefined 整个小程序直接全崩掉了，什么时候会解决这个啊

### ISSUE THREAD

**Issue by ScienceNoBorders** [dcloudio/uni-ui#586]
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/37797698/187339378-bd2e593d-e5df-4026-854a-c86cba4e4008.png">

**Comment by codexu** [comment]
升级 HBuilderX 3.5.5+ 问题已经修复
