### ISSUE TITLE
关于uni-popup/keypress文件的类型

### ISSUE THREAD

**Issue by OliverEChen** [dcloudio/uni-ui#587]
我在开发h5的过程中引入uni-pop插件，源文件是keypress.js。引入后项目无法运行;
分析后我修改为keypress.vue,项目正常运行。(vue3版本)

**Comment by OliverEChen** [comment]
![1661927288314](https://user-images.githubusercontent.com/67233559/187608956-544dd44c-8538-4575-acbf-8b2d294e6959.png)

**Comment by codexu** [comment]
如何引入的？发一下测试 demo

**Comment by OliverEChen** [comment]
HBuilder导入的

**Comment by OliverEChen** [comment]
> 如何引入的？发一下测试 demo

HBuilder 导入的

**Comment by codexu** [comment]
未能复现此 bug
测试一下 https://ext.dcloud.net.cn/plugin?name=uni-popup 使用 HBuilder 导入示例项目，可以改成 vue3。
如果还有问题，请将工程打包发到此处

**Comment by OliverEChen** [comment]
> 未能复现此 bug 测试一下 https://ext.dcloud.net.cn/plugin?name=uni-popup 使用 HBuilder 导入示例项目，可以改成 vue3。 如果还有问题，请将工程打包发到此处

[demo.zip](https://github.com/dcloudio/uni-ui/files/9459621/demo.zip)

**Comment by codexu** [comment]
测试了 demo ，没有出现这个报错，你升级HBuilder 到最新正式版试一下

**Comment by OliverEChen** [comment]
> 测试了 demo ，没有出现这个报错，你升级HBuilder 到最新正式版试一下

![1661933656670](https://user-images.githubusercontent.com/67233559/187628816-a4e7fdf8-9864-4bb0-bf85-ff5775365134.png)

**Comment by cucuzi** [comment]
我在开发的情况下打开页面也会报：
GET http://localhost:5173/h5/src/uni_modules/uni-drawer/components/uni-drawer/keypress.js net::ERR_BLOCKED_BY_CLIENT
GET http://localhost:5173/h5/src/uni_modules/uni-popup/components/uni-popup/keypress.js net::ERR_BLOCKED_BY_CLIENT
经排查是装了浏览器的广告过滤插件(uBlock)导致的，插件拦截了keypress.js这个名字的文件。加了自定义规则或者把插件关了就好了。
生产的话默认打包名字会变，所以不影响生产。
建议官方改下文件名称吧。
