### ISSUE TITLE
npm模式下uni-scss主题色修改不生效

### ISSUE THREAD

**Issue by dw08** [dcloudio/uni-ui#588]
## 问题描述
用npm安装uni-ui，想修改默认主题色，但是并不生效
## 版本
@1.4.20
## 环境
vue3微信小程序
## 代码
```
// uni.scss
@import '@dcloudio/uni-ui/lib/uni-scss/variables.scss';
$uni-primary:  #4cd964;
```
## 期望结果
打包出来的组件默认主题色为#4cd964

## 实际结果
打包出来的组件默认主题色为#2979FF"

**Comment by dw08** [comment]
生效了 只是部分组件不会读默认颜色！！！uni-steps

**Comment by WE5T3** [comment]
> 生效了 只是部分组件不会读默认颜色！！！uni-steps

请问下 最后怎么解决的 我的也用到了unisteps
