### ISSUE TITLE
uni-popup mask content 样式丢失

### ISSUE THREAD

**Issue by sirius-orion-black** [dcloudio/uni-ui#589]
![image](https://user-images.githubusercontent.com/109939267/188269385-d3da2266-bf9a-448a-8fd7-a531917aaf76.png)

project：ts+vite+uniapp
version"@dcloudio/uni-ui": "^1.4.20",
我想这个并不是uni-popup组件的问题

**Comment by codexu** [comment]
未能复现此问题，请问你是在什么环境下运行导致这个问题，查看一下 uni-transition 是否正确安装了。

**Comment by codexu** [comment]
长时间未响应，问题暂时关闭；
若后续依然有问题，可reopen这个issue。

**Comment by sirius-orion-black** [comment]
直接yarn add @dcloudio/uni-ui
原因 :styles="maskClass"  对象编译解析导致的
建议1 :styles="{width: autoWidth,height: autoHeight....}"
建议2 :class="className" 操纵类名来解决这个问题
我个人是用方法2解决的
