### ISSUE TITLE
uni-countdown 为什么使用 px 而不是 rpx

### ISSUE THREAD

**Issue by dannyZhou** [dcloudio/uni-ui#590]
https://github.com/dcloudio/uni-ui/blob/f3edda16907e2bf5d5f9eaec57637e9fd0c4eecb/uni_modules/uni-countdown/components/uni-countdown/uni-countdown.vue#L125

**Comment by codexu** [comment]
不单是 uni-countdown 使用 px，整个 uni-ui 也是主要使用 px。
这是因为开发组件库需要考虑的问题较多，例如 rpx 不支持动态横竖屏切换计算。
具体请详细阅读 [尺寸单位章节](https://uniapp.dcloud.net.cn/tutorial/syntax-css.html#%E5%B0%BA%E5%AF%B8%E5%8D%95%E4%BD%8D)
