### ISSUE TITLE
uni-data-checkbox报错

### ISSUE THREAD

**Issue by fsyadmin** [dcloudio/uni-ui#591]
![image](https://user-images.githubusercontent.com/104409210/188533193-3b82af83-4dca-469b-aa63-61a904369c0e.png)
![image](https://user-images.githubusercontent.com/104409210/188533170-fc15ba22-4932-42a2-84d7-d85fe1899f5c.png)

代码是官方的用例
<img width="904" alt="image" src="https://user-images.githubusercontent.com/104409210/188533364-1fa4b41c-6b45-420b-b915-bcc1bea957a0.png">

**Comment by codexu** [comment]
升级到 3.5.5+
