### ISSUE TITLE
uni-transition警告

### ISSUE THREAD

**Issue by chenyexuan** [dcloudio/uni-ui#593]
VM2883 WAService.js:2 [Component] slot "" is not found (for component "uni_modules/uni-transition/components/uni-transition/uni-transition")
虽然不会影响功能，但报错的时候看见这警告还挺下头，就加一行代码的事：`<view v-else style="display: none;"><slot /></view>`

**Comment by chenyexuan** [comment]
虽然不回影响功能，但报错的时候看见这警告还挺下头，就加一行代码的事：<view v-else style="display: none;"><slot /></view>

**Comment by codexu** [comment]
方便补充一个 demo 吗？我这边未发现这个警告

**Comment by chenyexuan** [comment]
> 方便补充一个 demo 吗？我这边未发现这个警告

`
			<uni-transition mode-class="slide-right" name="content" :styles="{position:'fixed',bottom:0,right:0,top:0,
			backgroundColor:'rgba(0,0,0,0.3)',display:'flex',flexDirection:'column'}" :duration="300"
				:show="showTrans" @click="() => {this.showTrans=!this.showTrans}">
				<view class="uni-popup__wrapper" v-if="showTrans">
					123
				</view>
			</uni-transition>
`
类似于这种，就是传给slot的值有可能会变成空值

**Comment by 18148764734** [comment]
还是未复现该问题，此ISSUE暂时关闭
