### ISSUE TITLE
表单校验规则必填显示星号且无法被隐藏

### ISSUE THREAD

**Issue by axolo** [dcloudio/uni-ui#595]
https://uniapp.dcloud.net.cn/component/uniui/uni-forms.html

表单校验规则：

required	Boolean	-	-	是否必填，配置此参数不会显示输入框左边的必填星号，如需要，请配置uni-forms-item组件的的required为true

恰恰相反，这个规则影响uni-forms-item而且无法被:required="false"覆盖

**Comment by codexu** [comment]
什么版本？请补充一个测试用例

**Comment by axolo** [comment]
npm上的版本还是2个月前的1.4.20：https://www.npmjs.com/package/@dcloudio/uni-ui

**Comment by haulong** [comment]
这个问题什么时候修复啊

**Comment by codexu** [comment]
> 这个问题什么时候修复啊

使用 npm 安装还是 uni-modules 安装的？

**Comment by haulong** [comment]
npm安装的

**Comment by liwenfengg** [comment]
需要官方更新一下 npm 版本
#598

**Comment by liwenfengg** [comment]
#570

**Comment by liwenfengg** [comment]
#580

**Comment by haulong** [comment]
> 需要官方更新一下 npm 版本 #598

1.4.21有修复这个问题了吗

**Comment by haulong** [comment]
> #580

看到了， 那我就等升级了 多谢了

**Comment by codexu** [comment]
npm [1.4.22](https://www.npmjs.com/package/@dcloudio/uni-ui/v/1.4.22) 已发布，请更新依赖。

**Comment by haulong** [comment]
> npm [1.4.22](https://www.npmjs.com/package/@dcloudio/uni-ui/v/1.4.22) 已发布，请更新依赖。

好的 多谢
