### ISSUE TITLE
麻烦 npm 版本更新一下谢谢 1.4.20 => 1.4.21

### ISSUE THREAD

**Issue by liwenfengg** [dcloudio/uni-ui#598]

**Comment by liwenfengg** [comment]
![image](https://user-images.githubusercontent.com/40257198/190964150-6667d83d-4fce-47e5-9b64-bf7cc2fab267.png)

**Comment by liwenfengg** [comment]
![image](https://user-images.githubusercontent.com/40257198/190964237-b7556a81-4979-4a94-a02f-e41c856bef6f.png)

**Comment by codexu** [comment]
npm [1.4.22](https://www.npmjs.com/package/@dcloudio/uni-ui/v/1.4.22) 已发布
