### ISSUE TITLE
feat: uni-data-picker非叶子节点响应选择事件

### ISSUE THREAD

**Issue by axolo** [dcloudio/uni-ui#603]
很多情况下多级联动并不会一定选择到叶子节点，往往在父节点或者需要数据（比如筛选）

需求uni-data-picker非叶子节点点击时也响应@change事件，或者另开一个事件响应选择事件

**Comment by wunaidouzi** [comment]
+1确实需要

**Comment by 18148764734** [comment]
现版本已添加，感谢反馈
