### ISSUE TITLE
uni-data-select 组件在窗口下方时无法显示选项列表

### ISSUE THREAD

**Issue by pangxieju** [dcloudio/uni-ui#606]
问题表述：
uni-data-select 组件在 PC 端使用的时候，组件在窗口左下方或右下方无法显示列表项。
查看了官方组件源码 ’.uni-select__selector‘ top 值目前是固定在下方显示。

期望结果：
使用的时候能够设置列表展示的位置或通过组件的位置来自动识别列表显示的位置。

**Comment by 18148764734** [comment]
感谢反馈，现已修复，下版本发布时会带上更新
