### ISSUE TITLE
代码赶快同步，h5字体图片不显示的问题赶快处理，uni-icons  uni-icon  命名问题

### ISSUE THREAD

**Issue by zhangyq233** [dcloudio/uni-ui#61]
代码赶快同步，h5字体图片不显示的问题赶快处理，uni-icons  uni-icon  命名问题

**Comment by Wangyaqi** [comment]
上周五已经修改，现在全部都叫uniicons了

**Comment by zhangyq233** [comment]
> 上周五已经修改，现在全部都叫uniicons了

但是npm版本没有更新   npm下载不到uni-icons

**Comment by Wangyaqi** [comment]
npm是周一上午更新的1.0.3版本

**Comment by zhangyq233** [comment]
> npm是周一上午更新的1.0.3版本

npm i    @dcloudio/uni-ui":   "version": "1.0.1"

**Comment by zhangyq233** [comment]
> npm是周一上午更新的1.0.3版本

可以了  安装了旧版的  谢谢了

**Comment by zhangyq233** [comment]
> npm是周一上午更新的1.0.3版本
> https://www.npmjs.com/package/@dcloudio/uni-ui

更到最新版本之后，启动就报错了 文件查找失败：'./index.wxs?vue&type=custom&index=0&blockType=script&issuerPath=F%3A%5Canjoy%5Cproject%5CuniAppBuyer%5Cnode_modules%5C%40dcloudio%5Cuni-ui%5Clib%5Cuni-swipe-action%5Cuni-swipe-action.vue&module=swipe&lang=wxs' at node_modules\@dcloudio\uni-ui\lib\uni-swipe-action\uni-swipe-action.vue:21
15:48:58.392 文件查找失败：'./mp' at node_modules\@dcloudio\uni-ui\lib\uni-swipe-action\uni-swipe-action.vue:33

**Comment by Wangyaqi** [comment]
马上修一下，提的时候处理用的脚本有点问题，感谢关注

**Comment by zhangyq233** [comment]
> 马上修一下，提的时候处理用的脚本有点问题，感谢关注

加油加油
