### ISSUE TITLE
 uni-icons 图标 H5正常显示, 微信小程序没有显示

### ISSUE THREAD

**Issue by joe123345** [dcloudio/uni-ui#615]
你好, 作者大大：
   uni-icons 图标 H5正常显示, 微信小程序没有显示

**Comment by thelostword** [comment]
![image](https://user-images.githubusercontent.com/41263837/211478493-4966a260-c36b-4957-9317-2549e6367e2e.png)
![image](https://user-images.githubusercontent.com/41263837/211478524-7ef6a708-bcde-4472-b7af-9744eb1de778.png)
uni-icons 无法显示，hbuilder下创建的 uni-ui 项目

**Comment by 18148764734** [comment]
此问题暂未复现，猜测现版本HBX已经修复该问题，此ISSUE暂时关闭

**Comment by fragrans-maotou** [comment]
同问，这个问题我也遇到了，是和那些配置有关，
目前：uni_modules里的组件，直接就用，不写引入组件，
结果：H5可以看到icons ，在小程序就不行

**Comment by thelostword** [comment]
> 同问，这个问题我也遇到了，是和那些配置有关？ 目前：uni_modules里的组件，直接就用，不写引入组件， 结果：H5可以看到icons ，在小程序就不行

重启可以解决90%的问题😂

**Comment by fragrans-maotou** [comment]
> > 同问，这个问题我也遇到了，是和那些配置有关？ 目前：uni_modules里的组件，直接就用，不写引入组件， 结果：H5可以看到icons ，在小程序就不行
> 
> 重启可以解决90%的问题😂

我找到了我这边是什么问题导致的了，
同事写H5使用uni-icons方式有问题

`<uni-icons class="uni-icons uniui-plusempty" color="#fff" size="24"></uni-icons>`
这个在H5下有展示而再微信小程序不会展示图片

<uni-icons type="plusempty" class="uni-icons" color="#fff" size="24"></uni-icons>
这个是官方案例上的，H5与小程序都可以展示

**Comment by HaiTangWeiYu** [comment]
起初H5、手机App都能展示，小程序不能展示。彻底关掉小程序，重启之后生效
