### ISSUE TITLE
请问vue3下的uni-ui样式怎么修改?

### ISSUE THREAD

**Issue by kangaroo711** [dcloudio/uni-ui#617]
全局修改影响太大, vue2我看网络方法是通过options的styleIsolation属性设为 "shared"解除uni-app样式隔离, vue3怎么做呢? 求指导感激不尽!

**Comment by 18148764734** [comment]
同时使用 <script setup> + <script>

**Comment by wlj0924** [comment]
Failed to set the 'body' property on 'Document': The 1st argument provided is either null, or an invalid HTMLElement object.(env: Windows,mp,1.06.2403122; lib: 3.3.4) 请问写两个script，报错怎么处理，ts语法下

**Comment by wlj0924** [comment]
Failed to set the 'body' property on 'Document': The 1st argument provided is either null, or an invalid HTMLElement object.(env: Windows,mp,1.06.2403122; lib: 3.3.4) 请问写两个script，报错怎么处理，ts语法下
