### ISSUE TITLE
uni-nav-bar  编译生成界面问题，默认多出/* #ifndef APP-NVUE *//* #endif */

### ISSUE THREAD

**Issue by fundodoo** [dcloudio/uni-ui#618]
/* #ifndef APP-NVUE *//* #endif */

**Comment by fundodoo** [comment]
![1665979381900](https://user-images.githubusercontent.com/14152350/196087081-d3e65901-6d62-4e6b-99d3-95afdf237e29.png)

**Comment by 18148764734** [comment]
nav-bar并没有该问题，请检查自身代码是否有误
