### ISSUE TITLE
npm 更新到最新版本  1.0.3之后 启动就报错了  怎么回事

### ISSUE THREAD

**Issue by zhangyq233** [dcloudio/uni-ui#62]
15:48:41.259  INFO  Starting development server...
15:48:58.391 文件查找失败：'./index.wxs?vue&type=custom&index=0&blockType=script&issuerPath=F%3A%5Canjoy%5Cproject%5CuniAppBuyer%5Cnode_modules%5C%40dcloudio%5Cuni-ui%5Clib%5Cuni-swipe-action%5Cuni-swipe-action.vue&module=swipe&lang=wxs' at node_modules\@dcloudio\uni-ui\lib\uni-swipe-action\uni-swipe-action.vue:21
15:48:58.392 文件查找失败：'./mp' at node_modules\@dcloudio\uni-ui\lib\uni-swipe-action\uni-swipe-action.vue:33

**Comment by Wangyaqi** [comment]
现在已经更新了1.0.4，这个问题已经修复了
