### ISSUE TITLE
uni-nav-bar组件问题

### ISSUE THREAD

**Issue by bokirs** [dcloudio/uni-ui#627]
### uni-ui库下的uni-nav-bar组件html注释使用了 /**/ 导致页面显示了注释内容

**Comment by hiktang** [comment]
找到 node_modules\@dcloudio\uni-ui\lib\uni-nav-bar\uni-nav-bar.vue 文件, 换成注释即可

**Comment by 18148764734** [comment]
现版本已修复，感谢反馈
