### ISSUE TITLE
uni-datetime-picker 不兼容nvue 使用了v-show

### ISSUE THREAD

**Issue by wangnaihe** [dcloudio/uni-ui#628]
![image](https://user-images.githubusercontent.com/13247600/198755266-d7d7f4be-73cd-4eb9-be1f-05b33b55da27.png)

**Comment by zhenyuWang** [comment]
平台兼容性中已注明，目前仅支持 app-vue https://ext.dcloud.net.cn/plugin?name=uni-datetime-picker
