### ISSUE TITLE
uni-data-checkbox 1.0.3版本 mode='list' 单选模式下 选中点无法显示

### ISSUE THREAD

**Issue by kouzha0** [dcloudio/uni-ui#629]
uni-data-checkbox 1.0.3版本 mode='list' 单选模式下 选中点无法显示

**Comment by FangwenMagician** [comment]
遇到了同样的问题。
uni-data-checkbox 组件在 mode='list' 时 ，多选模式下是正常的。单选模式下，选中点对选中操作没有反应，仅仅只有字体变蓝。
希望能尽快修复！！！
@mehaotian

**Comment by 18148764734** [comment]
感谢反馈，抱歉来晚了，问题已复现，现正修复，下版本更新时会带上

**Comment by 18148764734** [comment]
已修复，下版本更新时会带上，感谢反馈
