### ISSUE TITLE
A组件有slot B组件有slot 在微信小程序端会出现B组件的slot会分发到A组件的

### ISSUE THREAD

**Issue by zhangyq233** [dcloudio/uni-ui#63]
详细问题描述
[内容]

A组件有slot B组件有slot 在微信小程序端会出现B组件的slot会分发到A组件的slot.
通过查看微信小程序端的调试工具，source 发现了这个问题。提供了附件，麻烦处理一下

重现步骤
[步骤]

编译到微信小程序

[结果]

slot分发出错

IDE运行环境说明
HBuilderX 2.3.3.20190923

win10

uni-app运行环境说明
H5没问题，微信小程序有问题

HBuilderX创建

新的自定义组件模式

[附件](https://ask.dcloud.net.cn/file/download/file_name-dGVzdC56aXA=__url-Ly9pbWctY2RuLXFpbml1LmRjbG91ZC5uZXQuY24vdXBsb2Fkcy9xdWVzdGlvbnMvMjAxOTA5MjUvMGQ0NjFjMzVhOWVhMTI1NWMwZmU4YzFkNDU1NjAzODg=)

**Comment by Wangyaqi** [comment]
运行你的附件没发现你的问题，可以补充一下BUG相关的图片

**Comment by zhangyq233** [comment]
[图片](https://img-cdn-qiniu.dcloud.net.cn/uploads/questions/20190925/3f85e95d02eeac023d6362a6df0a7d0d.png)

**Comment by zhangyq233** [comment]
> 运行你的附件没发现你的问题，可以补充一下BUG相关的图片，另外uniapp的issue最好是到uniapp里面提

我补充了图片 麻烦看下。  问题是在于  子组件的slot 跟 父组件的slot平级了

**Comment by Wangyaqi** [comment]
> > 运行你的附件没发现你的问题，可以补充一下BUG相关的图片，另外uniapp的issue最好是到uniapp里面提
> 
> 我补充了图片 麻烦看下。 问题是在于 子组件的slot 跟 父组件的slot平级了

微信开发者工具就是这么显示的，不影响使用，你可以通过调试微信开发者工具查看真正的结构
![debug_wxdevtool](https://user-images.githubusercontent.com/12015319/65592030-538d6100-dfc0-11e9-98ef-8b60465c270c.png)

**Comment by zhangyq233** [comment]
> > > 运行你的附件没发现你的问题，可以补充一下BUG相关的图片，另外uniapp的issue最好是到uniapp里面提
> > 
> > 
> > 我补充了图片 麻烦看下。 问题是在于 子组件的slot 跟 父组件的slot平级了
> 
> 微信开发者工具就是这么显示的，不影响使用，你可以通过调试微信开发者工具查看真正的结构
> ![debug_wxdevtool](https://user-images.githubusercontent.com/12015319/65592030-538d6100-dfc0-11e9-98ef-8b60465c270c.png)

麻烦看一下我发的评论 又三张图片   您截的图  这是一个错误的效果

**Comment by zhangyq233** [comment]
> > > 运行你的附件没发现你的问题，可以补充一下BUG相关的图片，另外uniapp的issue最好是到uniapp里面提
> > 
> > 
> > 我补充了图片 麻烦看下。 问题是在于 子组件的slot 跟 父组件的slot平级了
> 
> 微信开发者工具就是这么显示的，不影响使用，你可以通过调试微信开发者工具查看真正的结构
> ![debug_wxdevtool](https://user-images.githubusercontent.com/12015319/65592030-538d6100-dfc0-11e9-98ef-8b60465c270c.png)

[这张才是正确的效果](https://img-cdn-qiniu.dcloud.net.cn/uploads/questions/20190925/550c2eeffb1d5c7c148c2de173d140b8.png)

**Comment by Wangyaqi** [comment]
> > > > 运行你的附件没发现你的问题，可以补充一下BUG相关的图片，另外uniapp的issue最好是到uniapp里面提
> > > 
> > > 
> > > 我补充了图片 麻烦看下。 问题是在于 子组件的slot 跟 父组件的slot平级了
> > 
> > 
> > 微信开发者工具就是这么显示的，不影响使用，你可以通过调试微信开发者工具查看真正的结构
> > ![debug_wxdevtool](https://user-images.githubusercontent.com/12015319/65592030-538d6100-dfc0-11e9-98ef-8b60465c270c.png)
> 
> 麻烦看一下我发的评论 又三张图片 您截的图 这是一个错误的效果

你要根据真正的结构去调整你的样式，现在的样式是不能达到你预期的效果的

**Comment by zhangyq233** [comment]
> > > > > 运行你的附件没发现你的问题，可以补充一下BUG相关的图片，另外uniapp的issue最好是到uniapp里面提
> > > > 
> > > > 
> > > > 我补充了图片 麻烦看下。 问题是在于 子组件的slot 跟 父组件的slot平级了
> > > 
> > > 
> > > 微信开发者工具就是这么显示的，不影响使用，你可以通过调试微信开发者工具查看真正的结构
> > > ![debug_wxdevtool](https://user-images.githubusercontent.com/12015319/65592030-538d6100-dfc0-11e9-98ef-8b60465c270c.png)
> > 
> > 
> > 麻烦看一下我发的评论 又三张图片 您截的图 这是一个错误的效果
> 
> 你要根据真正的结构去调整你的样式，现在的样式是不能达到你预期的效果的

不是样式的问题    在h5端可以正确效果   微信小程序端就不行了。   通过微信工具类查看结构发现是因为父子组件  slot 分发出了问题

**Comment by zhangyq233** [comment]
> > > > > 运行你的附件没发现你的问题，可以补充一下BUG相关的图片，另外uniapp的issue最好是到uniapp里面提
> > > > 
> > > > 
> > > > 我补充了图片 麻烦看下。 问题是在于 子组件的slot 跟 父组件的slot平级了
> > > 
> > > 
> > > 微信开发者工具就是这么显示的，不影响使用，你可以通过调试微信开发者工具查看真正的结构
> > > ![debug_wxdevtool](https://user-images.githubusercontent.com/12015319/65592030-538d6100-dfc0-11e9-98ef-8b60465c270c.png)
> > 
> > 
> > 麻烦看一下我发的评论 又三张图片 您截的图 这是一个错误的效果
> 
> 你要根据真正的结构去调整你的样式，现在的样式是不能达到你预期的效果的

![image](https://user-images.githubusercontent.com/28673757/65592630-8421ca80-dfc1-11e9-9852-9686e87ee9b5.png)

**Comment by zhangyq233** [comment]
> > > > > 运行你的附件没发现你的问题，可以补充一下BUG相关的图片，另外uniapp的issue最好是到uniapp里面提
> > > > 
> > > > 
> > > > 我补充了图片 麻烦看下。 问题是在于 子组件的slot 跟 父组件的slot平级了
> > > 
> > > 
> > > 微信开发者工具就是这么显示的，不影响使用，你可以通过调试微信开发者工具查看真正的结构
> > > ![debug_wxdevtool](https://user-images.githubusercontent.com/12015319/65592030-538d6100-dfc0-11e9-98ef-8b60465c270c.png)
> > 
> > 
> > 麻烦看一下我发的评论 又三张图片 您截的图 这是一个错误的效果
> 
> 你要根据真正的结构去调整你的样式，现在的样式是不能达到你预期的效果的

正确效果![image](https://user-images.githubusercontent.com/28673757/65592773-cfd47400-dfc1-11e9-9473-6a64098fdfd6.png)

**Comment by Wangyaqi** [comment]
我给你看的不是H5的结构，而是调试微信开发者工具看到的结构，是真实的结构，你在wxml这个标签看到的只是微信开发者工具让你看到的。运行到小程序之后会比多一层标签，让你的display:flex不能正常生效，你要根据真实结构调整样式

**Comment by zhangyq233** [comment]
> 我给你看的不是H5的结构，而是调试微信开发者工具看到的结构，是真实的结构，你在wxml这个标签看到的只是微信开发者工具让你看到的。运行到小程序之后会比H5多一层标签，让你设置的宽度不能正常生效，你要根据真实结构调整样式

感谢感谢 可以用了。不是bug。是我的写法问题，  发现不能采用百分比的方式，必须换算成对应的upx才可以实现多端都有效果
