### ISSUE TITLE
无法引入 @dcloudio/uni-ui

### ISSUE THREAD

**Issue by hesi726** [dcloudio/uni-ui#64]
## 详细问题描述

最新版本的 UNI-APP 项目
使用 CLI  创建 UNI-APP 项目，将 index 和 vue 文件分离，
分离后 ts 文件中引入 
import {uniBadge} from '@dcloudio/uni-ui' 会发生错误;

而在 2019-09-17 之前的版本中，则没有这个问题;

[内容]

## 重现步骤

[步骤]
1.  vue create -p dcloudio/uni-preset-vue my-project       

2. cd my-project

3. npm install @dcloudio/uni-ui node-sass  sass-loader   

4. 将 pages/index/index.vue 文件中 script 部分拆分到 index.ts 

index.vue 中 script 部分改为 
```javascript
<script lang="ts" src='./index.ts'></script>
```

index.ts 内容如下:
```javascript
import Vue from 'vue';
import {uniBadge} from '@dcloudio/uni-ui'; // 引入 uniBadge组件
// import uniBadge from '@dcloudio/uni-ui/lib/uni-badge/uni-badge.vue';  // 使用全路径方式引入可以正常工作;
export default Vue.extend({
	components: {uniBadge},
		data() {
			return {
				title: 'Hello'
			}
		},
		onLoad() {

		},
		methods: {

		}
	});
```

5. npm run serve

[结果]
安装 @dcloudio/uni-ui包、和相关依赖包
[期望]
正常编译（旧的版本，

[HBuilder 或 HBuilderX。如果你用其他工具开发uni-app，也需要在此说明]

[IDE版本号]  HBuilderX 2.3.3.20190923

**Comment by Ttou** [comment]
我这边发现按需导入组件不生效，需要一个个导入
```js
import uniGrid from '@dcloudio/uni-ui/lib/uni-grid/uni-grid.vue'
import uniGridItem from '@dcloudio/uni-ui/lib/uni-grid-item/uni-grid-item.vue'
import uniList from '@dcloudio/uni-ui/lib/uni-list/uni-list.vue'
import uniListItem from '@dcloudio/uni-ui/lib/uni-list-item/uni-list-item.vue'
```

**Comment by hesi726** [comment]
楼上的兄弟，估计你也是使用的 TypeScript, 下面这个是我自己写的 uni-ui 的导出文件，
你拿过去用吧。。
使用方法: 
import { uniGrid, uniGridItem, uniList, uniListItem } from '@/PublicUniTsLib/UniUi'; //ts文件的位置;

`/** uni-ui 的导出文件，莫名其妙的是 2019-09-23 的升级之后， 
 *  ts文件中，使用这个形式的 import {uniBadge} from '@dcloudio/uni-ui' 引入组件时，将报错;
 *  而在 vue 中却不会报这个错误;
 *  所以定义一个导出文件，导出所有 uni-ui 的组件，没有用到的组件则不导出;
 *  dir /b H:\maxmedia-selfadplatform\node_modules\@dcloudio\uni-ui\lib
 *  excel 中使用如下公式，
 *  =SUBSTITUTE(LEFT(A1,1)&MID(SUBSTITUTE(PROPER(A1),"_",""),2,100),"-","")  转换为 uniBadge
 * 如下公式引用
 *  ="import "&D1&" from ""@dcloudio/uni-ui/lib/"&A1&"/"&A1&".vue"";"
 * 
 */
import uniBadge from "@dcloudio/uni-ui/lib/uni-badge/uni-badge.vue";
import uniCalendar from "@dcloudio/uni-ui/lib/uni-calendar/uni-calendar.vue";
import uniCard from "@dcloudio/uni-ui/lib/uni-card/uni-card.vue";
import uniCollapse from "@dcloudio/uni-ui/lib/uni-collapse/uni-collapse.vue";
import uniCollapseItem from "@dcloudio/uni-ui/lib/uni-collapse-item/uni-collapse-item.vue";
import uniCountDown from "@dcloudio/uni-ui/lib/uni-count-down/uni-count-down.vue";
import uniDrawer from "@dcloudio/uni-ui/lib/uni-drawer/uni-drawer.vue";
import uniFab from "@dcloudio/uni-ui/lib/uni-fab/uni-fab.vue";
import uniFav from "@dcloudio/uni-ui/lib/uni-fav/uni-fav.vue";
import uniGoodsNav from "@dcloudio/uni-ui/lib/uni-goods-nav/uni-goods-nav.vue";
import uniGrid from "@dcloudio/uni-ui/lib/uni-grid/uni-grid.vue";
import uniGridItem from "@dcloudio/uni-ui/lib/uni-grid-item/uni-grid-item.vue";
import uniIcons from "@dcloudio/uni-ui/lib/uni-icons/uni-icons.vue";
import uniIndexedList from "@dcloudio/uni-ui/lib/uni-indexed-list/uni-indexed-list.vue";
import uniList from "@dcloudio/uni-ui/lib/uni-list/uni-list.vue";
import uniListItem from "@dcloudio/uni-ui/lib/uni-list-item/uni-list-item.vue";
import uniLoadMore from "@dcloudio/uni-ui/lib/uni-load-more/uni-load-more.vue";
import uniNavBar from "@dcloudio/uni-ui/lib/uni-nav-bar/uni-nav-bar.vue";
import uniNoticeBar from "@dcloudio/uni-ui/lib/uni-notice-bar/uni-notice-bar.vue";
import uniNumberBox from "@dcloudio/uni-ui/lib/uni-number-box/uni-number-box.vue";
import uniPagination from "@dcloudio/uni-ui/lib/uni-pagination/uni-pagination.vue";
import uniPopup from "@dcloudio/uni-ui/lib/uni-popup/uni-popup.vue";
import uniRate from "@dcloudio/uni-ui/lib/uni-rate/uni-rate.vue";
import uniSearchBar from "@dcloudio/uni-ui/lib/uni-search-bar/uni-search-bar.vue";
import uniSegmentedControl from "@dcloudio/uni-ui/lib/uni-segmented-control/uni-segmented-control.vue";
import uniStatusBar from "@dcloudio/uni-ui/lib/uni-status-bar/uni-status-bar.vue";
import uniSteps from "@dcloudio/uni-ui/lib/uni-steps/uni-steps.vue";
import uniSwipeAction from "@dcloudio/uni-ui/lib/uni-swipe-action/uni-swipe-action.vue";
import uniSwiperDot from "@dcloudio/uni-ui/lib/uni-swiper-dot/uni-swiper-dot.vue";
import uniTag from "@dcloudio/uni-ui/lib/uni-tag/uni-tag.vue";
import uniTitle from "@dcloudio/uni-ui/lib/uni-title/uni-title.vue";

export {
    uniBadge,
    uniCalendar,
    uniCard,
    uniCollapse,
    uniCollapseItem,
    uniCountDown,
    uniDrawer,
    uniFab,
    uniFav,
    uniGoodsNav,
    uniGrid,
    uniGridItem,
    uniIcons,
    uniIndexedList,
    uniList,
    uniListItem,
    uniLoadMore,
    uniNavBar,
    uniNoticeBar,
    uniNumberBox,
    uniPagination,
    uniPopup,
    uniRate,
    uniSearchBar,
    uniSegmentedControl,
    uniStatusBar,
    uniSteps,
    uniSwipeAction,
    uniSwiperDot,
    uniTag,
    uniTitle,
};

`

**Comment by hesi726** [comment]
非常神奇的事情发生了。。。(不加说明，以下专指小程序编译);

import { uniGrid, uniGridItem, uniList, uniListItem } from '@/PublicUniTsLib/UniUi';  
这种方式，编译没有错误, 小程序中出错; 

import {uniBadge} from '@dcloudio/uni-ui';
这种方式，编译出错，但是小程序中居然正常显示;

import uniBadge from "@dcloudio/uni-ui/lib/uni-badge/uni-badge.vue";
唯一让人感到放心的方式，编译正常，小程序中显示正常;

`import Vue from 'vue';
// import { uniBadge } from "./Xui";
import {uniBadge} from '@dcloudio/uni-ui'; //编译错误，但是居然可以正常显示;
// import uniBadge from "@dcloudio/uni-ui/lib/uni-badge/uni-badge.vue"; //编译无错误，能正常显示;
export default Vue.extend({
	 components: {uniBadge},
		data() {
			return {
				title: 'Hello',
				number1: 3,
				number2: 4
			}
		},
	});`

`<view><uniBadge :text='number1'></uniBadge> </view>
<view><uniBadge :text='number2'></uniBadge> </view>`

**Comment by 643104191** [comment]
1.0.0版本不会出问题

**Comment by ijry** [comment]
按需导入组件不生效!!!!

**Comment by JiangBee** [comment]
import {uniBadge} from '@dcloudio/uni-ui';
import uniBadge from "@dcloudio/uni-ui/lib/uni-badge/uni-badge.vue";
导入组件都不生效。

**Comment by hesi726** [comment]
> import {uniBadge} from '@dcloudio/uni-ui';
> import uniBadge from "@dcloudio/uni-ui/lib/uni-badge/uni-badge.vue";
> 导入组件都不生效。

我估计你使用的uniui的最新版本吧，你试试看看 uniui 的 github 网站上有一个老的版本的链接。
不过，老实说，如果你只是想做微信小程序，建议使用 kbone 和 kbone-ui 以及 kboneapi

**Comment by QiboZhong** [comment]
> 楼上的兄弟，估计你也是使用的TypeScript，下面这个是我自己写的uni-ui的导出文件，
> 你拿过去用吧。。
> 使用方法：
> import' PublicUniTsLib / UniUi'; // ts文件的位置;
> 
> `/ ** uni-ui的导出文件，莫名其妙的是2019-09-23的升级之后，
> 
> * ts文件中，使用这个形式的的。从'@ dcloudio / uni-ui'导入{uniBadge}。
> * 而在vue中却不会报这个错误;
> * 所以定义一个导出文件，导出所有uni-ui的组件，没有用到的组件则不导出;
> * 目录/ b H：\ maxmedia-selfadplatform \ node_modules @ dcloudio \ uni-ui \ lib
> * excel中使用如下公式，
> * = SUBSTITUTE（LEFT（A1,1）＆MID（SUBSTITUTE（PROPER（A1），“ _”，“”），2,100），“-”，“”）转换为uniBadge
> * 如下公式引用
> * =“从”“ @ dcloudio / uni-ui / lib /”＆A1＆“ /”＆A1＆“。vue”“中导入”＆D1＆“；”
> 
> * /
> 从“ @ dcloudio / uni-ui / lib / uni-badge / uni-badge.vue”导入uniBadge；
> 从“ @ dcloudio / uni-ui / lib / uni-calendar / uni-calendar.vue”导入uniCalendar；
> 从“ @ dcloudio / uni-ui / lib / uni-card / uni-card.vue”导入uniCard；
> 从“ @ dcloudio / uni-ui / lib / uni-collapse / uni-collapse.vue”导入uniCollapse；
> 从“ @ dcloudio / uni-ui / lib / uni-collapse-item / uni-collapse-item.vue”中导入uniCollapseItem；
> 从“ @ dcloudio / uni-ui / lib / uni-count-down / uni-count-down.vue”导入uniCountDown；
> 从“ @ dcloudio / uni-ui / lib / uni-drawer / uni-drawer.vue”导入uniDrawer；
> 从“ @ dcloudio / uni-ui / lib / uni-fab / uni-fab.vue”导入uniFab；
> 从“ @ dcloudio / uni-ui / lib / uni-fav / uni-fav”导入uniFav。
> 从“ @ dcloudio / uni-ui / lib / uni-goods-nav / uni-goods-nav.vue”导入uniGoodsNav；
> 从“ @ dcloudio / uni-ui / lib / uni-grid / uni-grid.vue”导入uniGrid；
> 从“ @ dcloudio / uni-ui / lib / uni-grid-item / uni-grid-item.vue”导入uniGridItem；
> 从“ @ dcloudio / uni-ui / lib / uni-icons / uni-icons.vue”导入uniIcons；
> 从“ @ dcloudio / uni-ui / lib / uni-indexed-list / uni-indexed-list.vue”中导入uniIndexedList；
> 从“ @ dcloudio / uni-ui / lib / uni-list / uni-list.vue”导入uniList；
> 从“ @ dcloudio / uni-ui / lib / uni-list-item / uni-list-item.vue”中导入uniListItem；
> 从“ @ dcloudio / uni-ui / lib / uni-load-more / uni-load-more.vue”导入uniLoadMore；
> 从“ @ dcloudio / uni-ui / lib / uni-nav-bar / uni-nav-bar”导入uniNavBar。
> 从“ @ dcloudio / uni-ui / lib / uni-notice-bar / uni-notice-bar.vue”导入uniNoticeBar；
> 从“ @ dcloudio / uni-ui / lib / uni-number-box / uni-number-box.vue”导入uniNumberBox；
> 从“ @ dcloudio / uni-ui / lib / uni-pagination / uni-pagination.vue”导入uniPagination；
> 从“ @ dcloudio / uni-ui / lib / uni-popup / uni-popup.vue”导入uniPopup；
> 从“ @ dcloudio / uni-ui / lib / uni-rate / uni-rate.vue”导入uniRate；
> 从“ @ dcloudio / uni-ui / lib / uni-search-bar / uni-search-bar.vue”导入uniSearchBar；
> 从“ @ dcloudio / uni-ui / lib / uni-segmented-control / uni-segmented-control.vue”导入uniSegmentedControl；
> 从“ @ dcloudio / uni-ui / lib / uni-status-bar / uni-status-bar.vue”导入uniStatusBar；
> 从“导入uniStep
> 从“ @ dcloudio / uni-ui / lib / uni-swipe-action / uni-swipe-action.vue”导入uniSwipeAction；
> 从“ @ dcloudio / uni-ui / lib / uni-swiper-dot / uni-swiper-dot.vue”导入uniSwiperDot；
> 从“ @ dcloudio / uni-ui / lib / uni-tag / uni-tag.vue”导入uniTag；
> 从“ @ dcloudio / uni-ui / lib / uni-title / uni-title.vue”导入uniTitle；
> 
> export {
> uniBadge,
> uniCalendar,
> uniCard,
> uniCollapse,
> uniCollapseItem,
> uniCountDown,
> uniDrawer,
> uniFab,
> uniFav,
> uniGoodsNav,
> uniGrid,
> uniGridItem,
> uniIcons,
> uniIndexedList,
> uniList,
> uniListItem,
> uniLoadMore,
> uniNavBar,
> uniNoticeBar,
> uniNumberBox,
> uniPagination,
> uniPopup,
> uniRate,
> uniSearchBar,
> uniSegmentedControl,
> uniStatusBar,
> uniSteps,
> uniSwipeAction,
> uniSwiperDot,
> uniTag,
> uniTitle,
> };
> 
> `
老哥，  万分感谢， 好人一生平安。哈哈哈

**Comment by mehaotian** [comment]
使用最新版本的 cli 或者开发工具，已经修复此问题

**Comment by KtfwyCJ** [comment]
> 使用最新版本的 cli 或者开发工具，已经修复此问题

已经升级到了2.8.11.20200907，依旧存在这个问题

**Comment by MeetTheBest** [comment]
@KtfwyCJ  
我遇到了类似的问题，我引用的是`uni-indexed-list`这个组件。

通过`import uniIndexedList from '@dcloudio/uni-ui/lib/uni-indexed-list/uni-indexed-list.vue';` 后，页面提示组件引入错误。

`uni`在配置文件中`pages.json`中的`easycom`进行了`@dcloudio/uni-ui` 的自动引入。可以进行自定义的匹配修改。

![image](https://user-images.githubusercontent.com/21294768/93233385-9639e180-f7ad-11ea-8912-4baeb261220b.png)

我项目中遇到的问题是，`list`组件中引用了`uni-indexed-list-item`，但是`@dcloudio/uni-ui`中并没有这个`uni-indexed-list-item`路径，所以导致引用报错了。

看看能不能对你有所帮助。

**Comment by FungSaikit** [comment]
> 楼上的兄弟，估计你也是使用的 TypeScript, 下面这个是我自己写的 uni-ui 的导出文件， 你拿过去用吧。。 使用方法: import { uniGrid, uniGridItem, uniList, uniListItem } from '@/PublicUniTsLib/UniUi'; //ts文件的位置;
> 
> `/** uni-ui 的导出文件，莫名其妙的是 2019-09-23 的升级之后，
> 
> * ts文件中，使用这个形式的 import {uniBadge} from '@dcloudio/uni-ui' 引入组件时，将报错;
> * 而在 vue 中却不会报这个错误;
> * 所以定义一个导出文件，导出所有 uni-ui 的组件，没有用到的组件则不导出;
> * dir /b H:\maxmedia-selfadplatform\node_modules@dcloudio\uni-ui\lib
> * excel 中使用如下公式，
> * =SUBSTITUTE(LEFT(A1,1)&MID(SUBSTITUTE(PROPER(A1),"_",""),2,100),"-","")  转换为 uniBadge
> * 如下公式引用
> * ="import "&D1&" from ""@dcloudio/uni-ui/lib/"&A1&"/"&A1&".vue"";"
> 
> */ import uniBadge from "@dcloudio/uni-ui/lib/uni-badge/uni-badge.vue"; import uniCalendar from "@dcloudio/uni-ui/lib/uni-calendar/uni-calendar.vue"; import uniCard from "@dcloudio/uni-ui/lib/uni-card/uni-card.vue"; import uniCollapse from "@dcloudio/uni-ui/lib/uni-collapse/uni-collapse.vue"; import uniCollapseItem from "@dcloudio/uni-ui/lib/uni-collapse-item/uni-collapse-item.vue"; import uniCountDown from "@dcloudio/uni-ui/lib/uni-count-down/uni-count-down.vue"; import uniDrawer from "@dcloudio/uni-ui/lib/uni-drawer/uni-drawer.vue"; import uniFab from "@dcloudio/uni-ui/lib/uni-fab/uni-fab.vue"; import uniFav from "@dcloudio/uni-ui/lib/uni-fav/uni-fav.vue"; import uniGoodsNav from "@dcloudio/uni-ui/lib/uni-goods-nav/uni-goods-nav.vue"; import uniGrid from "@dcloudio/uni-ui/lib/uni-grid/uni-grid.vue"; import uniGridItem from "@dcloudio/uni-ui/lib/uni-grid-item/uni-grid-item.vue"; import uniIcons from "@dcloudio/uni-ui/lib/uni-icons/uni-icons.vue"; import uniIndexedList from "@dcloudio/uni-ui/lib/uni-indexed-list/uni-indexed-list.vue"; import uniList from "@dcloudio/uni-ui/lib/uni-list/uni-list.vue"; import uniListItem from "@dcloudio/uni-ui/lib/uni-list-item/uni-list-item.vue"; import uniLoadMore from "@dcloudio/uni-ui/lib/uni-load-more/uni-load-more.vue"; import uniNavBar from "@dcloudio/uni-ui/lib/uni-nav-bar/uni-nav-bar.vue"; import uniNoticeBar from "@dcloudio/uni-ui/lib/uni-notice-bar/uni-notice-bar.vue"; import uniNumberBox from "@dcloudio/uni-ui/lib/uni-number-box/uni-number-box.vue"; import uniPagination from "@dcloudio/uni-ui/lib/uni-pagination/uni-pagination.vue"; import uniPopup from "@dcloudio/uni-ui/lib/uni-popup/uni-popup.vue"; import uniRate from "@dcloudio/uni-ui/lib/uni-rate/uni-rate.vue"; import uniSearchBar from "@dcloudio/uni-ui/lib/uni-search-bar/uni-search-bar.vue"; import uniSegmentedControl from "@dcloudio/uni-ui/lib/uni-segmented-control/uni-segmented-control.vue"; import uniStatusBar from "@dcloudio/uni-ui/lib/uni-status-bar/uni-status-bar.vue"; import uniSteps from "@dcloudio/uni-ui/lib/uni-steps/uni-steps.vue"; import uniSwipeAction from "@dcloudio/uni-ui/lib/uni-swipe-action/uni-swipe-action.vue"; import uniSwiperDot from "@dcloudio/uni-ui/lib/uni-swiper-dot/uni-swiper-dot.vue"; import uniTag from "@dcloudio/uni-ui/lib/uni-tag/uni-tag.vue"; import uniTitle from "@dcloudio/uni-ui/lib/uni-title/uni-title.vue";
> 
> export { uniBadge, uniCalendar, uniCard, uniCollapse, uniCollapseItem, uniCountDown, uniDrawer, uniFab, uniFav, uniGoodsNav, uniGrid, uniGridItem, uniIcons, uniIndexedList, uniList, uniListItem, uniLoadMore, uniNavBar, uniNoticeBar, uniNumberBox, uniPagination, uniPopup, uniRate, uniSearchBar, uniSegmentedControl, uniStatusBar, uniSteps, uniSwipeAction, uniSwiperDot, uniTag, uniTitle, };
> 
> `

太强了
