### ISSUE TITLE
uni-app (Vue3 + UnoCSS + uni-ui) 微信小程序开发模式下，不生成有效wxss样式文件，H5下一切正常。 

### ISSUE THREAD

**Issue by jocstech** [dcloudio/uni-ui#643]
uni-app (Vue3 + UnoCSS + uni-ui) 微信小程序开发模式下，不生成有效wxss样式文件，H5下一切正常。 
请问是不是 uni-ui和原子css库存在一定的机制冲突？ 希望有人可以一起探讨一下。

**Comment by 18148764734** [comment]
感谢反馈，若H5可以，微信小程序不行，这代表微信小程序暂不支持某种css写法。
