### ISSUE TITLE
uni-forms示例代码，无法检验uni-data-checkbox

### ISSUE THREAD

**Issue by yaoyin2014** [dcloudio/uni-ui#644]
https://ext.dcloud.net.cn/plugin?id=2773 
下载示例代码，在微信小程序中，【自定义检验规则】【兴趣爱好】只要被勾选后，无论值为多少，validateFunction都不再触发。

![image](https://user-images.githubusercontent.com/7578856/204994030-64da185e-d4e1-4072-abe0-aa06315a8f81.png)

**Comment by LarryHangFan** [comment]
这个问题不是还在吗，怎么关闭了？
