### ISSUE TITLE
uni-ui , vue-cli方式编译为支付宝小程序，icon无法正常显示

### ISSUE THREAD

**Issue by tengyuanOasis** [dcloudio/uni-ui#646]
问题：
uniapp + vue-cli 方式引入uni-ui , 编译伟支付宝小程序， icon显示为方块，支付宝及微信显示正常

相关版本：
"vue": "^2.6.11"，
"@dcloudio/uni-mp-alipay": "^2.0.1-36420220922003",
"@dcloudio/uni-ui": "^1.4.23",

复现步骤：
uniapp + vue-cli + 编译支付宝小程序必现
![image](https://user-images.githubusercontent.com/58558076/205876425-24e80962-a24c-4384-b0d0-0ecf4a726cae.png)

**Comment by 18148764734** [comment]
现版本已修复，此ISSUE暂时关闭

**Comment by SoftJ1** [comment]
"vue": ">= 2.6.14 < 2.7", APP下也有bug
  "@dcloudio/uni-app": "2.0.2-3080720230703001",
  "@dcloudio/uni-app-plus": "2.0.2-3080720230703001",
"@dcloudio/uni-ui": "^1.5.5",
![image](https://github.com/dcloudio/uni-ui/assets/67351430/66636332-b196-40a6-bda3-ab8af2b48ed9)

**Comment by SoftJ1** [comment]
> "vue": ">= 2.6.14 < 2.7", APP下也有bug
> "@dcloudio/uni-app": "2.0.2-3080720230703001",
> "@dcloudio/uni-app-plus": "2.0.2-3080720230703001",
> "@dcloudio/uni-ui": "^1.5.5",
