### ISSUE TITLE
编译飞书小程序uni-swipe-action-item 没有内容

### ISSUE THREAD

**Issue by TangWenZERO** [dcloudio/uni-ui#651]
1. 使用的是官网的例子，
<uni-swipe-action>
	
	<uni-swipe-action-item>
		<view>SwipeAction 基础使用场景</view>
	</uni-swipe-action-item>
	
	<uni-swipe-action-item>
		<template v-slot:left>
			<view><text>置顶</text></view>
		</template>
		<view>
			<text >使用插槽</text>
		</view>
		<template v-slot:right>
			<view><text>删除</text></view>
		</template>
	</uni-swipe-action-item>
	
	<uni-swipe-action-item>
		<template v-slot:left>
			<view><text>置顶</text></view>
		</template>
		<view><text>混合使用</text></view>
	</uni-swipe-action-item>
</uni-swipe-action>
<img width="1064" alt="截屏2022-12-13 上午11 16 37" src="https://user-images.githubusercontent.com/19620403/207218052-407d030c-2706-4514-9a19-82a1b272053f.png">

**Comment by TangWenZERO** [comment]
`<uni-swipe-action>
	
	<uni-swipe-action-item>
		<view>SwipeAction 基础使用场景</view>
	</uni-swipe-action-item>
	
	<uni-swipe-action-item>
		<template v-slot:left>
			<view><text>置顶</text></view>
		</template>
		<view>
			<text >使用插槽</text>
		</view>
		<template v-slot:right>
			<view><text>删除</text></view>
		</template>
	</uni-swipe-action-item>
	
	<uni-swipe-action-item>
		<template v-slot:left>
			<view><text>置顶</text></view>
		</template>
		<view><text>混合使用</text></view>
	</uni-swipe-action-item>
</uni-swipe-action>`

**Comment by 18148764734** [comment]
感谢反馈，现版本未复现该问题，排查出已修复该bug，此ISSUE暂时关闭
