### ISSUE TITLE
uni-swiper-dot为nav模式时,怎么可以只显示Index不显示内容?

### ISSUE THREAD

**Issue by aizela** [dcloudio/uni-ui#652]
目前mode为nav时filed必填,不然就会显示undefined,但是我确实不需要显示其他信息,怎么做?
![image](https://user-images.githubusercontent.com/52120594/207809857-5b8a991c-41df-4e75-b33f-95a49ab81f31.png)

**Comment by 18148764734** [comment]
感谢反馈，只是显示index的功能目前用户需求不高，需要讨论，你可以通过修改uni_moduels文件夹下的swiper-dot的相关代码来达到自定义的效果
