### ISSUE TITLE
uni-drawer 组件在vue3中报错，Uncaught TypeError: showLeftDrawerRef.value.open is not a function。

### ISSUE THREAD

**Issue by ElsaOOo** [dcloudio/uni-ui#654]
模板中的代码：
<img width="727" alt="image" src="https://user-images.githubusercontent.com/48074435/208831920-7bcec0ef-68f6-4c54-a5dc-5ba85fefef7c.png">

script中的代码：
<img width="623" alt="image" src="https://user-images.githubusercontent.com/48074435/208831998-beb5cca3-6fc3-4523-b913-cf72987f9928.png">

调用open方法报错：
Uncaught TypeError: showLeftDrawerRef.value.open is not a function。

**Comment by 18148764734** [comment]
暂未复现该问题，此贴由于时间过长，暂时关闭
