### ISSUE TITLE
uni-datetime-picker导致编译支付宝mpaas报错

### ISSUE THREAD

**Issue by Aliom252181** [dcloudio/uni-ui#655]
使用hbuilderx，选择vue3 uni ui初始项目，然后index页面使用uni-datetime-picker组件运行报错。

**Comment by Aliom252181** [comment]
![image](https://user-images.githubusercontent.com/49222345/208846945-cedfc46d-6ea6-47de-a6b0-2c1fc4e2f655.png)

**Comment by Aliom252181** [comment]
![image](https://user-images.githubusercontent.com/49222345/208847023-82cf509b-c437-494e-a0cc-d7ef988e2491.png)

**Comment by mehaotian** [comment]
框架bug ，正在排查中

**Comment by mehaotian** [comment]
问题已修复，请升级HBuilderX到3.7.0+版本
