### ISSUE TITLE
uni-data-select 提示“应用未关联服务空间，请在uniCloud目录右键关联服务空间”

### ISSUE THREAD

**Issue by ElsaOOo** [dcloudio/uni-ui#656]
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/48074435/208857175-7359485c-09e8-46f3-868c-bba689230ccd.png">

未使用unicloud情况下，也没有传递collection，配置了localdata，控制台报错：
<img width="540" alt="image" src="https://user-images.githubusercontent.com/48074435/208857286-20e9bb74-9a99-4f25-9cf0-87124f3f1c91.png">

**Comment by yurj26** [comment]
这个应该是你传入`collection`的原因，排查下代码吧，如果还存在此问题，可以去ask社区上传测试工程。

**Comment by ElsaOOo** [comment]
> 这个应该是你传入`collection`的原因，排查下代码吧，如果还存在此问题，可以去ask社区上传测试工程。

我没有传入collection，可以看我贴的截图~

**Comment by yurj26** [comment]
看一下其他地方是否传入

**Comment by ElsaOOo** [comment]
> 

没有哦，目前整个项目，就这一个vue文件使用到了uni-data-select组件。

**Comment by yurj26** [comment]
> 没有哦，目前整个项目，就这一个vue文件使用到了uni-data-select组件。

在dcloud ask社区上传一个可复现的测试工程吧

**Comment by ElsaOOo** [comment]
> > 没有哦，目前整个项目，就这一个vue文件使用到了uni-data-select组件。
> 
> 在dcloud ask社区上传一个可复现的测试工程吧

ok

**Comment by mehaotian** [comment]
问题已经修复 ，请更新插件
