### ISSUE TITLE
https://uniui.dcloud.net.cn/

### ISSUE THREAD

**Issue by ctocode** [dcloudio/uni-ui#658]
这个没用网站就下架吧。
https://uniui.dcloud.net.cn/
https://uniapp.dcloud.net.cn/component/uniui/uni-ui.html
这2个你们维护着不累吗？？

**Comment by mehaotian** [comment]
https://uniui.dcloud.net.cn/ 这个地址现在已经不维护了且并没有对外发布 ，使用 https://uniapp.dcloud.net.cn/component/uniui/uni-ui.html 即可
