### ISSUE TITLE
uni-data-checkbox 的map属性怎么映射呢？

### ISSUE THREAD

**Issue by xcondor** [dcloudio/uni-ui#659]
我现在选择的uni-data-checkbox 是一行有样式和数据值的文本组成的。所以{text:'',value: 0}， text属性是无法把这块内容当作字符串传进去，如何用map映射呢？

**Comment by mehaotian** [comment]
目前 uni-data-checkbox 的属性渲染，只支持 text:文本，value:值， 如您的数据格式不是 text value 的话，需要使用 map 属性指定渲染字段，如您的格式为：
```
let localdata = [{
  "key":"1",
  "label":"文本1"
},{
  "key":"2",
  "label":"文本2"
}]
```

label 用来显示， key 为值，使用 map 映射为：

```html
<uni-data-checkbox :localdata="localdata" :map="{text:"label",value:"key"}"></uni-data-checkbox >
```

如上，代码为： 将 text 属性映射到 原json的 label 属性上，将 value 属性映射到原json 的 key属性上
