### ISSUE TITLE
PC端打开微信小程序无法触发

### ISSUE THREAD

**Issue by fupan1018** [dcloudio/uni-ui#660]
1、PC端使用uni-file-picker组件，点击上传文件，没有反应
2、打包成微信小程序后，使用uni-file-picker上传文件时，只能在微信聊天记录里面选择文件

**Comment by mehaotian** [comment]
问题一 没有复现，使用 mac 开发者工具 ，可以选择文件
问题二 目前设计如此，微信只提供了 这一个 api ，无法自由选择文件，需要等微信小程序这边更新 ，不然暂时无解

**Comment by fupan1018** [comment]
问题一：可能我表达不是蛮清楚，我说的PC端打开微信小程序无法触发uni-file-picker组件，是指在电脑端使用小程序，不是指微信开发者工具；
![image](https://user-images.githubusercontent.com/16321092/217755238-dd5c8f49-042b-4c49-8be3-77b102913f2f.png)
如图上图

**Comment by 18148764734** [comment]
该ISSUE测试之后并未复现，暂时关闭，后续若用户提供问题工程则重新打开
