### ISSUE TITLE
uni-swipe-action-item 报错

### ISSUE THREAD

**Issue by WebGamer** [dcloudio/uni-ui#665]
<img width="977" alt="image" src="https://user-images.githubusercontent.com/56241499/212861024-a0df2ffb-c6ac-4175-bc61-aaf0f57830f3.png">
把mounted里面注释就不会报错了
![image](https://user-images.githubusercontent.com/56241499/212861163-3b28b70a-a68b-456c-8556-84bbe9916a31.png)

**Comment by mehaotian** [comment]
这是那个平台？是 nvue 吗？

**Comment by WebGamer** [comment]
> 

不是nvue  就是在h5环境，直接使用就会报错

**Comment by WebGamer** [comment]
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/56241499/215936205-6a20ca14-cca0-4a89-aa55-7df1dd233bde.png">
这里没加条件渲染，导致使用直接报错

**Comment by WebGamer** [comment]
@mehaotian

**Comment by WebGamer** [comment]
@hbcui1984

**Comment by mehaotian** [comment]
条件编译未生效 ，如果是 cli项目 ，在 vue.config.js 中添加

```js
// vue.config.js
module.exports = {
		transpileDependencies:['@dcloudio/uni-ui']
}
```
