### ISSUE TITLE
uni-tag 背景颜色 文档错误   danger 应该改成了error  但是文档还是写 danger

### ISSUE THREAD

**Issue by zhangyq233** [dcloudio/uni-ui#67]
![image](https://user-images.githubusercontent.com/28673757/66727385-55d13580-ee71-11e9-9f6d-e92cbbfe0ba2.png)
![image](https://user-images.githubusercontent.com/28673757/66727388-5ec20700-ee71-11e9-97ce-c5e632156f80.png)

**Comment by Wangyaqi** [comment]
已修改，感谢反馈
