### ISSUE TITLE
申请将NavBar、uniicons等插件也加入到@cloudio/uni-ui项目

### ISSUE THREAD

**Issue by qinkaiyuan** [dcloudio/uni-ui#68]
申请将NavBar、uniicons等插件也加入到@cloudio/uni-ui项目

目前未在uni-ui项目中找到，无法使用npm安装，只能单独在项目中引入，为方便使用，申请将NavBar、uniicons等插件也加入到此项目

**Comment by Wangyaqi** [comment]
目前npm上最新版本是1.0.4，里面是包含NavBar、uniicons的，看下你的是什么版本

**Comment by qinkaiyuan** [comment]
1.0.4找到了

因为在这个里面没找到，然后在对应的NavBar 文档也没有相关npm文档，所以以为没有呢

https://github.com/dcloudio/uni-ui#uni-ui-%E5%B7%B2%E6%94%AF%E6%8C%81%E7%9A%84%E7%BB%84%E4%BB%B6%E5%88%97%E8%A1%A8

**Comment by Wangyaqi** [comment]
近期修改完毕后会统一整理文档，感谢关注
