### ISSUE TITLE
【uni-easyinput  trim属性】源码与文档描述不符

### ISSUE THREAD

**Issue by montisan** [dcloudio/uni-ui#682]
【uni-easyinput  trim属性】源码与文档描述不符：
文档中描述默认的值是false，但是源代码中默认是true。应该默认是false才合理，希望能修复一下啊。
（我们很多业务系统都是默认值，造成输入英文时，空格被自动删除的问题）

**Comment by 18148764734** [comment]
感谢反馈，现源码已修改为false
