### ISSUE TITLE
uni-datetime-picker 日期选择器范围选择问题

### ISSUE THREAD

**Issue by lotherli** [dcloudio/uni-ui#684]
<uni-datetime-picker type="daterange" />
当type='daterange', 选择一个日期区间后（如 ["2023-02-01", "2023-02-02"]），进行二次选择时，只选择一个日期（“2023-02-03”）后直接点击确认，返回的还是上次选择的值（["2023-02-01", "2023-02-02"]）。

修复位置为 ： uni-datetime-picker.vue ，mobileChange函数增加下列内容
if (!(before && after)) return

**Comment by zhenyuWang** [comment]
你的问题是只选择了一个日期的时候不应该触发change事件是吧？

**Comment by lotherli** [comment]
是的，既然是日期范围选择，只选择单个日期时，应不触发onchange事件




--
发自我的网易邮箱手机智能版



在 2023-02-06 17:28:14，"running snail" ***@***.***> 写道：


你的问题是只选择了一个日期的时候不应该触发change事件是吧？

**Comment by zhenyuWang** [comment]
2.2.18 已修复

**Comment by AKclown** [comment]
你好，如何当他选择只选择单个日期时把确定按钮禁用掉呢？ 而不是确定保持选择范围不变
