### ISSUE TITLE
uni-datetime-picker最新版本在vue3下安卓机选择区间无效

### ISSUE THREAD

**Issue by Nangras** [dcloudio/uni-ui#686]
https://user-images.githubusercontent.com/30164340/217753503-523a03e9-79ea-436d-ace6-69a5d9a4e8fb.mp4

页面代码：
![image](https://user-images.githubusercontent.com/30164340/217753586-1391b612-73dc-46c6-adcc-1ba543f366b7.png)
![image](https://user-images.githubusercontent.com/30164340/217753717-e1dfbd5c-6e51-4579-8cfb-65cd914c923f.png)
![image](https://user-images.githubusercontent.com/30164340/217753776-44a741f5-b517-40e9-ad5c-0e49683099c6.png)

**Comment by zhenyuWang** [comment]
2.2.19 已修复
