### ISSUE TITLE
ios端NumberBox组件图标不居中

### ISSUE THREAD

**Issue by zhongzhifa** [dcloudio/uni-ui#687]
![d8730ced521ca27ee11563752920c1a](https://user-images.githubusercontent.com/25548250/217784644-74177746-ab41-426b-8b8f-be8dbe201e07.jpg)

截图如上↑，加+减-图标未居中

机型：14 pro
小程序：官方示例小程序HelloUniApp
平台：微信小程序

**Comment by 18148764734** [comment]
感谢反馈，现已修复，请到插件市场更新插件
