### ISSUE TITLE
自定义图标无法显示

### ISSUE THREAD

**Issue by zhongzhifa** [dcloudio/uni-ui#688]
![93786355c66c2550f06af5d01fe8846](https://user-images.githubusercontent.com/25548250/217785985-fe129384-682a-42a5-9149-034e13126c74.jpg)

详见上图↑，自定义图标无法显示

机型：14 pro
小程序：官方示例小程序HelloUniApp
平台：微信小程序

**Comment by 18148764734** [comment]
现版本已修复，感谢反馈
