### ISSUE TITLE
uni-datetime-picker 日期选择器  是否可以默认不显示输入框

### ISSUE THREAD

**Issue by lotherli** [dcloudio/uni-ui#690]
在某些特定的场景下，不需要输入框，是否可以通过传入特定的值（true/false），进行是否展示输入框。
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/36142693/218406394-b006acc0-eb88-45f9-96c0-891d42ed05af.png">

比如props 新增 slotshow默认为true，展示输入框。当为false的时候没有输入框，就通过Methods方法去调用打开。
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/36142693/218407692-7aa3e45e-0d31-4040-8033-431b3715deda.png">
<img width="661" alt="image" src="https://user-images.githubusercontent.com/36142693/218407849-f9850f23-7052-4e91-aad7-7658e527e6f0.png">

**Comment by zhenyuWang** [comment]
https://uniapp.dcloud.net.cn/component/uniui/uni-datetime-picker.html#datetimepicker-slots

**Comment by lotherli** [comment]
功能大概属于增加一个props【slotShow】，跟slot的功效很雷同。
区别就是slot插槽的内容会覆盖文件 uni-datetime-picker.vue 里面的内容，而props【slotShow】只是在不使用slot的情况下，也可以让输入框不显示。
<uni-datetime-picker ref="calendar"  slotShow="false"></uni-datetime-picker>
![image](https://user-images.githubusercontent.com/36142693/218660351-9bc6fe5e-8b03-4a3e-a585-b01d4dd238bd.png)

**Comment by zhenyuWang** [comment]
你在插槽写个空标签不就好了，增加 slotShow 属性的必要性是什么呢？

**Comment by lotherli** [comment]
🫢,是我没想到
