### ISSUE TITLE
vite使用uni-ui时h5运行显示正常，但生成App资源是报错

### ISSUE THREAD

**Issue by JoeXin** [dcloudio/uni-ui#692]
问题描述：
 1、![image](https://user-images.githubusercontent.com/17316003/219358380-0e28d68d-ca7f-4386-9466-f0bb3bfb13f9.png)

page.json文件中已经配置了自动导包，生成资源包时提示vite提示需要配置
![image](https://user-images.githubusercontent.com/17316003/219358580-f49d7e45-5ce4-40b7-84e3-e632f323a68e.png)
官方文档中说明，不需要进行配置
![image](https://user-images.githubusercontent.com/17316003/219358800-39f20710-e2df-4d0e-98b2-f4b5ea20c399.png)

**Comment by JoeXin** [comment]
vue版本： 3.2.47
 vite版本：3.2.4

**Comment by im55cc** [comment]
老哥，这个问题解决了没？

**Comment by JoeXin** [comment]
之前我重新更新了uni-ui就可以了

**Comment by inksnowhailong** [comment]
生成为 微信小程序 也会有丢失node_moduels问题 如何解决

**Comment by 18148764734** [comment]
> 生成为 微信小程序 也会有丢失node_moduels问题 如何解决

更新uni-ui到最新版后重新配置一下自动导入试试

**Comment by 18148764734** [comment]
此ISSUE由于用户未回复，如果旧版本还是复现该问题，请配置一下vue.config.js或者升级到vite v4.1.4
