### ISSUE TITLE
uniRate的BUG

### ISSUE THREAD

**Issue by FontEndArt** [dcloudio/uni-ui#7]
uniRate传参size  小于44upx即【uni.upx2px(44)】时候   选中的星星会发生向下偏移  请注意修复

**Comment by hulinNeil** [comment]
我在chrome使用下面的方式不能重现问题，请提供可重现问题的demo和出现问题的环境
```html
<uni-rate value="2" size="14"></uni-rate>
```

**Comment by FontEndArt** [comment]
运行环境是app  一加手机
`
<uni-rate
							:size="rateSizeT"
							:margin="rateMarginT"
							value="0"
							:color="rateColor"
							:active-color="rateColor"
							:is-fill="false"
							@change="res => ChangeRate(2, res.value)"
						></uni-rate>
-------
	data() {
		return {
			rateSize: 45,
		};
	},
	computed: {
		rateSizeT() {
			return uni.upx2px(this.rateSize);
		},
		rateMarginT() {
			return uni.upx2px(this.rateMargin);
		},
		anonymousColor() {
			return this.anonymous ? this.rateColor : '#999999';
		}
	},
	methods: {
		ChangeRate(index, value) {
			this[`Rate${index}`] = `${value * 20}分`;
		}
	}
`

**Comment by hulinNeil** [comment]
你好请提供完整示例，你粘贴的代码有部分变量是无效的：rateMargin/rateColor,你可以使用添加附件的方式提供demo，或者在 [DCloud论坛](https://ask.dcloud.net.cn/explore/) 提交问题，在这里附上链接地址。

**Comment by hulinNeil** [comment]
长时间不回复，关闭此issues，有问题可重新提出
