### ISSUE TITLE
uni-datetime-picker  配置动态start、end属性，日期禁用区域选择问题

### ISSUE THREAD

**Issue by zhaowei97** [dcloudio/uni-ui#702]
测试步骤：
1、type设置为date（业务场景需要拆分两行进行单独选择，所以未能使用type: 'daterange'），分别给两个uni-datetime-picker组件配置动态start和end属性
2、起始日期随机选中一个值并确认，随后直接点击该组件的清空图标进行重置操作

期望：
进行清空操作时，禁用范围能够同步更新

现在：
清空起止日期后，截止日期不能选择到起始日期第一次选中前的日期

其他：由于第一次使用uni-ui 不知道是个人使用方式有误还是本身组件稍有瑕疵，目前本地看了下组件源码发现应该是这段代码影响到的, 由于清空操作传入的是空值，而处理函数对于空值直接return了，所以没有更新禁用区域字段：

```
	start: {
		immediate: true,
		handler(newVal) {
			if (!newVal) return
			this.calendarRange.startDate = getDate(newVal)
			if (this.hasTime) {
				this.calendarRange.startTime = getTime(newVal)
			}
		}
	},
	end: {
		immediate: true,
		handler(newVal) {
			if (!newVal) return
			this.calendarRange.endDate = getDate(newVal)
			if (this.hasTime) {
				this.calendarRange.endTime = getTime(newVal, this.hideSecond)
			}
		}
	},
```

当前我使用的规避方案为：
```
	start: {
		immediate: true,
		handler(newVal) {
			// if (!newVal) return
			this.calendarRange.startDate = newVal ? getDate(newVal) : ''
			if (this.hasTime) {
				this.calendarRange.startTime = newVal ? getTime(newVal) : ''
			}
		}
	},
	end: {
		immediate: true,
		handler(newVal) {
			// if (!newVal) return
			this.calendarRange.endDate = newVal ? getDate(newVal) : ''
			if (this.hasTime) {
				this.calendarRange.endTime = newVal ? getTime(newVal, this.hideSecond) : ''
			}
		}
	},
```

**Comment by zhenyuWang** [comment]
没懂你的问题，能否再详细说下或提供下截图、视频补充说明

**Comment by zhaowei97** [comment]
希望dalao指点一下  看看是我使用问题还是组件的问题呢

[20230304164837.webm](https://user-images.githubusercontent.com/49801294/222905513-8fd39dfa-32f6-41fc-996e-412a74168f6b.webm)

**Comment by zhaowei97** [comment]
> 没懂你的问题，能否再详细说下或提供下截图、视频补充说明

希望dalao指点一下 看看是我使用问题还是组件的问题呢

[20230304164837.webm](https://user-images.githubusercontent.com/49801294/222905587-231bc4f8-3c13-4808-a553-05d934bc502e.webm)

**Comment by zhenyuWang** [comment]
大致了解你的问题是 start end 未按你的预期更新，start end 是两个单独的值，和清空操作没有关系，建议调整你的业务逻辑传入符合预期的值即可

**Comment by zhaowei97** [comment]
> 大致了解你的问题是 start end 未按你的预期更新，start end 是两个单独的值，和清空操作没有关系，建议调整你的业务逻辑传入符合预期的值即可
了解  谢谢~
