### ISSUE TITLE
uni-ui uni-list-item customStyle 属性逻辑错误

### ISSUE THREAD

**Issue by jzsn2018** [dcloudio/uni-ui#703]
看 props 中的定义，customStyle 中的 padding 应该是字符串的类型
```js
customStyle: {
				type: Object,
				default () {
					return {
						padding: '',
						backgroundColor: '#FFFFFF'
					}
				}
			},
```
```js
	'customStyle.padding': {
		handler(padding) {
			if(typeof padding == 'number'){
				padding += ''
			}
			let paddingArr = padding.split(' ')
			if (paddingArr.length === 1) {
				this.padding = {
					"top": padding, 
					"right": padding,
					"bottom": padding,
					"left": padding
				}
			} else if (paddingArr.length === 2) {
				this.padding = {
					"top": padding[0],  //  这里正常是不是 paddingArr ？padding不是字符串吗？字符串的数字索引获取到的根本就不是对应的padding 值
					"right": padding[1],
					"bottom": padding[0],
					"left": padding[1]
				}
			} else if (paddingArr.length === 4) {
				this.padding = {
					"top": padding[0],
					"right": padding[1],
					"bottom": padding[2],
					"left": padding[3]
				}
			}
		},
		immediate: true
	}
```

**Comment by zqy233** [comment]
没问题吧，不是判断是数字就转成字符串了嘛
if(typeof padding == 'number'){
				padding += ''
			}

**Comment by jzsn2018** [comment]
> 

 看props 我们传递的 padding 应该是这种， padding: "40px 40px 20px 32px" 通过 “ ” 进行拆分得到paddingArr数组 [40px,40px, 20px,32px]，这时候赋值的时候应该是通过  paddingArr[0] 去获取的padding值才能拿到。
 
 但是代码里面是通过 padding[0] 去拿。  "40px 40px 20px 32px"[0] 拿到的数据是 4 和 paddingArr[0] 拿到的 40px 不一样！！！

**Comment by jzsn2018** [comment]
> > > 
> > 
> > 
> > 看props 我们传递的 padding 应该是这种， padding: "40px 40px 20px 32px" 通过 “ ” 进行拆分得到paddingArr数组 [40px,40px, 20px,32px]，这时候赋值的时候应该是通过 paddingArr[0] 去获取的padding值才能拿到。
> > 但是代码里面是通过 padding[0] 去拿。 "40px 40px 20px 32px"[0] 拿到的数据是 4 和 paddingArr[0] 拿到的 40px 不一样！！！
> 
> 我明白了，这应该是写错了，你可以提一个pr，或者我可以帮忙提交一个pr

等我下班提一个PR
