### ISSUE TITLE
uni-popup type='buttom' 时弹窗高度异常

### ISSUE THREAD

**Issue by Aliom252181** [dcloudio/uni-ui#707]
支付宝小程序导入示例，底部弹窗高度异常。
直接导入uni-popup示例，在支付宝小程序立即复现。

**Comment by 1104930159** [comment]
我也出现这样的问题了 你的解决了没

**Comment by 18148764734** [comment]
> 我也出现这样的问题了 你的解决了没

你的popup有没有更新到最新版本，我测试了一下并未复现该问题

**Comment by 18148764734** [comment]
该ISSUE由于用户未回复，暂时关闭
