### ISSUE TITLE
uni-data-picker组件的bug

### ISSUE THREAD

**Issue by lvzhenbo** [dcloudio/uni-ui#708]
1. 组件v-model的值如果为空字符串，弹出框的内容为空，目前暂未找出原因。
2. Vue规范已经明确禁止子组件改变props，但是当我按下清除按钮的时候，控制台报出子组件违规改变props的错误（有点怀疑是vue新人做的）
3. 开发终端里报出v-for没有带key的警告，vue规范里也写了v-for得带key

**Comment by canyonwan** [comment]
也不官方是怎么搞的 居然还有v-for得带key的警告  

<uni-data-picker :localdata="cityData" popup-title="请选择班级" @change="onchange" @nodeclick="onnodeclick"></uni-data-picker>
还无法显示数据

**Comment by lvzhenbo** [comment]
> 也不官方是怎么搞的 居然还有v-for得带key的警告
> 
> <uni-data-picker :localdata="cityData" popup-title="请选择班级" @change="onchange" @nodeclick="onnodeclick"> 还无法显示数据

你看看是不是给空字符串了
然后这不是重点，重点是22年6月之前的版本都是好的，然后我看提交改了一次以后就各种问题，所以我怀疑是不是一个临时工啊而且测都不测的吗

**Comment by lxqgithub** [comment]
用uni-data-picker的1.0.7版本。或者先新建uni hello.再把uni_moudles 下的uni ui 全部复制过来

**Comment by yurj26** [comment]
已经修复了，请升级下版本 [https://ext.dcloud.net.cn/plugin?id=3796](https://ext.dcloud.net.cn/plugin?id=3796)

**Comment by lvzhenbo** [comment]
> 已经修复了，请升级下版本 [ext.dcloud.net.cn/plugin?id=3796](https://ext.dcloud.net.cn/plugin?id=3796)

npm包还没有，希望能更新上去

**Comment by yurj26** [comment]
> > 已经修复了，请升级下版本 [ext.dcloud.net.cn/plugin?id=3796](https://ext.dcloud.net.cn/plugin?id=3796)
> 
> npm包还没有，希望能更新上去

可以先临时替换文件，npm包是定期更新的。
