### ISSUE TITLE
uni-fab icon 附加自定义代码

### ISSUE THREAD

**Issue by blackWins** [dcloudio/uni-ui#710]
增加 uni-fab 图标自定义属性
文件 uni-fab.vue 
第36行属性 `type` 改为` :type="styles.icon"`。
修改后：
```
<uni-icons
 class="fab-circle-icon" 
:type="styles.icon" //修改位置
:color="styles.iconColor" size="32"
:class="{'uni-fab__plus--active': isShow && content.length > 0}">
</uni-icons>
```

第111行`styles`增加 `icon`字段。
修改后：

```
styles: {
		color: '#3c3e49',
		selectedColor: '#007AFF',
		backgroundColor: '#fff',
		buttonColor: '#007AFF',
		iconColor: '#fff',
		icon:'plusempty'//新增字段
}
```
![image](https://user-images.githubusercontent.com/34080651/225202912-6d9328f2-2b02-4df2-adf4-4204f4b653b5.png)

**Comment by zhuddan** [comment]
你好，我有个疑问想请教一下。我今天无论从插件市场下载uni-ui 、使用npm下载的@dcloudio/uni-ui或者使用`hbuilder`创建新的uni-ui模板项目中的源代码中，`<uni-fab/> `组件中的`<uni-icons/>`的type属性是的`plusempty`，并不是`style.icon`，下面是截图
- uni-ui项目实例截图
![image](https://user-images.githubusercontent.com/32126992/228771421-23225d4d-053f-499f-bc74-4649cf5b3b04.png)
![image](https://user-images.githubusercontent.com/32126992/228771485-9d2d3986-9a22-4808-aebb-d69274bd9ad3.png)
- npm 下载的node_modules中
![image](https://user-images.githubusercontent.com/32126992/228771740-1e63f060-e9ab-45bf-ad4e-4b0915504ef9.png)
![image](https://user-images.githubusercontent.com/32126992/228771787-e8289e46-04b4-4f8c-a0d4-c3cfdaaf0dfb.png)
