### ISSUE TITLE
uni-datetime-picker 在pc端报错 Cannot read properties of undefined (reading 'next')

### ISSUE THREAD

**Issue by 13100667380** [dcloudio/uni-ui#715]
在浏览器开发调试的时候，把尺寸设置为ipad的时，点击uni-datetime-picker组件就会报错 Cannot read properties of undefined (reading 'next')且样式也有点小问题，改为手机尺寸时就不会报错

**Comment by zhenyuWang** [comment]
示例项目测试未复现该问题，如确认组件问题，请提供详细信息（vue2版本，哪个浏览器）及复现步骤，如有必要，提供下测试工程，谢谢

**Comment by zhenyuWang** [comment]
长时间未响应，问题暂时关闭；
若后续依然有问题，可 reopen 该 issue。
