### ISSUE TITLE
uni-swipe-action引入组件后编译正常，但微信小程序中直接报错

### ISSUE THREAD

**Issue by Jen0** [dcloudio/uni-ui#72]
系统win10

**Comment by Jen0** [comment]
使用vue-cli搭建的项目，package.json显示
`
dependencies：{
 "@dcloudio/uni-ui": "^1.0.4"
}
`
引入方式如下：
`
import { uniSwipeAction } from '@dcloudio/uni-ui';
export default {
   components: {
      uniSwipeAction
   }
}
`
然后编译成功，微信小程序开发工具报错如下：
`
VM369:1 ./node-modules/@dcloudio/uni-ui/lib/uni-swipe-action/uni-swipe-action.wxml
./index.wxs not found from ./node-modules/@dcloudio/uni-ui/lib/uni-swipe-action/uni-swipe-action.wxml
> 1 | <wxs src="./index.wxs" module="swipe"></wxs>
    | ^
  2 | <view class="uni-swipe_content">......
`

**Comment by Jen0** [comment]
```
VM369:1 ./node-modules/@dcloudio/uni-ui/lib/uni-swipe-action/uni-swipe-action.wxml
./index.wxs not found from ./node-modules/@dcloudio/uni-ui/lib/uni-swipe-action/uni-swipe-action.wxml

1 | <wxs src="./index.wxs" module="swipe"></wxs>
    | ^
  2 | <view class="uni-swipe_content">
```

**Comment by Jen0** [comment]
请问是不是我引入姿势不对？

**Comment by aydfe** [comment]
同问，一样的错误

**Comment by mehaotian** [comment]
cli 是什么版本  ？使用最新的 cli 、uni-ui ,uni-ui 目前最新版本是 1.0.7 。

**Comment by mehaotian** [comment]
确保使用 2.3.8 以上的 HBuilderX , 使用最新nvue-uni-ui分支下代码,或者 npm 安装最新uni-ui(1.0.9+)。

**Comment by 662** [comment]
npm安装的`"@dcloudio/uni-ui": "^1.1.0"`编译到APP要报错，和楼主同样的错误。

**Comment by msdog** [comment]
![image](https://user-images.githubusercontent.com/34001318/75403690-5dd2d300-5943-11ea-807c-a45029c17438.png)
怎么编译位置跑到外层目录去了? 复制过来就没问题了, 赶紧修复一下
