### ISSUE TITLE
点击清除按钮无法清空父组件绑定的值

### ISSUE THREAD

**Issue by MCZeroDu** [dcloudio/uni-ui#725]
![image](https://user-images.githubusercontent.com/48675747/227086951-77815218-68ee-4af4-9ccf-0b3832de08da.png)

**Comment by zqy233** [comment]
因为源码是这样的，先调用clear方法，再清空值，我觉得是想把清空前的值交给用户
```
clear() {
	this.$emit("clear", {
	value: this.searchVal
	})
	this.searchVal = ""
},
```

**Comment by qinshige** [comment]
既然是清空操作 应该把空值反馈给父组件，而不是把清空之前的值反馈给父组件；源码把 this.searchVal = ""  放到了 this.$emit 后面，searchVal 值得通过了 watch 监听通知父组件的。

![image](https://user-images.githubusercontent.com/48675747/227135443-060838bf-cad1-4b5d-a83e-515957a0e421.png)

**Comment by 18148764734** [comment]
感谢反馈，现已修复，请到插件市场更新！
