### ISSUE TITLE
uni-easyInput组件的primaryColor问题

### ISSUE THREAD

**Issue by rmd1710714107** [dcloudio/uni-ui#727]
![image](https://user-images.githubusercontent.com/38684466/227784498-709cfef9-6b9e-4b5d-8bd3-c3c48e752e12.png)
![image](https://user-images.githubusercontent.com/38684466/227784855-b3e84d7a-d26a-470a-8a4e-6a68c48ca469.png)
primaryColor作为props的参数可以由用户自定义，但是文档中并未标出，而且由于primaryColor的颜色用在了style里，导致改变￥uni-primary的值后无法再easyinput中生效。
希望官方能修复这个bug

**Comment by 18148764734** [comment]
primaryColor现能正常使用,同时也在文档中标出。PrimaryColor确实是用在了style里面，但是并不存在uni-primary这个变量，请检查变量名是否有误
