### ISSUE TITLE
uni.startPullDownRefresh() 在h5页面只会触发一次，success和complete都执行了，但是onPullDownRefresh里面的方法没有执行

### ISSUE THREAD

**Issue by zhangyq233** [dcloudio/uni-ui#73]
uni.startPullDownRefresh() 在h5页面只会触发一次，success和complete都执行了，但是onPullDownRefresh里面的方法没有执行

**Comment by javascriptchen** [comment]
你是不是生命周期写错了，onPullDownRefresh是正常的啊

**Comment by zhangyq233** [comment]
> 你是不是生命周期写错了，onPullDownRefresh是正常的啊

我描述的不够准确  我先关闭 到时候上传demo 并 描述清楚在上来反馈。  之类问题 在dcloud社区也有很多人反应，有时间 你也可以搜一下。  谢谢
