### ISSUE TITLE
uni-datetime-picker 日期选择器面板是否能直接显示，不用任何事件。

### ISSUE THREAD

**Issue by 851091009** [dcloudio/uni-ui#734]
找了其它框架的示例：
![微信截图_20230408093207](https://user-images.githubusercontent.com/8460036/230697557-38b162a3-e981-4d0f-8345-9315aadb7dfd.png)

**Comment by zhenyuWang** [comment]
[uni-calendar](https://uniapp.dcloud.net.cn/component/uniui/uni-calendar.html) 是否满足需求
