### ISSUE TITLE
datetime-picker

### ISSUE THREAD

**Issue by sen4116** [dcloudio/uni-ui#737]
设置为默认值后，第一次点击修改时间，开始时间没有被修改
默认当前时间
![image](https://user-images.githubusercontent.com/61816026/233032958-5ab698f0-ce9e-4112-8436-e3cea88086b6.png)
修改当前时间
![image](https://user-images.githubusercontent.com/61816026/233033262-06dfe67f-299d-40f4-aa19-3cfa21ba69e6.png)
选中的样式有了，但是开始时间没有被修改

**Comment by sen4116** [comment]
watch监听的值没有被改变
![image](https://user-images.githubusercontent.com/61816026/233033852-bf7e00c1-8e24-4b26-a6c2-1afddaef7579.png)

**Comment by zhenyuWang** [comment]
2.2.22 版本未复现该问题，如确认非版本问题，详细描述下复现步骤，如有必要提供下测试工程，谢谢

**Comment by sen4116** [comment]
![image](https://user-images.githubusercontent.com/61816026/233249279-f14e3738-6e37-4f30-bc5a-b6b13192175a.png)

**Comment by sen4116** [comment]
第一步：设置 range为默认当天日期
mounted(){
  range = ['2023-04-20','2023-04-20']
}
第二步：修改时间
![image](https://user-images.githubusercontent.com/61816026/233270560-286115b5-7926-450b-938f-01b5d5742b5d.png)
将开始选择时间
这样就会发现开始时间没有被修改还是2023-04-20

**Comment by sen4116** [comment]
> 2.2.22 版本未复现该问题，如确认非版本问题，详细描述下复现步骤，如有必要提供下测试工程，谢谢

你看看

**Comment by sen4116** [comment]
![image](https://user-images.githubusercontent.com/61816026/233293548-d80b103d-0f49-447e-aa19-ee4fe9e3e116.png)
![image](https://user-images.githubusercontent.com/61816026/233293650-0a468a54-b346-406b-ac22-571bf7042f0a.png)
![image](https://user-images.githubusercontent.com/61816026/233293741-2ac85090-ba67-4624-a2b9-2f97168467ee.png)
左右两侧同步数据有问题

**Comment by zhenyuWang** [comment]
问题复现，感谢反馈，后续修复会在该贴回复

**Comment by sen4116** [comment]
> 问题复现，感谢反馈，后续修复
其实type 为 daterang和 datetimerang 一样有这样的问题

**Comment by zhenyuWang** [comment]
2.2.23 已修复

**Comment by sen4116** [comment]
> 2.2.23 已修复
不行啊，问题还是在呢

**Comment by sen4116** [comment]
> 2.2.23 已修复
不行啊，问题还是在呢

**Comment by sen4116** [comment]
![image](https://user-images.githubusercontent.com/61816026/236129045-aba17728-01c9-4b32-8370-554d96bea7c0.png)
修复的并不是我这个问题

> 2.2.23 已修复

**Comment by zhenyuWang** [comment]
2.2.25 再试下
