### ISSUE TITLE
uni-calendar: monthSwitch事件错误

### ISSUE THREAD

**Issue by he1q** [dcloudio/uni-ui#740]
切换月份后，点击回到今日触发的monthSwitch事件是原来的年月而非今日的年月

**Comment by gl716** [comment]
![image](https://github.com/dcloudio/uni-ui/assets/38275616/03050372-1d45-4036-a59d-d11c8e51da65)
我把画红色圈的代码挪下来就好了，基本思路就是点击回到今日后，先初始化日历，然后再触发monthSwitch。

**Comment by 18148764734** [comment]
现版本已修复，感谢你的贡献！
