### ISSUE TITLE
uni-easyinput有大量警告输出

### ISSUE THREAD

**Issue by zhongzhifa** [dcloudio/uni-ui#747]
![image](https://user-images.githubusercontent.com/25548250/236742328-92365b7c-225d-423a-9c35-c4f8898798b4.png)

[Vue warn]: Component emitted event "keyboardheightchange" but it is neither declared in the emits option nor as an "onKeyboardheightchange" prop. __WARN

![image](https://user-images.githubusercontent.com/25548250/236742576-18161126-64df-4b59-b749-e7edb769c4e2.png)

判断应该是没有声明emit

**Comment by yurj26** [comment]
请升级下版本，已经修复了。

**Comment by zhongzhifa** [comment]
> 请升级下版本，已经修复了。

在哪里升级呢？我看插件市场和npm都还是1.4.27（2023-04-23）版本
