### ISSUE TITLE
uni-popup连续打开，必须setTimeout 300ms，否则不会显示

### ISSUE THREAD

**Issue by zhongzhifa** [dcloudio/uni-ui#749]
300ms是看源码得来的，什么时候修复一下？或者在文档说明一下，踩坑了

**Comment by yurj26** [comment]
什么平台？

**Comment by zhongzhifa** [comment]
![image](https://github.com/dcloudio/uni-ui/assets/25548250/0f413eb3-4f19-402a-a09c-b9611d7abf65)
从源码看，应该是不区分任何平台的，都是300ms内不能重复打开

**Comment by 18148764734** [comment]
感谢反馈，确实是发现了这个问题，我排查一下设置该定时器的原因
