### ISSUE TITLE
popup组件 打开之后，被遮住的页面 滚动事件还是有效的，请问是否能禁用

### ISSUE THREAD

**Issue by zhangyq233** [dcloudio/uni-ui#75]
popup组件 打开之后，被遮住的页面 滚动事件还是有效的，请问是否能禁用

**Comment by zhetengbiji** [comment]
如果想阻止弹出层的滚动，可以在遮罩层监听touchmove事件同时阻止事件冒泡和默认行为：``` <view class="mask" @touchmove.stop.prevent="moveHandle"></view>```

**Comment by zhangyq233** [comment]
> 如果想阻止弹出层的滚动，可以在遮罩层监听touchmove事件同时阻止事件冒泡和默认行为：` <view class="mask" @touchmove.stop.prevent="moveHandle"></view>`

感谢  官方最新的也解决了这个bug了
