### ISSUE TITLE
uni-data-select 属性没有国际化支持吗？

### ISSUE THREAD

**Issue by zhaojiede** [dcloudio/uni-ui#750]
uni-data-select 组件的 label、placeholder和emptyText 属性不支持国际化吗

**Comment by 18148764734** [comment]
除了iOS date 类型的 picker 因系统限制无法设置国际化，其他都是可以国际化的，详细请查看
[国际化](https://uniapp.dcloud.net.cn/tutorial/i18n.html#vue%E7%95%8C%E9%9D%A2%E5%92%8Cjs%E5%86%85%E5%AE%B9%E7%9A%84%E5%9B%BD%E9%99%85%E5%8C%96)
