### ISSUE TITLE
uni-datetime-picker 日期组件绑定的日期更新了，组件面板还是显示之前选中的日期

### ISSUE THREAD

**Issue by freezyh** [dcloudio/uni-ui#754]
使用日期组件初始化的时候，日期显示初始化的字段，当通过组件日期以后，重置了日期字段的值，再次打开日期组件，组件默认显示的是之前的值并非重置的值，没有达到更新的状态

**Comment by 18148764734** [comment]
是否能提供一个问题工程？什么叫当通过组件日期以后？
