### ISSUE TITLE
uni-ui下包含Input输入框的组件，建议增加enableNative属性配置

### ISSUE THREAD

**Issue by semdy** [dcloudio/uni-ui#758]
uni-ui下包含Input输入框的组件，建议增加enableNative属性配置，在android下input被聚集时文字会消失。
参考文档[https://opendocs.alipay.com/mini/component/input](https://opendocs.alipay.com/mini/component/input)

**Comment by 18148764734** [comment]
我测试了一下在支付宝小程序上面的android，并不会复现该问题。我搜了一下支付宝社区，关于这个enableNative属性他们也没有进行详细的说明，后续如果他们更新了文档我会查看并考虑添加该属性到编译到支付宝端
