### ISSUE TITLE
使用 uni-popup-dialog组件报Component is not found in path "uni_modules/uni-popup/components/uni-popup-dialog/uni-popup-dialog" (using by "pages/xx/xx")

### ISSUE THREAD

**Issue by jiaotianqi** [dcloudio/uni-ui#766]
错误信息:

<img width="559" alt="image" src="https://github.com/dcloudio/uni-ui/assets/30230931/182319b9-5647-4051-91f6-01d7181bd317">

描述:
使用工具 HBuiderx工具,通过插件市场导入uni-popup 弹出层 https://ext.dcloud.net.cn/plugin?name=uni-popup 
代码按照下边截图直接使用,发现单独使用uni-popup层就没问题,里边使用 uni-popup-dialog uni-popup-share 都不行
 
<img width="747" alt="image" src="https://github.com/dcloudio/uni-ui/assets/30230931/0dc38370-ca73-4fda-a0dd-5d6d087ff21f">

**Comment by jiaotianqi** [comment]
补充:用 浏览器发布就可以正常弹框,放到微信开发者工具中就不行了

**Comment by jianfei1991** [comment]
出现了同样的问题，我是通过更新node和npm版本解决的

**Comment by 18148764734** [comment]
删除后，重新下载一下插件，看样子是组件没有下载全
