### ISSUE TITLE
nvue 如何引用组件？

### ISSUE THREAD

**Issue by JerrySir** [dcloudio/uni-ui#77]
![image](https://user-images.githubusercontent.com/20677373/68296857-87d06300-00d0-11ea-9b91-9dca5b9fed30.png)

`
import {
    uniDrawer
} from "@dcloudio/uni-ui"
// ......
components: {
    uniDrawer
},
`

**Comment by javascriptchen** [comment]
暂时先用这种方式引入
import uniBadge from '@dcloudio/uni-ui/lib/uni-badge/uni-badge.vue'

**Comment by JerrySir** [comment]
![image](https://user-images.githubusercontent.com/20677373/68298565-ad5f6b80-00d4-11ea-8548-f975f371deec.png)

**Comment by JerrySir** [comment]
@javascriptchen

**Comment by Wangyaqi** [comment]
什么方式安装的，还是自己拷贝进去的，报错完整的截下来看看

**Comment by JerrySir** [comment]
![image](https://user-images.githubusercontent.com/20677373/68299630-08925d80-00d7-11ea-8cfa-15cbb2348520.png)

npm集成，报错完整j截图就是这些 @Wangyaqi

**Comment by Wangyaqi** [comment]
用 nvue-uni-ui 分支的

**Comment by Wangyaqi** [comment]
下面一个报错需要截图看一下你的项目里面的node_modules\@dcloudio\uni-ui\lib\uni-drawer\uni-drawer.nvue, 我这新安装的没问题

**Comment by JerrySir** [comment]
![image](https://user-images.githubusercontent.com/20677373/68300091-0f6da000-00d8-11ea-8043-cdf75aa0edf1.png)


![image](https://user-images.githubusercontent.com/20677373/68300126-21e7d980-00d8-11ea-9f1b-b0faecfe60a6.png)


我这里没有.nvue文件

**Comment by JerrySir** [comment]
@Wangyaqi

**Comment by JerrySir** [comment]
> 页面里面自己的样式要注意符合weex规范

我如果不引用这个组件，就正常的

**Comment by Wangyaqi** [comment]
`import uniDrawer from '@dcloudio/uni-ui'` 试试这样

**Comment by JerrySir** [comment]
> `import uniDrawer from '@dcloudio/uni-ui'` 试试这样

试过了，不行

**Comment by JerrySir** [comment]
后来是通过下载分支的 component里面的源码引入，就正常了，好像npm没有nvue的分支？
