### ISSUE TITLE
列表中使用uni-number-box，删除一条数据后，下一个的数值会变成0

### ISSUE THREAD

**Issue by mengerzhuanyong** [dcloudio/uni-ui#770]
如题，在小程序环境下，列表里使用number-box，减少数量到0时，删除该条数据，会导致下一条数据的number-box的value变成0.
问题只在下一个的value是1的时候有问题，大于1的时候没有问题。

**Comment by 18148764734** [comment]
你说的列表是指用v-for+uni-number-box渲染吗，用的是哪个方式删除该条数据？shift()？

**Comment by 18148764734** [comment]
该issue由于长时间未更新，暂时关闭，后续若用户回复则重新open
