### ISSUE TITLE
uni-popup在dev时正常,build完在微信开发者工具里面调试就报错了

### ISSUE THREAD

**Issue by peachtang** [dcloudio/uni-ui#772]
![image](https://github.com/dcloudio/uni-ui/assets/22881737/fecb0ab3-505e-43ae-a2b3-8018170420eb)
我用的vue3定义的ref
在dev的时候能看到有open方法,然而到了build完的代码,open方法就没了,看下图:
![image](https://github.com/dcloudio/uni-ui/assets/22881737/e43f1021-675d-4b47-a313-81af6e9d5c31)

**Comment by peachtang** [comment]
<img width="578" alt="image" src="https://github.com/dcloudio/uni-ui/assets/22881737/c3bc00de-bb32-43b7-b668-25ed2806ebe8">
<img width="411" alt="image" src="https://github.com/dcloudio/uni-ui/assets/22881737/7366869c-dc5d-49ec-a4e1-8ce0df0ec8c4">
<img width="406" alt="image" src="https://github.com/dcloudio/uni-ui/assets/22881737/4785a85d-87ba-42e2-a4e9-8471014ce683">

**Comment by yurj26** [comment]
参考下该 [帖子](https://ask.dcloud.net.cn/question/168927) 的回复
