### ISSUE TITLE
vite 下如何引入 uni-ui，easycom 引入无法使用

### ISSUE THREAD

**Issue by DIVINER-CODE** [dcloudio/uni-ui#774]
问题描述：
  1，通过 npm 方式安装 "@dcloudio/uni-ui": "^1.4.28"
  2，配置了 pages.json easycom
  3，页面引入 uni-ui 组件 均 无法显示 
文件 pages.json 配置：
  "easycom": {
    "autoscan": true,
    "^uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue"
  }

**Comment by shenhao98** [comment]
`npm i -D @dcloudio/vite-plugin-uni` 下载插件

然后vite.config.ts 添加插件


import { defineConfig } from 'vite'
import uni from '@dcloudio/vite-plugin-uni'
export default defineConfig({
  plugins: [
    uni()
  ]
})

**Comment by inksnowhailong** [comment]
但是我运行到小程序时候 将会出现各种资源报错  node_modules并没在小程序那边生成

**Comment by shenhao98** [comment]
![image](https://github.com/dcloudio/uni-ui/assets/55233979/283bf212-ce44-4e7c-891f-ae736fb2728c)
打开小程序点击了工具 -> 构建npm没有

**Comment by shenhao98** [comment]
> 但是我运行到小程序时候 将会出现各种资源报错 node_modules并没在小程序那边生成

![image](https://github.com/dcloudio/uni-ui/assets/55233979/13417e97-f82b-4efd-a924-74deeafa2810)
打开小程序点击了工具 -> 构建npm没有

**Comment by 18148764734** [comment]
注意 cli 项目默认是不编译 node_modules 下的组件的，导致条件编译等功能失效 ，导致组件异常 需要在根目录创建 vue.config.js 文件 ，增加 @dcloudio/uni-ui 包的编译即可正常

// vue.config.js
module.exports = {
		transpileDependencies:['@dcloudio/uni-ui']
}

**Comment by 18148764734** [comment]
如果后续还有问题，欢迎reopen后继续提问

**Comment by lanyuzx** [comment]
> 注意 cli 项目默认是不编译 node_modules 下的组件的，导致条件编译等功能失效 ，导致组件异常 需要在根目录创建 vue.config.js 文件 ，增加 @dcloudio/uni-ui 包的编译即可正常
> 
> // vue.config.js module.exports = { transpileDependencies:['@dcloudio/uni-ui'] }

vite下怎么配值

**Comment by calmliming** [comment]
@lanyuzx vite+vue3 不需要配置这个
