### ISSUE TITLE
小程序使用uni-data-picker组件报错 找不到文件

### ISSUE THREAD

**Issue by 958728656** [dcloudio/uni-ui#775]
![image](https://github.com/dcloudio/uni-ui/assets/58684907/3649c9e3-249f-4572-b7ca-79dd058c95ea)

**Comment by 18148764734** [comment]
注意 cli 项目默认是不编译 node_modules 下的组件的，导致条件编译等功能失效 ，导致组件异常 需要在根目录创建 vue.config.js 文件 ，增加 @dcloudio/uni-ui 包的编译即可正常

// vue.config.js
module.exports = {
		transpileDependencies:['@dcloudio/uni-ui']
}
