### ISSUE TITLE
对vue3+vite支持吗？

### ISSUE THREAD

**Issue by cg123456** [dcloudio/uni-ui#779]
我从官网上看到并按照其给的方式配置了，但在打包后预览微信小程序会有报错，开发时没问题，正常预览。
<img width="1250" alt="image" src="https://github.com/dcloudio/uni-ui/assets/49542520/efba53d4-e3a6-4c5d-a840-1c79c51a1106">

**Comment by 18148764734** [comment]
可以正常使用，是支持的，检查一下小程序基础库版本号
