### ISSUE TITLE
使用官方文档按照uni-ui，会导致组件引入路径问题

### ISSUE THREAD

**Issue by GlenLee** [dcloudio/uni-ui#78]
复现：
根据官方教程 npm install @dcloudio/uni-ui 安装。
然后无法使用这样的引入方式：
	import uniIcons from '@/components/uni-icons/uni-icons.vue'
	import uniBadge from '@/components/uni-badge/uni-badge.vue'
教程告诉我们要这样引入：
        import {uniBadge} from '@dcloudio/uni-ui'
        import uniListItem from  '@dcloudio/uni-ui/lib/uni-list-item/uni-list-item.vue'
但是UI组件中还是使用：（例如：uniListItem）
	import uniIcons from '@/components/uni-icons/uni-icons.vue'
导致直接报错。

**Comment by Wangyaqi** [comment]
npm安装 1.0.7 版，已经修复
