### ISSUE TITLE
uni-datetime-picker 组件

### ISSUE THREAD

**Issue by 533230** [dcloudio/uni-ui#780]
日期范围用法：给了当天的默认值 然后第一次更改时间(跨月的情况) 开始时间没有修改成功
<img width="387" alt="image" src="https://github.com/dcloudio/uni-ui/assets/15622373/37b3d59c-eaf7-4990-8c10-df1cc24eaa49">

**Comment by 18148764734** [comment]
不太明白你的意思，假设我赋值2021.02.01-2021.02.01，然后我选择了2021.03.03
以下哪种情况是你的实际结果和预期结果呢？
2021.02.01-2021.03.03
2021.03.03-2021.03.03

**Comment by 18148764734** [comment]
由于此贴暂未回复，暂时先关闭该issue
