### ISSUE TITLE
uni-search-bar 清除内容问题

### ISSUE THREAD

**Issue by xiaorui-23** [dcloudio/uni-ui#781]
`uni-search-bar` 在使用 clear 清除输入框中全部内容时出现输入框中的内容已清除，但`@clear`执行时变量依旧存在内容，页面输入框展示未出现内容。

```
<uni-search-bar v-model="searchValue" @cancel="search"></uni-search-bar>
```
### 环境说明：

- `uni-app vue3`
- 
![image](https://github.com/dcloudio/uni-ui/assets/85375465/c5218b9e-08a0-416c-b0ad-258f7c348d13)

### 编译目标平台

- 微信小程序

### `uni-ui` 下载源

- 通过 插件市场下载，`hbuilderx` 导入

### 页面及回调截图

![image](https://github.com/dcloudio/uni-ui/assets/85375465/cd0f5a35-1f17-47da-86fe-bd1168749279)
![image](https://github.com/dcloudio/uni-ui/assets/85375465/b6d3454b-754a-46f2-abe1-d0551d7617ea)

### 额外说明

通过 `cancel` 回调清除正常

**Comment by 18148764734** [comment]
在vue中，不允许子组件修改父组件的值，所以才提供了@clear方法供用户自行清除内容
