### ISSUE TITLE
 uni-search-bar 居中问题

### ISSUE THREAD

**Issue by de1ck** [dcloudio/uni-ui#787]
![image](https://github.com/dcloudio/uni-ui/assets/26627486/224c51a8-a17c-486e-b8ad-563884b44113)
默认应该是居左，但是样式默认居中

**Comment by HealerLZH** [comment]
我是显示剧中的，但是聚焦一次，后就居左回不来中间了。。。

**Comment by 18148764734** [comment]
感谢反馈，我排查跟进一下

**Comment by 18148764734** [comment]
现已修复，请进入uni_modules目录下右键对应的插件进行更新
