### ISSUE TITLE
uni-popup 删除了z-index  请问是基于什么原因 请问可以恢复吗

### ISSUE THREAD

**Issue by zhangyq233** [dcloudio/uni-ui#79]
uni-popup 删除了z-index  请问是基于什么原因 请问可以恢复吗？  不然会导致以前的某些代码设置z-index  导致现在就算打开了遮盖层 也会显示在那里

**Comment by javascriptchen** [comment]
具体说的是哪里的z-index？你可以审查元素改css啊

**Comment by mehaotian** [comment]
在下版uni-ui会修复此问题

**Comment by zhangyq233** [comment]
> 在下版uni-ui会修复此问题

弹框设置成bottom的时候  顶部会闪一下   就是那种现在顶部显示一下在移到底部的效果。 特别在app端显示特别明显。

**Comment by mehaotian** [comment]
更新 nvue-uni-ui 分支代码，h5平台修复该问题

**Comment by dnt1996** [comment]
> 更新 nvue-uni-ui 分支代码，h5平台修复该问题

为什么现在uni-popup组件还是不能设置z-index？
