### ISSUE TITLE
uni-forms validateFunction不起效

### ISSUE THREAD

**Issue by LarryHangFan** [dcloudio/uni-ui#790]
<img width="924" alt="image" src="https://github.com/dcloudio/uni-ui/assets/43339400/d3ea5610-87d3-4a8f-8d3e-d3efc70adec0">
<img width="1197" alt="image" src="https://github.com/dcloudio/uni-ui/assets/43339400/e8c26e33-028f-499c-a616-16c7790c1bc9">
问题：我拉取的hello-uniapp 项目的master，运行uni-forms validateFunction不起效，onready 调用了setRules

**Comment by LarryHangFan** [comment]
有人吗，help me

**Comment by zmm2tysu** [comment]
怎么关了？  我也遇到这个问题了
