### ISSUE TITLE
微信小程序skyline渲染模式下，uni-icon不显示

### ISSUE THREAD

**Issue by wangjieCode** [dcloudio/uni-ui#792]
<img width="1218" alt="image" src="https://github.com/dcloudio/uni-ui/assets/49115360/c15c4828-4f80-42cc-ac4c-802aedc07712">

**Comment by 18148764734** [comment]
感谢反馈，排查出问题是开启skyline后内容被顶到导航栏上面了

**Comment by 18148764734** [comment]
现正尝试修复

**Comment by 18148764734** [comment]
已更新回复，请参考楼上的问题分析
