### ISSUE TITLE
webstorm中怎么才能有uni-ui的语法提示

### ISSUE THREAD

**Issue by lwxk** [dcloudio/uni-ui#793]

**Comment by wmmhnsz** [comment]
同求

**Comment by luoshuaidev** [comment]
一直可以用, 将 node_modules/@dcloudio/uni-ui 标记目录就可以了
![image](https://github.com/dcloudio/uni-ui/assets/65377438/8e3383a2-342a-4665-b5d7-2bfa1581d66f)
![image](https://github.com/dcloudio/uni-ui/assets/65377438/d20d35af-f010-44e1-bf46-9237530a7662)
