### ISSUE TITLE
uni-file-picker 微信小程序线上环境点击无反应，微信开发工具中使用一切正常

### ISSUE THREAD

**Issue by BRETVON** [dcloudio/uni-ui#794]
如题，uni-file-picker 组件，微信开发工具中使用一切正常；但微信小程序线上环境点击无反应，无法选择图片：
`
<uni-file-picker
        ref="files" v-model="review.form.pic" :autoUpload="false" :limit="9"
	title="最多选择9张图片" disable-preview mode="grid" @select="selectFilePicker"
	@success="successFilePicker"
></uni-file-picker>
`

**Comment by wxp686** [comment]
同问，怎么解决的啊

**Comment by 18148764734** [comment]
因为微信更新了api，现版本已修复，请更新插件
