### ISSUE TITLE
您好，麻烦问一下，使用uni-ui是否能够使用自己的服务端，谢谢

### ISSUE THREAD

**Issue by JAVPHP** [dcloudio/uni-ui#797]
您好，麻烦问一下，使用uni-ui是否能够使用自己的服务端，谢谢，望作者回复一下，谢谢

**Comment by hbcui1984** [comment]
uni-ui是一个前端框架，你想服务端渲染也是可以的，但需要自己实现uni-app的服务端渲染，有些麻烦。

**Comment by JAVPHP** [comment]
![image](https://github.com/dcloudio/uni-ui/assets/48326762/9afdcec5-b390-4c5b-930e-9ad28ce02555)

**Comment by JAVPHP** [comment]
我的意思是想问根据许可协议，我们后台是否能够用自己java服务端，而不使用uniCloud提供的云服务

**Comment by JAVPHP** [comment]
> uni-ui是一个前端框架，你想服务端渲染也是可以的，但需要自己实现uni-app的服务端渲染，有些麻烦。


我的意思是想问根据许可协议，我们后台是否能够用自己java服务端，而不使用uniCloud提供的云服务

**Comment by raver** [comment]
同问。使用uni-ui时，我们后台是否能够用自己java服务端，而不使用uniCloud提供的云服务？

**Comment by 18148764734** [comment]
> 同问。使用uni-ui时，我们后台是否能够用自己java服务端，而不使用uniCloud提供的云服务？
可以
