### ISSUE TITLE
ui组件可以独立于uni-app单独开源出来

### ISSUE THREAD

**Issue by ranwawa** [dcloudio/uni-ui#8]
### 遇到的问题
在`mpvue`项目里面引入`uni-ui`
编译时报错,没有引入`sass`变量
### 错误截图如下
![image](https://user-images.githubusercontent.com/30344590/52769910-b4d57500-306c-11e9-804f-4f665afd4f1a.png)
### 期望的效果
直接把`css`样式编译到ui里面去吧
模板市场优秀的第3方模板,也可以按照规范,统一到官方ui库里面进行维护

**Comment by hulinNeil** [comment]
感谢你的建议，我们会考虑的。
