### ISSUE TITLE
打包成h5之后，在安卓6 跟安卓7.1 环境会报 异常

### ISSUE THREAD

**Issue by zhangyq233** [dcloudio/uni-ui#80]
打包成h5之后，在安卓6 跟安卓7.1 环境会报 异常
看了代码  是底层写了，不是我写的业务代码
主要在打包之后的h5   js   chunk**.js  里面 搜索 e=t.effectiveType.replace("slow-","")
报错 TypeError
Cannot read property 'replace' of undefined

不知道在哪里反馈，麻烦帮忙反应一下

![image](https://user-images.githubusercontent.com/28673757/68405034-621f8880-01ba-11ea-985c-c6189a7cf0c7.png)

**Comment by javascriptchen** [comment]
我记得一般都是某个值你没赋值，才会导致的这个错误，dev没事吗？

**Comment by mehaotian** [comment]
是使用某个组件报的错？还是框架出现了问题 ？如果框架问题到 ask 社区发帖，描述详细报错信息和平台[社区地址](http://ask.dcloud.net.cn/explore/)，[发帖指南](http://ask.dcloud.net.cn/article/35334)
