### ISSUE TITLE
uni-file-picker在安卓手机H5上选择多个图片，上传没反应，且上传最大数量只能是9个

### ISSUE THREAD

**Issue by yc0123450** [dcloudio/uni-ui#802]
在H5浏览器环境，从相册选择多张图片，苹果手机上传正常，但安卓手机没反应，控制台也没报错。上传单张图片都没问题；还有关于图片数量限制是处于什么考虑，为什么最大只能是9张。

**Comment by 18148764734** [comment]
我在手机H5上面测试了一下，并未复现你的问题，能否提供更详细的信息方便我们定位
微信上传图片限制了九张，这为了跟他们的接口一致，
而且移动设备的内存和处理能力相对较低，上传大量图片可能会占用大量系统资源，
为了不影响设备性能才限制了9张。
