### ISSUE TITLE
uni-tooltip 组件弹出内容超出屏幕

### ISSUE THREAD

**Issue by yao378186268** [dcloudio/uni-ui#803]
uni-tooltip 组件在屏幕偏右的位置时，弹出内容会超出屏幕，导致部分内容看不到，有解决的办法吗？

**Comment by 18148764734** [comment]
目前tooltip是出现在偏左下的位置，如果是偏右应该是能正常显示的，能具体描述一下吗

**Comment by yao378186268** [comment]
> 目前tooltip是出现在偏左下的位置，如果是偏右应该是能正常显示的，能具体描述一下吗

提供了复现的地址：https://gitee.com/yao-chengcheng/uni-tooltip.git

tooltip中content的内容，我给定了一个固定的宽度，当tooltip包裹的内容在屏幕最右边的时候，tooltip就会超出屏幕外面。
我当时已经换成 popup 组件应付过去了哈哈哈哈。
![Snipaste_2024-01-15_13-19-32](https://github.com/dcloudio/uni-ui/assets/84838562/c5c3608b-d211-4db0-afdd-c4b264a9300a)
![Snipaste_2024-01-15_13-18-40](https://github.com/dcloudio/uni-ui/assets/84838562/486b6740-a2b8-4c96-8fe4-bcb6043e3479)

**Comment by 18148764734** [comment]
感谢您的反馈，下版本我将尝试添加传入一个可以改变显示位置的prop属性，目前暂定：上下左右，以及对角八个方向

**Comment by 18148764734** [comment]
感谢您的反馈，现版本已添加上下左右四个方向，右键uni_modules并点击插件市场更新插件
