### ISSUE TITLE
组件库的单位px如何转为rpx来使用

### ISSUE THREAD

**Issue by WalkAlone0325** [dcloudio/uni-ui#804]
我想问问，官方的 `transformPx` 也被弃用了，还有什么方案可以，或者说转换 组件库的 px 为 rpx，在适配上出现了点问题

**Comment by LYQI2022** [comment]
同问！！！

**Comment by haliuhei** [comment]
直接改源码吧，大部分都px写死了

**Comment by 18148764734** [comment]
目前我们暂不考虑全部使用rpx作为单位，如果需要，可以手动更改为rpx
