### ISSUE TITLE
uni-badge多端样式不一一致

### ISSUE THREAD

**Issue by 1030907690** [dcloudio/uni-ui#808]
- 网页端的界面
![image](https://github.com/dcloudio/uni-ui/assets/30923090/2df41253-1308-4f67-a42d-a839be01253e)
- App的界面：
![image](https://github.com/dcloudio/uni-ui/assets/30923090/6cc6100f-8e73-4918-9b61-f9abbbf93fbe)

**Comment by 18148764734** [comment]
能否提供一下问题工程，我检查了一下官方示例编译出来没有复现你的问题

**Comment by 1030907690** [comment]
过去了几个月，现在新创建的项目已经修复了这个问题

**Comment by 1030907690** [comment]
问题出现在nvue页面，nvue是否不支持uni-badge？

**Comment by 1030907690** [comment]
问题出现在nvue页面，nvue是否不支持uni-badge？

**Comment by 1030907690** [comment]
问题工程地址： https://github.com/1030907690/uni-badge-test

**Comment by 1030907690** [comment]
问题出现在nvue页面，nvue是否不支持uni-badge？ 问题工程地址： https://github.com/1030907690/uni-badge-test







                       
Original
                       
                     

From:"HRK"< ***@***.*** &gt;;

Date:2024/1/12 18:08

To:"dcloudio/uni-ui"< ***@***.*** &gt;;

CC:"1030907690"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [dcloudio/uni-ui] uni-badge多端样式不一一致 (Issue #808)




 
能否提供一下问题工程，我检查了一下官方示例编译出来没有复现你的问题

**Comment by 18148764734** [comment]
感谢您的反馈，我验证一下

**Comment by 18148764734** [comment]
已复现该问题，现正联系同事进行排查并尝试修复
