### ISSUE TITLE
npm 更新1.0.7  uni-grid-item 改动太大了  连角标都没了

### ISSUE THREAD

**Issue by zhangyq233** [dcloudio/uni-ui#81]
npm 更新1.0.7  uni-grid-item 改动太大了  连角标都没了

**Comment by javascriptchen** [comment]
你看的是案例吧，我们没有改参数，只是改了一下案例的样式

**Comment by Zhang-Shaoqiang** [comment]
1.0.7 用v-for 后不显示，1.0.4没有问题

**Comment by javascriptchen** [comment]
> 1.0.7 用v-for 后不显示，1.0.4没有问题

是你自己的项目里用grid吗？

**Comment by mehaotian** [comment]
uni-grid 考虑到自带角标类的属性，会影响性能，所以新版本移除类额外的附加功能，只保留基础功能，角标红点之类的额外内容都交给用户自己处理。

**Comment by zhangyq233** [comment]
> uni-grid 考虑到自带角标类的属性，会影响性能，所以新版本移除类额外的附加功能，只保留基础功能，角标红点之类的额外内容都交给用户自己处理。

好的 谢谢。    请问在哪里可以看到你们的 ui的 更新记录文档。 都找不到。  导致很多都乱了。

**Comment by mehaotian** [comment]
> > uni-grid 考虑到自带角标类的属性，会影响性能，所以新版本移除类额外的附加功能，只保留基础功能，角标红点之类的额外内容都交给用户自己处理。
> 
> 好的 谢谢。 请问在哪里可以看到你们的 ui的 更新记录文档。 都找不到。 导致很多都乱了。

到插件市场，找到对应组件，可以看到更新日志

**Comment by zhangyq233** [comment]
> > > uni-grid 考虑到自带角标类的属性，会影响性能，所以新版本移除类额外的附加功能，只保留基础功能，角标红点之类的额外内容都交给用户自己处理。
> > 
> > 
> > 好的 谢谢。 请问在哪里可以看到你们的 ui的 更新记录文档。 都找不到。 导致很多都乱了。
> 
> 到插件市场，找到对应组件，可以看到更新日志

![image](https://user-images.githubusercontent.com/28673757/68557752-bdc76b80-0471-11ea-9f35-fac4efdc1296.png)
 
没有最新的更新日志

**Comment by zhangyq233** [comment]
> > > uni-grid 考虑到自带角标类的属性，会影响性能，所以新版本移除类额外的附加功能，只保留基础功能，角标红点之类的额外内容都交给用户自己处理。
> > 
> > 
> > 好的 谢谢。 请问在哪里可以看到你们的 ui的 更新记录文档。 都找不到。 导致很多都乱了。
> 
> 到插件市场，找到对应组件，可以看到更新日志，不过现在有些组件日志不是最新的，最近改动比较大，有些组件还没来得及更新，可以看nvue-uni-ui分支下，每个组件目录下的readme.md

好的 谢谢

**Comment by zhangyq233** [comment]
> > > > uni-grid 考虑到自带角标类的属性，会影响性能，所以新版本移除类额外的附加功能，只保留基础功能，角标红点之类的额外内容都交给用户自己处理。
> > > 
> > > 
> > > 好的 谢谢。 请问在哪里可以看到你们的 ui的 更新记录文档。 都找不到。 导致很多都乱了。
> > 
> > 
> > 到插件市场，找到对应组件，可以看到更新日志，不过现在有些组件日志不是最新的，最近改动比较大，有些组件还没来得及更新，可以看nvue-uni-ui分支下，每个组件目录下的readme.md
> 
> 好的 谢谢

现在是都要往 nvue-uni-ui的方向走是吗

**Comment by Zhang-Shaoqiang** [comment]
用npm安装uni-ui 1.0.7 uni-grid-item不显示  1.0.4版本正常
![image](https://user-images.githubusercontent.com/16910047/68568526-c7af9580-0496-11ea-89d6-eaed000abcd9.png)
![image](https://user-images.githubusercontent.com/16910047/68568630-14936c00-0497-11ea-9f26-9e89881f51be.png)

**Comment by Zhang-Shaoqiang** [comment]
> > 1.0.7 用v-for 后不显示，1.0.4没有问题
> 
> 是你自己的项目里用grid吗？

自己的项目使用，用的npm安装
