### ISSUE TITLE
npm包@dcloudio/uni-ui (版本号: 1.4.28)中的uni-data-picker组件无法使用

### ISSUE THREAD

**Issue by YFwillmakeit** [dcloudio/uni-ui#814]
npm包@dcloudio/uni-ui (版本号: 1.4.28)中的uni-data-picker组件无法使用。公司项目是用npm形式下载，这样导致每次都要先从插件市场下载一份uni-data-picker替换掉npm包中的，特别麻烦。能帮忙解决下这个问题吗，thank U~

**Comment by 18148764734** [comment]
现版本已经更新，感谢反馈

**Comment by 18148764734** [comment]
npm版本刚刚发布更新了，请更新一下
