### ISSUE TITLE
在移动端在日期范围选择时如果用户是想选择一天，在点击一个日期后立马去点确定，则不会触发任何change效果

### ISSUE THREAD

**Issue by terranc** [dcloudio/uni-ui#815]
https://github.com/dcloudio/uni-ui/blob/d0f68536f5ba7bd7b525abaf71fd803c4dc4b057/uni_modules/uni-datetime-picker/components/uni-datetime-picker/uni-datetime-picker.vue#L629C21-L629C21

在移动端在日期范围选择时如果用户是想选择一天，在点击一个日期后立马去点确定，则不会触发任何change效果。并且开发者也无法对这个情况做进一步的提示，比如提示用户选择截止日期或者没选截止日期则认为结束和开始是同一日期之类的。
这个问题有什么办法可以破？

**Comment by 18148764734** [comment]
感谢您的反馈，接下来我将负责验证并跟进

**Comment by 18148764734** [comment]
感谢你的反馈，现版本已添加noChange事件，当有空值时，则触发改事件

**Comment by 18148764734** [comment]
经过讨论，决定移除nochange时间，2.2.28版本之后，nochange事件移除，改为：当用户选择一天时，触发change事件并设置开始和结束为同一天

**Comment by terranc** [comment]
> 经过讨论，决定移除nochange事件，2.2.28版本之后，nochange事件移除，改为：当用户选择一天时，触发change事件并设置开始和结束为同一天

现在已经这么更新了吗？

**Comment by 18148764734** [comment]
> > 经过讨论，决定移除nochange事件，2.2.28版本之后，nochange事件移除，改为：当用户选择一天时，触发change事件并设置开始和结束为同一天
> 
> 现在已经这么更新了吗？

十分抱歉，上次对与nochange事件的添加是由于个人疏忽设计考虑不周到，十分感谢您的批评
