### ISSUE TITLE
官网错别字

### ISSUE THREAD

**Issue by kekenobug** [dcloudio/uni-ui#817]
官网>指南>组件Props 有错别字 在【官网>指南>组件Props】页面，Ctrl+F搜索‘行参’，正确应为“形参”

![image](https://github.com/dcloudio/uni-ui/assets/59693879/3d9e24c5-e8dd-4809-8d3a-0e09c51955e1)

**Comment by 18148764734** [comment]
uchart为第三方组件，请到他们的代码仓库提交ISSUES
