### ISSUE TITLE
uni-file-picker现在用的是`uni.chooseImage`，需要改用`uni.chooseMedia`

### ISSUE THREAD

**Issue by and218** [dcloudio/uni-ui#820]
[uni.chooseImage](https://uniapp.dcloud.net.cn/api/media/image.html#chooseimage):
微信小程序从基础库 2.21.0 开始， wx.chooseImage 停止维护，请使用 uni.chooseMedia 代替。

这个大概多久之后会优化？

**Comment by 18148764734** [comment]
感谢您的反馈，现版本已优化
