### ISSUE TITLE
uni-table宽度计算有错误

### ISSUE THREAD

**Issue by kokonatsuli** [dcloudio/uni-ui#822]
1. `this.root.minWidth` 只在 `mounted` 钩子中计算了一次，列变化之后并未更新。解决方案：`this.root.minWidth` 的计算转移到 `minWidthUpdate` 方法中；
2. `this.root.minWidth` 计算有错误，当只有一列时，计算结果有误。解决方案：将 `this.widthThArr` 之和转换为 `number` 类型。

```js
const selectionWidth = 0
['100', '100'].reduce((a, b) => Number(a) + Number(b)) + selectionWidth
// 200  √
['100'].reduce((a, b) => Number(a) + Number(b)) + selectionWidth
// 1000 ×
Number(['100'].reduce((a, b) => Number(a) + Number(b))) + selectionWidth
// 100 √
```

**Comment by 18148764734** [comment]
能提供一下具体的测试工程吗，是在哪个端出现的这个问题呢？

**Comment by 18148764734** [comment]
第二条测试确实是有问题，照你的方法确实可以改正，第一条BUG的列变化描述的（列变化）有点不清楚，需要提供问题工程

**Comment by 18148764734** [comment]
已修复，感谢您的反馈
