### ISSUE TITLE
uni-popup设置safe-area仍然不生效

### ISSUE THREAD

**Issue by XuJianChen1999** [dcloudio/uni-ui#823]
uni-popup设置safe-area仍然不生效，底部仍然有透明区域，即padding-bottom
<img width="594" alt="image" src="https://github.com/dcloudio/uni-ui/assets/98016891/029fcc0f-e7ec-486d-827d-40e732bbc44e">
<img width="382" alt="image" src="https://github.com/dcloudio/uni-ui/assets/98016891/5a74a9ef-3874-42da-81b1-599d0d89a069">

**Comment by 18148764734** [comment]
感谢反馈。我在这边测试的popup无法复现你的问题，
请提供更多上下文，提供复现工程，这有助于定位并解决你的问题。
是编译到哪个平台呢？HBX版本号是多少？能否提供机型信息？

**Comment by 18148764734** [comment]
在mainfest.json里面配置了吗

**Comment by 18148764734** [comment]
此issues暂时关闭，后续如果有新的进展我会负责跟进
