### ISSUE TITLE
uni-file-picker组件 绑定v-model后  选择文件后 再打印v-model并没有数据，但是视图上已经有了刚上传的文件了，请问有没有解决办法

### ISSUE THREAD

**Issue by bigProK** [dcloudio/uni-ui#824]

**Comment by Qiu-Jun** [comment]
文件选择上传组件，可以选择图片、视频等任意文件并上传到当前**绑定的服务空间**

介绍
v-model 值需要**自动上传成功后**才会绑定值，一般只用来回显数据


没理解错的话就是让你要用他的uniClound， 成功才能回显

**Comment by bigProK** [comment]
> 文件选择上传组件，可以选择图片、视频等任意文件并上传到当前**绑定的服务空间**
> 
> 介绍 v-model 值需要**自动上传成功后**才会绑定值，一般只用来回显数据
> 
> 没理解错的话就是让你要用他的uniClound， 成功才能回显

这样我就明白了，感谢您的解答 ！
