### ISSUE TITLE
通过npm安装uni-ui后，要怎么更改uni-ui提供的scss变量以便切换主题颜色?

### ISSUE THREAD

**Issue by 904317681** [dcloudio/uni-ui#825]
通过npm安装uni-ui后，要怎么更改uni-ui提供的scss变量以便切换主题颜色？
按照官网的描述@import '@/uni_modules/uni-scss/variables.scss';（链接https://uniapp.dcloud.net.cn/component/uniui/uni-sass.html  ）然后改具体变量就行了，但是npm安装的没有uni_modules文件夹。
我尝试直接引用node_modules下的变量文件，但是也不生效的，请问我需要怎么改？

**Comment by 18148764734** [comment]
注意 cli 项目默认是不编译 node_modules 下的组件的，导致条件编译等功能失效 ，导致组件异常 需要在根目录创建 vue.config.js 文件 ，增加 @dcloudio/uni-ui 包的编译即可正常

// vue.config.js
module.exports = {
		transpileDependencies:['@dcloudio/uni-ui']
}

**Comment by 18148764734** [comment]
> 大佬解决了吗

看我上面更新的回复

**Comment by jackzhujie** [comment]
@import '@dcloudio/uni-ui/lib/uni-scss/variables.scss';
$uni-primary: #5f014f;

这样写了，也不能改主题色，该怎么处理，我是用vite5搭建的

**Comment by mivvm** [comment]
src/uni.scss  下面有一个这个文件，直接修改里面的变量就行
----- 原始邮件 -----
发件人：jackzhujie ***@***.***>
收件人：dcloudio/uni-ui ***@***.***>
抄送人：mivvm ***@***.***>,  Comment ***@***.***>
主题：Re:_[dcloudio/uni-ui]_通过npm安装uni-ui后，要怎么更改uni-ui提供的scss变量以便切换主题颜色?_(Issue_#825)
日期：2024年07月22日 17点34分


@import ***@***.***/uni-ui/lib/uni-scss/variables.scss';

$uni-primary: #5f014f;
这样写了，也不能改主题色，该怎么处理，我是用vite5搭建的
