### ISSUE TITLE
uni-icons 图标缺少一个常用的 filter 漏斗

### ISSUE THREAD

**Issue by gyjcode** [dcloudio/uni-ui#826]
uni-icons 图标缺少一个常用的 filter 漏斗

**Comment by 18148764734** [comment]
好的，用作过滤条件的话，确实挺常用的，可以考虑添加

**Comment by 18148764734** [comment]
由于体积原因，uni-icons不能无限新增图标
可以通过customprefix来自定义新图标
https://uniapp.dcloud.net.cn/component/uniui/uni-icons.html#%E9%80%9A%E8%BF%87-customprefix-%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9B%BE%E6%A0%87-%E5%8D%B3%E5%B0%86%E5%BA%9F%E5%BC%83
