### ISSUE TITLE
fix(uni-data-select): 没有多选功能

### ISSUE THREAD

**Issue by David-TechNomad** [dcloudio/uni-ui#829]
fix(uni-data-select): 没有多选功能

**Comment by 18148764734** [comment]
select主要用来解决满足用户单选项的需求，如果你想进行日期多选，那可以转用uni-datetime-picker

**Comment by 18148764734** [comment]
此issues暂时关闭，后续如果有新的进展我会负责跟进

**Comment by Yalhu** [comment]
插个眼。。什么时候可以支持多选，，或者有推荐的插件吗

**Comment by PeiXiaoMeng** [comment]
> select主要用来解决满足用户单选项的需求，后续会添加多选功能，感谢反馈

@18148764734 你好，我看不是有DataCheckbox的组件吗？这个怎么又放开了，是希望实现像antd-design pc端的那种多选的效果？
![hah](https://github.com/dcloudio/uni-ui/assets/26082030/50d38a6f-ebe4-49d3-a909-1e8e4500bc9a)
![haha2](https://github.com/dcloudio/uni-ui/assets/26082030/2d4f7a75-dbb4-4fc3-bb79-37eb7b939675)

**Comment by PeiXiaoMeng** [comment]
> select主要用来解决满足用户单选项的需求，后续会添加多选功能，感谢反馈

@18148764734 你好，我看不是有DataCheckbox组件了么？
![hah](https://github.com/dcloudio/uni-ui/assets/26082030/418811cb-2c16-40ee-bbe8-b49bfdee8c67)


是希望实现一个像antd-design pc端那样的？
![haha2](https://github.com/dcloudio/uni-ui/assets/26082030/c254e805-e2ad-4c32-acda-16ee0c2e3c25)

**Comment by 18148764734** [comment]
> > select主要用来解决满足用户单选项的需求，后续会添加多选功能，感谢反馈
> 
> @18148764734 你好，我看不是有DataCheckbox组件了么？ ![hah](https://private-user-images.githubusercontent.com/26082030/325540144-418811cb-2c16-40ee-bbe8-b49bfdee8c67.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTgxMDEsIm5iZiI6MTcxNDExNzgwMSwicGF0aCI6Ii8yNjA4MjAzMC8zMjU1NDAxNDQtNDE4ODExY2ItMmMxNi00MGVlLWJiZTgtYjQ5YmZkZWU4YzY3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA3NTAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhYjQ2NTdlMTVjYTRiZmViOTBmZjc3NzgyZTE1NTI1NmQ4NTY1NTE5YjUyNmY1ZTI2ZDdjZTZmMWFmM2M1MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5YVUmFos7ILiZzYgkYu6ZWdvBsKQaihhVfMXYAFn3jA)
> 
> 是希望实现一个像antd-design pc端那样的？ ![haha2](https://private-user-images.githubusercontent.com/26082030/325540312-c254e805-e2ad-4c32-acda-16ee0c2e3c25.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTgxMDEsIm5iZiI6MTcxNDExNzgwMSwicGF0aCI6Ii8yNjA4MjAzMC8zMjU1NDAzMTItYzI1NGU4MDUtZTJhZC00YzMyLWFjZGEtMTZlZTBjMmUzYzI1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA3NTAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmN2Y1MTU1NTg5MzhmNTE1ZjZmYmU3NDQzNjE4NzdkYmRkYTg0M2U1ZmRhMTE1YWY5NGU0NzkyMmI1N2Y4OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DDmIlbIlqF67r2lPgTI5HScZFb1wvghNYPMzX_0YyYg)

是的，后续考虑添加这种多选形式

**Comment by PeiXiaoMeng** [comment]
@18148764734 你好，有时间可以看下pr，增加了多选功能，看下有啥问题没？
