### ISSUE TITLE
app端，nvue引入uni-ui报错

### ISSUE THREAD

**Issue by huanghaodong** [dcloudio/uni-ui#83]
app端，按照文档说的，引入uni-badge
![image](https://user-images.githubusercontent.com/24872469/68524040-753a7180-02fc-11ea-91ba-58b03a120c67.png)

![image](https://user-images.githubusercontent.com/24872469/68524026-22f95080-02fc-11ea-8b4a-b4e78b99ea26.png)

引入其它ui组件也会报类似错误，如uni-popup
![image](https://user-images.githubusercontent.com/24872469/68524063-e11cda00-02fc-11ea-82a6-0086091d59b0.png)

uni-ui 版本1.0.7
HBuilderX 版本2.3.7.20191024

**Comment by javascriptchen** [comment]
这样引入试试 import uniGrid from '@dcloudio/uni-ui/lib/uni-grid/uni-grid.vue'

**Comment by huanghaodong** [comment]
> 这样引入试试 import uniGrid from '@dcloudio/uni-ui/lib/uni-grid/uni-grid.vue'

试过不行。

**Comment by javascriptchen** [comment]
[#77 ]

**Comment by huanghaodong** [comment]
可以了，总结：npm不行，要用手动下载uvue-uni-ui分支
