### ISSUE TITLE
uni-datetime-picker设置type="daterange"，在抖音小程序中选择日期范围时出错

### ISSUE THREAD

**Issue by yj-liuzepeng** [dcloudio/uni-ui#834]
1. 在抖音开发者工具中，使用正常
2. 在真机上，选择日期范围，比如说选择 2024-01-28 到 2024-01-31，确认之后，input框内显示  2024-01-28 到  2024-01-28

[bug复现](https://liuzepeng.com/bug.mp4)

**Comment by 18148764734** [comment]
感谢反馈，现版本我已修复，后续有问题可在此继续反馈
