### ISSUE TITLE
1.4.29版本的npm包结构改变导致异常

### ISSUE THREAD

**Issue by julytian** [dcloudio/uni-ui#835]
1.4.8版本npm包组件的存放目录是@dcloudio/uni-ui/lib
1.4.9版本npm包组件的存放目录是没有lib目录，导致配置easycom的方式都改变，麻烦检查下

**Comment by 18148764734** [comment]
好的，感谢反馈！现在紧急修复

**Comment by 18148764734** [comment]
已修复，感谢您的反馈

**Comment by mtyuio** [comment]
> 咋解决的？等新版本吗？

他就没修复，谁知道他说的已修复是咋修复的。。。发行的 npm 包里还是 uni_modules 结构

https://www.npmjs.com/package/@dcloudio/uni-ui?activeTab=code

对于 1.4.29..33 这个版本出现问题的，可以通过这样改 pages.json 里的方式解决

```diff
-      "^uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue"
+      "^uni-(.*)": "@dcloudio/uni-ui/uni_modules/uni-$1/components/uni-$1/uni-$1.vue"
```

**Comment by 18148764734** [comment]
由于版本发布时目录设置错误，导致发布的npm包目录结构与以前不一致，现已重新修正目录结构发布并废弃上次发布的版本
