### ISSUE TITLE
uni-popup-dialog组件能不能给个属性隐藏取消按钮？

### ISSUE THREAD

**Issue by gzlboy** [dcloudio/uni-ui#837]
就像当alert用，目前有两个按钮没有必要

**Comment by 18148764734** [comment]
dialog对话框设计就是有取消按钮的（其他示例可查看elementUI也是无法隐藏取消按钮），目前用户并无过多这方面的需求，变暂时不考虑添加。如果你想要隐藏，可自行修改uni_modules下的popupdialog组件源码

**Comment by gzlboy** [comment]
其他项目基本都有alert组件的，elementUI的MessageBox就可以隐藏取消按钮呀。dialog设计初衷就有取消确认没有问题，能隐藏肯定是更好

**Comment by 18148764734** [comment]
感谢您的反馈，后续我与同事讨论一下，决定是否需要添加改功能

**Comment by 18148764734** [comment]
感谢反馈，现版本已添加该属性:showClose，请到插件市场更新插件，后续会同步更新官方文档

**Comment by gzlboy** [comment]
赞！感谢你们的开源付出！
