### ISSUE TITLE
uni-file-picker组件选择图片后返回的结果中，能不能加一个属性用于获取的图片的来源-拍照还是相册

### ISSUE THREAD

**Issue by veryredscarf** [dcloudio/uni-ui#838]
希望官方能在uni-file-picker组件的select回调函数返回结果中，加一个属性用于判断图片的来源(相册还是拍摄)，非常谢谢！

**Comment by 18148764734** [comment]
感谢您的反馈，已接受该issue，后续尝试在回调函数返回的参数中添加返回的文件来源。

**Comment by 18148764734** [comment]
目前已经提交添加uni-file-picker属性的PR，预计下版本发布时会带上，
但由于各家小程序的暂不支持返回该属性，所以预计仅在app端生效

**Comment by Joslyn-Chen** [comment]
我的方法是在choose()用showActionSheet，自己做个选择界面，用type区分，再调用chooseFiles(type)，最后在chooseFileCallback里，把type放在filedata里面。效果感觉相差不大。
