### ISSUE TITLE
选日期范围时可否限制所选日期跨度为多少天?

### ISSUE THREAD

**Issue by jinzong8** [dcloudio/uni-ui#842]
比如银行查询历史账单时, 只允许查询跨度为90天内的数据，  但是起始日期和结束日期可以不限制。

**Comment by 18148764734** [comment]
这个需求不太符合逻辑，既然要限制跨度，为什么不 通过设置start和end方式？

**Comment by jinzong8** [comment]
> 这个需求不太符合逻辑，既然要限制跨度，为什么不 通过设置start和end方式？

需要查询的是任意90天的跨度，限制的是查询的天数，而不限制具体查哪年的。 设置start和end只能限制固定的90天。

**Comment by 18148764734** [comment]
还是不太明白你的意思，能提供几个具体场景示例说明一下吗

**Comment by jinzong8** [comment]
> 还是不太明白你的意思，能提供几个具体场景示例说明一下吗

像我顶楼说的查询银行的历史清单，你可以选几年前的时间去查，但是每次查询跨度只能限制90天，也就是说一次只能查90天的数据。
主要用在对账的场景里，目的是限制每次查询的天数（减轻服务器压力），但是不限制你要对账的日期范围。
如图是美团外卖商家版的方案： 选中一个日期后，向前和向后都是只能选30天内的日期。
![微信图片_20240220203938](https://github.com/dcloudio/uni-ui/assets/125254512/c889f329-c4a5-449c-80ac-f35216f10706)
![微信图片_20240220203949](https://github.com/dcloudio/uni-ui/assets/125254512/5760e5ce-8e0b-40f3-91eb-8936d0a28151)

**Comment by 18148764734** [comment]
此ISSUE已记录，后续考虑添加该功能，感谢反馈

**Comment by 18148764734** [comment]
> > 此ISSUE已记录，后续考虑添加该功能，感谢反馈
> 
> 这个功能有排期么，挺实用的

功能添加不难，但是需要考虑到新增属性歧义所带来的影响范围

**Comment by 18148764734** [comment]
已添加calendarClick事件。请到插件市场进行更新
