### ISSUE TITLE
uni-datetime-picker 组件点击右上角的“X”进行关闭和打开弹窗后直接点确定时候，关闭事件maskClick 没有，希望可以加上

### ISSUE THREAD

**Issue by hymsnow** [dcloudio/uni-ui#844]
uni-datetime-picker 组件点击右上角的“X”进行关闭和打开弹窗后直接点确定时候，关闭事件maskClick 没有，希望可以加上
![image](https://github.com/dcloudio/uni-ui/assets/16634708/6bfcb031-56be-42c4-80d4-ea9080b75e01)

**Comment by 18148764734** [comment]
maskClick（遮罩点击事件）是只有通过点击遮罩才会触发,但是忽略了右上角的关闭时触发，现已修复，请更新
确认事件和maskClick事件是分开的，点击“确认”触发的是change事件
