### ISSUE TITLE
uni-easyinput 期待新增左侧插槽

### ISSUE THREAD

**Issue by julytian** [dcloudio/uni-ui#847]
目前,uni-easyinput 组件只有右侧内容插槽，有些场景下需要左侧插槽。
例如有个手机号输入框，左侧有些手机号+86前缀提示文案

**Comment by 18148764734** [comment]
现版本已添加左侧插槽left，请更新，使用示例：
<uni-easyinput v-model="value" placeholder="左侧插槽" >
				<template #left></template>
			</uni-easyinput>

**Comment by 18148764734** [comment]
已更新

> > 现版本已添加左侧插槽left，请更新，使用示例： <template #left>
> 
> 麻烦更新下 npm 仓库
