### ISSUE TITLE
uni-tooltip  如何动态关闭？

### ISSUE THREAD

**Issue by zhoufanglu** [dcloudio/uni-ui#849]
目前效果是这样的
![image](https://github.com/dcloudio/uni-ui/assets/24451091/5decf9bb-61fe-45ef-b125-8a8306ed7b25)
我想点击的时候 关闭tooltip ，有什么方法吗？
api上没找到

**Comment by 18148764734** [comment]
tooltip悬浮到元素就显示，不悬浮就自动隐藏，看你这样式不应该把tooltip用到这里吧，这样一点击就没了

**Comment by 18148764734** [comment]
用户未回复，此ISSUE暂时关闭
