### ISSUE TITLE
uni-collapse 组件无法显示页面报错 TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by baiyifengyun** [dcloudio/uni-ui#850]
![image](https://github.com/dcloudio/uni-ui/assets/17200434/fdcf9c38-8efd-4f0a-8d60-34a1b5ea0f2f)
![image](https://github.com/dcloudio/uni-ui/assets/17200434/742fc28d-3d22-43dd-9ddc-f82f8bc64b04)
这个问题怎么解决？vue3环境

**Comment by baiyifengyun** [comment]
![image](https://github.com/dcloudio/uni-ui/assets/17200434/4d106b8c-f9c3-416c-9622-9fe9e2bf8f16)
我把整个uni-ui组件导入也不行

**Comment by 18148764734** [comment]
贴一下问题工程（zip压缩包

**Comment by baiyifengyun** [comment]
![image](https://github.com/dcloudio/uni-ui/assets/17200434/7a1fcfce-21d6-4046-9c86-3a2d306a0fd6)
这个是页面

**Comment by baiyifengyun** [comment]
![image](https://github.com/dcloudio/uni-ui/assets/17200434/f04a1be4-201d-4510-a588-d7203b602566)
直接使用HX导入的

**Comment by 18148764734** [comment]
还是无法复现你的问题，最好把整个工程提交上来，你新建一个hello项目或者uni-ui项目看看是否还是会复现

**Comment by baiyifengyun** [comment]
新建一个项目不会复现这个问题

**Comment by 18148764734** [comment]
> 新建一个项目不会复现这个问题

我也无法复现该问题，无法排查，最好还是把你的问题工程提供出来

**Comment by 18148764734** [comment]
> 新建一个项目不会复现这个问题

问题现在解决了吗？若还是复现请提供一下工程压缩包

**Comment by 18148764734** [comment]
此ISSUE用户长时间未更新，暂时关闭
