### ISSUE TITLE
titleBorder注释有误，应该是String类型

### ISSUE THREAD

**Issue by aqz236** [dcloudio/uni-ui#851]
https://github.com/dcloudio/uni-ui/blob/c62c9ff1679b88751de8c14984b2c7db4b73137d/uni_modules/uni-collapse/components/uni-collapse-item/uni-collapse-item.vue#L42

titleBorder注释有误，应该是String类型

			// 标题分隔线显示类型
			titleBorder: {
				type: String,
				default: 'auto'
			},

**Comment by 18148764734** [comment]
感谢反馈，现已更正，下次版本更新时会带上
