### ISSUE TITLE
Component is not found in path "node-modules/@dcloudio/uni-ui/lib/uni-data-picker/uni-data-picker

### ISSUE THREAD

**Issue by zhoufanglu** [dcloudio/uni-ui#854]
## 问题
uni-data-picker 找不到错误  
其它组件能直接使用 例如 `uni-badge`  
 报错: `Component is not found in path "node-modules/@dcloudio/uni-ui/lib/uni-data-picker/uni-data-picker`
##  配置项
版本 "@dcloudio/uni-ui": "^1.4.28",
```js
  "easycom": {
    "autoscan": true,
    "custom": {
      "^uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue"
    }
  },
```

## 补充 
- 其它组件都能使用的，就这个组件报错，奇怪了。。。
- 我看nodemodules 内也有这个组件 
- code
```js
<uni-data-picker
        :localdata="items"
        popup-title="请选择班级"
        @change="onchange"
        @nodeclick="onnodeclick"
></uni-data-picker>
```

**Comment by zhoufanglu** [comment]
> 28版本的结构不对，更新到最新版的1.5.2

我昨天晚上已经试过更新版本了， 还是报一样的错 目前是1.5.2

**Comment by 18148764734** [comment]
> > 28版本的结构不对，更新到最新版的1.5.2
> 
> 我昨天晚上已经试过更新版本了， 还是报一样的错 目前是1.5.2

能提供一下问题工程zip附件吗，我测试了一下

**Comment by zhoufanglu** [comment]
> > > 28版本的结构不对，更新到最新版的1.5.2
> > 
> > 
> > 我昨天晚上已经试过更新版本了， 还是报一样的错 目前是1.5.2
> 
> 能提供一下问题工程zip附件吗，我测试了一下

怎么给你呢？

**Comment by 18148764734** [comment]
就上传附件即可

**Comment by zhoufanglu** [comment]
[归档.zip](https://github.com/dcloudio/uni-ui/files/14507001/default.zip)
你看看行不行，`GoodsList.vue`文件, `114`行， `pages/plaza/index` 这个路径

**Comment by 18148764734** [comment]
项目运行到微信小程序能正常运行，你的是编译到小程序平台吗

**Comment by zhoufanglu** [comment]
> 测试了一下demo能正常运行，把modules文件夹删了再重新安装试试

删除了下node_modules又可以了。。不好意思打扰了。。
