### ISSUE TITLE
uni-file-picker 配置怎么不行

### ISSUE THREAD

**Issue by TryChai** [dcloudio/uni-ui#859]
![image](https://github.com/dcloudio/uni-ui/assets/30064871/b6c802c0-c45f-4807-99bd-bd62849cf486)
![image](https://github.com/dcloudio/uni-ui/assets/30064871/74a5d722-811f-4955-a7f4-0892233fdcad)
![image](https://github.com/dcloudio/uni-ui/assets/30064871/3ecd901f-fd3a-4869-a205-76931d76e40b)
说好的9宫格呢 ？自定义就不支持 9宫格吗

**Comment by 18148764734** [comment]
我测试了H5跟小程序端都是正常的，请问你是什么端？检查一下是否有样式冲突？

**Comment by 18148764734** [comment]
此issue用户长时间未回复，暂时关闭，后续希望用户能提供更多信息
