### ISSUE TITLE
编译scss变量报错

### ISSUE THREAD

**Issue by kiss-yu** [dcloudio/uni-ui#86]
```
error  in ./node_modules/@dcloudio/uni-ui/lib/uni-search-bar/uni-search-bar.vue?vue&type=style&index=0&id=b0a8ce34&lang=scss&scoped=true&

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

                border-color: $uni-border-color;
              ^
      Undefined variable: "$uni-border-color"。
```
这就就算我不写这些变量总的有默认值吧？我在src下放了uni.scss还是不行。找半天也没找到关于这个uni.scss相关的文档
```
"node-sass": {
      "version": "4.12.0",
"sass-loader": {
      "version": "7.3.1",
```

**Comment by mehaotian** [comment]
安装 sass ，在src目录下新建 uni.scss ,复制 [uni.scss](https://github.com/dcloudio/uni-ui/blob/master/src/uni.scss) 的内容

**Comment by mehaotian** [comment]
cli 项目的话，如果src下没有uni.scss ，需要手动创建文件，内容为 [https://github.com/dcloudio/uni-ui/blob/master/src/uni.scss](https://github.com/dcloudio/uni-ui/blob/master/src/uni.scss)

**Comment by Jocs** [comment]
@mehaotian 希望将这个写到文档里面。

**Comment by kiss-yu** [comment]
@mehaotian 你们文档应该忽略了其他的依赖，src下有uni.css的。重新cli构建的把nodel_modelds复制进去就好了。
