### ISSUE TITLE
uni-drawer 报错

### ISSUE THREAD

**Issue by webarn** [dcloudio/uni-ui#861]
使用cli 方式创建 vue3+vite+ts

easycom已配置
```js
"easycom": {
    "autoscan": true,
    "custom": {
      "^uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue",
    }
  },
```
版本为：1.5.2

`uni-link uni-rate`都可以正常使用，`uni-drawer uni-popup`无法使用，报错如下：
<img width="637" alt="image" src="https://github.com/dcloudio/uni-ui/assets/23495159/888016e7-a0e7-4892-8599-897934c8d760">

**Comment by 18148764734** [comment]
此ISSUE用户长时间未回复，暂时关闭
