### ISSUE TITLE
uni-popup-dialog组件设置value值双向绑定出错，需修改组件代码

### ISSUE THREAD

**Issue by peipeiyoung** [dcloudio/uni-ui#863]
经过检查发现uni-popup-dialog.vue文件中，对于vue2与vue3条件编译的那一块出现问题，导致页面上无法显示value初始值

没法上传图片。。。我去gitee上再提交一下吧

**Comment by 18148764734** [comment]
感谢反馈，我去GITEE查看一下

**Comment by 18148764734** [comment]
此ISSUE暂时，转至GITEE跟进
