### ISSUE TITLE
1.5.3版本的uni-data-select报错

### ISSUE THREAD

**Issue by jia2251** [dcloudio/uni-ui#864]
Module Error (from ./node_modules/@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib/loaders/templateLoader.js):
(Emitted value instead of an instance of Error) 

  Errors compiling template:

  :style 不支持 getOffsetByPlacement() 语法
<img width="557" alt="Snipaste_2024-03-27_16-41-29" src="https://github.com/dcloudio/uni-ui/assets/64509182/fa3e53e1-4984-4244-b96c-cfec031e827d">
在新版本1.5.3中会出现

**Comment by jia2251** [comment]
uni-ui换成1.5.2版本就正常了，node本地版本14.16.1

**Comment by 18148764734** [comment]
这个是新增的属性，你是运行到哪个端报这个错误？nvue页面？

**Comment by 18148764734** [comment]
好的感谢反馈。

**Comment by 18148764734** [comment]
现已修复，可到插件市场更新最新插件，npm 包预计周五发布
