### ISSUE TITLE
cli创建的项目vite+vue3+ts下如何引入 uni-ui

### ISSUE THREAD

**Issue by wlj0924** [dcloudio/uni-ui#867]
问题描述：
1，通过 npm 方式安装 "@dcloudio/uni-ui": "^1.5.3"
2，配置了 pages.json easycom
3，页面引入 uni-ui 组件 均 无法显示
文件 pages.json 配置：
"easycom": {
"autoscan": true,
"^uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue"
}

**Comment by hobeas** [comment]
`pages.json` 配置有误，少了一层 `custom`.
```json
{
  "easycom": {
    "autoscan": true,
    "custom": {
      "^uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue"
    }
  }
}
```

**Comment by 18148764734** [comment]
配置有误，请参考楼上回答，此ISSUE暂时关闭，后续若有问题可追问

**Comment by wlj0924** [comment]
"easycom": {
		"autoscan": true,
		"custom": {
			"^uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue"
		}
	}
发错了，这个才是我的配置

**Comment by 18148764734** [comment]
有什么报错吗

**Comment by wlj0924** [comment]
上面贴错了，这个才是我的配置
{
  "easycom": {
    "autoscan": true,
    "custom": {
      "^uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue"
    }
  }
}
使用easycom不生效，自己手动导入组件生效

**Comment by wlj0924** [comment]
无任何报错

**Comment by 18148764734** [comment]
打开node_modules目录我看看

**Comment by wlj0924** [comment]
你要看所有的还是@dcloudio里面的

**Comment by 18148764734** [comment]
uni-ui文件夹

**Comment by wlj0924** [comment]
![企业微信截图_17116944796480](https://github.com/dcloudio/uni-ui/assets/58384941/d0bbfc1f-7a46-4e26-bfce-7949d83d34df)
![企业微信截图_17116944699647](https://github.com/dcloudio/uni-ui/assets/58384941/d3b343b9-3916-42c6-a342-0f093089394f)

**Comment by 18148764734** [comment]
嗯，看着没什么问题，看看你是如何使用的

**Comment by wlj0924** [comment]
![企业微信截图_17117089359035](https://github.com/dcloudio/uni-ui/assets/58384941/785f7da4-26f3-4349-89e5-44b4ca96c7ca)
![企业微信截图_1711708947843](https://github.com/dcloudio/uni-ui/assets/58384941/3b5802b9-49ce-4bfb-9dc3-4f8b929f9331)
像是没编译成功，但是目前所有的配置都是安照官方文档来的https://uniapp.dcloud.net.cn/component/uniui/quickstart.html
还是没发现哪里有问题

**Comment by 18148764734** [comment]
方便发个问题工程吗

**Comment by PT600** [comment]
node_modules/@dcloudio/uni-ui/的目录下没有lib目录了，但是有个uni_modules目录

**Comment by wlj0924** [comment]
暂时不方便发

**Comment by 18148764734** [comment]
> node_modules/@dcloudio/uni-ui/的目录下没有lib目录了，但是有个uni_modules目录

更新到1.5.5

**Comment by 18148764734** [comment]
> 暂时不方便发

那尝试删除node_modules并重新安装试试

**Comment by wlj0924** [comment]
更新到1.5.5，还是有lib目录

**Comment by 18148764734** [comment]
> 更新到1.5.5，还是有lib目录

有lib目录才是正常的

**Comment by wlj0924** [comment]
执行npx @dcloudio/uvm@latest 更新依赖就可以了
