### ISSUE TITLE
1.9.0版本，在vue3版本使用 uni-popup-dialog 设置了modelValue值页面上不显示bug

### ISSUE THREAD

**Issue by bianleiming** [dcloudio/uni-ui#868]
原因是，vue3使用的是modelValue，但create初始化时，this.val还是使用的value赋值，没有使用modelValue进行赋值
prop：
![Snipaste_2024-03-29_10-18-42](https://github.com/dcloudio/uni-ui/assets/33416526/c58666e8-0fd6-4de4-9762-9ba00cfc8c23)
create：
![Snipaste_2024-03-29_10-18-54](https://github.com/dcloudio/uni-ui/assets/33416526/eb8393e8-eb9b-4433-ad1a-fb29a4d31f8a)

**Comment by 18148764734** [comment]
该问题已修复，插件市场28日已更新，npm预计今天晚点时候发布
