### ISSUE TITLE
error    @import '~@/uni.scss';  not found

### ISSUE THREAD

**Issue by Darren-chenchen** [dcloudio/uni-ui#87]

**Comment by Darren-chenchen** [comment]
![image](https://user-images.githubusercontent.com/16269032/68649309-5555b880-055d-11ea-9780-91adbc578583.png)

**Comment by Darren-chenchen** [comment]
![image](https://user-images.githubusercontent.com/16269032/68649324-643c6b00-055d-11ea-9e6b-482c117e8755.png)

**Comment by mehaotian** [comment]
下载最新版本，uni.sscc 已经框架引入，看不到这段代码了。
