### ISSUE TITLE
npm 模式下找不到 lib

### ISSUE THREAD

**Issue by qiuqfang** [dcloudio/uni-ui#870]
v1.5.4版本中
![image](https://github.com/dcloudio/uni-ui/assets/39936160/eef85d1d-24b3-4b91-8570-27ede3a8f43d)
![image](https://github.com/dcloudio/uni-ui/assets/39936160/8ed1e676-674e-4026-ac1d-a3b3a5b6c617)

**Comment by 18148764734** [comment]
感谢反馈，更新到1.5.5版本即可
