### ISSUE TITLE
这个uni-icon的大小， 在微信小程序上怎么是12 ？？

### ISSUE THREAD

**Issue by banrenma** [dcloudio/uni-ui#871]
![image](https://github.com/dcloudio/uni-ui/assets/7576010/953591bc-ab00-412c-94ab-f527bcdc434d)
代码：
![image](https://github.com/dcloudio/uni-ui/assets/7576010/e4fbd6f5-5a15-4bfa-b8b5-85fbc86b61bd)

**Comment by 18148764734** [comment]
我测试是正常的。你检查下有没有什么样式覆盖
![Uploading Xnip2024-04-01_17-36-19.jpg…]()

**Comment by 18148764734** [comment]
![Uploading 123.jpg…]()

**Comment by 18148764734** [comment]
![123](https://github.com/dcloudio/uni-ui/assets/119110706/c510aa0d-e761-4697-86ce-b32d2b5e2469)

**Comment by banrenma** [comment]
> ![123](https://private-user-images.githubusercontent.com/119110706/318671544-c510aa0d-e761-4697-86ce-b32d2b5e2469.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDIxODcsIm5iZiI6MTcxMjA0MTg4NywicGF0aCI6Ii8xMTkxMTA3MDYvMzE4NjcxNTQ0LWM1MTBhYTBkLWU3NjEtNDY5Ny04NmNlLWIzMmQyYjVlMjQ2OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQwNzExMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGYyMDU3NmU1MmExY2E5YTE5NWZmODdhMTlmNDc3OTRjYmUzZjg3ODBkYWFiN2MwOWYxZGNkODFhZWQwNmNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xBZAEezcZCPl9fEGJWG_moVGWxeHXvmJAq5Hd6esWG8)

是text上的父节点uni-icons  48x12 ， text节点的大小是正常的

**Comment by banrenma** [comment]
uni-icons 高度只有12px， 导致flex 布局的， 没居中

**Comment by 18148764734** [comment]
> uni-icons 高度只有12px， 导致flex 布局的， 没居中

我父节点是正常的。你发个简单复现的代码我看看

**Comment by 18148764734** [comment]
此issue用户长时间未回复，暂时关闭
