### ISSUE TITLE
在设置start和end限制范围时，开始日期等于start日期时，开始时间的选择，不能低于结束时间，否则会不生效。

### ISSUE THREAD

**Issue by chenwenchao-mr** [dcloudio/uni-ui#878]
复现步骤：
1.假设范围设置start和end为2024-04-16 ~ 2024-04-30
2.此时日期选中2024-04-16 ~ 2024~04~20
3.开始时间设置为15:20,结束时间设置为12:00,
4.确认后，开始时间未能生效，会回到上一次的值。
![image](https://github.com/dcloudio/uni-ui/assets/129763015/702244b6-904a-4144-b362-d68b20a0ed2c)
![image](https://github.com/dcloudio/uni-ui/assets/129763015/4b5424ff-c3b9-404b-9139-12098ea5a1ee)
![image](https://github.com/dcloudio/uni-ui/assets/129763015/a25f57c4-f11e-4530-b0ea-28881ee98207)

**Comment by 18148764734** [comment]
确实是复现了该问题。感谢反馈，我排查一下

**Comment by chenwenchao-mr** [comment]
嗯啊，希望能尽快解决。其实还有一个问题，就是在小程序中使用，在真机上，弹框的唤起太慢，有比较明显的卡顿现象。

**Comment by 18148764734** [comment]
> 嗯啊，希望能尽快解决。其实还有一个问题，就是在小程序中使用，在真机上，弹框的唤起太慢，有比较明显的卡顿现象。

日历的目前性能还不太好，后续需要优化

**Comment by 18148764734** [comment]
> 刚刚测出来是开始时间的时分秒被默认设置为了现在时间才会导致这个问题，你应该是直接通过Data.now设置的吧，now指向的时分秒就是当前的时分秒，给我看看你的开始和结束时间

**Comment by chenwenchao-mr** [comment]
![image](https://github.com/dcloudio/uni-ui/assets/129763015/957ce3da-c195-484f-881b-3da05171c309)
![image](https://github.com/dcloudio/uni-ui/assets/129763015/54c91666-5ffd-4518-956c-bd4c299e1547)

**Comment by 18148764734** [comment]
用法错了，你这个限制到的是具体的时分秒，所以才导致了这个问题把start的时分秒改为00:00:00

**Comment by chenwenchao-mr** [comment]
意思是start的时间，必须是00:00:00吗···

**Comment by 18148764734** [comment]
是的
