### ISSUE TITLE
引入文件报错

### ISSUE THREAD

**Issue by codeLittleNewbie** [dcloudio/uni-ui#88]
不知道为何(这里我只写了一个组件,其他组件也是一样)
  import uniNumberBox	 from "@dcloudio/uni-ui/lib/uni-number-box/uni-number-box.vue";
正常导入组件,时好时不好,

Cannot read property 'call' of undefined"

一报错就是这个错误,非常头疼,不知是否有解决方案

**Comment by mehaotian** [comment]
什么情况下会出现问题 ？ 修改保存编译的时候，还是第一次运行的报错 ？

**Comment by mehaotian** [comment]
长时间未回复，issues 将关闭，如还有问题，请重新打开
