### ISSUE TITLE
怎么遮罩navbar和tabbar

### ISSUE THREAD

**Issue by luotingv1** [dcloudio/uni-ui#89]
怎么遮罩navbar和tabbar

**Comment by zhetengbiji** [comment]
https://ext.dcloud.net.cn/plugin?id=953

**Comment by wakaryry** [comment]
最好的方法就是 navbar和tabbar全部自定义。全部使用自己的就是控制的。

我就是全部使用自己的。

**Comment by mehaotian** [comment]
uni-ui 中组件暂时不支持遮盖原生组件，你参考上面的回答
