### ISSUE TITLE
uni-notice-bar 组件会偶然报错Cannot read properties of null (reading 'width')

### ISSUE THREAD

**Issue by wode0weiyi** [dcloudio/uni-ui#899]
uni-notice-bar 组件会偶然报错Cannot read properties of null (reading 'width')；查看源码，发现有使用到wx.createSelectorQuery方法,有概率会导致取不到元素值

**Comment by GRCmade** [comment]
能帮助我们查找吗，给出一个复现场景

**Comment by GRCmade** [comment]
长时间没有回复，如果之后有消息可以重新打开
