### ISSUE TITLE
希望uni-list-item增加右侧slot

### ISSUE THREAD

**Issue by FontEndArt** [dcloudio/uni-ui#9]
uni-ui/packages/uni-list-item/uni-list-item.vue

目前右侧只有角标/右箭头/Switch

希望在右侧增加一个可以自定义样式的slot

**Comment by zhangyq233** [comment]
赞成 现在也需要用到

**Comment by FontEndArt** [comment]
> 赞成现在也需要用到

目前我是在单独项目中重写了item  通过slot实现   在等官方更新

**Comment by jbasttdi** [comment]
实在太需要在右侧显示文字，最好可以在右侧上，中，下位置都可以显示文字

**Comment by Wangyaqi** [comment]
已添加，提交到了github
