### ISSUE TITLE
目前这个支持 ts 引入么

### ISSUE THREAD

**Issue by canbefree** [dcloudio/uni-ui#90]

**Comment by Wangyaqi** [comment]
cli创建的ts默认项目吗

**Comment by canbefree** [comment]
嗯, cli创建的默认项目

**Comment by Wangyaqi** [comment]
可以用，引用的时候注意引到具体vue文件

**Comment by kabeiaaa** [comment]
请教一下，怎么使用呢？我在ts页面引入，还是会报 script 节点必须使用 lang="ts"

**Comment by mehaotian** [comment]
需要在 script 标签上声明 lang="ts" `<script lang="ts">`

**Comment by mdy999** [comment]
这一定要引用到具体文件嘛，有没有简洁的按需引入方法呢
