### ISSUE TITLE
uni-nav-bar h5 内嵌到app 里面 苹果手机 高度失效

### ISSUE THREAD

**Issue by xaiodi** [dcloudio/uni-ui#911]
刚开始打开app 是正常的，完了切入后台一个半小时后，在进入会出现
错误截图
<img width="511" alt="image" src="https://github.com/dcloudio/uni-ui/assets/33322734/f1b02a62-13d7-4b60-8511-4fdd88db8e67">

正确的截图

<img width="451" alt="image" src="https://github.com/dcloudio/uni-ui/assets/33322734/1a184ee9-82bc-40c0-a30a-0fc8c41aba0d">

**Comment by GRCmade** [comment]
你好，这个问题uniui侧无法解决，我们没法控制平台后台做了什么。你可以尝试一下重新加载bar试一下
