### ISSUE TITLE
h5组件引入方式问题

### ISSUE THREAD

**Issue by richie523** [dcloudio/uni-ui#92]
我正常使用  
import {uniRate, uniLoadMore} from '@dcloudio/uni-ui'
    components: { uniRate, uniLoadMore },
这种方式引入，小程序没有问题，但是h5下面就提示组件未注册

我必须要加上
Vue.component('uniRate', uniRate)
  Vue.component('uniLoadMore', uniLoadMore)
才可以，不知道什么原因，要想小程序和h5都能用，必须两种方式注册组件

**Comment by Wangyaqi** [comment]
没复现你说的问题，是在页面引入还是在main.js引入，方便的话可以上传一下你的项目我们测试一下

**Comment by richie523** [comment]
我是在页面引入的，项目太大，不太方便独立出来上传
`  import {uniRate, uniLoadMore} from '@dcloudio/uni-ui'`
`Vue.component('uniRate', uniRate)`
`Vue.component('uniLoadMore', uniLoadMore)`
`export default {`
`  components: { uniRate, uniLoadMore },`

我现在只能这样

**Comment by richie523** [comment]
> 没复现你说的问题，是在页面引入还是在main.js引入，方便的话可以上传一下你的项目我们测试一下

我是在页面引入的，项目太大，不太方便独立出来上传
import {uniRate, uniLoadMore} from '@dcloudio/uni-ui'
Vue.component('uniRate', uniRate)
Vue.component('uniLoadMore', uniLoadMore)
export default {
components: { uniRate, uniLoadMore },

我现在只能这样

**Comment by Wangyaqi** [comment]
报错提示什么

**Comment by richie523** [comment]
> 报错提示什么

我刚发现好像是因为在组件内调用会出这个问题
`[Vue warn]: Unknown custom element: <uni-rate> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

**Comment by Wangyaqi** [comment]
什么版本的vue-cli？

**Comment by richie523** [comment]
> 什么版本的vue-cli？

我用的uniapp，不是用vue-cli建的项目

**Comment by richie523** [comment]
是我自己页面bug，不好意思，打扰了
