### ISSUE TITLE
[bug] 使用hbuild编辑器导入uni-ui组件库

### ISSUE THREAD

**Issue by kang-hui-jun** [dcloudio/uni-ui#921]
uni-datetime-picker.vue组件报错
![1720249411272](https://github.com/dcloudio/uni-ui/assets/67360395/ada313ca-6159-4762-a4fb-ba813683e299)

**Comment by GRCmade** [comment]
你这是在哪下载的

**Comment by kang-hui-jun** [comment]
插件市场导入啊，标题已经写了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月16日 19:54 |
| 收件人 | dcloudio/uni-ui ***@***.***> |
| 抄送人 | kang ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [dcloudio/uni-ui] [bug] 使用hbuild编辑器导入uni-ui组件库 (Issue #921) |

你这是在哪下载的

**Comment by GRCmade** [comment]
暂时没有复现这个问题
