### ISSUE TITLE
uni-ui -> uni-datetime-picker  Css 属性导致的报错

### ISSUE THREAD

**Issue by axinss** [dcloudio/uni-ui#923]
![image](https://github.com/dcloudio/uni-ui/assets/55694168/feb152bc-1a77-495f-9b67-8f4c8d5b7199)
在Style代码内出现这段不是注释的注释导致使用时报错

**Comment by GRCmade** [comment]
css的注释不是这么写的

**Comment by GRCmade** [comment]
你这是在哪下载的
