### ISSUE TITLE
uni_modules/uni-data-select/components/uni-data-select/uni-data-select.vue

### ISSUE THREAD

**Issue by longwangsam** [dcloudio/uni-ui#926]
<uni-icons :type="showSelector? 'top' : 'bottom'" size="14" color="#999" />

uni-icons 无 type 为top 和 bottom的数据

**Comment by GRCmade** [comment]
请你仔细说一下data-select与uni-icons有啥问题？

**Comment by GRCmade** [comment]
可以使用up和down
