### ISSUE TITLE
uni-data-picker 当value相同时，会陷入死循环，严重影响性能

### ISSUE THREAD

**Issue by AltinaNissan** [dcloudio/uni-ui#927]
1. uni-data-picker  这个组件 当绑定的value相同时，会陷入死循环，严重影响性能  经发现是 _findNodePath这个函数导致
2. 还是uni-data-picker 这个组件，当快速选择内容 一直触发_dispatchEvent这个函数的时候，不知道被哪个函数影响到了，会导致treeData数据丢失，选择页面无内容可选，关闭重新打开组件才可以恢复数据

**Comment by GRCmade** [comment]
你好，可以提供一个你的代码吗？

**Comment by AltinaNissan** [comment]
> 你好，可以提供一个你的代码吗？

[uni-data-picker.zip](https://github.com/user-attachments/files/16781330/uni-data-picker.zip)
这是我们根据需要在组件的基础上增加了功能，同时_findNodePath函数注释。第二个问题需要快速选择

**Comment by GRCmade** [comment]
你好，看你的changelog是过去的版本，修改也是过去版本，暂时就不考虑加入了
![image](https://github.com/user-attachments/assets/b22c6ed0-d079-49f1-960e-3e5990c4c2c1)

**Comment by AltinaNissan** [comment]
> 你好，看你的changelog是过去的版本，修改也是过去版本，暂时就不考虑加入了 ![image](https://private-user-images.githubusercontent.com/97457593/362621171-b22c6ed0-d079-49f1-960e-3e5990c4c2c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNDA4MzgsIm5iZiI6MTcyNTI0MDUzOCwicGF0aCI6Ii85NzQ1NzU5My8zNjI2MjExNzEtYjIyYzZlZDAtZDA3OS00OWYxLTk2MGUtM2U1OTkwYzRjMmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDAxMjg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3ZWVjNTQzYTU1NjE0Yzc1ZDQwYTA0MTQ0NmNiY2ZmZjkyYTM0NTk5M2ExNWQ3YWI5ZTRlYTA3YWUzYmE1MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jygPlwD5YBpK-GoJDQUqx8NvtJ_5fhdZjQtOH0-Wlik)
[uni-data-picker.zip](https://github.com/user-attachments/files/16831325/uni-data-picker.zip)
根据最新的版本 我进行了一些适配，包括选择的数据也放在了里面 已知的问题有两个 1 选择过快的时候可能会造成treeData为空 2选择完一个选项后 没有回到第一级
![image](https://github.com/user-attachments/assets/8cb7b91e-2e3b-41e0-9881-bd8b29f2b44d)
