### ISSUE TITLE
【新手求助】使用uni-file-picker，某张上传失败后，需要在页面回显该图片上传失败的样式应该如何配置？

### ISSUE THREAD

**Issue by BIGFAM** [dcloudio/uni-ui#935]
由于不使用官方的图片空间服务器配置，:auto-upload设置了"false"
只用他的@select 和@delete方法
目前select后，将会使用uni.uploadFile来进行上传图片。
但是upload时，需要对于各个图片附上一些样式，上传中、上传失败的两个样式，
我应该怎么配置呢？

**Comment by GRCmade** [comment]
你好，想要修改样式，需要修改源码，你可以尝试修改uni-file-picker下的upload-image.vue
