### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by 3476244552** [dcloudio/uni-ui#936]
怎么设置uni-tag标签的的宽度？我想给所有标签搞一个固定的大小

**Comment by GRCmade** [comment]
你好，你可以，在uni-tag.vue中，修改，$tag-default-pd或者修改.uni-tag来尝试实现

**Comment by 3476244552** [comment]
> 你好，你可以，在uni-tag.vue中，修改，$tag-default-pd或者.uni-tag来尝试修改实现

ok，我去试试
