### ISSUE TITLE
uni-calendar 能做到默认不选择任何日期吗？

### ISSUE THREAD

**Issue by stu2162583** [dcloudio/uni-ui#937]
uni-calendar 现在必须有一个日期，不设置date默认是当前日期。

需求，需要预定义一个日期，如果这个选择的时间不在“有效时间”内容，就需要提示功能，所以默认不会选择任何日期，在选择日期之后，如果选择的日期不合理，则给与提示，当前选择的日期是否取消选择应该也可以作为一个功能；

场景：
一个旅店有一个小程序，他可以选择住一天，也可以选择连续住3天。
旅店的营业日期是 2024-01-01 ~ 2024-01-06 那么，如果选择可以连续住3天，就必须要选择03以前的日期，如果选择04的日期就会提示日期不合法

**Comment by GRCmade** [comment]
你好，暂时还没有见到很多这样的需求，因此还不考虑增加不选择日期的功能。但是我可以一下修改的思路，你可以尝试自己修改

在uni-calendar.vue中，有一个init方法会初始化日期，你可以去掉这个函数

在uni-calendar-item.vue中，有一个属性：.uni-calendar-item--checked，你可以去掉它的背景颜色显示，改为控制是否显示
