### ISSUE TITLE
uni-pop弹出后会展示再input的下面

### ISSUE THREAD

**Issue by Darren-chenchen** [dcloudio/uni-ui#94]
![image](https://user-images.githubusercontent.com/16269032/69605476-28c09700-105b-11ea-9568-05d491f0680d.png)

**Comment by Darren-chenchen** [comment]
![image](https://user-images.githubusercontent.com/16269032/69605521-48f05600-105b-11ea-8e8b-5b4363c89619.png)
![image](https://user-images.githubusercontent.com/16269032/69605539-54438180-105b-11ea-9ac3-6bff2ff2b432.png)

**Comment by mehaotian** [comment]
什么平台出现的问题 ？

**Comment by Wangyaqi** [comment]
长时间未响应暂时关闭
