### ISSUE TITLE
uni-calender中选择时间段后,再次选择需要点击两次问题

### ISSUE THREAD

**Issue by gaochuang159753** [dcloudio/uni-ui#941]
util.js -> 299 行
this.multipleStatus.before = fullDate
this.multipleStatus.after = ''
this.multipleStatus.data = []

**Comment by GRCmade** [comment]
你好，可以给出你是如何使用的吗？

**Comment by gaochuang159753** [comment]
场景: 
<uni-calendar
      ref="calendar"
      :clearDate="false"
      :insert="false"
      range
      :start-date="startDate"
      :end-date="endDate"
      @confirm="changeDate"
    />
1. 插件中代码在选择before && after 再次点击时会把before 置空(this.multipleStatus.before = '')

**Comment by GRCmade** [comment]
感谢你的反馈，我会进行验证对
