### ISSUE TITLE
uni-popup在app android端，设置中间弹窗，快速点击有问题，不会居中。

### ISSUE THREAD

**Issue by LeoKun1231** [dcloudio/uni-ui#948]
代码仓库 https://github.com/LeoKun1231/test-uni-popup.git

**Comment by LeoKun1231** [comment]
![image](https://github.com/user-attachments/assets/d16786a2-206b-443d-80c2-10bf13c87973)
目前这样解决有效，希望以后有更好的解决办法。

**Comment by qhl123456** [comment]
我也遇到了，暂时一样的解决办法，看看官方有什么办法解决吗

**Comment by GRCmade** [comment]
感谢反馈，正在查找相关问题

**Comment by GRCmade** [comment]
已提交修复，感谢你们对uni-ui的贡献
