### ISSUE TITLE
索引列表组件中右边索引栏出现卡顿且无法继续进行滑动

### ISSUE THREAD

**Issue by MooozzZ** [dcloudio/uni-ui#95]
目前问题在滑动之后会出现卡顿，无法滑动，且如果对非字母会出现 t.group is not a function 报错。

**Comment by MooozzZ** [comment]
目前解决方案是 对  touchmove.stop => touchmove  位于  uni-indexed-list.vue  p33左右 ，仍不支持非字母索引。不知道这样改是否合适？

**Comment by Wangyaqi** [comment]
在哪端出现的卡顿？什么版本的HBuilderX

**Comment by Wangyaqi** [comment]
nvue分支已修改支持非字母数字索引

**Comment by MooozzZ** [comment]
在做h5页面时，出现这个情况，且出现几率80%，

**Comment by Wangyaqi** [comment]
是不是在chrome模拟的时候？用真机呢

**Comment by MooozzZ** [comment]
模拟没问题，真机上发现的，然后修改了上述代码就可以了

**Comment by Wangyaqi** [comment]
真机的什么浏览器，按理说是不用修改的

**Comment by MooozzZ** [comment]
在微信公众号H5页面，安卓和ios都有这个情况，

**Comment by Wangyaqi** [comment]
> 在微信公众号H5页面，安卓和ios都有这个情况，

那就你这么改吧，确实没考虑周全

**Comment by MooozzZ** [comment]
这个原因是为什么呢，为什么阻止了冒泡，会出现这种情况。请教一下。

**Comment by Wangyaqi** [comment]
> 这个原因是为什么呢，为什么阻止了冒泡，会出现这种情况。请教一下。

跟冒泡没关系，需要阻止默认行为  @touchmove.stop.prevent
