### ISSUE TITLE
多个uni-easyinput切换时会失去焦点，官方demo也是如此

### ISSUE THREAD

**Issue by yuzhongxingke** [dcloudio/uni-ui#951]
在微信小程序开发过程中，一个页面会用到多个uni-easyinput，在type="text" 或者 type="textarea"之间切换时会失去焦点，键盘会来会先显示 然后立马隐藏， 不能按需显示键盘

目前这个问题只在android手机上复现，iOS手机是好的。

复现步骤：

微信小程序---官方提供的demo【HelloUniApp】 --- 底部菜单选中【扩展组件】-- 选择【uni-forms 表单】
在该页面中，先选中【年龄】输入框，然后再选中【自我介绍】输入框，就会复现这个问题

**Comment by GRCmade** [comment]
你好，经过测试，这不是uni-easyinput的bug，你使用原生的input和textarea标签进行切换也会出现这个问题

![image](https://github.com/user-attachments/assets/d0956653-bd39-4508-90fa-14189f14e0b4)
