### ISSUE TITLE
uni-grid动态变化时，@change返回的index错误

### ISSUE THREAD

**Issue by chendanlin** [dcloudio/uni-ui#97]
`<uni-grid :column="3" :show-border="false" :square="false" @change="handleGridChange">
	<uni-grid-item v-for="item in arrays" :key="item.id">
		<view class="grid-item bg-white radius shadow-warp">{{ item.name }}</view>
		<view class="grid-dot">
			<uni-badge type="error" text=" "></uni-badge>
		</view>
	</uni-grid-item>
</uni-grid>`
当arrays先添加，再减少，再增加数据时，handleGridChange方法接收到错误的index，源码实现中uni-grid-item的index依赖uni-grid的index，减少数据时uni-grid的index没有减少，导致增加数据时，新的uni-grid-item的index超过arrays.length

**Comment by mehaotian** [comment]
nvue-uni-ui 分支已经修复该问题，请拉取最新代码验证

**Comment by chendanlin** [comment]
新版本（1.2.1）还有一个问题，在动态获取数据时，数据中前后有一部分重复，由于vue的渲染机制，uni-grid-item标签不能使用:key，不然复用还是会导致@chang返回的index错误
