### ISSUE TITLE
uni-ui cli以后意思是这里不再维护了？

### ISSUE THREAD

**Issue by guyuewuren** [dcloudio/uni-ui#99]
官方的UI太难用了，简陋，还丑爆，作为一个前端的框架，UI是必不可少的部分，但是官方在这上面却很少投入精力，仅仅以性能标杆来自居以规避自己的无所作为，现在都什么年代了？用户更需要的是体验！而第三方的UI在多端适配上各种坑，比如在插件热门排行榜第二的ColorUI，作者也懒得维护，导致至今UI成为uniapp发展的瓶颈，无法快速堆积木的速度出成品交付客服，这和DCLOUD官方提倡的解放生产力理念很是矛盾

**Comment by CheJJ** [comment]
> 官方的UI太难用了，简陋，还丑爆，作为一个前端的框架，UI是必不可少的部分，但是官方在这上面却很少投入精力，仅仅以性能标杆来自居以规避自己的无所作为，现在都什么年代了？用户更需要的是体验！而第三方的UI在多端适配上各种坑，比如在插件热门排行榜第二的ColorUI，作者也懒得维护，导致至今UI成为uniapp发展的瓶颈，无法快速堆积木的速度出成品交付客服，这和DCLOUD官方提倡的解放生产力理念很是矛盾

同意楼上观点，现在的UI库都太丑了。
我不是针对谁，是说在座的各位。全都丑爆了，其中包括 UniUI、TaroUI、Vant、WeUI、ColorUI。
9102年都要过去了，还都长这么丑。

**Comment by mehaotian** [comment]
uni-ui 一直都在维护，只是最近有些比较大的目录结构的变化，我们一直在持续性的对 uni-ui 进行一定的美化和性能上的优化。对于 UI 方面的建议，您可以提供你的想法，我们对于好的建议，都是会积极接受的。
